@startuml


usecase "Manage AI Models" as ManageAIModels #yellow

Actor "Data Scientist" as DataScientist

DataScientist --> ManageAIModels

Actor "DevOps Engineer" as DevOpsEngineer

DevOpsEngineer --> ManageAIModels

Actor "Application Developer" as ApplicationDeveloper

ApplicationDeveloper --> ManageAIModels

Actor "DataEngineer" as DataEngineer

DataEngineer --> ManageAIModels



usecase "CreateAIModel" as CreateAIModel #lightgrey

ManageAIModels --> CreateAIModel

usecase "DeployAIModel" as DeployAIModel #lightgrey

ManageAIModels --> DeployAIModel

usecase "DestroyAIModel" as DestroyAIModel #lightgrey

ManageAIModels --> DestroyAIModel

usecase "UpdateAIModel" as UpdateAIModel #lightgrey

ManageAIModels --> UpdateAIModel



usecase "OrganizeSolutions" as OrganizeSolutions #lightyellow

ManageAIModels <-- OrganizeSolutions : extends







@enduml
