@startuml

actor "Application Developer"

actor "Data Scientist"


entity EventBus

box Application Management Layer #lightblue
    boundary aml #white
end box


box Software Defined Infrastructure #lightyellow
            participant storageresource
    end box


"Application Developer" -> aml: Create AI Model

    aml -> "aimodel": create (name: name1)



"Data Scientist" -> aml: Create AI Model

    aml -> "aimodel": create (name: name1)




box "Distributed Information Management Layer" #ffcc88
    boundary diml #white
end box
EventBus -\ diml: method()
diml --/ EventBus: Model.Event2
box "Service Management Layer" #lightgreen
    boundary sml #white
end box
EventBus -\ sml: method()
sml --/ EventBus: Model.Event2
box "Security Aspect" #pink
    boundary sa #white
end box
EventBus -\ sa: method()
sa --/ EventBus: Model.Event2
box "Identity Aspect" #pink
    boundary ia #white
end box
EventBus -\ ia: method()
ia --/ EventBus: Model.Event2

EventBus --/ aml : method2()
@enduml
