@startuml


actor "Application Developer"

actor "Data Scientist"


entity EventBus

box Application Management Layer #88cccc
    boundary aml #white
end box


box Software Defined Infrastructure #cccc88
            participant storageresource
    end box

group Given [An application developer or data scientist wants to create an AI model]

"Application Developer" --/ aml: They use the &#39;aimodel/create&#39; method and provide &#39;name1&#39; as the name parameter
"aml" -> aml: Create AI Model

    aml -> "storageresource": create (name: name1)

    "storageresource" --/ EventBus: aimodel.create


"Data Scientist" --/ aml: They use the &#39;aimodel/create&#39; method and provide &#39;name1&#39; as the name parameter
"aml" -> aml: Create AI Model

    aml -> "storageresource": create (name: name1)

    "storageresource" --/ EventBus: aimodel.create



"Application Developer" /-- aml: The AI model with the provided name is created successfully

"Data Scientist" /-- aml: The AI model with the provided name is created successfully


end

@enduml
