@startuml


actor "DevOpsEngineer"

actor "ApplicationDeveloper"

actor "DataEngineer"


entity EventBus

box Application Management Layer #88cccc
    boundary aml #white
end box


group Given [The AI model is trained and ready to be deployed]

"DevOpsEngineer" --/ aml: The DevOps, Application Developer or Data Engineer triggers the deployment process
"aml" -> aml: Deploy AI Model


"ApplicationDeveloper" --/ aml: The DevOps, Application Developer or Data Engineer triggers the deployment process
"aml" -> aml: Deploy AI Model


"DataEngineer" --/ aml: The DevOps, Application Developer or Data Engineer triggers the deployment process
"aml" -> aml: Deploy AI Model



"DevOpsEngineer" /-- aml: The AI Model is successfully deployed and is ready to be used

"ApplicationDeveloper" /-- aml: The AI Model is successfully deployed and is ready to be used

"DataEngineer" /-- aml: The AI Model is successfully deployed and is ready to be used


end

@enduml
