@startuml

actor "DataEngineer"

actor "ApplicationDeveloper"


entity EventBus

box Application Management Layer #lightblue
    boundary aml #white
end box



"DataEngineer" -> aml: Destroy AI Model


"ApplicationDeveloper" -> aml: Destroy AI Model



@enduml
