@startuml


actor "DataEngineer"

actor "DevOpsEngineer"

actor "ApplicationDeveloper"


entity EventBus

box Application Management Layer #88cccc
    boundary aml #white
end box


group Given [A Data Engineer, DevOps Engineer, or Application Developer uses the AI model]

"DataEngineer" --/ aml: The AI model needs an update
"aml" -> aml: Update AI Model


"DevOpsEngineer" --/ aml: The AI model needs an update
"aml" -> aml: Update AI Model


"ApplicationDeveloper" --/ aml: The AI model needs an update
"aml" -> aml: Update AI Model



"DataEngineer" /-- aml: The AI model gets updated through the &#39;aimodel/update&#39; method

"DevOpsEngineer" /-- aml: The AI model gets updated through the &#39;aimodel/update&#39; method

"ApplicationDeveloper" /-- aml: The AI model gets updated through the &#39;aimodel/update&#39; method


end

@enduml
