@startuml
  interface CLI
  interface Web
  interface WebSocket
node "Service Orchestrator" #88cc88 {
  component express as REST
  component socket.io as socket
  folder bin #ffffff {
    card " edgemere sml so" as binName
  }
  binName --> REST

  folder deploy #ffffff {
      file "node server.js\n" as sml_so_container
      REST --> sml_so_container

  
    file "web" as web_container
    REST --> web_container
    socket ---> web_container
  
  }
  folder images #ffffff {
    collections "sml_so" as sml_soimage
    artifact "ailtire:swarm" as ailtireswarm
    sml_soimage <|-- ailtireswarm
    sml_so_container --> sml_soimage

  
      artifact "sml_so_web" as sml_so_web
      web_container --> sml_so_web
    
  }
}
CLI " edgemere sml so" -- binName
Web "/edgemere/sml/so" - REST
WebSocket ".edgemere.sml.so" -- socket

@enduml
