@startuml

class "RunScript" as Model {
 string name

 
}

rectangle "ServiceInstance" as ServiceInstance #lightblue {
}

Model o--> "1" ServiceInstance : owner




    rectangle "ServiceInstance" as ServiceInstance #lightgreen {
    }
    
        ServiceInstance   *--> "n" Model : "runScripts"
    
    rectangle "StackInstance" as StackInstance #lightgreen {
    }
    
        StackInstance   *--> "n" Model : "runScripts"
    

@enduml
