@startuml

class "DataSource" as Model {
 string name
 json parameters

 create()
 
}

rectangle "DataBluePrintInstance" as DataBluePrintInstance #lightblue {
}

Model o--> "n" DataBluePrintInstance : blueprints


rectangle "DataAdaptor" as DataAdaptor #lightblue {
}

Model o--> "1" DataAdaptor : adaptor


rectangle "Data" as Data #lightblue {
}

Model *--> "n" Data : data




    rectangle "DataAdaptor" as DataAdaptor #lightgreen {
    }
    
        DataAdaptor   *--> "n" Model : "sources"
    
    rectangle "DataBluePrintInstance" as DataBluePrintInstance #lightgreen {
    }
    
        DataBluePrintInstance   o--> "n" Model : "sources"
    
    rectangle "DataBluePrintInstance" as DataBluePrintInstance #lightgreen {
    }
    
        DataBluePrintInstance   o--> "n" Model : "sinks"
    
    rectangle "DataFlowInstance" as DataFlowInstance #lightgreen {
    }
    
        DataFlowInstance   o--> "n" Model : "sinks"
    
    rectangle "DataFlowInstance" as DataFlowInstance #lightgreen {
    }
    
        DataFlowInstance   o--> "n" Model : "sources"
    
    rectangle "DataReservation" as DataReservation #lightgreen {
    }
    
        DataReservation   o--> "1" Model : "source"
    
    rectangle "Data" as Data #lightgreen {
    }
    
        Data   o--> "1" Model : "source"
    

@enduml
