@startuml



state DataSource #ffcc88 {

    state Init #ffcc88 {
    }

    state Ready #ffcc88 {
    }

    state Suspended #ffcc88 {
    }

    state Shutdown #ffcc88 {
    }

}


Init --> Ready : create

Ready --> Suspended : suspend

Ready --> Shutdown : shutdown




@enduml
