@startuml


package "Software Defined Infrastructure" #lightyellow {
    }


package "Provision Engine" #lightgreen {

    interface "Provision Engine" as i {
    
    }
}

CLI ()-- i
REST ()-- i
Web ()-- i

package "Provision Engine" #lightgreen {
    
}


    "Provision Engine" --> "Software Defined Infrastructure"


@enduml
