@startuml



package "Infrastructure Orchestrator" #cccc88 {

    interface "Infrastructure Orchestrator" as i {
            /edgemere/sdi/io/evaluaterequest()
            /edgemere/sdi/io/provision()
    
    }
}

CLI ()-- i
REST ()-- i
Web ()-- i

package "Infrastructure Orchestrator" #cccc88 {
    
}



@enduml
