@startuml
left to right direction


state "sdi" as sdi #cccc88 {
state "io" as sdiio #cccc88 {
}
}


state "sdiio" as pstatename #cccc88 {
    state "Custom Function" as iofunction {
    }
}

        state "sdi" as sdi #cccc88 {
state "io" as sdiio #cccc88 {
state "evaluaterequest" as sdiioevaluaterequest #cccc88 {
}
}
}


        state "sdi" as sdi #cccc88 {
state "io" as sdiio #cccc88 {
state "provision" as sdiioprovision #cccc88 {
}
}
}




        state "sdi" as sdi #cccc88 {
state "Request" as sdirequest #cccc88 {
state "selected" as sdirequestselected #cccc88 {
}
}
}

        
    state "sdi" as sdi #cccc88 {
state "io" as sdiio #cccc88 {
state "evaluateRequest" as sdiioevaluaterequest #cccc88 {
}
}
}

    sdirequestselected ---> sdiioevaluaterequest
  

        state "sdi" as sdi #cccc88 {
state "Reservation" as sdireservation #cccc88 {
state "confirmed" as sdireservationconfirmed #cccc88 {
}
}
}

        
    state "sdi" as sdi #cccc88 {
state "io" as sdiio #cccc88 {
state "provision" as sdiioprovision #cccc88 {
}
}
}

    sdireservationconfirmed ---> sdiioprovision
  



@enduml
