@startuml


package "Identity Aspect" #cc8888 {
    
        class User {
        }
    
        class IdentityAttribute {
        }
    
        class Group {
        }
    }

package "Security Profile Manager" #cc8888 {
    
        class SecurityProfile {
        }
    }


package "Identity Aspect" #cc8888 {

    interface "Identity Aspect" as i {
            /edgemere/ia/creategroup()
            /edgemere/ia/group/create()
    
    }
}

CLI ()-- i
REST ()-- i
Web ()-- i

package "Identity Aspect" #cc8888 {
        class "Group" {
                 string name
                    }
                Group o--> "n" User : users
            
    
    class "Identity" {
                 string name
                 string username
                 string password
                 string cert
                    }
                Identity o--> "n" SecurityProfile : securityProfiles
                        Identity o--> "n" IdentityAttribute : characterisitcs
            
    
    class "IdentityAttribute" {
                 string name
                 string value
                    }
    
    
    class "User" {
                 string name
                 string username
                 string password
                 string cert
                    }
                User o--> "n" Group : groups
                        User o--> "n" IdentityAttribute : attributes
                        User o--> "n" SecurityProfile : securityProfiles
                        User o--> "n" IdentityAttribute : characterisitcs
            
    
        Identity <|-- User
    

}



@enduml
