@startuml


package "Identity Aspect" #pink {
    
        class User {
        }
    
        class Group {
        }
    
        class IdentityAttribute {
        }
    }


package "Identity Aspect" #pink {

    interface "Identity Aspect" as i {
    
    }
}

CLI ()-- i
REST ()-- i
Web ()-- i

package "Identity Aspect" #pink {
        class "Group" {
                 string name
                    }
                Group o--> "n" User : users
            
    
    class "Identity" {
                 string name
                 string username
                 string password
                 string cert
                    }
    
    
    class "IdentityAttribute" {
                 string name
                 string value
                    }
    
    
    class "User" {
                 string name
                    }
                User o--> "n" Group : groups
                        User o--> "n" IdentityAttribute : attributes
            
    

}



@enduml
