@startuml
left to right direction


state "ia" as ia #cc8888 {
}


state "ia" as pstatename #cc8888 {
    state "Custom Function" as iafunction {
    }
}

        state "ia" as ia #cc8888 {
state "creategroup" as iacreategroup #cc8888 {
}
}


        state "ia" as ia #cc8888 {
state "group" as iagroup #cc8888 {
state "create" as iagroupcreate #cc8888 {
}
}
}






@enduml
