@startuml
left to right direction


    package "edgemere" as edgemere {
 component "ia" as edgemereia
 interface "creategroup" as edgemereiacreategroup
edgemereia -- edgemereiacreategroup
}

    
    package "edgemere" as edgemere {
package "ia" as edgemereia #cc8888 {
 component "group" as edgemereiagroup
 interface "create" as edgemereiagroupcreate
edgemereiagroup -- edgemereiagroupcreate
}
}

    























































@enduml
