@startuml


package "Identity Aspect" #cc8888 {

}

package "Security Profile Manager" #cc8888 {

}


package "Identity Aspect" #cc8888 {

    interface "Identity Aspect" as i {
    
            /edgemere/ia/creategroup()
            /edgemere/ia/group/create()
    
    }
}

circle REST
circle Web
circle CLI
circle WebSocket

i -down- Web
i -down- CLI
i -down- REST
WebSocket -left- i: events >

package "Identity Aspect" #cc8888 {


}



@enduml
