@startuml
left to right direction



state "IT Operations" as ITOperations {
    state "Manage Data Center" as ITOperationsManageDataCenter {
    }
}
state "cpl" as cpl #lightgray {
state "datacenter" as cpldatacenter #lightgray {
state "list" as cpldatacenterlist #lightgray {
}
}
}

ITOperationsManageDataCenter --> cpldatacenterlist


    state "IT Operations" as ITOperations {
        state "Manage Data Center" as ITOperationsManageDataCenter {
            state "Create Data Center" as ITOperationsManageDataCenterCreateDataCenter {
            }
        }
    }
    state "cpldatacenter" as cpldatacenter #lavender {
state "create" as cpldatacentercreate #lavender {
}
}

    ITOperationsManageDataCenterCreateDataCenter --> cpldatacentercreate
    
 
    state "IT Operations" as ITOperations {
        state "Manage Data Center" as ITOperationsManageDataCenter {
            state "Disable Data Center" as ITOperationsManageDataCenterDisableDataCenter {
            }
        }
    }
    state "cpldatacenter" as cpldatacenter #lavender {
state "disable" as cpldatacenterdisable #lavender {
}
}

    ITOperationsManageDataCenterDisableDataCenter --> cpldatacenterdisable
    
 
    state "IT Operations" as ITOperations {
        state "Manage Data Center" as ITOperationsManageDataCenter {
            state "Enable Data Center" as ITOperationsManageDataCenterEnableDataCenter {
            }
        }
    }
    state "cpldatacenter" as cpldatacenter #lavender {
state "enable" as cpldatacenterenable #lavender {
}
}

    ITOperationsManageDataCenterEnableDataCenter --> cpldatacenterenable
    
 
    state "IT Operations" as ITOperations {
        state "Manage Data Center" as ITOperationsManageDataCenter {
            state "Remove Data Center" as ITOperationsManageDataCenterRemoveDataCenter {
            }
        }
    }
    state "cpldatacenter" as cpldatacenter #lavender {
state "remove" as cpldatacenterremove #lavender {
}
}

    ITOperationsManageDataCenterRemoveDataCenter --> cpldatacenterremove
    
 
    state "IT Operations" as ITOperations {
        state "Manage Data Center" as ITOperationsManageDataCenter {
            state "Update Data Center" as ITOperationsManageDataCenterUpdateDataCenter {
            }
        }
    }
    state "cpldatacenter" as cpldatacenter #lavender {
state "update" as cpldatacenterupdate #lavender {
}
}

    ITOperationsManageDataCenterUpdateDataCenter --> cpldatacenterupdate
    
 
 
state "IT Operations" as ITOperations {
    state "Manage Infrastructure" as ITOperationsManageInfrastructure {
    }
}
state "cpl" as cpl #lightgray {
state "data" as cpldata #lightgray {
state "govern" as cpldatagovern #lightgray {
}
}
}

ITOperationsManageInfrastructure --> cpldatagovern


    state "IT Operations" as ITOperations {
        state "Manage Infrastructure" as ITOperationsManageInfrastructure {
            state "Add Device" as ITOperationsManageInfrastructureAddDevice {
            }
        }
    }
    state "cpldata" as cpldata #lavender {
state "source" as cpldatasource #lavender {
}
}

    ITOperationsManageInfrastructureAddDevice --> cpldatasource
    
 
    state "IT Operations" as ITOperations {
        state "Manage Infrastructure" as ITOperationsManageInfrastructure {
            state "Manage Aggregated Devices" as ITOperationsManageInfrastructureManageAggregatedDevices {
            }
        }
    }
    state "cpldata" as cpldata #lavender {
state "source" as cpldatasource #lavender {
}
}

    ITOperationsManageInfrastructureManageAggregatedDevices --> cpldatasource
    
 
    state "IT Operations" as ITOperations {
        state "Manage Infrastructure" as ITOperationsManageInfrastructure {
            state "Manage Data Center" as ITOperationsManageInfrastructureManageDataCenter {
            }
        }
    }
    state "cpldata" as cpldata #lavender {
state "source" as cpldatasource #lavender {
}
}

    ITOperationsManageInfrastructureManageDataCenter --> cpldatasource
    
 
    state "IT Operations" as ITOperations {
        state "Manage Infrastructure" as ITOperationsManageInfrastructure {
            state "Remove Device" as ITOperationsManageInfrastructureRemoveDevice {
            }
        }
    }
    state "cpldata" as cpldata #lavender {
state "source" as cpldatasource #lavender {
}
}

    ITOperationsManageInfrastructureRemoveDevice --> cpldatasource
    
 
    state "IT Operations" as ITOperations {
        state "Manage Infrastructure" as ITOperationsManageInfrastructure {
            state "Update Device" as ITOperationsManageInfrastructureUpdateDevice {
            }
        }
    }
    state "cpldata" as cpldata #lavender {
state "source" as cpldatasource #lavender {
}
}

    ITOperationsManageInfrastructureUpdateDevice --> cpldatasource
    
 
 

@enduml
