@startuml

left to right direction


boundary ailtire_appname_sml_family #red


entity ailtire_appname_sml_cb_family #black




package "sml_cb" #lightgreen {
    queue childrennet #black [
            <b><color:white>children</color></b>
    ]
    
    childrennet -[#black]- ailtire_appname_sml_cb_family
    
    queue siblingnet #blue [
            <b><color:white>sibling</color></b>
    ]
    
    queue parentnet #red [
            <b><color:white>parent</color></b>
    ]
    
    parentnet -[#red]- ailtire_appname_sml_family
    

node "frontend" as frontendService
node "gw" as gwService


        artifact "sml_cb_web" as sml_cb_webimage
    
        artifact "sml_cb_gw" as sml_cb_gwimage
    
}

frontendService -[#blue]- siblingnet

gwService -[#black]- childrennet

gwService -[#blue]- siblingnet
frontendService .... sml_cb_webimage
gwService .... sml_cb_gwimage


@enduml
