@startuml

left to right direction


Actor "Security Operator" as SecurityOperator


rectangle "Security Profile Manager" as spm #pink {
        usecase "Apply Security Profiles" as ApplySecurityProfiles
    SecurityOperator --> ApplySecurityProfiles

}


@enduml
