@startuml

left to right direction


Actor "Security Operator" as SecurityOperator


rectangle "Security Profile Manager" as spm #cc8888 {
        usecase "Apply Security Profiles" as ApplySecurityProfiles
    SecurityOperator --> ApplySecurityProfiles

}

rectangle "edgemere" as edgemere #ccaaff {
        usecase "Govern Identities" as GovernIdentities
    SecurityOperator --> GovernIdentities
    usecase "Secure Assets" as SecureAssets
    SecurityOperator --> SecureAssets

}


@enduml
