@startuml


left to right direction

usecase "Manage Physical Infrastructure" as ManagePhysicalInfrastructure #yellow

Actor "IT Operations" as ITOperations

ITOperations --> ManagePhysicalInfrastructure







usecase "ManageDataCenter" as ManageDataCenter #lightyellow

ManagePhysicalInfrastructure --> ManageDataCenter : extends

usecase "ManageInfrastructure" as ManageInfrastructure #lightyellow

ManagePhysicalInfrastructure --> ManageInfrastructure : extends





@enduml
