@startuml

class "Request" as Model {
 string name
 string ename
 string type
 string message

 confirm()
 evaluated()
 failed()
 fulfill()
 satisfied()
 
}

rectangle "MetricComposite" as MetricComposite #lightblue {
}

Model *--> "1" MetricComposite : requirements


rectangle "Reservation" as Reservation #lightblue {
}

Model *--> "n" Reservation : reservations


rectangle "Resource" as Resource #lightblue {
}

Model *--> "n" Resource : resources


rectangle "Cloud" as Cloud #lightblue {
}

Model o--> "1" Cloud : cloud


rectangle "DataCenter" as DataCenter #lightblue {
}

Model o--> "n" DataCenter : datacenters


rectangle "Device" as Device #lightblue {
}

Model o--> "n" Device : devices


rectangle "AggregatedDevice" as AggregatedDevice #lightblue {
}

Model o--> "n" AggregatedDevice : aggregates




    rectangle "Cloud" as Cloud #lightgreen {
    }
    
        Cloud   *--> "n" Model : "requests"
    
    rectangle "Reservation" as Reservation #lightgreen {
    }
    
        Reservation   o--> "1" Model : "request"
    
    rectangle "Resource" as Resource #lightgreen {
    }
    
        Resource   o--> "1" Model : "request"
    
    rectangle "AcceleratorResource" as AcceleratorResource #lightgreen {
    }
    
        AcceleratorResource   o--> "1" Model : "request"
    
    rectangle "ComputeResource" as ComputeResource #lightgreen {
    }
    
        ComputeResource   o--> "1" Model : "request"
    
    rectangle "NetworkResource" as NetworkResource #lightgreen {
    }
    
        NetworkResource   o--> "1" Model : "request"
    
    rectangle "StorageResource" as StorageResource #lightgreen {
    }
    
        StorageResource   o--> "1" Model : "request"
    

@enduml
