@startuml



state Request #cccc88 {

    state Init #cccc88 {
    }

    state Needed #cccc88 {
    }

    state Failed #cccc88 {
    }

    state Selected #cccc88 {
    }

    state Satisfied #cccc88 {
    }

    state Evaluated #cccc88 {
    }

    state Completed #cccc88 {
    }




Init -[#black]--> Needed : fulfill

Needed -[#black]--> Selected : selected

Needed -[#black]--> Failed : failed

Selected -[#black]--> Evaluated : evaluated

Satisfied -[#black]--> Completed : complete

Evaluated -[#black]--> Satisfied : satisfied

Evaluated -[#black]--> Failed : failed

}

 
 Needed -[#black]--> Null
 
 
 Selected -[#black]--> Null
 
 
 Satisfied -[#black]--> Null
 

@enduml
