version: "3.7"
services:
  data_orchestrator:
    image: diml_dml_do:latest
    stop_grace_period: 1m
    stop_signal: SIGINT
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      replicas: 1
    environment:
      - AILTIRE_STACKNAME={{.Service.Name}}-{{.Task.Slot}}
      - AILTIRE_PARENT=${AILTIRE_STACKNAME}
      - AILTIRE_PARENTHOST=${AILTIRE_PARENTHOST}
      - AILTIRE_APPNAME=${AILTIRE_APPNAME}
      - AILTIRE_PARENT_NETWORK=${AILTIRE_APPNAME}_cpl_dm
    networks:
      - children
      - parent
  policy_engine:
    image: sa_pe:latest
    stop_grace_period: 1m
    stop_signal: SIGINT
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      replicas: 1
    environment:
      - AILTIRE_STACKNAME={{.Service.Name}}-{{.Task.Slot}}
      - AILTIRE_PARENT=${AILTIRE_STACKNAME}
      - AILTIRE_PARENTHOST=${AILTIRE_PARENTHOST}
      - AILTIRE_APPNAME=${AILTIRE_APPNAME}
      - AILTIRE_PARENT_NETWORK=${AILTIRE_APPNAME}_cpl_dm
    networks:
      - children
      - parent
  service_orchestrator:
    image: sml_so:latest
    stop_grace_period: 1m
    stop_signal: SIGINT
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      replicas: 1
    environment:
      - AILTIRE_STACKNAME={{.Service.Name}}-{{.Task.Slot}}
      - AILTIRE_PARENT=${AILTIRE_STACKNAME}
      - AILTIRE_PARENTHOST=${AILTIRE_PARENTHOST}
      - AILTIRE_APPNAME=${AILTIRE_APPNAME}
      - AILTIRE_PARENT_NETWORK=${AILTIRE_APPNAME}_cpl_dm
    networks:
      - children
      - parent
  telemetry_aggregator:
    image: cpl_ta:latest
    stop_grace_period: 1m
    stop_signal: SIGINT
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      replicas: 1
    environment:
      - AILTIRE_STACKNAME={{.Service.Name}}-{{.Task.Slot}}
      - AILTIRE_PARENT=${AILTIRE_STACKNAME}
      - AILTIRE_PARENTHOST=${AILTIRE_PARENTHOST}
      - AILTIRE_APPNAME=${AILTIRE_APPNAME}
      - AILTIRE_PARENT_NETWORK=${AILTIRE_APPNAME}_cpl_dm
    networks:
      - children
      - parent
  frontend:
      image: traefik:latest
      command:
        - --api=true
        - --api.dashboard=true
        - --api.insecure=true
        - --api.debug=true
        - --accesslog=true
        - --log.level=DEBUG
        - --providers.docker=true
        - --providers.docker.swarmMode=true
        - --providers.docker.network=children
        - --providers.docker.exposedbydefault=false
        - --entrypoints.http.address=:80
        - --entrypoints.https.address=:443
        - --providers.docker.constraints=Label(`traefik.tags`,`${AILTIRE_APPNAME}_cpl_dm_family`)
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      networks:
        - children
  portal:
    image: cpl_dm_web
    deploy:
      replicas: 1
      labels:
        - traefik.tags=${AILTIRE_APPNAME}_cpl_dm_family
        - traefik.enable=true
        - traefik.docker.network=${AILTIRE_APPNAME}_cpl_da_family
        - traefik.http.services.portal.loadbalancer.server.port=3000
        - traefik.http.routers.portal_http.rule=PathPrefix(`/admin`)
        - traefik.http.routers.portal_http.service=portal
        - traefik.http.routers.portal_http.entrypoints=http
    networks:
      - sibling
networks:
  children:
    driver: overlay
    attachable: true
    name: ${AILTIRE_APPNAME}_cpl_dm_family
  sibling:
    driver: overlay
  parent:
    external: true
    name: ${AILTIRE_APPNAME}_cpl_family
