@startuml

left to right direction


boundary ailtire_appname_diml_cds_family #red


entity ailtire_appname_diml_cds_insite_family #black




package "insite" #lightblue {
    queue childrennet #black [
            <b><color:white>children</color></b>
    ]
    
    childrennet -[#black]- ailtire_appname_diml_cds_insite_family
    
    queue siblingnet #blue [
            <b><color:white>sibling</color></b>
    ]
    
    queue parentnet #red [
            <b><color:white>parent</color></b>
    ]
    
    parentnet -[#red]- ailtire_appname_diml_cds_family
    

node "frontend" as frontendService


        artifact "diml_cds_insite_web" as diml_cds_insite_webimage
    
}

frontendService -[#blue]- siblingnet
frontendService .... diml_cds_insite_webimage


@enduml
