@startuml
  interface CLI
  interface Web
  interface WebSocket
package "Insite Services" #lightblue {
  component express as REST
  component socket.io as socket
  folder bin #ffffff {
    component " edgemere diml cds insite" as binName
  }
  binName --> REST

  folder deploy #ffffff {
      file "node server.js\ndocker-compose.yml" as insite_container
      REST --> insite_container

  
    file "web" as web_container
    REST --> web_container
    socket ---> web_container
  
    file "gateway" as gateway_container
    REST --> gateway_container
    socket ---> gateway_container
  
  }
  folder images #ffffff {
    collections "insite" as insiteimage
    artifact "ailtire:swarm" as ailtireswarm
    insiteimage <|-- ailtireswarm
    insite_container --> insiteimage

  
      artifact "diml_cds_insite_web" as diml_cds_insite_web
      web_container --> diml_cds_insite_web
    
      artifact "diml_cds_insite_gw" as diml_cds_insite_gw
      gateway_container --> diml_cds_insite_gw
    
  }
}
CLI " edgemere diml cds insite" -- binName
Web "/edgemere/diml/cds/insite" - REST
WebSocket ".edgemere.diml.cds.insite" -- socket

@enduml
