@startuml

class "PolicyCollection" as Model {

 
}

rectangle "Policy" as Policy #lightblue {
}

Model *--> "n" Policy : policies




    rectangle "Environment" as Environment #lightgreen {
    }
    
        Environment   o--> "1" Model : "policies"
    
    rectangle "Policy" as Policy #lightgreen {
    }
    
        Policy   o--> "1" Model : "owner"
    
    rectangle "SecurityProfile" as SecurityProfile #lightgreen {
    }
    
        SecurityProfile   o--> "1" Model : "policies"
    
    rectangle "MultiCloud" as MultiCloud #lightgreen {
    }
    
        MultiCloud   o--> "1" Model : "polices"
    
    rectangle "Service" as Service #lightgreen {
    }
    
        Service   o--> "1" Model : "policies"
    
    rectangle "Stack" as Stack #lightgreen {
    }
    
        Stack   o--> "1" Model : "policies"
    

@enduml
