@startuml

class "Stack" as Model {
 string name
 string version
 json ports
 json expose
 json parameters

 create()
 createlet()
 debug()
 deploy()
 get()
 show()
 update()
 
}

rectangle "PolicyCollection" as PolicyCollection #lightblue {
}

Model o--> "1" PolicyCollection : policies


rectangle "Stacklet" as Stacklet #lightblue {
}

Model *--> "n" Stacklet : stacklets


rectangle "Service" as Service #lightblue {
}

Model *--> "n" Service : services


rectangle "StackInstance" as StackInstance #lightblue {
}

Model *--> "n" StackInstance : instances


rectangle "Application" as Application #lightblue {
}

Model o--> "1" Application : app


rectangle "DataReference" as DataReference #lightblue {
}

Model *--> "n" DataReference : data


rectangle "Stack" as Stack #lightblue {
}

Model o--> "1" Stack : stack


rectangle "Servicelet" as Servicelet #lightblue {
}

Model *--> "n" Servicelet : servicelets


rectangle "Service" as Service #lightblue {
}

Model o--> "n" Service : children


rectangle "Service" as Service #lightblue {
}

Model o--> "1" Service : parent




    rectangle "Application" as Application #lightgreen {
    }
    
        Application   *--> "n" Model : "stacks"
    
    rectangle "Service" as Service #lightgreen {
    }
    
        Service   o--> "1" Model : "stack"
    
    rectangle "Stack" as Stack #lightgreen {
    }
    
        Stack   o--> "1" Model : "stack"
    
    rectangle "Stacklet" as Stacklet #lightgreen {
    }
    
        Stacklet   o--> "1" Model : "stack"
    
    rectangle "StackletDefinition" as StackletDefinition #lightgreen {
    }
    
        StackletDefinition   o--> "1" Model : "stack"
    
    rectangle "StackInstance" as StackInstance #lightgreen {
    }
    
        StackInstance   o--> "1" Model : "stack"
    

@enduml
