@startuml

actor "Actor"


entity EventBus

box Common Data Service #ffcc88
    boundary cds #white
end box



"Actor" -> cds: Move Data



box "Service Management Layer" #lightgreen
    boundary sml #white
end box
EventBus -\ sml: method()
sml --/ EventBus: Model.Event2

EventBus --/ cds : method2()
@enduml
