@startuml



package "Governance Engine" ##aaffff {

    interface "Governance Engine" as i {
    
    }
}

CLI ()-- i
REST ()-- i
Web ()-- i

package "Governance Engine" ##aaffff {
    
}



@enduml
