@startuml

class "DataReservation" as Model {
 number cost

 
}

rectangle "Data" as Data #lightblue {
}

Model o--> "1" Data : data


rectangle "DataSource" as DataSource #lightblue {
}

Model o--> "1" DataSource : source


rectangle "DataRequest" as DataRequest #lightblue {
}

Model o--> "1" DataRequest : request




    rectangle "DataRequest" as DataRequest #lightgreen {
    }
    
        DataRequest   *--> "n" Model : "reservations"
    

@enduml
