@startuml



state DataReservation #lightblue {

    state Init #lightblue {
    }

    state Created #lightblue {
    }

    state Confirmed #lightblue {
    }

    state Rejected #lightblue {
    }




Init -[#black]--> Created : create

Init -[#black]--> Confirmed : confirm

Init -[#black]--> Rejected : free

Created -[#black]--> Confirmed : confirm

Created -[#black]--> Rejected : free

}


@enduml
