@startuml



state DataReservation ##aaffff {

    state Init ##aaffff {
    }

    state Created ##aaffff {
    }

    state Confirmed ##aaffff {
    }

    state Rejected ##aaffff {
    }




Init -[#black]--> Created : create

Init -[#black]--> Confirmed : confirm

Init -[#black]--> Rejected : free

Created -[#black]--> Confirmed : confirm

Created -[#black]--> Rejected : free

}


@enduml
