@startuml


package "Service Orchestrator" #lightgreen {

}

package "Service Management Layer" #lightgreen {

}

package "Security Aspect" #pink {

}


package "Environment Management" #lightgreen {

    interface "Environment Management" as i {
            /edgemere/sml/em/environment/addpolicies()
            /edgemere/sml/em/environment/create()
            /edgemere/sml/em/environment/destroy()
            /edgemere/sml/em/environment/disable()
            /edgemere/sml/em/environment/enable()
            /edgemere/sml/em/environment/list()
            /edgemere/sml/em/environment/update()
    
    }
}

CLI ()-- i
REST ()-- i
Web ()-- i

package "Environment Management" #lightgreen {


}


    "Environment Management" --> "Service Orchestrator"


@enduml
