@startuml



package "Data Adaptor Framework" ##aaffff {

    interface "Data Adaptor Framework" as i {
    
    }
}

CLI ()-- i
REST ()-- i
Web ()-- i

package "Data Adaptor Framework" ##aaffff {
    
}



@enduml
