@startuml
left to right direction


state "diml" as diml #ffcc88 {
state "ddf" as dimlddf #ffcc88 {
state "daf" as dimlddfdaf #lightblue {
}
}
}


state dimlddfdaf #lightblue {
    state "Custom Function" as daffunction {
    }
}





@enduml
