@startuml



package "Blue Print Management" #lightblue {

    interface "Blue Print Management" as i {
    
    }
}

CLI ()-- i
REST ()-- i
Web ()-- i

package "Blue Print Management" #lightblue {


}



@enduml
