@startuml


package "Workflow Services" #lightblue {

}


package "AI ML Services" #lightblue {

    interface "AI ML Services" as i {
    
    }
}

CLI ()-- i
REST ()-- i
Web ()-- i

package "AI ML Services" #lightblue {


}


    "AI ML Services" --> "Workflow Services"


@enduml
