@startuml

left to right direction


boundary parent #black


entity children #blue




package "diml_dml_ge" #lightblue {
    queue parentnet #black [
            <b><color:white>parent</color></b>
    ]
    
    parentnet -[#black]- parent
    
    queue childrennet #blue [
            <b><color:white>children</color></b>
    ]
    
    childrennet -[#blue]- children
    
    queue siblingsnet #red [
            <b><color:white>siblings</color></b>
    ]
    

node "web" as webService


        artifact "diml_dml_ge_web" as diml_dml_ge_webimage
    
}

webService -[#blue]- childrennet

webService -[#red]- siblingsnet
webService .... diml_dml_ge_webimage


@enduml
