@startuml


usecase "Manage Stacks" as ManageStacks #yellow

Actor "Stack Developer" as StackDeveloper

StackDeveloper --> ManageStacks

Actor "Application Developer" as ApplicationDeveloper

ApplicationDeveloper --> ManageStacks



usecase "BuildStack" as BuildStack #lightgrey

ManageStacks --> BuildStack

usecase "CreateApplicationStack" as CreateApplicationStack #lightgrey

ManageStacks --> CreateApplicationStack

usecase "CreateServiceStack" as CreateServiceStack #lightgrey

ManageStacks --> CreateServiceStack

usecase "DeployStack" as DeployStack #lightgrey

ManageStacks --> DeployStack

usecase "ModifyApplicationStack" as ModifyApplicationStack #lightgrey

ManageStacks --> ModifyApplicationStack

usecase "ModifyServiceStack" as ModifyServiceStack #lightgrey

ManageStacks --> ModifyServiceStack

usecase "TestApplicationStack" as TestApplicationStack #lightgrey

ManageStacks --> TestApplicationStack

usecase "TestServiceStack" as TestServiceStack #lightgrey

ManageStacks --> TestServiceStack

usecase "UninstallStack" as UninstallStack #lightgrey

ManageStacks --> UninstallStack

usecase "UpdateStack" as UpdateStack #lightgrey

ManageStacks --> UpdateStack

usecase "VersionApplicationStack" as VersionApplicationStack #lightgrey

ManageStacks --> VersionApplicationStack

usecase "VersionServiceStack" as VersionServiceStack #lightgrey

ManageStacks --> VersionServiceStack



usecase "Control Virtual Infrastructure" as ControlVirtualInfrastructure #lightyellow

ManageStacks <-- ControlVirtualInfrastructure : extends







@enduml
