@startuml


usecase "Manage Stacks" as ManageStacks #yellow

Actor "Stack Developer" as StackDeveloper

StackDeveloper --> ManageStacks

Actor "Application Developer" as ApplicationDeveloper

ApplicationDeveloper --> ManageStacks



usecase "DeployStack" as DeployStack #lightgrey

ManageStacks --> DeployStack

usecase "UninstallStack" as UninstallStack #lightgrey

ManageStacks --> UninstallStack

usecase "UpdateStack" as UpdateStack #lightgrey

ManageStacks --> UpdateStack









@enduml
