@startuml


actor "DevOpsEngineer"


entity EventBus

box Service Orchestrator #88cc88
    boundary so #white
end box


box Software Defined Infrastructure #cccc88
            participant storageresource
    end box

group Given [A DevOps Engineer has access to data/create]

"DevOpsEngineer" --/ so: 
"so" -> so: Build Stack

    so -> "storageresource": list (name: hello,file: ./templates/world.yml)

    "storageresource" --/ EventBus: data.list

    so -> "storageresource": list (name: hello,file: ./templates/world.yml)

    "storageresource" --/ EventBus: data.list



"DevOpsEngineer" /-- so: A stack is built using the provided file


end

@enduml
