@startuml


actor "ApplicationDeveloper"

actor "StackDeveloper"


entity EventBus

box Service Orchestrator #88cc88
    boundary so #white
end box


box Software Defined Infrastructure #cccc88
            participant storageresource
    end box

group Given [The application and stack developers have access to ./templates/world.yml]

"ApplicationDeveloper" --/ so: ApplicationDeveloper and StackDeveloper use data/list method
"so" -> so: Create Application Stack

    so -> "storageresource": list (name: hello,file: ./templates/world.yml)

    "storageresource" --/ EventBus: data.list

    so -> "storageresource": list (name: hello,file: ./templates/world.yml)

    "storageresource" --/ EventBus: data.list


"StackDeveloper" --/ so: ApplicationDeveloper and StackDeveloper use data/list method
"so" -> so: Create Application Stack

    so -> "storageresource": list (name: hello,file: ./templates/world.yml)

    "storageresource" --/ EventBus: data.list

    so -> "storageresource": list (name: hello,file: ./templates/world.yml)

    "storageresource" --/ EventBus: data.list



"ApplicationDeveloper" /-- so: The &#39;hello&#39; application stack is created

"StackDeveloper" /-- so: The &#39;hello&#39; application stack is created


end

@enduml
