@startuml


actor "DevOps Engineer"


entity EventBus

box Service Orchestrator #88cc88
    boundary so #white
end box


group Given [A DevOps engineer can deploy a stack to an environment with parameters]

"DevOps Engineer" --/ so: Policies are attached to the stack during deployment
"so" -> so: Deploy Stack



"DevOps Engineer" /-- so: Service Orchestrator creates a landscape request to match the stack requirements


end

@enduml
