@startuml

actor "StackDeveloper"


entity EventBus

box Service Orchestrator #88cc88
    boundary so #white
end box


box Software Defined Infrastructure #cccc88
            participant storageresource
    end box


"StackDeveloper" -> so: Test Service Stack

    so -> "storageresource": list (name: hello,file: ./templates/world.yml)

    "storageresource" --/ EventBus: data.list

    so -> "storageresource": list (name: hello,file: ./templates/world.yml)

    "storageresource" --/ EventBus: data.list



@enduml
