@startuml


actor "DevOps Engineer"


entity EventBus

box Service Orchestrator #88cc88
    boundary so #white
end box


group Given [A DevOps Engineer has a running stack with services]

"DevOps Engineer" --/ so: The Engineer decides to shut down the stack
"so" -> so: Uninstall Stack



"DevOps Engineer" /-- so: The stack and all of its services are uninstalled


end

@enduml
