@startuml


actor "DevOps Engineer"


entity EventBus

box Service Orchestrator #88cc88
    boundary so #white
end box


group Given [The DevOps Engineer uses the deployed stack]

"DevOps Engineer" --/ so: Policy changes, updates to stack or service definitions, or environmental changes occur
"so" -> so: Update Stack



"DevOps Engineer" /-- so: The stack is updated using the &#39;stack/update&#39; method


end

@enduml
