@startuml

actor "SecurityEngineer"


entity EventBus

box Security Profile Manager #cc8888
    boundary spm #white
end box


box Software Defined Infrastructure #cccc88
            participant storageresource
    end box

box Security Profile Manager #cc8888
    end box


"SecurityEngineer" -> spm: Monitor Security Profile

    spm -> "storageresource": create (name: secProfileMSP,file: ./templates/secprofile.yml)

    "storageresource" --/ EventBus: securityprofile.create

    spm -> "securityprofile": status (name: secProfileMSP)

    "securityprofile" --/ EventBus: securityprofile.status



@enduml
