@startuml

actor "SecurityEngineer"


entity EventBus

box Security Profile Manager #cc8888
    boundary spm #white
end box


box Software Defined Infrastructure #cccc88
            participant storageresource
    end box

box Security Profile Manager #cc8888
    end box


"SecurityEngineer" -> spm: Test Security Profile

    spm -> "storageresource": create (name: secProfileTSP1,file: ./templates/secprofile.yml)

    "storageresource" --/ EventBus: securityprofile.create

    spm -> "storageresource": create (name: secProfileTSP2,file: ./templates/secprofile.yml)

    "storageresource" --/ EventBus: securityprofile.create

    spm -> "storageresource": create (name: secProfileTSP3,file: ./templates/secprofile.yml)

    "storageresource" --/ EventBus: securityprofile.create

    spm -> "securityprofile": test (name: secProfileTSP1)

    "securityprofile" --/ EventBus: securityprofile.test



@enduml
