version: "3.7"
services:
  frontend:
    image: diml_cds_transform_web
    networks:
      - sibling
  gw:
    image: diml_cds_transform_gw
    networks:
      children:
        aliases:
          - parent
          - top
      sibling:
        aliases:
          - gateway

networks:
  children:
    driver: overlay
    attachable: true
    name: ${AILTIRE_APPNAME}_diml_cds_transform_family
  sibling:
    driver: overlay
  parent:
    external: true
    name: ${AILTIRE_APPNAME}_diml_cds_family
