@startuml


package "Application Management Layer" #lightblue {
    
        class Workload {
        }
    
        class ApplicationInstance {
        }
    }


package "Application Management Layer" #lightblue {

    interface "Application Management Layer" as i {
            /edgemere/aml/aimodel/list()
            /edgemere/aml/application/list()
            /edgemere/aml/workflow/list()
    
    }


    CLI ()-- i
    REST ()-- i
    Web ()-- i
        class "Application" {
                 string name
                 string version
                    }
                Application o--> "n" Workload : workloads
                        Application *--> "n" Stack : stacks
                        Application o--> "n" DataReference : data
                        Application *--> "n" ApplicationInstance : instances
            

    class "ApplicationInstance" {
                 string name
                 string status
                 string message
                    }
                ApplicationInstance o--> "1" ModelName : assoc1
            

    class "ApplicationTemplate" {
                 string attr1
                    }
                ApplicationTemplate o--> "1" ModelName : assoc1
            

    class "Workload" {
                 string attr1
                    }
                Workload o--> "1" ModelName : assoc1
            

    class "WorkloadInstance" {
                 string attr1
                    }
                WorkloadInstance o--> "1" ModelName : assoc1
            

    class "WorkloadTemplate" {
                 string attr1
                    }
                WorkloadTemplate o--> "1" ModelName : assoc1
            




package ams #white {
}

package as #white {
}

package ds #white {
}

package ws #white {
}

}

@enduml
