@startuml
left to right direction


state "aml" as aml #88cccc {
}


state "aml" as pstatename #88cccc {
    state "Custom Function" as amlfunction {
    }
}

        state "aml" as aml #88cccc {
state "aimodel" as amlaimodel #88cccc {
state "create" as amlaimodelcreate #88cccc {
}
}
}


        state "aml" as aml #88cccc {
state "aimodel" as amlaimodel #88cccc {
state "deploy" as amlaimodeldeploy #88cccc {
}
}
}


        state "aml" as aml #88cccc {
state "aimodel" as amlaimodel #88cccc {
state "destroy" as amlaimodeldestroy #88cccc {
}
}
}


        state "aml" as aml #88cccc {
state "aimodel" as amlaimodel #88cccc {
state "list" as amlaimodellist #88cccc {
}
}
}


        state "aml" as aml #88cccc {
state "aimodel" as amlaimodel #88cccc {
state "update" as amlaimodelupdate #88cccc {
}
}
}


        state "aml" as aml #88cccc {
state "application" as amlapplication #88cccc {
state "create" as amlapplicationcreate #88cccc {
}
}
}


        state "aml" as aml #88cccc {
state "application" as amlapplication #88cccc {
state "deploy" as amlapplicationdeploy #88cccc {
}
}
}


        state "aml" as aml #88cccc {
state "application" as amlapplication #88cccc {
state "destroy" as amlapplicationdestroy #88cccc {
}
}
}


        state "aml" as aml #88cccc {
state "application" as amlapplication #88cccc {
state "list" as amlapplicationlist #88cccc {
}
}
}


        state "aml" as aml #88cccc {
state "application" as amlapplication #88cccc {
state "monitor" as amlapplicationmonitor #88cccc {
}
}
}


        state "aml" as aml #88cccc {
state "application" as amlapplication #88cccc {
state "update" as amlapplicationupdate #88cccc {
}
}
}


        state "aml" as aml #88cccc {
state "data" as amldata #88cccc {
state "create" as amldatacreate #88cccc {
}
}
}


        state "aml" as aml #88cccc {
state "workload" as amlworkload #88cccc {
state "create" as amlworkloadcreate #88cccc {
}
}
}


        state "aml" as aml #88cccc {
state "workload" as amlworkload #88cccc {
state "deploy" as amlworkloaddeploy #88cccc {
}
}
}


        state "aml" as aml #88cccc {
state "workload" as amlworkload #88cccc {
state "destroy" as amlworkloaddestroy #88cccc {
}
}
}


        state "aml" as aml #88cccc {
state "workload" as amlworkload #88cccc {
state "list" as amlworkloadlist #88cccc {
}
}
}


        state "aml" as aml #88cccc {
state "workload" as amlworkload #88cccc {
state "monitor" as amlworkloadmonitor #88cccc {
}
}
}


        state "aml" as aml #88cccc {
state "workload" as amlworkload #88cccc {
state "update" as amlworkloadupdate #88cccc {
}
}
}






@enduml
