@startuml
left to right direction


    package "edgemere" as edgemere {
package "aml" as edgemereaml #88cccc {
 component "aimodel" as edgemereamlaimodel
 interface "create" as edgemereamlaimodelcreate
edgemereamlaimodel -- edgemereamlaimodelcreate
}
}

    
    package "edgemere" as edgemere {
package "aml" as edgemereaml #88cccc {
 component "aimodel" as edgemereamlaimodel
 interface "deploy" as edgemereamlaimodeldeploy
edgemereamlaimodel -- edgemereamlaimodeldeploy
}
}

    
    package "edgemere" as edgemere {
package "aml" as edgemereaml #88cccc {
 component "aimodel" as edgemereamlaimodel
 interface "destroy" as edgemereamlaimodeldestroy
edgemereamlaimodel -- edgemereamlaimodeldestroy
}
}

    
    package "edgemere" as edgemere {
package "aml" as edgemereaml #88cccc {
 component "aimodel" as edgemereamlaimodel
 interface "list" as edgemereamlaimodellist
edgemereamlaimodel -- edgemereamlaimodellist
}
}

    
    package "edgemere" as edgemere {
package "aml" as edgemereaml #88cccc {
 component "aimodel" as edgemereamlaimodel
 interface "update" as edgemereamlaimodelupdate
edgemereamlaimodel -- edgemereamlaimodelupdate
}
}

    
    package "edgemere" as edgemere {
package "aml" as edgemereaml #88cccc {
 component "application" as edgemereamlapplication
 interface "create" as edgemereamlapplicationcreate
edgemereamlapplication -- edgemereamlapplicationcreate
}
}

    
    package "edgemere" as edgemere {
package "aml" as edgemereaml #88cccc {
 component "application" as edgemereamlapplication
 interface "deploy" as edgemereamlapplicationdeploy
edgemereamlapplication -- edgemereamlapplicationdeploy
}
}

    
    package "edgemere" as edgemere {
package "aml" as edgemereaml #88cccc {
 component "application" as edgemereamlapplication
 interface "destroy" as edgemereamlapplicationdestroy
edgemereamlapplication -- edgemereamlapplicationdestroy
}
}

    
    package "edgemere" as edgemere {
package "aml" as edgemereaml #88cccc {
 component "application" as edgemereamlapplication
 interface "list" as edgemereamlapplicationlist
edgemereamlapplication -- edgemereamlapplicationlist
}
}

    
    package "edgemere" as edgemere {
package "aml" as edgemereaml #88cccc {
 component "application" as edgemereamlapplication
 interface "monitor" as edgemereamlapplicationmonitor
edgemereamlapplication -- edgemereamlapplicationmonitor
}
}

    
    package "edgemere" as edgemere {
package "aml" as edgemereaml #88cccc {
 component "application" as edgemereamlapplication
 interface "update" as edgemereamlapplicationupdate
edgemereamlapplication -- edgemereamlapplicationupdate
}
}

    
    package "edgemere" as edgemere {
package "aml" as edgemereaml #88cccc {
 component "data" as edgemereamldata
 interface "create" as edgemereamldatacreate
edgemereamldata -- edgemereamldatacreate
}
}

    
    package "edgemere" as edgemere {
package "aml" as edgemereaml #88cccc {
 component "workload" as edgemereamlworkload
 interface "create" as edgemereamlworkloadcreate
edgemereamlworkload -- edgemereamlworkloadcreate
}
}

    
    package "edgemere" as edgemere {
package "aml" as edgemereaml #88cccc {
 component "workload" as edgemereamlworkload
 interface "deploy" as edgemereamlworkloaddeploy
edgemereamlworkload -- edgemereamlworkloaddeploy
}
}

    
    package "edgemere" as edgemere {
package "aml" as edgemereaml #88cccc {
 component "workload" as edgemereamlworkload
 interface "destroy" as edgemereamlworkloaddestroy
edgemereamlworkload -- edgemereamlworkloaddestroy
}
}

    
    package "edgemere" as edgemere {
package "aml" as edgemereaml #88cccc {
 component "workload" as edgemereamlworkload
 interface "list" as edgemereamlworkloadlist
edgemereamlworkload -- edgemereamlworkloadlist
}
}

    
    package "edgemere" as edgemere {
package "aml" as edgemereaml #88cccc {
 component "workload" as edgemereamlworkload
 interface "monitor" as edgemereamlworkloadmonitor
edgemereamlworkload -- edgemereamlworkloadmonitor
}
}

    
    package "edgemere" as edgemere {
package "aml" as edgemereaml #88cccc {
 component "workload" as edgemereamlworkload
 interface "update" as edgemereamlworkloadupdate
edgemereamlworkload -- edgemereamlworkloadupdate
}
}

    


        rectangle "Manage AI Models" as ManageAIModels #ffffaa {
            ("Create AI Model")/ as ApplicationDeveloperManageAIModelsCreateAIModel
        }
    
    edgemereamlaimodelcreate <-- ApplicationDeveloperManageAIModelsCreateAIModel
    
        rectangle "Manage AI Models" as ManageAIModels #ffffaa {
            ("Create AI Model")/ as DataScientistManageAIModelsCreateAIModel
        }
    
    edgemereamlaimodelcreate <-- DataScientistManageAIModelsCreateAIModel
    
        rectangle "Manage AI Models" as ManageAIModels #ffffaa {
            ("Deploy AI Model")/ as DevOpsEngineerManageAIModelsDeployAIModel
        }
    
    edgemereamlaimodeldeploy <-- DevOpsEngineerManageAIModelsDeployAIModel
    
        rectangle "Manage AI Models" as ManageAIModels #ffffaa {
            ("Deploy AI Model")/ as ApplicationDeveloperManageAIModelsDeployAIModel
        }
    
    edgemereamlaimodeldeploy <-- ApplicationDeveloperManageAIModelsDeployAIModel
    
        rectangle "Manage AI Models" as ManageAIModels #ffffaa {
            ("Deploy AI Model")/ as DataEngineerManageAIModelsDeployAIModel
        }
    
    edgemereamlaimodeldeploy <-- DataEngineerManageAIModelsDeployAIModel
    
        rectangle "Manage AI Models" as ManageAIModels #ffffaa {
            ("Destroy AI Model")/ as DataEngineerManageAIModelsDestroyAIModel
        }
    
    edgemereamlaimodeldestroy <-- DataEngineerManageAIModelsDestroyAIModel
    
        rectangle "Manage AI Models" as ManageAIModels #ffffaa {
            ("Destroy AI Model")/ as ApplicationDeveloperManageAIModelsDestroyAIModel
        }
    
    edgemereamlaimodeldestroy <-- ApplicationDeveloperManageAIModelsDestroyAIModel
    
        rectangle "Manage AI Models" as ManageAIModels #ffffaa {
            ("Update AI Model")/ as DataEngineerManageAIModelsUpdateAIModel
        }
    
    edgemereamlaimodelupdate <-- DataEngineerManageAIModelsUpdateAIModel
    
        rectangle "Manage AI Models" as ManageAIModels #ffffaa {
            ("Update AI Model")/ as DevOpsEngineerManageAIModelsUpdateAIModel
        }
    
    edgemereamlaimodelupdate <-- DevOpsEngineerManageAIModelsUpdateAIModel
    
        rectangle "Manage AI Models" as ManageAIModels #ffffaa {
            ("Update AI Model")/ as ApplicationDeveloperManageAIModelsUpdateAIModel
        }
    
    edgemereamlaimodelupdate <-- ApplicationDeveloperManageAIModelsUpdateAIModel
    

        rectangle "Manage Applications" as ManageApplications #ffffaa {
            ("Build Application")/ as DevOpsEngineerManageApplicationsBuildApplication
        }
    
    edgemereamldatacreate <-- DevOpsEngineerManageApplicationsBuildApplication
    
        rectangle "Manage Applications" as ManageApplications #ffffaa {
            ("Create Application")/ as ApplicationDeveloperManageApplicationsCreateApplication
        }
    
    edgemereamlapplicationcreate <-- ApplicationDeveloperManageApplicationsCreateApplication
    
        rectangle "Manage Applications" as ManageApplications #ffffaa {
            ("Deploy Application")/ as DevOpsEngineerManageApplicationsDeployApplication
        }
    
    edgemereamlapplicationdeploy <-- DevOpsEngineerManageApplicationsDeployApplication
    
        rectangle "Manage Applications" as ManageApplications #ffffaa {
            ("Destroy Application")/ as DevOpsEngineerManageApplicationsDestroyApplication
        }
    
    edgemereamlapplicationdestroy <-- DevOpsEngineerManageApplicationsDestroyApplication
    
        rectangle "Manage Applications" as ManageApplications #ffffaa {
            ("Monitor Application")/ as DevOpsEngineerManageApplicationsMonitorApplication
        }
    
    edgemereamlapplicationmonitor <-- DevOpsEngineerManageApplicationsMonitorApplication
    
        rectangle "Manage Applications" as ManageApplications #ffffaa {
            ("Monitor Application")/ as ApplicationDeveloperManageApplicationsMonitorApplication
        }
    
    edgemereamlapplicationmonitor <-- ApplicationDeveloperManageApplicationsMonitorApplication
    
        rectangle "Manage Applications" as ManageApplications #ffffaa {
            ("Update Application")/ as ApplicationDeveloperManageApplicationsUpdateApplication
        }
    
    edgemereamlapplicationupdate <-- ApplicationDeveloperManageApplicationsUpdateApplication
    
        rectangle "Manage Applications" as ManageApplications #ffffaa {
            ("Update Application")/ as DevOpsEngineerManageApplicationsUpdateApplication
        }
    
    edgemereamlapplicationupdate <-- DevOpsEngineerManageApplicationsUpdateApplication
    

        rectangle "Manage Workloads" as ManageWorkloads #ffffaa {
            ("Create Workload")/ as ApplicationDeveloperManageWorkloadsCreateWorkload
        }
    
    edgemereamlworkloadcreate <-- ApplicationDeveloperManageWorkloadsCreateWorkload
    
        rectangle "Manage Workloads" as ManageWorkloads #ffffaa {
            ("Deploy Workload")/ as ApplicationDeveloperManageWorkloadsDeployWorkload
        }
    
    edgemereamlworkloaddeploy <-- ApplicationDeveloperManageWorkloadsDeployWorkload
    
        rectangle "Manage Workloads" as ManageWorkloads #ffffaa {
            ("Deploy Workload")/ as DevOpsEngineerManageWorkloadsDeployWorkload
        }
    
    edgemereamlworkloaddeploy <-- DevOpsEngineerManageWorkloadsDeployWorkload
    
        rectangle "Manage Workloads" as ManageWorkloads #ffffaa {
            ("Destroy Workload")/ as DevOpsEngineerManageWorkloadsDestroyWorkload
        }
    
    edgemereamlworkloaddestroy <-- DevOpsEngineerManageWorkloadsDestroyWorkload
    
        rectangle "Manage Workloads" as ManageWorkloads #ffffaa {
            ("Monitor Workload")/ as ApplicationDeveloperManageWorkloadsMonitorWorkload
        }
    
    edgemereamlworkloadmonitor <-- ApplicationDeveloperManageWorkloadsMonitorWorkload
    
        rectangle "Manage Workloads" as ManageWorkloads #ffffaa {
            ("Monitor Workload")/ as DevOpsEngineerManageWorkloadsMonitorWorkload
        }
    
    edgemereamlworkloadmonitor <-- DevOpsEngineerManageWorkloadsMonitorWorkload
    
        rectangle "Manage Workloads" as ManageWorkloads #ffffaa {
            ("Update Workload")/ as ApplicationDeveloperManageWorkloadsUpdateWorkload
        }
    
    edgemereamlworkloadupdate <-- ApplicationDeveloperManageWorkloadsUpdateWorkload
    
        rectangle "Manage Workloads" as ManageWorkloads #ffffaa {
            ("Update Workload")/ as DevOpsEngineerManageWorkloadsUpdateWorkload
        }
    
    edgemereamlworkloadupdate <-- DevOpsEngineerManageWorkloadsUpdateWorkload
    

        rectangle "Change Physical World" as ChangePhysicalWorld #ffffaa {
            ("Adjust Temperature")/ as ActorChangePhysicalWorldAdjustTemperature
        }
    
    edgemereamldatacreate <-- ActorChangePhysicalWorldAdjustTemperature
    
        rectangle "Change Physical World" as ChangePhysicalWorld #ffffaa {
            ("Toogle Switch")/ as ActorChangePhysicalWorldtoggleSwitch
        }
    
    edgemereamldatacreate <-- ActorChangePhysicalWorldtoggleSwitch
    


        rectangle "Connect Physical Asset to a Device" as ConnectPhysicalAssettoaDevice #ffffaa {
            ("Asset Digital Device Connectivity")/ as ActorConnectPhysicalAssettoaDeviceAssetDigitalDeviceConnectivity
        }
    
    edgemereamldatacreate <-- ActorConnectPhysicalAssettoaDeviceAssetDigitalDeviceConnectivity
    



        rectangle "Monitor Physical World" as MonitorPhysicalWorld #ffffaa {
            ("Continuous Monitoring")/ as ActorMonitorPhysicalWorldContinuousMonitoring
        }
    
    edgemereamldatacreate <-- ActorMonitorPhysicalWorldContinuousMonitoring
    











        rectangle "Manage Meta Data" as ManageMetaData #ffffaa {
            ("Capture Meta Data")/ as DataEngineerManageMetaDataCaptureMetaData
        }
    
    edgemereamldatacreate <-- DataEngineerManageMetaDataCaptureMetaData
    
        rectangle "Manage Meta Data" as ManageMetaData #ffffaa {
            ("Capture Meta Data")/ as DataStewardManageMetaDataCaptureMetaData
        }
    
    edgemereamldatacreate <-- DataStewardManageMetaDataCaptureMetaData
    














        rectangle "Manage Stacks" as ManageStacks #ffffaa {
            ("Build Stack")/ as DevOpsEngineerManageStacksBuildStack
        }
    
    edgemereamldatacreate <-- DevOpsEngineerManageStacksBuildStack
    
        rectangle "Manage Stacks" as ManageStacks #ffffaa {
            ("Create Application Stack")/ as ApplicationDeveloperManageStacksCreateApplicationStack
        }
    
    edgemereamldatacreate <-- ApplicationDeveloperManageStacksCreateApplicationStack
    
        rectangle "Manage Stacks" as ManageStacks #ffffaa {
            ("Create Application Stack")/ as StackDeveloperManageStacksCreateApplicationStack
        }
    
    edgemereamldatacreate <-- StackDeveloperManageStacksCreateApplicationStack
    
        rectangle "Manage Stacks" as ManageStacks #ffffaa {
            ("Create Service Stack")/ as StackDeveloperManageStacksCreateServiceStack
        }
    
    edgemereamldatacreate <-- StackDeveloperManageStacksCreateServiceStack
    
        rectangle "Manage Stacks" as ManageStacks #ffffaa {
            ("Modify Application Stack")/ as StackDeveloperManageStacksModifyApplicationStack
        }
    
    edgemereamldatacreate <-- StackDeveloperManageStacksModifyApplicationStack
    
        rectangle "Manage Stacks" as ManageStacks #ffffaa {
            ("Modify Application Stack")/ as ApplicationDeveloperManageStacksModifyApplicationStack
        }
    
    edgemereamldatacreate <-- ApplicationDeveloperManageStacksModifyApplicationStack
    
        rectangle "Manage Stacks" as ManageStacks #ffffaa {
            ("Modify Service Stack")/ as StackDeveloperManageStacksModifyServiceStack
        }
    
    edgemereamldatacreate <-- StackDeveloperManageStacksModifyServiceStack
    
        rectangle "Manage Stacks" as ManageStacks #ffffaa {
            ("Test Application Stack")/ as StackDeveloperManageStacksTestApplicationStack
        }
    
    edgemereamldatacreate <-- StackDeveloperManageStacksTestApplicationStack
    
        rectangle "Manage Stacks" as ManageStacks #ffffaa {
            ("Test Application Stack")/ as ApplicationDeveloperManageStacksTestApplicationStack
        }
    
    edgemereamldatacreate <-- ApplicationDeveloperManageStacksTestApplicationStack
    
        rectangle "Manage Stacks" as ManageStacks #ffffaa {
            ("Test Service Stack")/ as StackDeveloperManageStacksTestServiceStack
        }
    
    edgemereamldatacreate <-- StackDeveloperManageStacksTestServiceStack
    
        rectangle "Manage Stacks" as ManageStacks #ffffaa {
            ("Version Application Stack")/ as ApplicationDeveloperManageStacksVersionApplicationStack
        }
    
    edgemereamldatacreate <-- ApplicationDeveloperManageStacksVersionApplicationStack
    
        rectangle "Manage Stacks" as ManageStacks #ffffaa {
            ("Version Service Stack")/ as StackDeveloperManageStacksVersionServiceStack
        }
    
    edgemereamldatacreate <-- StackDeveloperManageStacksVersionServiceStack
    



        rectangle "Manage Services" as ManageServices #ffffaa {
            ("Build Service")/ as StackDeveloperManageServicesBuildService
        }
    
    edgemereamldatacreate <-- StackDeveloperManageServicesBuildService
    








@enduml
