@startuml


package "Distributed Information Management Layer" #ffcc88 {

}

package "Service Management Layer" #88cc88 {

}

package "Security Aspect" #cc8888 {

}

package "Identity Aspect" #cc8888 {

}

package "Application Management Layer" #88cccc {

}

package "Data Management Layer" #ffcc88 {

}


package "Application Management Layer" #88cccc {

    interface "Application Management Layer" as i {
            ^aimodel.create
            ^aimodel.updated
            ^application.create
            ^application.updated
    
            /edgemere/aml/aimodel/create()
            /edgemere/aml/aimodel/deploy()
            /edgemere/aml/aimodel/destroy()
            /edgemere/aml/aimodel/list()
            /edgemere/aml/aimodel/scan()
            /edgemere/aml/aimodel/sign()
            /edgemere/aml/aimodel/update()
            /edgemere/aml/aimodel/validate()
            /edgemere/aml/application/create()
            /edgemere/aml/application/deploy()
            /edgemere/aml/application/destroy()
            /edgemere/aml/application/list()
            /edgemere/aml/application/monitor()
            /edgemere/aml/application/update()
            /edgemere/aml/data/create()
            /edgemere/aml/workload/create()
            /edgemere/aml/workload/deploy()
            /edgemere/aml/workload/destroy()
            /edgemere/aml/workload/list()
            /edgemere/aml/workload/monitor()
            /edgemere/aml/workload/update()
    
    }
}

circle REST
circle Web
circle CLI
circle WebSocket

i -down- Web
i -down- CLI
i -down- REST
WebSocket -left- i: events >

package "Application Management Layer" #88cccc {


rectangle "AI ML Services" #white {
}

rectangle "Analytics Services" #white {
}

rectangle "Developer Services" #white {
}

rectangle "Workflow Services" #white {
}

    "AI ML Services" --> "Workflow Services"
    
    "Analytics Services" --> "Workflow Services"
    
    "Developer Services" --> "Security Aspect"
    
    "Workflow Services" --> "Developer Services"
    
    "Workflow Services" --> "Identity Aspect"
    
}


    "Distributed Information Management Layer" <-- "Application Management Layer"

    "Service Management Layer" <-- "Application Management Layer"

    "Security Aspect" <-- "Application Management Layer"

    "Identity Aspect" <-- "Application Management Layer"


@enduml
