@startuml

left to right direction
Actor "Data Scientist" as DataScientist
Actor "DevOps Engineer" as DevOpsEngineer
Actor "ApplicationDeveloper" as ApplicationDeveloper
Actor "DataEngineer" as DataEngineer
Actor "DevOps Engineer" as DevOpsEngineer
Actor "Application Developer" as ApplicationDeveloper
Actor "Application Developer" as ApplicationDeveloper
Actor "DevOps Engineer" as DevOpsEngineer


rectangle "Application Management Layer" #lightblue {
usecase "ManageAIModels" as ManageAIModels
    DataScientist --> ManageAIModels
    DevOpsEngineer --> ManageAIModels
    ApplicationDeveloper --> ManageAIModels
    DataEngineer --> ManageAIModels
    usecase "ManageApplications" as ManageApplications
    DevOpsEngineer --> ManageApplications
    ApplicationDeveloper --> ManageApplications
    usecase "ManageWorkloads" as ManageWorkloads
    ApplicationDeveloper --> ManageWorkloads
    DevOpsEngineer --> ManageWorkloads
    }


@enduml
