@startuml

actor "Data Scientist" as datascientist

actor "DevOps Engineer" as devops

actor "Application Developer" as appdev




datascientist -> "Application Management Layer": Manage AI Models
"Application Management Layer" -> bin: AIModel/list
bin -> REST: AIModel/list

devops -> "Application Management Layer": Manage AI Models
"Application Management Layer" -> bin: AIModel/list
bin -> REST: AIModel/list

devops -> "Application Management Layer": Manage Applications
"Application Management Layer" -> bin: application/list
bin -> REST: application/list

appdev -> "Application Management Layer": Manage Applications
"Application Management Layer" -> bin: application/list
bin -> REST: application/list

appdev -> "Application Management Layer": Manage Workflows
"Application Management Layer" -> bin: workflow/list
bin -> REST: workflow/list


@enduml
