@startuml



state Resource #cccc88 {

    state Init #cccc88 {
    }

    state Provisioning #cccc88 {
    }

    state Failed #cccc88 {
    }

    state Ready #cccc88 {
    }

    state Disabled #cccc88 {
    }




Init -[#black]--> Provisioning : provision

Init -[#black]--> Disabled : disable

Provisioning -[#black]--> Ready : finishedProvision

Provisioning -[#black]--> Failed : failedProvision

Ready -[#black]--> Disabled : disable

}

 
 Provisioning -[#black]--> Null
 
 
 Ready -[#black]--> Null
 

@enduml
