@startuml



state Resource #lightyellow {

    state Init #lightyellow {
    }

    state Provisioning #lightyellow {
    }

    state Failed #lightyellow {
    }

    state Ready #lightyellow {
    }

    state Disabled #lightyellow {
    }

}


Init --> Provisioning : provision

Init --> Disabled : disable

Provisioning --> Ready : finishedProvision

Provisioning --> Failed : failedProvision

Ready --> Disabled : disable



 state "edgemere" as edgemere #lightgray {
state "cpl" as edgemerecpl #lightgray {
state "provision" as edgemerecplprovision #lightgray {
}
}
}

 Provisioning -[#black]--> edgemerecplprovision
 
 
 Ready -[#black]--> Null
 

@enduml
