@startuml



state Resource #lightyellow {

    state Init #lightyellow {
    }

    state Provisioning #lightyellow {
    }

    state Failed #lightyellow {
    }

    state Ready #lightyellow {
    }

    state Disabled #lightyellow {
    }

}


Init --> Provisioning : provision

Init --> Disabled : disable

Provisioning --> Ready : finishedProvision

Provisioning --> Failed : failedProvision

Ready --> Disabled : disable



 state "cpl" as cpl #lightgray {
state "provision" as cplprovision #lightgray {
}
}

 Provisioning -[#black]--> cplprovision
 
 state "sdi" as sdi #lightyellow {
state "request" as sdirequest #lightyellow {
state "reserve" as sdirequestreserve #lightyellow {
}
}
}

 Ready -[#black]--> sdirequestreserve
 

@enduml
