@startuml

left to right direction


boundary ailtire_appname_aml_family #red


entity ailtire_appname_aml_as_family #black




package "amlas" #lightblue {
    queue childrennet #black [
            <b><color:white>children</color></b>
    ]
    
    childrennet -[#black]- ailtire_appname_aml_as_family
    
    queue siblingnet #blue [
            <b><color:white>sibling</color></b>
    ]
    
    queue parentnet #red [
            <b><color:white>parent</color></b>
    ]
    
    parentnet -[#red]- ailtire_appname_aml_family
    

node "frontend" as frontendService
node "gw" as gwService


        artifact "aml_as_web" as aml_as_webimage
    
        artifact "aml_as_gw" as aml_as_gwimage
    
}

frontendService -[#blue]- siblingnet

gwService -[#black]- childrennet

gwService -[#blue]- siblingnet
frontendService .... aml_as_webimage
gwService .... aml_as_gwimage


@enduml
