@startuml

left to right direction




node "aml_as" as aml_asStack #88cccc {
    portin "parent" as aml_asStackPortIn #blue
}
node "aml_ds" as aml_dsStack #aaffff {
    portin "parent" as aml_dsStackPortIn #blue
}
node "aml_ws" as aml_wsStack #88cccc {
    portin "parent" as aml_wsStackPortIn #blue
}
node "aml_ams" as aml_amsStack #88cccc {
    portin "parent" as aml_amsStackPortIn #blue
}



node "aml" #88cccc {


    hexagon parentnet #black [
            <b><color:white>parent</color></b>
    ]
    
    portin " " as parentnetPortIn #black
    parentnetPortIn -[#black]- parentnet
    
    hexagon childrennet #blue [
            <b><color:white>children</color></b>
    ]
    
    portout " " as childrennetPortOut #blue
    childrennet -[#blue]- childrennetPortOut
    
    hexagon siblingsnet #red [
            <b><color:white>siblings</color></b>
    ]
    

node "aml_web" as aml_webService #white {
    portOut " " as aml_webServicechildrennet #blue
   aml_webServicechildrennet -[#blue]- childrennet
       portOut " " as aml_webServicesiblingsnet #red
   aml_webServicesiblingsnet -[#red]- siblingsnet
   

    artifact "aml_web" as aml_webimage
    
}
node "aml_as" as aml_asService #white {
    portOut " " as aml_asServicechildrennet #blue
   aml_asServicechildrennet -[#blue]- childrennet
   
    collections "aml_as" as aml_asimage
    
}
node "aml_ds" as aml_dsService #white {
    portOut " " as aml_dsServicechildrennet #blue
   aml_dsServicechildrennet -[#blue]- childrennet
   
    collections "aml_ds" as aml_dsimage
    
}
node "aml_ws" as aml_wsService #white {
    portOut " " as aml_wsServicechildrennet #blue
   aml_wsServicechildrennet -[#blue]- childrennet
   
    collections "aml_ws" as aml_wsimage
    
}
node "aml_ams" as aml_amsService #white {
    portOut " " as aml_amsServicechildrennet #blue
   aml_amsServicechildrennet -[#blue]- childrennet
   
    collections "aml_ams" as aml_amsimage
    
}

}

aml_asimage --> aml_asStack
    
    childrennetPortOut -[#blue]- aml_asStackPortIn
    
aml_dsimage --> aml_dsStack
    
    childrennetPortOut -[#blue]- aml_dsStackPortIn
    
aml_wsimage --> aml_wsStack
    
    childrennetPortOut -[#blue]- aml_wsStackPortIn
    
aml_amsimage --> aml_amsStack
    
    childrennetPortOut -[#blue]- aml_amsStackPortIn
    

@enduml
