@startuml
  interface CLI
  interface Web
  interface WebSocket
package "Application Management Layer" #lightblue {
  component express as REST
  component socket.io as socket
  folder bin #ffffff {
    component " edgemere aml" as binName
  }
  binName --> REST

  folder deploy #ffffff {
      file "node server.js\ndocker-compose.yml" as aml_container
      REST --> aml_container

  
    file "node web/server.js" as web_container
    REST --> web_container
    socket ---> web_container
  
    file "node gateway/server.js" as gateway_container
    REST --> gateway_container
    socket ---> gateway_container
  
  }
  folder images #ffffff {
    collections "aml" as amlimage
    artifact "ailtire:swarm" as ailtireswarm
    amlimage <|-- ailtireswarm
    aml_container --> amlimage

  
      artifact aml_web
      web_container --> aml_web
    
      artifact aml_gw
      gateway_container --> aml_gw
    
  }
}
CLI " edgemere aml" -- binName
Web "/edgemere/aml" - REST
WebSocket ".edgemere.aml" -- socket

@enduml
