@startuml


package "Data Management Layer" #ffcc88 {

}

package "Data Orchestrator" #lightblue {

}

package "Data Definition Framework" #ffcc88 {

}


package "Data Orchestrator" #lightblue {

    interface "Data Orchestrator" as i {
            /edgemere/diml/dml/do/evaluate()
            /edgemere/diml/dml/do/reserve()
            /edgemere/diml/dml/do/datainstance/create()
            /edgemere/diml/dml/do/datainstance/destroy()
            /edgemere/diml/dml/do/datainstance/find()
            /edgemere/diml/dml/do/datainstance/list()
    
    }
}

CLI ()-- i
REST ()-- i
Web ()-- i

package "Data Orchestrator" #lightblue {


}



@enduml
