@startuml

class "LineageMetaData" as Model {
 string creationAction
 string name
 string value

 
}

rectangle "DataInstance" as DataInstance #lightblue {
}

Model o--> "n" DataInstance : parents


rectangle "Data" as Data #lightblue {
}

Model o--> "1" Data : data




    rectangle "Data" as Data #lightgreen {
    }
    
        Data   *--> "n" Model : "lineage"
    

@enduml
