@startuml

left to right direction


Actor "Data Scientist" as DataScientist


rectangle "AI ML Services" as ams #88cccc {
        usecase "addTo AIModel" as addToAIModel
    DataScientist --> addToAIModel
    usecase "create AIModel" as createAIModel
    DataScientist --> createAIModel
    usecase "destroy AIModel" as destroyAIModel
    DataScientist --> destroyAIModel
    usecase "removeFrom AIModel" as removeFromAIModel
    DataScientist --> removeFromAIModel
    usecase "update AIModel" as updateAIModel
    DataScientist --> updateAIModel

}

rectangle "Application Management Layer" as aml #88cccc {
        usecase "Manage AI Models" as ManageAIModels
    DataScientist --> ManageAIModels

}

rectangle "Common Data Service" as cds #ffcc88 {
        usecase "Manage Data" as ManageData
    DataScientist --> ManageData

}

rectangle "Data Definition Framework" as ddf #ffcc88 {
        usecase "Manage Data Adaptors" as ManageDataAdaptors
    DataScientist --> ManageDataAdaptors
    usecase "Manage Data Blue Prints" as ManageDataBluePrints
    DataScientist --> ManageDataBluePrints
    usecase "Manage Meta Data" as ManageMetaData
    DataScientist --> ManageMetaData

}

rectangle "Data Orchestrator" as do ##aaffff {
        usecase "Manage Data Instances" as ManageDataInstances
    DataScientist --> ManageDataInstances

}

rectangle "edgemere" as edgemere #ccaaff {
        usecase "Provide Business Information" as ProvideBusinessInformation
    DataScientist --> ProvideBusinessInformation

}


@enduml
