@startuml

left to right direction


boundary ailtire_appname_aml_family #red


entity ailtire_appname_aml_ws_family #black




package "amlws" #lightblue {
    queue childrennet #black [
            <b><color:white>children</color></b>
    ]
    
    childrennet -[#black]- ailtire_appname_aml_ws_family
    
    queue siblingnet #blue [
            <b><color:white>sibling</color></b>
    ]
    
    queue parentnet #red [
            <b><color:white>parent</color></b>
    ]
    
    parentnet -[#red]- ailtire_appname_aml_family
    

node "frontend" as frontendService
node "gw" as gwService


        artifact "aml_ws_web" as aml_ws_webimage
    
        artifact "aml_ws_gw" as aml_ws_gwimage
    
}

frontendService -[#blue]- siblingnet

gwService -[#black]- childrennet

gwService -[#blue]- siblingnet
frontendService .... aml_ws_webimage
gwService .... aml_ws_gwimage


@enduml
