@startuml


package "Common Physical Layer" #lightblue {
    
        class PhysicalProfile {
        }
    
        class Device {
        }
    
        class DataCenter {
        }
    
        class Hardware {
        }
    
        class AggregatedDevice {
        }
    
        class Metric {
        }
    
        class MetricComposite {
        }
    }

package "Software Defined Infrastructure" #lightblue {
    
        class Resource {
        }
    }


package "Common Physical Layer" #lightblue {

    interface "Common Physical Layer" as i {
            /edgemere/cpl/adddevices()
            /edgemere/cpl/provision()
            /edgemere/cpl/reserve()
            /edgemere/cpl/data/govern()
            /edgemere/cpl/datacenter/list()
            /edgemere/cpl/device/disable()
            /edgemere/cpl/device/enable()
    
    }


    CLI ()-- i
    REST ()-- i
    Web ()-- i
        class "AcceleratorHardware" {
                 string name
                 string ename
                             create()
                     factory()
            }
                AcceleratorHardware o--> "1" PhysicalProfile : profile
                        AcceleratorHardware o--> "1" Device : device
                        AcceleratorHardware o--> "n" Resource : resources
            

    class "AggregatedDevice" {
                 string name
                 string ename
                 string type
                             addDevices()
                     reserve()
                     addToHardware()
                     create()
                     disable()
                     enable()
                     getReservations()
                     provision()
            }
                AggregatedDevice *--> "n" Device : devices
                        AggregatedDevice o--> "1" PhysicalProfile : profile
                        AggregatedDevice o--> "1" DataCenter : datacenter
                        AggregatedDevice *--> "n" Hardware : hardware
                        AggregatedDevice o--> "1" AggregatedDevice : parent
            

    class "ComputeHardware" {
                 string name
                 string ename
                             create()
                     factory()
            }
                ComputeHardware o--> "1" PhysicalProfile : profile
                        ComputeHardware o--> "1" Device : device
                        ComputeHardware o--> "n" Resource : resources
            

    class "DataCenter" {
                 string name
                             addAdevices()
                     addDevices()
                     reserve()
            }
                DataCenter o--> "1" PhysicalProfile : profile
                        DataCenter *--> "n" Device : devices
                        DataCenter *--> "n" AggregatedDevice : adevices
            

    class "Device" {
                 string name
                 string ename
                 string type
                             addToHardware()
                     create()
                     disable()
                     enable()
                     getReservations()
                     provision()
                     reserve()
            }
                Device o--> "1" PhysicalProfile : profile
                        Device *--> "n" Hardware : hardware
                        Device o--> "1" DataCenter : datacenter
                        Device o--> "1" AggregatedDevice : parent
            

    class "Hardware" {
                 string name
                 string ename
                             create()
                     factory()
            }
                Hardware o--> "1" PhysicalProfile : profile
                        Hardware o--> "1" Device : device
                        Hardware o--> "n" Resource : resources
            

    class "Metric" {
                 string name
                 string value
                             copy()
                     factory()
                     greaterThanEq()
                     lessThanEq()
                     minus()
                     plus()
            }
    

    class "MetricAttribute" {
                 string name
                 string value
                             copy()
                     lessThanEq()
                     minus()
                     plus()
                     valueToString()
                     factory()
                     greaterThanEq()
            }
    

    class "MetricComposite" {
                 string name
                 string value
                             create()
                     findMatchDeep()
                     lessThanEq()
                     minus()
                     plus()
                     copy()
                     factory()
                     greaterThanEq()
            }
                MetricComposite *--> "n" Metric : values
            

    class "MetricConsumeable" {
                 string name
                 string value
                             create()
                     valueToString()
                     copy()
                     factory()
                     greaterThanEq()
                     lessThanEq()
                     minus()
                     plus()
            }
    

    class "NetworkHardware" {
                 string name
                 string ename
                             create()
                     factory()
            }
                NetworkHardware o--> "1" PhysicalProfile : profile
                        NetworkHardware o--> "1" Device : device
                        NetworkHardware o--> "n" Resource : resources
            

    class "PhysicalProfile" {
                 string name
                             combine()
                     create()
                     propagate()
                     satisfies()
                     stats()
            }
                PhysicalProfile *--> "1" MetricComposite : capabilities
                        PhysicalProfile *--> "1" MetricComposite : available
                        PhysicalProfile *--> "1" MetricComposite : reserved
                        PhysicalProfile *--> "1" MetricComposite : metrics
                        PhysicalProfile o--> "1" PhysicalProfile : parent
            

    class "StorageHardware" {
                 string name
                 string ename
                             create()
                     factory()
            }
                StorageHardware o--> "1" PhysicalProfile : profile
                        StorageHardware o--> "1" Device : device
                        StorageHardware o--> "n" Resource : resources
            




}

@enduml
