@startuml
left to right direction


state "cpl" as cpl #lightgray {
}


state "cpl" as pstatename #lightgray {
    state "Custom Function" as cplfunction {
    }
}

        state "cpl" as cpl #lightgray {
state "adddevices" as cpladddevices #lightgray {
}
}


        state "cpl" as cpl #lightgray {
state "provision" as cplprovision #lightgray {
}
}


        state "cpl" as cpl #lightgray {
state "reserve" as cplreserve #lightgray {
}
}


        state "cpl" as cpl #lightgray {
state "data" as cpldata #lightgray {
state "govern" as cpldatagovern #lightgray {
}
}
}


        state "cpl" as cpl #lightgray {
state "data" as cpldata #lightgray {
state "source" as cpldatasource #lightgray {
}
}
}


        state "cpl" as cpl #lightgray {
state "datacenter" as cpldatacenter #lightgray {
state "create" as cpldatacentercreate #lightgray {
}
}
}


        state "cpl" as cpl #lightgray {
state "datacenter" as cpldatacenter #lightgray {
state "disable" as cpldatacenterdisable #lightgray {
}
}
}


        state "cpl" as cpl #lightgray {
state "datacenter" as cpldatacenter #lightgray {
state "enable" as cpldatacenterenable #lightgray {
}
}
}


        state "cpl" as cpl #lightgray {
state "datacenter" as cpldatacenter #lightgray {
state "list" as cpldatacenterlist #lightgray {
}
}
}


        state "cpl" as cpl #lightgray {
state "datacenter" as cpldatacenter #lightgray {
state "remove" as cpldatacenterremove #lightgray {
}
}
}


        state "cpl" as cpl #lightgray {
state "datacenter" as cpldatacenter #lightgray {
state "update" as cpldatacenterupdate #lightgray {
}
}
}


        state "cpl" as cpl #lightgray {
state "device" as cpldevice #lightgray {
state "disable" as cpldevicedisable #lightgray {
}
}
}


        state "cpl" as cpl #lightgray {
state "device" as cpldevice #lightgray {
state "enable" as cpldeviceenable #lightgray {
}
}
}




        state "sdi" as sdi #lightyellow {
state "Request" as sdirequest #lightyellow {
state "needed" as sdirequestneeded #lightyellow {
}
}
}

        
    state "cpl" as cpl #lightgray {
state "reserve" as cplreserve #lightgray {
}
}

    sdirequestneeded ---> cplreserve
  

        state "sdi" as sdi #lightyellow {
state "Reservation" as sdireservation #lightyellow {
state "rejected" as sdireservationrejected #lightyellow {
}
}
}

        
    state "cpl" as cpl #lightgray {
state "Function" as cplfunction #lightgray {
}
}

    sdireservationrejected ---> cplfunction
  

        state "sdi" as sdi #lightyellow {
state "Resource" as sdiresource #lightyellow {
state "provisioning" as sdiresourceprovisioning #lightyellow {
}
}
}

        
    state "cpl" as cpl #lightgray {
state "provision" as cplprovision #lightgray {
}
}

    sdiresourceprovisioning ---> cplprovision
  


    state "cpl" as cpl #lightgray {
state "Device" as cpldevice #lightgray {
state "stats" as cpldevicestats #lightgray {
}
}
}

    state "ta" as ta #lavender {
state "report" as tareport #lavender {
}
}

        cpldevicestats ---> tareport
       
    
    state "tc" as tc #lavender {
state "report" as tcreport #lavender {
}
}

        cpldevicestats ---> tcreport
       
    
    
        
       
    
    
        
       

@enduml
