@startuml
left to right direction


    package "edgemere" as edgemere {
 component "cpl" as edgemerecpl
 interface "adddevices" as edgemerecpladddevices
edgemerecpl -- edgemerecpladddevices
}

    
    package "edgemere" as edgemere {
 component "cpl" as edgemerecpl
 interface "provision" as edgemerecplprovision
edgemerecpl -- edgemerecplprovision
}

    
    package "edgemere" as edgemere {
 component "cpl" as edgemerecpl
 interface "reserve" as edgemerecplreserve
edgemerecpl -- edgemerecplreserve
}

    
    package "edgemere" as edgemere {
package "cpl" as edgemerecpl #cccccc {
 component "data" as edgemerecpldata
 interface "govern" as edgemerecpldatagovern
edgemerecpldata -- edgemerecpldatagovern
}
}

    
    package "edgemere" as edgemere {
package "cpl" as edgemerecpl #cccccc {
 component "data" as edgemerecpldata
 interface "source" as edgemerecpldatasource
edgemerecpldata -- edgemerecpldatasource
}
}

    
    package "edgemere" as edgemere {
package "cpl" as edgemerecpl #cccccc {
 component "datacenter" as edgemerecpldatacenter
 interface "create" as edgemerecpldatacentercreate
edgemerecpldatacenter -- edgemerecpldatacentercreate
}
}

    
    package "edgemere" as edgemere {
package "cpl" as edgemerecpl #cccccc {
 component "datacenter" as edgemerecpldatacenter
 interface "disable" as edgemerecpldatacenterdisable
edgemerecpldatacenter -- edgemerecpldatacenterdisable
}
}

    
    package "edgemere" as edgemere {
package "cpl" as edgemerecpl #cccccc {
 component "datacenter" as edgemerecpldatacenter
 interface "enable" as edgemerecpldatacenterenable
edgemerecpldatacenter -- edgemerecpldatacenterenable
}
}

    
    package "edgemere" as edgemere {
package "cpl" as edgemerecpl #cccccc {
 component "datacenter" as edgemerecpldatacenter
 interface "list" as edgemerecpldatacenterlist
edgemerecpldatacenter -- edgemerecpldatacenterlist
}
}

    
    package "edgemere" as edgemere {
package "cpl" as edgemerecpl #cccccc {
 component "datacenter" as edgemerecpldatacenter
 interface "remove" as edgemerecpldatacenterremove
edgemerecpldatacenter -- edgemerecpldatacenterremove
}
}

    
    package "edgemere" as edgemere {
package "cpl" as edgemerecpl #cccccc {
 component "datacenter" as edgemerecpldatacenter
 interface "update" as edgemerecpldatacenterupdate
edgemerecpldatacenter -- edgemerecpldatacenterupdate
}
}

    
    package "edgemere" as edgemere {
package "cpl" as edgemerecpl #cccccc {
 component "device" as edgemerecpldevice
 interface "disable" as edgemerecpldevicedisable
edgemerecpldevice -- edgemerecpldevicedisable
}
}

    
    package "edgemere" as edgemere {
package "cpl" as edgemerecpl #cccccc {
 component "device" as edgemerecpldevice
 interface "enable" as edgemerecpldeviceenable
edgemerecpldevice -- edgemerecpldeviceenable
}
}

    
hexagon "request.needed" as requestneeded
            edgemerecpl <-- requestneeded
        
hexagon "reservation.rejected" as reservationrejected
            edgemerecpl <-- reservationrejected
        
hexagon "resource.provisioning" as resourceprovisioning
            edgemerecpl <-- resourceprovisioning
        





        rectangle "Manage Data Center" as ManageDataCenter #ffffaa {
            ("Create Data Center")/ as ITOperationsManageDataCenterCreateDataCenter
        }
    
    edgemerecpldatacentercreate <-- ITOperationsManageDataCenterCreateDataCenter
    
        rectangle "Manage Data Center" as ManageDataCenter #ffffaa {
            ("Disable Data Center")/ as ITOperationsManageDataCenterDisableDataCenter
        }
    
    edgemerecpldatacenterdisable <-- ITOperationsManageDataCenterDisableDataCenter
    
        rectangle "Manage Data Center" as ManageDataCenter #ffffaa {
            ("Enable Data Center")/ as ITOperationsManageDataCenterEnableDataCenter
        }
    
    edgemerecpldatacenterenable <-- ITOperationsManageDataCenterEnableDataCenter
    
        rectangle "Manage Data Center" as ManageDataCenter #ffffaa {
            ("Remove Data Center")/ as ITOperationsManageDataCenterRemoveDataCenter
        }
    
    edgemerecpldatacenterremove <-- ITOperationsManageDataCenterRemoveDataCenter
    
        rectangle "Manage Data Center" as ManageDataCenter #ffffaa {
            ("Update Data Center")/ as ITOperationsManageDataCenterUpdateDataCenter
        }
    
    edgemerecpldatacenterupdate <-- ITOperationsManageDataCenterUpdateDataCenter
    

        rectangle "Manage Infrastructure" as ManageInfrastructure #ffffaa {
            ("Add Device")/ as ITOperationsManageInfrastructureAddDevice
        }
    
    edgemerecpldatasource <-- ITOperationsManageInfrastructureAddDevice
    
        rectangle "Manage Infrastructure" as ManageInfrastructure #ffffaa {
            ("Manage Aggregated Devices")/ as ITOperationsManageInfrastructureManageAggregatedDevices
        }
    
    edgemerecpldatasource <-- ITOperationsManageInfrastructureManageAggregatedDevices
    
        rectangle "Manage Infrastructure" as ManageInfrastructure #ffffaa {
            ("Manage Data Center")/ as ITOperationsManageInfrastructureManageDataCenter
        }
    
    edgemerecpldatasource <-- ITOperationsManageInfrastructureManageDataCenter
    
        rectangle "Manage Infrastructure" as ManageInfrastructure #ffffaa {
            ("Remove Device")/ as ITOperationsManageInfrastructureRemoveDevice
        }
    
    edgemerecpldatasource <-- ITOperationsManageInfrastructureRemoveDevice
    
        rectangle "Manage Infrastructure" as ManageInfrastructure #ffffaa {
            ("Update Device")/ as ITOperationsManageInfrastructureUpdateDevice
        }
    
    edgemerecpldatasource <-- ITOperationsManageInfrastructureUpdateDevice
    































@enduml
