@startuml


package "Common Physical Layer" #cccccc {

}

package "Software Defined Infrastructure" #cccc88 {

}


package "Common Physical Layer" #cccccc {

    interface "Common Physical Layer" as i {
            ^request.needed
            ^reservation.rejected
            ^resource.provisioning
    
            /edgemere/cpl/adddevices()
            /edgemere/cpl/provision()
            /edgemere/cpl/reserve()
            /edgemere/cpl/data/govern()
            /edgemere/cpl/data/source()
            /edgemere/cpl/datacenter/create()
            /edgemere/cpl/datacenter/disable()
            /edgemere/cpl/datacenter/enable()
            /edgemere/cpl/datacenter/list()
            /edgemere/cpl/datacenter/remove()
            /edgemere/cpl/datacenter/update()
            /edgemere/cpl/device/disable()
            /edgemere/cpl/device/enable()
    
    }
}

circle REST
circle Web
circle CLI
circle WebSocket

i -down- Web
i -down- CLI
i -down- REST
WebSocket -left- i: events >

package "Common Physical Layer" #cccccc {


rectangle "Cyber" #white {
}

rectangle "Device Agent" #white {
}

rectangle "Device Manager" #white {
}

rectangle "PhysicalWorld" #white {
}

rectangle "Telemetry Aggregator" #white {
}

rectangle "Telemetry Consumer" #white {
}

rectangle "Telemetry Producer" #white {
}

}



@enduml
