@startuml

left to right direction
Actor "IT Operations" as ITOperations
Actor "IT Operations" as ITOperations


rectangle "Common Physical Layer" #cccccc {
usecase "ManageDataCenter" as ManageDataCenter
    ITOperations --> ManageDataCenter
    usecase "ManageInfrastructure" as ManageInfrastructure
    ITOperations --> ManageInfrastructure
    }


@enduml
