FROM node:21.2-alpine3.18

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)

COPY ./deploy/producer/package.json ./
RUN npm install
COPY . .

EXPOSE 3000
CMD [ "node", "deploy/tester/server.js" ]
