@startuml
  interface CLI
  interface Web
  interface WebSocket
node "Governance Engine" ##aaffff {
  component express as REST
  component socket.io as socket
  folder bin #ffffff {
    card " edgemere diml dml ge" as binName
  }
  binName --> REST

  folder deploy #ffffff {
      file "node server.js\n" as diml_dml_ge_container
      REST --> diml_dml_ge_container

  
    file "web" as web_container
    REST --> web_container
    socket ---> web_container
  
  }
  folder images #ffffff {
    collections "diml_dml_ge" as diml_dml_geimage
    artifact "ailtire:swarm" as ailtireswarm
    diml_dml_geimage <|-- ailtireswarm
    diml_dml_ge_container --> diml_dml_geimage

  
      artifact "diml_dml_ge_web" as diml_dml_ge_web
      web_container --> diml_dml_ge_web
    
  }
}
CLI " edgemere diml dml ge" -- binName
Web "/edgemere/diml/dml/ge" - REST
WebSocket ".edgemere.diml.dml.ge" -- socket

@enduml
