@startuml

class "DataCenter" as Model {
 string name

 addAdevices()
 addDevices()
 reserve()
 
}

rectangle "PhysicalProfile" as PhysicalProfile {
}

Model o--> "1" PhysicalProfile : profile


rectangle "Device" as Device {
}

Model *--> "n" Device : devices


rectangle "AggregatedDevice" as AggregatedDevice {
}

Model *--> "n" AggregatedDevice : adevices




@enduml
