@startuml


left to right direction

usecase "Manage Meta Data" as ManageMetaData #yellow

Actor "Data Scientist" as DataScientist

DataScientist --> ManageMetaData



json CaptureMetaData #lightyellow {
    "Given": "Data Engineer and Data Steward are using data create method",
    "When": "Data blueprint and sources are created and deployed for simulation",
    "Then": "Specific owner&#39;s data can be searched and found"
}

ManageMetaData <|-- CaptureMetaData

json ManageDataCatalog #lightyellow {
    "Given": "A data scientist wants to manage the data catalog",
    "When": "The data scientist uses the &#39;datacatalog/list&#39; method",
    "Then": "The data scientist should be able to manage the data catalog"
}

ManageMetaData <|-- ManageDataCatalog



usecase "Provide Business Information" as ProvideBusinessInformation #lightyellow

ManageMetaData <-- ProvideBusinessInformation : extends







@enduml
