@startuml


usecase "Manage Meta Data" as ManageMetaData #yellow

Actor "Data Scientist" as DataScientist

DataScientist --> ManageMetaData



usecase "CaptureMetaData" as CaptureMetaData #lightgrey

ManageMetaData --> CaptureMetaData

usecase "ManageDataCatalog" as ManageDataCatalog #lightgrey

ManageMetaData --> ManageDataCatalog









@enduml
