@startuml


actor "DataScientist"


entity EventBus

box Data Definition Framework #ffcc88
    boundary ddf #white
end box


group Given [A data scientist wants to manage the data catalog]

"DataScientist" --/ ddf: The data scientist uses the &#39;datacatalog/list&#39; method
"ddf" -> ddf: Manage Data Catalog



"DataScientist" /-- ddf: The data scientist should be able to manage the data catalog


end

@enduml
