@startuml

actor "DataScientist"


entity EventBus

box Data Definition Framework #ffcc88
    boundary ddf #white
end box



"DataScientist" -> ddf: Manage Data Catalog



box "Data Management Layer" #ffcc88
    boundary dml #white
end box
EventBus -\ dml: method()
dml --/ EventBus: Model.Event2

EventBus --/ ddf : method2()
@enduml
