@startuml

left to right direction







node "diml_ddf_dr" #lightblue {


    hexagon parentnet #black [
            <b><color:white>parent</color></b>
    ]
    
    portin " " as parentnetPortIn #black
    parentnetPortIn -[#black]- parentnet
    
    hexagon childrennet #blue [
            <b><color:white>children</color></b>
    ]
    
    portout " " as childrennetPortOut #blue
    childrennet -[#blue]- childrennetPortOut
    
    hexagon siblingsnet #red [
            <b><color:white>siblings</color></b>
    ]
    

node "web" as webService #white {
    portOut " " as webServicechildrennet #blue
   webServicechildrennet -[#blue]- childrennet
       portOut " " as webServicesiblingsnet #red
   webServicesiblingsnet -[#red]- siblingsnet
   

    artifact "diml_ddf_dr_web" as diml_ddf_dr_webimage
    
}

}


@enduml
