@startuml

class "DataAdaptor" as Model {
 string name

 create()
 
}

rectangle "DataBluePrint" as DataBluePrint #lightblue {
}

Model o--> "1" DataBluePrint : blueprint


rectangle "DataSource" as DataSource #lightblue {
}

Model *--> "n" DataSource : sources


rectangle "DataAdaptorInstance" as DataAdaptorInstance #lightblue {
}

Model *--> "n" DataAdaptorInstance : instances




    rectangle "DataAdaptorInstance" as DataAdaptorInstance #lightgreen {
    }
    
        DataAdaptorInstance   o--> "1" Model : "parent"
    
    rectangle "DataAdaptorTemplate" as DataAdaptorTemplate #lightgreen {
    }
    
        DataAdaptorTemplate   o--> "1" Model : "adaptor"
    
    rectangle "DataSource" as DataSource #lightgreen {
    }
    
        DataSource   o--> "1" Model : "adaptor"
    
    rectangle "Data" as Data #lightgreen {
    }
    
        Data   o--> "1" Model : "adaptor"
    

@enduml
