@startuml
left to right direction


state "diml" as diml #ffcc88 {
state "dml" as dimldml #ffcc88 {
state "ge" as dimldmlge #lightblue {
}
}
}


state dimldmlge #lightblue {
    state "Custom Function" as gefunction {
    }
}





@enduml
