@startuml

left to right direction


boundary ailtire_appname_sdi_family #red


entity ailtire_appname_sdi_io_family #black




package "sdi_io" #lightyellow {
    queue childrennet #black [
            <b><color:white>children</color></b>
    ]
    
    childrennet -[#black]- ailtire_appname_sdi_io_family
    
    queue siblingnet #blue [
            <b><color:white>sibling</color></b>
    ]
    
    queue parentnet #red [
            <b><color:white>parent</color></b>
    ]
    
    parentnet -[#red]- ailtire_appname_sdi_family
    

node "frontend" as frontendService
node "gw" as gwService


        artifact "sdi_io_web" as sdi_io_webimage
    
        artifact "sdi_io_gw" as sdi_io_gwimage
    
}

frontendService -[#blue]- siblingnet

gwService -[#black]- childrennet

gwService -[#blue]- siblingnet
frontendService .... sdi_io_webimage
gwService .... sdi_io_gwimage


@enduml
