@startuml

left to right direction


boundary parent #black


entity children #blue




package "sdi_io" #cccc88 {
    queue parentnet #black [
            <b><color:white>parent</color></b>
    ]
    
    parentnet -[#black]- parent
    
    queue childrennet #blue [
            <b><color:white>children</color></b>
    ]
    
    childrennet -[#blue]- children
    
    queue siblingsnet #red [
            <b><color:white>siblings</color></b>
    ]
    

node "web" as webService


        artifact "sdi_io_web" as sdi_io_webimage
    
}

webService -[#blue]- childrennet

webService -[#red]- siblingsnet
webService .... sdi_io_webimage


@enduml
