@startuml

left to right direction


boundary appname_a_d_family #red


entity appname_a_d_af_family #black




package "a_d_af" #lightblue {
    queue childrennet #black [
            <b><color:white>children</color></b>
    ]
    
    childrennet -[#black]- appname_a_d_af_family
    
    queue siblingnet #blue [
            <b><color:white>sibling</color></b>
    ]
    
    queue parentnet #red [
            <b><color:white>parent</color></b>
    ]
    
    parentnet -[#red]- appname_a_d_family
    

node "child" as childService
node "frontend" as frontendService
node "gw" as gwService


        artifact "child_image:latest" as child_imagelatestimage
    
        artifact "a_d_af_web" as a_d_af_webimage
    
        artifact "a_d_af_gw" as a_d_af_gwimage
    
}

childService -[#black]- childrennet

childService -[#red]- parentnet

frontendService -[#blue]- siblingnet

gwService -[#black]- childrennet

gwService -[#blue]- siblingnet
childService .... child_imagelatestimage
frontendService .... a_d_af_webimage
gwService .... a_d_af_gwimage


@enduml
