@startuml

left to right direction






node "cpl_tp" #cccccc {


    hexagon parentnet #black [
            <b><color:white>parent</color></b>
    ]
    
    portin " " as parentnetPortIn #black
    parentnetPortIn -[#black]- parentnet
    
    hexagon telemetrynet #blue [
            <b><color:white>telemetry</color></b>
    ]
    
    portin " " as telemetrynetPortIn #blue
    telemetrynetPortIn -[#blue]- telemetrynet
    

node "producer" as producerService #white {

    portIn " " as producerServiceparentnet #black
    parentnet -[#black]- producerServiceparentnet
    
    portIn " " as producerServicetelemetrynet #blue
    telemetrynet -[#blue]- producerServicetelemetrynet
    

    artifact "cpl_tp_producer:latest" as cpl_tp_producerlatestimage
    
}

}


@enduml
