@startuml



state Environment #88cc88 {

    state Init #88cc88 {
    }

    state Enabled #88cc88 {
    }

    state Disabled #88cc88 {
    }




Init -[#black]--> Enabled : create

Enabled -[#black]--> Disabled : disable

Disabled -[#black]--> Enabled : enable

}


@enduml
