@startuml


usecase "Find Resources" as FindResources #yellow

Actor "IT Operations" as ITOperations

ITOperations --> FindResources





usecase "Control Virtual Infrastructure" as ControlVirtualInfrastructure #lightyellow

FindResources <-- ControlVirtualInfrastructure : extends







@enduml
