@startuml
left to right direction


state "diml" as diml #ffcc88 {
state "cds" as dimlcds #ffcc88 {
state "insite" as dimlcdsinsite ##aaffff {
}
}
}


state "dimlcdsinsite" as pstatename ##aaffff {
    state "Custom Function" as insitefunction {
    }
}





@enduml
