@startuml

left to right direction


Actor "Data Scientist" as DataScientist


rectangle "Application Management Layer" as aml #lightblue {
        usecase "Manage AI Models" as ManageAIModels
    DataScientist --> ManageAIModels

}

rectangle "Common Data Service" as cds #ffcc88 {
        usecase "Manage Data" as ManageData
    DataScientist --> ManageData

}

rectangle "Data Definition Framework" as ddf #ffcc88 {
        usecase "Manage Data Adaptors" as ManageDataAdaptors
    DataScientist --> ManageDataAdaptors
    usecase "Manage Data Blue Prints" as ManageDataBluePrints
    DataScientist --> ManageDataBluePrints
    usecase "Manage Meta Data" as ManageMetaData
    DataScientist --> ManageMetaData

}

rectangle "Data Orchestrator" as do #lightblue {
        usecase "Manage Data Instances" as ManageDataInstances
    DataScientist --> ManageDataInstances

}


@enduml
