@startuml
  interface CLI
  interface Web
  interface WebSocket
node "AI ML Services" #88cccc {
  component express as REST
  component socket.io as socket
  folder bin #ffffff {
    card " edgemere aml ams" as binName
  }
  binName --> REST

  folder deploy #ffffff {
      file "node server.js\n" as aml_ams_container
      REST --> aml_ams_container


    file "web" as web_container
    REST --> web_container
    socket ---> web_container

  }
  folder images #ffffff {
    collections "aml_ams" as aml_amsimage
    artifact "ailtire:swarm" as ailtireswarm
    aml_amsimage <|-- ailtireswarm
    aml_ams_container --> aml_amsimage


      artifact "aml_ams_web" as aml_ams_web
      web_container --> aml_ams_web

  }
}
CLI " edgemere aml ams" -- binName
Web "/edgemere/aml/ams" - REST
WebSocket ".edgemere.aml.ams" -- socket

@enduml
