@startuml



state Reservation #lightyellow {

    state Init #lightyellow {
    }

    state Created #lightyellow {
    }

    state Confirmed #lightyellow {
    }

    state Rejected #lightyellow {
    }

}


Init --> Created : create

Init --> Confirmed : confirm

Init --> Rejected : free

Created --> Confirmed : confirm

Created --> Rejected : free



 state "sdi" as sdi #lightyellow {
state "io" as sdiio #lightyellow {
state "provision" as sdiioprovision #lightyellow {
}
}
}

 Confirmed -[#black]--> sdiioprovision
 
 state "cpl" as cpl #lightgray {
state "Function" as cplFunction #lightgray {
}
}

 Rejected -[#black]--> cplFunction
 

@enduml
