@startuml
  interface CLI
  interface Web
  interface WebSocket
node "Provision Engine" #88cc88 {
  component express as REST
  component socket.io as socket
  folder bin #ffffff {
    card " edgemere sml pe" as binName
  }
  binName --> REST

  folder deploy #ffffff {
      file "node server.js\n" as sml_pe_container
      REST --> sml_pe_container


    file "web" as web_container
    REST --> web_container
    socket ---> web_container

  }
  folder images #ffffff {
    collections "sml_pe" as sml_peimage
    artifact "ailtire:swarm" as ailtireswarm
    sml_peimage <|-- ailtireswarm
    sml_pe_container --> sml_peimage


      artifact "sml_pe_web" as sml_pe_web
      web_container --> sml_pe_web

  }
}
CLI " edgemere sml pe" -- binName
Web "/edgemere/sml/pe" - REST
WebSocket ".edgemere.sml.pe" -- socket

@enduml
