@startuml

left to right direction


boundary parent #black


entity children #blue

rectangle "aml" as amlStack #88cccc {
    queue amlStacksnet #blue [
        <b><color:white>parent</color></b>
    ]
}
rectangle "cpl" as cplStack #cccccc {
    queue cplStacksnet #blue [
        <b><color:white>parent</color></b>
    ]
}
rectangle "diml" as dimlStack #ffcc88 {
    queue dimlStacksnet #blue [
        <b><color:white>parent</color></b>
    ]
}
rectangle "ia" as iaStack #cc8888 {
    queue iaStacksnet #blue [
        <b><color:white>parent</color></b>
    ]
}
rectangle "sa" as saStack #cc8888 {
    queue saStacksnet #blue [
        <b><color:white>parent</color></b>
    ]
}
rectangle "sml" as smlStack #88cc88 {
    queue smlStacksnet #blue [
        <b><color:white>parent</color></b>
    ]
}
rectangle "sdi" as sdiStack #cccc88 {
    queue sdiStacksnet #blue [
        <b><color:white>parent</color></b>
    ]
}



package "edgemere" #lavender {
    queue parentnet #black [
            <b><color:white>parent</color></b>
    ]
    
    parentnet -[#black]- parent
    
    queue childrennet #blue [
            <b><color:white>children</color></b>
    ]
    
    childrennet -[#blue]- children
    
    queue siblingsnet #red [
            <b><color:white>siblings</color></b>
    ]
    

node "aml" as amlService
node "cpl" as cplService
node "diml" as dimlService
node "ia" as iaService
node "sa" as saService
node "sml" as smlService
node "sdi" as sdiService
node "web" as webService
node "doc" as docService

        collections "aml" as amlimage
            collections "cpl" as cplimage
            collections "diml" as dimlimage
            collections "ia" as iaimage
            collections "sa" as saimage
            collections "sml" as smlimage
            collections "sdi" as sdiimage
    
        artifact "edgemere_web" as edgemere_webimage
    
        artifact "edgemere_doc" as edgemere_docimage
    
}

amlService -[#blue]- childrennet

cplService -[#blue]- childrennet

dimlService -[#blue]- childrennet

iaService -[#blue]- childrennet

saService -[#blue]- childrennet

smlService -[#blue]- childrennet

sdiService -[#blue]- childrennet

webService -[#blue]- childrennet

webService -[#red]- siblingsnet

docService -[#red]- siblingsnet
amlService .... amlimage
cplService .... cplimage
dimlService .... dimlimage
iaService .... iaimage
saService .... saimage
smlService .... smlimage
sdiService .... sdiimage
webService .... edgemere_webimage
docService .... edgemere_docimage

amlimage --> amlStack
    
cplimage --> cplStack
    
dimlimage --> dimlStack
    
iaimage --> iaStack
    
saimage --> saStack
    
smlimage --> smlStack
    
sdiimage --> sdiStack
    

@enduml
