@startuml

class "BuildLedger" as Model {
 string name

 
}

rectangle "LedgerEntry" as LedgerEntry #lightblue {
}

Model *--> "n" LedgerEntry : entries


rectangle "BuildInstance" as BuildInstance #lightblue {
}

Model o--> "1" BuildInstance : parent




    rectangle "Build" as Build #lightgreen {
    }
    
        Build   *--> "1" Model : "ledger"
    
    rectangle "BuildInstance" as BuildInstance #lightgreen {
    }
    
        BuildInstance   *--> "1" Model : "ledger"
    

@enduml
