@startuml


package "Common Physical Layer" #lightgray {
    
        class PhysicalProfile {
        }
    
        class Hardware {
        }
    
        class Device {
        }
    
        class AggregatedDevice {
        }
    
        class DataCenter {
        }
    
        class MetricComposite {
        }
    }

package "Software Defined Infrastructure" #lightyellow {
    
        class Request {
        }
    
        class Cloud {
        }
    
        class Resource {
        }
    
        class Reservation {
        }
    }

package "Service Orchestrator" #lightgreen {
    
        class ServiceInstance {
        }
    }

package "Cloud Broker" #lightgreen {
    
        class CloudType {
        }
    }


package "Software Defined Infrastructure" #lightyellow {

    interface "Software Defined Infrastructure" as i {
            /edgemere/sdi/checkrequest()
            /edgemere/sdi/reserve()
            /edgemere/sdi/resource/get()
            /edgemere/sdi/resource/list()
            /edgemere/sdi/resource/release()
    
    }
}

CLI ()-- i
REST ()-- i
Web ()-- i

package "Software Defined Infrastructure" #lightyellow {
        class "AcceleratorResource" {
                 string name
                 string ename
                 boolean disabled
                 string type
                             factory()
                     provision()
            }
                AcceleratorResource o--> "1" Request : request
                        AcceleratorResource *--> "1" PhysicalProfile : profile
                        AcceleratorResource o--> "n" Hardware : hardware
                        AcceleratorResource o--> "n" ServiceInstance : instances
                        AcceleratorResource o--> "1" Cloud : cloud
            
    
        Resource <|-- AcceleratorResource
    
    class "Cloud" {
                 string name
                 string ename
                             create()
                     reserve()
            }
                Cloud o--> "1" CloudType : type
                        Cloud *--> "n" Resource : resources
                        Cloud o--> "n" Device : devices
                        Cloud o--> "n" AggregatedDevice : adevices
                        Cloud o--> "n" DataCenter : datacenters
                        Cloud *--> "n" Reservation : reservations
                        Cloud *--> "n" Request : requests
            
    
    class "ComputeResource" {
                 string name
                 string ename
                 boolean disabled
                 string type
                             factory()
                     provision()
            }
                ComputeResource o--> "1" Request : request
                        ComputeResource *--> "1" PhysicalProfile : profile
                        ComputeResource o--> "n" Hardware : hardware
                        ComputeResource o--> "n" ServiceInstance : instances
                        ComputeResource o--> "1" Cloud : cloud
            
    
        Resource <|-- ComputeResource
    
    class "NetworkResource" {
                 string name
                 string ename
                 boolean disabled
                 string type
                             factory()
                     provision()
            }
                NetworkResource o--> "1" Request : request
                        NetworkResource *--> "1" PhysicalProfile : profile
                        NetworkResource o--> "n" Hardware : hardware
                        NetworkResource o--> "n" ServiceInstance : instances
                        NetworkResource o--> "1" Cloud : cloud
            
    
        Resource <|-- NetworkResource
    
    class "Request" {
                 string name
                 string ename
                 string type
                 string message
                             confirm()
                     evaluated()
                     failed()
                     fulfill()
                     satisfied()
            }
                Request *--> "1" MetricComposite : requirements
                        Request *--> "n" Reservation : reservations
                        Request *--> "n" Resource : resources
                        Request o--> "1" Cloud : cloud
                        Request o--> "n" DataCenter : datacenters
                        Request o--> "n" Device : devices
                        Request o--> "n" AggregatedDevice : aggregates
            
    
    class "Reservation" {
                 number cost
                             confirm()
                     create()
                     free()
            }
                Reservation o--> "1" Device : device
                        Reservation o--> "1" Request : request
                        Reservation o--> "1" Cloud : cloud
            
    
    class "Resource" {
                 string name
                 string ename
                 boolean disabled
                 string type
                             factory()
                     provision()
            }
                Resource o--> "1" Request : request
                        Resource *--> "1" PhysicalProfile : profile
                        Resource o--> "n" Hardware : hardware
                        Resource o--> "n" ServiceInstance : instances
                        Resource o--> "1" Cloud : cloud
            
    
    class "StorageResource" {
                 string name
                 string ename
                 boolean disabled
                 string type
                             factory()
                     provision()
            }
                StorageResource o--> "1" Request : request
                        StorageResource *--> "1" PhysicalProfile : profile
                        StorageResource o--> "n" Hardware : hardware
                        StorageResource o--> "n" ServiceInstance : instances
                        StorageResource o--> "1" Cloud : cloud
            
    
        Resource <|-- StorageResource
    

}


    "Software Defined Infrastructure" --> "Common Physical Layer"


@enduml
