@startuml


package "Software Defined Infrastructure" #lightblue {
    
        class Resource {
        }
    
        class Reservation {
        }
    
        class Request {
        }
    
        class Cloud {
        }
    }

package "Common Physical Layer" #lightblue {
    
        class Device {
        }
    
        class AggregatedDevice {
        }
    
        class DataCenter {
        }
    
        class MetricComposite {
        }
    
        class PhysicalProfile {
        }
    
        class Hardware {
        }
    }


package "Software Defined Infrastructure" #lightblue {

    interface "Software Defined Infrastructure" as i {
            /edgemere/sdi/getresources()
            /edgemere/sdi/listresources()
            /edgemere/sdi/releaseresources()
            /edgemere/sdi/reserve()
            /edgemere/sdi/sdi/getresources()
    
    }


    CLI ()-- i
    REST ()-- i
    Web ()-- i
        class "Cloud" {
                 string name
                 string ename
                             reserve()
            }
                Cloud *--> "n" Resource : resources
                        Cloud o--> "n" Device : devices
                        Cloud o--> "n" AggregatedDevice : adevices
                        Cloud o--> "n" DataCenter : datacenters
                        Cloud *--> "n" Reservation : reservations
                        Cloud *--> "n" Request : requests
            

    class "Request" {
                 string name
                 string ename
                 string type
                             confirm()
            }
                Request *--> "1" MetricComposite : requirements
                        Request *--> "n" Reservation : reservations
                        Request o--> "1" Cloud : cloud
                        Request o--> "1" LandscapeRequest : parent
            

    class "Reservation" {
                 number cost
                             confirm()
                     create()
                     free()
            }
                Reservation o--> "1" Device : device
                        Reservation o--> "1" Request : request
                        Reservation o--> "1" Cloud : cloud
            

    class "Resource" {
                 string name
                 string ename
                 boolean disabled
                 string type
                    }
                Resource *--> "1" PhysicalProfile : profile
                        Resource o--> "n" Hardware : hardware
                        Resource o--> "n" ServiceInstance : instances
                        Resource o--> "1" Cloud : cloud
            




}

@enduml
