@startuml
left to right direction


state "sdi" as sdi #cccc88 {
}


state "sdi" as pstatename #cccc88 {
    state "Custom Function" as sdifunction {
    }
}

        state "sdi" as sdi #cccc88 {
state "checkrequest" as sdicheckrequest #cccc88 {
}
}


        state "sdi" as sdi #cccc88 {
state "reserve" as sdireserve #cccc88 {
}
}


        state "sdi" as sdi #cccc88 {
state "resource" as sdiresource #cccc88 {
state "get" as sdiresourceget #cccc88 {
}
}
}


        state "sdi" as sdi #cccc88 {
state "resource" as sdiresource #cccc88 {
state "list" as sdiresourcelist #cccc88 {
}
}
}


        state "sdi" as sdi #cccc88 {
state "resource" as sdiresource #cccc88 {
state "release" as sdiresourcerelease #cccc88 {
}
}
}




        state "sdi" as sdi #cccc88 {
state "Request" as sdirequest #cccc88 {
state "satisfied" as sdirequestsatisfied #cccc88 {
}
}
}

        
    state "sdi" as sdi #cccc88 {
state "Function" as sdifunction #cccc88 {
}
}

    sdirequestsatisfied ---> sdifunction
  

        state "sdi" as sdi #cccc88 {
state "Resource" as sdiresource #cccc88 {
state "ready" as sdiresourceready #cccc88 {
}
}
}

        
    state "sdi" as sdi #cccc88 {
state "request" as sdirequest #cccc88 {
state "reserve" as sdirequestreserve #cccc88 {
}
}
}

    sdiresourceready ---> sdirequestreserve
  


    state "sdi" as sdi #cccc88 {
state "Request" as sdirequest #cccc88 {
state "needed" as sdirequestneeded #cccc88 {
}
}
}

    state "cpl" as cpl #cccccc {
state "reserve" as cplreserve #cccccc {
}
}

        sdirequestneeded ---> cplreserve
       
    state "sdi" as sdi #cccc88 {
state "Reservation" as sdireservation #cccc88 {
state "rejected" as sdireservationrejected #cccc88 {
}
}
}

    state "cpl" as cpl #cccccc {
state "Function" as cplfunction #cccccc {
}
}

        sdireservationrejected ---> cplfunction
       
    state "sdi" as sdi #cccc88 {
state "Resource" as sdiresource #cccc88 {
state "provisioning" as sdiresourceprovisioning #cccc88 {
}
}
}

    state "cpl" as cpl #cccccc {
state "provision" as cplprovision #cccccc {
}
}

        sdiresourceprovisioning ---> cplprovision
       
    state "sdi" as sdi #cccc88 {
state "Request" as sdirequest #cccc88 {
state "selected" as sdirequestselected #cccc88 {
}
}
}

    state "sdi" as sdi #cccc88 {
state "io" as sdiio #cccc88 {
state "evaluateRequest" as sdiioevaluaterequest #cccc88 {
}
}
}

        sdirequestselected ---> sdiioevaluaterequest
       
    state "sdi" as sdi #cccc88 {
state "Reservation" as sdireservation #cccc88 {
state "confirmed" as sdireservationconfirmed #cccc88 {
}
}
}

    state "sdi" as sdi #cccc88 {
state "io" as sdiio #cccc88 {
state "provision" as sdiioprovision #cccc88 {
}
}
}

        sdireservationconfirmed ---> sdiioprovision
       
    
    
        
       
    
    state "sdi" as sdi #cccc88 {
state "request" as sdirequest #cccc88 {
state "reserve" as sdirequestreserve #cccc88 {
}
}
}

        
       

@enduml
