@startuml
left to right direction


    package "edgemere" as edgemere {
 component "sdi" as edgemeresdi
 interface "checkrequest" as edgemeresdicheckrequest
edgemeresdi -- edgemeresdicheckrequest
}

    
    package "edgemere" as edgemere {
 component "sdi" as edgemeresdi
 interface "reserve" as edgemeresdireserve
edgemeresdi -- edgemeresdireserve
}

    
    package "edgemere" as edgemere {
package "sdi" as edgemeresdi #cccc88 {
 component "resource" as edgemeresdiresource
 interface "get" as edgemeresdiresourceget
edgemeresdiresource -- edgemeresdiresourceget
}
}

    
    package "edgemere" as edgemere {
package "sdi" as edgemeresdi #cccc88 {
 component "resource" as edgemeresdiresource
 interface "list" as edgemeresdiresourcelist
edgemeresdiresource -- edgemeresdiresourcelist
}
}

    
    package "edgemere" as edgemere {
package "sdi" as edgemeresdi #cccc88 {
 component "resource" as edgemeresdiresource
 interface "release" as edgemeresdiresourcerelease
edgemeresdiresource -- edgemeresdiresourcerelease
}
}

    
hexagon "request.satisfied" as requestsatisfied
            edgemeresdi <-- requestsatisfied
        
hexagon "resource.ready" as resourceready
            edgemeresdi <-- resourceready
        






























        rectangle "Manage Resources" as ManageResources #ffffaa {
            ("Get Resources")/ as ITOperationsManageResourcesGetResources
        }
    
    edgemeresdiresourceget <-- ITOperationsManageResourcesGetResources
    
        rectangle "Manage Resources" as ManageResources #ffffaa {
            ("List Resources")/ as ITOperationsManageResourcesListResources
        }
    
    edgemeresdiresourcelist <-- ITOperationsManageResourcesListResources
    
        rectangle "Manage Resources" as ManageResources #ffffaa {
            ("Release Resources")/ as ITOperationsManageResourcesReleaseResources
        }
    
    edgemeresdiresourcerelease <-- ITOperationsManageResourcesReleaseResources
    







@enduml
