@startuml
left to right direction



state "IT Operations" as ITOperations {
    state "Manage Resources" as ITOperationsManageResources {
    }
}
state "edgemere" as edgemere #lightyellow {
state "sdi" as edgemeresdi #lightyellow {
state "resource" as edgemeresdiresource #lightyellow {
state "list" as edgemeresdiresourcelist #lightyellow {
}
}
}
}

ITOperationsManageResources --> edgemeresdiresourcelist


    state "IT Operations" as ITOperations {
        state "Manage Resources" as ITOperationsManageResources {
            state "Get Resources" as ITOperationsManageResourcesGetResources {
            }
        }
    }
    
    ITOperationsManageResourcesGetResources --> Null
    
 
    state "IT Operations" as ITOperations {
        state "Manage Resources" as ITOperationsManageResources {
            state "List Resources" as ITOperationsManageResourcesListResources {
            }
        }
    }
    
    ITOperationsManageResourcesListResources --> Null
    
 
    state "IT Operations" as ITOperations {
        state "Manage Resources" as ITOperationsManageResources {
            state "Release Resources" as ITOperationsManageResourcesReleaseResources {
            }
        }
    }
    
    ITOperationsManageResourcesReleaseResources --> Null
    
 
 

@enduml
