@startuml


package "Common Physical Layer" #cccccc {

}

package "Software Defined Infrastructure" #cccc88 {

}

package "Service Orchestrator" #88cc88 {

}

package "Cloud Broker" #88cc88 {

}


package "Software Defined Infrastructure" #cccc88 {

    interface "Software Defined Infrastructure" as i {
            ^request.satisfied
            ^resource.ready
    
            /edgemere/sdi/checkrequest()
            /edgemere/sdi/reserve()
            /edgemere/sdi/resource/get()
            /edgemere/sdi/resource/list()
            /edgemere/sdi/resource/release()
    
    }
}

circle REST
circle Web
circle CLI
circle WebSocket

i -down- Web
i -down- CLI
i -down- REST
WebSocket -left- i: events >

package "Software Defined Infrastructure" #cccc88 {


rectangle "Infrastructure Orchestrator" #white {
}

}


    "Common Physical Layer" <-- "Software Defined Infrastructure"


@enduml
