@startuml


actor "ITOperations" as itops




itops -> "Software Defined Infrastructure": Manage Resources
"Software Defined Infrastructure" -> bin: resource list
bin -> REST: resource/list



@enduml
