@startuml

left to right direction

actor :Application\nDeveloper: as User

rectangle "Application Management Layer" #lightBlue {
    UseCase MA as "Manage\nApplications" #white
    UseCase MW as "Manage\nWorkloads" #white
    UseCase MM as "Manage\nModels" #white
    UseCase UC2 as "Deploy\nApplication" #lightgray
    UseCase UC7 as "Deploy\nModel" #lightgray
    UseCase UC4 as "Update\nApplication" #lightgray
    UseCase UC5 as "Update\nModel" #lightgray
    UseCase UC11 as "Update\nWorkload" #lightgray
    UseCase UC12 as "Deploy\nWorkload" #lightgray
    UseCase UC9 as "Monitor\nApplication" #lightgray
    UseCase UC13 as "Monitor\nWorkload" #lightgray
}
rectangle "Service Management Layer" #lightgreen {
    UseCase MS as "Manage\nServices" #white
    UseCase UC3 as "Deploy\nService" #lightgray
    UseCase UC6 as "Update\nService" #lightgray
    UseCase UC8 as "Monitor\nService" #lightgray
}


User --> MS
User --> MA
User --> MW
User --> MM
MA ..> MS
MA ..> MM
MM ..> UC7
MM ..> UC5
UC2 ..> UC9
MA ..> UC4
UC12 ..> UC13
UC13 ..> UC9
UC9 ..> UC8
MW ..> MA
MW .> UC11
MW .> UC12
UC12 .> UC2
UC11 .> UC4
UC2 ..> UC7
MA ..> UC2
UC2 ..> UC3
UC4 ..> UC6
UC4 ..> UC5

@enduml

