version: "3.7"
services:
  consumer:
    image: cpl_tc_web:latest
    ports:
    - "3001:3001"
    environment:
      - AILTIRE_STACKNAME={{.Service.Name}}-{{.Task.Slot}}
      - AILTIRE_PARENT=${AILTIRE_STACKNAME}
      - AILTIRE_PARENTHOST=${AILTIRE_PARENTHOST}
      - AILTIRE_APPNAME=${AILTIRE_APPNAME}
      - AILTIRE_BASEURL=/
      - EDGEMERE_PORT=3001
  producer:
    image: cpl_tp_producer:latest
    deploy:
      replicas: 5
    environment:
      - EDGEMERE_TELEMETRY_PARENT=consumer:3001
      - EDGEMERE_DEVICE_NAME={{.Service.Name}}-{{.Task.Slot}}
      - EDGEMERE_PORT=3000
