@startuml


usecase "Manage Data Procedures" as ManageDataProcedures

Actor "DataEngineer" as DataEngineer

DataEngineer --> ManageDataProcedures

Actor "Chief Data Officer" as ChiefDataOfficer

ChiefDataOfficer --> ManageDataProcedures



@enduml
