version: "3.7"
services:
  frontend:
    image: diml_cds_ss_web
    networks:
      - sibling
  gw:
    image: diml_cds_ss_gw
    networks:
      children:
        aliases:
          - parent
          - top
      sibling:
        aliases:
          - gateway

networks:
  children:
    driver: overlay
    attachable: true
    name: ${APPNAME}_diml_cds_ss_family
  sibling:
    driver: overlay
  parent:
    external: true
    name: ${APPNAME}_diml_cds_family
