version: "3.7"
services:
  frontend:
    image: diml_cds_storage_web
    networks:
      - sibling

networks:
  children:
    driver: overlay
    attachable: true
    name: ${AILTIRE_APPNAME}_diml_cds_storage_family
  sibling:
    driver: overlay
  parent:
    external: true
    name: ${AILTIRE_APPNAME}_diml_cds_family
