@startuml

left to right direction


boundary ailtire_appname_sml_family #red


entity ailtire_appname_sml_em_family #black




package "sml_em" #lightgreen {
    queue childrennet #black [
            <b><color:white>children</color></b>
    ]
    
    childrennet -[#black]- ailtire_appname_sml_em_family
    
    queue siblingnet #blue [
            <b><color:white>sibling</color></b>
    ]
    
    queue parentnet #red [
            <b><color:white>parent</color></b>
    ]
    
    parentnet -[#red]- ailtire_appname_sml_family
    

node "frontend" as frontendService
node "gw" as gwService


        artifact "sml_em_web" as sml_em_webimage
    
        artifact "sml_em_gw" as sml_em_gwimage
    
}

frontendService -[#blue]- siblingnet

gwService -[#black]- childrennet

gwService -[#blue]- siblingnet
frontendService .... sml_em_webimage
gwService .... sml_em_gwimage


@enduml
