@startuml
left to right direction


state "sml" as sml #lightgreen {
}


state sml #lightgreen {
    state "Custom Function" as smlfunction {
    }
}

        state "sml" as sml #lightgreen {
state "cloud" as smlcloud #lightgreen {
state "list" as smlcloudlist #lightgreen {
}
}
}


        state "sml" as sml #lightgreen {
state "data" as smldata #lightgreen {
state "govern" as smldatagovern #lightgreen {
}
}
}


        state "sml" as sml #lightgreen {
state "data" as smldata #lightgreen {
state "source" as smldatasource #lightgreen {
state "name" as smldatasourcename #lightgreen {
}
}
}
}


        state "sml" as sml #lightgreen {
state "environmenet" as smlenvironmenet #lightgreen {
state "addpolicies" as smlenvironmenetaddpolicies #lightgreen {
}
}
}


        state "sml" as sml #lightgreen {
state "environment" as smlenvironment #lightgreen {
state "create" as smlenvironmentcreate #lightgreen {
}
}
}


        state "sml" as sml #lightgreen {
state "environment" as smlenvironment #lightgreen {
state "destroy" as smlenvironmentdestroy #lightgreen {
}
}
}


        state "sml" as sml #lightgreen {
state "environment" as smlenvironment #lightgreen {
state "disable" as smlenvironmentdisable #lightgreen {
}
}
}


        state "sml" as sml #lightgreen {
state "environment" as smlenvironment #lightgreen {
state "enable" as smlenvironmentenable #lightgreen {
}
}
}


        state "sml" as sml #lightgreen {
state "environment" as smlenvironment #lightgreen {
state "list" as smlenvironmentlist #lightgreen {
}
}
}


        state "sml" as sml #lightgreen {
state "environment" as smlenvironment #lightgreen {
state "update" as smlenvironmentupdate #lightgreen {
}
}
}


        state "sml" as sml #lightgreen {
state "multicloud" as smlmulticloud #lightgreen {
state "addclouds" as smlmulticloudaddclouds #lightgreen {
}
}
}


        state "sml" as sml #lightgreen {
state "multicloud" as smlmulticloud #lightgreen {
state "addpolicies" as smlmulticloudaddpolicies #lightgreen {
}
}
}


        state "sml" as sml #lightgreen {
state "multicloud" as smlmulticloud #lightgreen {
state "list" as smlmulticloudlist #lightgreen {
}
}
}


        state "sml" as sml #lightgreen {
state "multicloud" as smlmulticloud #lightgreen {
state "removepolicies" as smlmulticloudremovepolicies #lightgreen {
}
}
}


        state "sml" as sml #lightgreen {
state "service" as smlservice #lightgreen {
state "list" as smlservicelist #lightgreen {
}
}
}


        state "sml" as sml #lightgreen {
state "stack" as smlstack #lightgreen {
state "list" as smlstacklist #lightgreen {
}
}
}





    state "sml" as sml #lightgreen {
state "Service" as smlservice #lightgreen {
state "started" as smlservicestarted #lightgreen {
}
}
}

    state "da" as da #lavender {
state "service" as daservice #lavender {
state "register" as daserviceregister #lavender {
}
}
}

        smlservicestarted ---> daserviceregister
       

@enduml
