@startuml
left to right direction



state "IT Operations" as ITOperations {
    state "Manage Clouds" as ITOperationsManageClouds {
    }
}
state "sml" as sml #lightgreen {
state "Cloud" as smlCloud #lightgreen {
state "list" as smlCloudlist #lightgreen {
}
}
}

ITOperationsManageClouds --> smlCloudlist


 
state "Stack Developer" as StackDeveloper {
    state "Manage Services" as StackDeveloperManageServices {
    }
}
state "sml" as sml #lightgreen {
state "service" as smlservice #lightgreen {
state "list" as smlservicelist #lightgreen {
}
}
}

StackDeveloperManageServices --> smlservicelist

state "Application Developer" as ApplicationDeveloper {
    state "Manage Services" as ApplicationDeveloperManageServices {
    }
}
state "sml" as sml #lightgreen {
state "service" as smlservice #lightgreen {
state "list" as smlservicelist #lightgreen {
}
}
}

ApplicationDeveloperManageServices --> smlservicelist


 

@enduml
