@startuml


actor "Actor"


entity EventBus

box PhysicalWorld #lightblue
    boundary pw #white
end box


box Software Defined Infrastructure #cccc88
            participant storageresource
    end box

group Given [A physical asset needs to be connected to a digital device]

"Actor" --/ pw: The user attempts to connect the physical asset to the digital device
"pw" -> pw: Asset-Digital Device Connectivity

    pw -> "storageresource": list (name: hello,file: ./templates/world.yml)

    "storageresource" --/ EventBus: data.list

    pw -> "storageresource": list (name: hello,file: ./templates/world.yml)

    "storageresource" --/ EventBus: data.list



"Actor" /-- pw: The physical asset should show as connected on the digital device


end

@enduml
