@startuml

class "Cloud" as Model {
 string name
 string ename

 reserve()
 
}

rectangle "Resource" as Resource {
}

Model *--> "n" Resource : resources


rectangle "Device" as Device {
}

Model o--> "n" Device : devices


rectangle "AggregatedDevice" as AggregatedDevice {
}

Model o--> "n" AggregatedDevice : adevices


rectangle "DataCenter" as DataCenter {
}

Model o--> "n" DataCenter : datacenters


rectangle "Reservation" as Reservation {
}

Model *--> "n" Reservation : reservations


rectangle "Request" as Request {
}

Model *--> "n" Request : requests




@enduml
