@startuml

left to right direction






node "cpl_tp" #cccccc {



node "producer" as producerService #white {


    artifact "cpl_tp_producer:latest" as cpl_tp_producerlatestimage
    
}
node "tester" as testerService #white {


    artifact "cpl_tp_tester:latest" as cpl_tp_testerlatestimage
    
}

}


@enduml
