@startuml

class "StageInstance" as Model {
 string attr1

 
}

rectangle "BuildInstance" as BuildInstance #lightblue {
}

Model o--> "1" BuildInstance : build


rectangle "Stage" as Stage #lightblue {
}

Model o--> "1" Stage : definition


rectangle "StepInstance" as StepInstance #lightblue {
}

Model *--> "n" StepInstance : steps




    rectangle "Build" as Build #lightgreen {
    }
    
        Build   o--> "1" Model : "stages"
    
    rectangle "BuildInstance" as BuildInstance #lightgreen {
    }
    
        BuildInstance   *--> "n" Model : "stages"
    
    rectangle "Stage" as Stage #lightgreen {
    }
    
        Stage   o--> "n" Model : "instances"
    

@enduml
