@startuml


boundary _diml_cds_family #blue


entity _diml_family #orange


package  "Common Data Service"  #lightblue {
    card children #blue [
        <b><color:white>children</color></b>
    ]
    
    _diml_cds_family -[#blue]- children
    
    
    card sibling #red [
        <b><color:white>sibling</color></b>
    ]
    
    
    card parent #orange [
        <b><color:white>parent</color></b>
    ]
    
    
    _diml_family -[#orange]- parent
    
    artifact images #ffffff {
        
        file diml_cds_web
        
        file diml_cds_gw
        
    }

    node frontend
    frontend .. diml_cds_web
    
        sibling -[#red]- frontend
    

    node gw
    gw .. diml_cds_gw
    
        children -[#blue]- gw
    
        sibling -[#red]- gw
    




    
}


package  "is"  #lightgray {
    card isparent #blue [
        <b><color:white>parent</color></b>
    ]
    isparent ==[#blue]= children
}


package  "ss"  #lightgray {
    card ssparent #blue [
        <b><color:white>parent</color></b>
    ]
    ssparent ==[#blue]= children
}


package  "ts"  #lightgray {
    card tsparent #blue [
        <b><color:white>parent</color></b>
    ]
    tsparent ==[#blue]= children
}




package diml #lightgray {
    card dimlchildren #orange [
        <b><color:white>children</color></b>
    ]
    dimlchildren ==[#orange]= parent
}


@enduml
