@startuml
left to right direction


state "diml" as diml #ffcc88 {
state "cds" as dimlcds #ffcc88 {
}
}


state dimlcds #ffcc88 {
    state "Custom Function" as cdsfunction {
    }
}

        state "diml" as diml #ffcc88 {
state "cds" as dimlcds #ffcc88 {
state "data" as dimlcdsdata #ffcc88 {
state "list" as dimlcdsdatalist #ffcc88 {
}
}
}
}


        state "diml" as diml #ffcc88 {
state "cds" as dimlcds #ffcc88 {
state "data" as dimlcdsdata #ffcc88 {
state "source" as dimlcdsdatasource #ffcc88 {
state "name" as dimlcdsdatasourcename #ffcc88 {
}
}
}
}
}






@enduml
