@startuml
left to right direction


    package "edgemere" as edgemere {
package "diml" as edgemerediml {
package "cds" as edgemeredimlcds #ffcc88 {
 component "data" as edgemeredimlcdsdata
 interface "list" as edgemeredimlcdsdatalist
edgemeredimlcdsdata -- edgemeredimlcdsdatalist
}
}
}

    
    package "edgemere" as edgemere {
package "diml" as edgemerediml {
package "cds" as edgemeredimlcds #ffcc88 {
 component "data" as edgemeredimlcdsdata
 interface "move" as edgemeredimlcdsdatamove
edgemeredimlcdsdata -- edgemeredimlcdsdatamove
}
}
}

    
    package "edgemere" as edgemere {
package "diml" as edgemerediml {
package "cds" as edgemeredimlcds #ffcc88 {
package "data" as edgemeredimlcdsdata {
 component "source" as edgemeredimlcdsdatasource
 interface "name" as edgemeredimlcdsdatasourcename
edgemeredimlcdsdatasource -- edgemeredimlcdsdatasourcename
}
}
}
}

    







        rectangle "Manage Data" as ManageData #ffffaa {
            ("Destroy Data")/ as DataStewardManageDataDestroyData
        }
    
    edgemeredimlcdsdatasourcename <-- DataStewardManageDataDestroyData
    
        rectangle "Manage Data" as ManageData #ffffaa {
            ("Egress Data")/ as DataStewardManageDataEgressData
        }
    
    edgemeredimlcdsdatasourcename <-- DataStewardManageDataEgressData
    
        rectangle "Manage Data" as ManageData #ffffaa {
            ("Ingest Data")/ as DataStewardManageDataIngestData
        }
    
    edgemeredimlcdsdatasourcename <-- DataStewardManageDataIngestData
    
        rectangle "Manage Data" as ManageData #ffffaa {
            ("Move Data")/ as DataStewardManageDataMoveData
        }
    
    edgemeredimlcdsdatamove <-- DataStewardManageDataMoveData
    























@enduml
