@startuml
left to right direction



state "Data Scientist" as DataScientist {
    state "Manage Data" as DataScientistManageData {
    }
}
state "diml" as diml #ffcc88 {
state "cds" as dimlcds #ffcc88 {
state "data" as dimlcdsdata #ffcc88 {
state "list" as dimlcdsdatalist #ffcc88 {
}
}
}
}

DataScientistManageData --> dimlcdsdatalist

state "Data Analyst" as DataAnalyst {
    state "Manage Data" as DataAnalystManageData {
    }
}
state "diml" as diml #ffcc88 {
state "cds" as dimlcds #ffcc88 {
state "data" as dimlcdsdata #ffcc88 {
state "list" as dimlcdsdatalist #ffcc88 {
}
}
}
}

DataAnalystManageData --> dimlcdsdatalist

state "Data Engineer" as DataEngineer {
    state "Manage Data" as DataEngineerManageData {
    }
}
state "diml" as diml #ffcc88 {
state "cds" as dimlcds #ffcc88 {
state "data" as dimlcdsdata #ffcc88 {
state "list" as dimlcdsdatalist #ffcc88 {
}
}
}
}

DataEngineerManageData --> dimlcdsdatalist


    state "Actor" as Actor {
        state "Manage Data" as ActorManageData {
            state "Destroy Data" as ActorManageDataDestroyData {
            }
        }
    }
    state "diml" as diml #ffcc88 {
state "cdsdata" as dimlcdsdata #ffcc88 {
state "source" as dimlcdsdatasource #ffcc88 {
state "name" as dimlcdsdatasourcename #ffcc88 {
}
}
}
}

    ActorManageDataDestroyData --> dimlcdsdatasourcename
    
 
    state "Actor" as Actor {
        state "Manage Data" as ActorManageData {
            state "Egress Data" as ActorManageDataEgressData {
            }
        }
    }
    state "diml" as diml #ffcc88 {
state "cdsdata" as dimlcdsdata #ffcc88 {
state "source" as dimlcdsdatasource #ffcc88 {
state "name" as dimlcdsdatasourcename #ffcc88 {
}
}
}
}

    ActorManageDataEgressData --> dimlcdsdatasourcename
    
 
    state "Actor" as Actor {
        state "Manage Data" as ActorManageData {
            state "Ingest Data" as ActorManageDataIngestData {
            }
        }
    }
    state "diml" as diml #ffcc88 {
state "cdsdata" as dimlcdsdata #ffcc88 {
state "source" as dimlcdsdatasource #ffcc88 {
state "name" as dimlcdsdatasourcename #ffcc88 {
}
}
}
}

    ActorManageDataIngestData --> dimlcdsdatasourcename
    
 
    state "Actor" as Actor {
        state "Manage Data" as ActorManageData {
            state "Move Data" as ActorManageDataMoveData {
            }
        }
    }
    state "diml" as diml #ffcc88 {
state "cdsdata" as dimlcdsdata #ffcc88 {
state "source" as dimlcdsdatasource #ffcc88 {
state "name" as dimlcdsdatasourcename #ffcc88 {
}
}
}
}

    ActorManageDataMoveData --> dimlcdsdatasourcename
    
 
 

@enduml
