@startuml


package "Service Management Layer" #lightgreen {

}


package "Common Data Service" #ffcc88 {

    interface "Common Data Service" as i {
    
            /edgemere/diml/cds/data/list()
            /edgemere/diml/cds/data/source/name()
    
    }
}

circle REST
circle Web
circle CLI
circle WebSocket

i -down- Web
i -down- CLI
i -down- REST
WebSocket -left- i: events >

package "Common Data Service" #ffcc88 {


rectangle "Ingress Services" #white {
}

rectangle "Insite Services" #white {
}

rectangle "Storage Services" #white {
}

rectangle "Transform Services" #white {
}

}


    "Service Management Layer" <-- "Common Data Service"


@enduml
