@startuml

left to right direction
Actor "Data Scientist" as DataScientist
Actor "Data Analyst" as DataAnalyst
Actor "Data Engineer" as DataEngineer


rectangle "Common Data Service" #ffcc88 {
usecase "ManageData" as ManageData
    DataScientist --> ManageData
    DataAnalyst --> ManageData
    DataEngineer --> ManageData
    }


@enduml
