@startuml

actor "DataScientist" as datascientist

actor "DataAnalyst" as analyst

actor "DataEngineer" as dataengineer




datascientist -> "Common Data Service": Manage Data
"Common Data Service" -> bin: data/list
bin -> REST: data/list

analyst -> "Common Data Service": Manage Data
"Common Data Service" -> bin: data/list
bin -> REST: data/list

dataengineer -> "Common Data Service": Manage Data
"Common Data Service" -> bin: data/list
bin -> REST: data/list


@enduml
