@startuml

left to right direction


Actor "SecurityEngineer" as SecurityEngineer


rectangle "Security Profile Manager" as spm #cc8888 {
        usecase "Manage Security Profiles" as ManageSecurityProfiles
    SecurityEngineer --> ManageSecurityProfiles

}

rectangle "edgemere" as edgemere #ccaaff {
        usecase "Secure Assets" as SecureAssets
    SecurityEngineer --> SecureAssets

}


@enduml
