@startuml



package "edgemere" #lavender {

    interface "edgemere" as i {
            /edgemere/admin/status()
    
    }
}

CLI ()-- i
REST ()-- i
Web ()-- i

package "edgemere" #lavender {
    
}



@enduml
