@startuml



package "edgemere" #ccaaff {

    interface "edgemere" as i {
            /edgemere/admin/status()
    
    }
}

CLI ()-- i
REST ()-- i
Web ()-- i

package "edgemere" #ccaaff {
    
}



@enduml
