@startuml
  interface CLI
  interface Web
  interface WebSocket
package "edgemere" #lightgreen {
  component express as REST
  component socket.io as socket
  folder bin #ffffff {
    component "edgemere" as binName
  }
  binName --> REST

  folder deploy #ffffff {
  
    file "" as web_container
    REST --> web_container
    socket ---> web_container
  
    file "" as doc_container
    REST --> doc_container
    socket ---> doc_container
  
  }
  folder images #ffffff {
  
      artifact edgemere_web
      web_container --> edgemere_web
    
      artifact edgemere_doc
      doc_container --> edgemere_doc
    
  }
}
CLI -- binName
Web - REST
WebSocket -- socket

@enduml
