@startuml
left to right direction




state "edgemere" as pstatename #ccaaff {
    state "Custom Function" as edgemerefunction {
    }
}

        state "admin" as admin #ccaaff {
state "status" as adminstatus #ccaaff {
}
}






@enduml
