@startuml
left to right direction


    package "edgemere" as edgemere lavender {
 component "admin" as edgemereadmin
 interface "status" as edgemereadminstatus
edgemereadmin -- edgemereadminstatus
}

    






























@enduml
