@startuml
  interface CLI
  interface Web
  interface WebSocket
package "Environment Management" #lightgreen {
  component express as REST
  component socket.io as socket
  folder bin #ffffff {
    component " edgemere sml em" as binName
  }
  binName --> REST

  folder deploy #ffffff {
      file "node server.js\ndocker-compose.yml" as sml_em_container
      REST --> sml_em_container

  
    file "node web/server.js" as web_container
    REST --> web_container
    socket ---> web_container
  
    file "node gateway/server.js" as gateway_container
    REST --> gateway_container
    socket ---> gateway_container
  
  }
  folder images #ffffff {
    collections "sml_em" as sml_emimage
    artifact "ailtire:swarm" as ailtireswarm
    sml_emimage <|-- ailtireswarm
    sml_em_container --> sml_emimage

  
      artifact sml_em_web
      web_container --> sml_em_web
    
      artifact sml_em_gw
      gateway_container --> sml_em_gw
    
  }
}
CLI " edgemere sml em" -- binName
Web "/edgemere/sml/em" - REST
WebSocket ".edgemere.sml.em" -- socket

@enduml
