@startuml


package "Service Orchestrator" #lightgreen {
    }

package "Service Management Layer" #lightgreen {
    
        class MultiCloud {
        }
    }

package "Security Aspect" #pink {
    
        class PolicyCollection {
        }
    }

package "Security Profile Manager" #pink {
    
        class SecurityProfile {
        }
    }


package "Environment Management" #lightgreen {

    interface "Environment Management" as i {
            /edgemere/aml/ds/em/environment/addpolicies()
            /edgemere/aml/ds/em/environment/create()
            /edgemere/aml/ds/em/environment/destroy()
            /edgemere/aml/ds/em/environment/disable()
            /edgemere/aml/ds/em/environment/enable()
            /edgemere/aml/ds/em/environment/list()
            /edgemere/aml/ds/em/environment/update()
    
    }
}

CLI ()-- i
REST ()-- i
Web ()-- i

package "Environment Management" #lightgreen {
        class "Environment" {
                 string name
                    }
                Environment o--> "n" MultiCloud : clouds
                        Environment o--> "1" PolicyCollection : policies
                        Environment o--> "1" SecurityProfile : profile
            
    

}


    "Environment Management" --> "Service Orchestrator"


@enduml
