@startuml
left to right direction


state "aml" as aml #88cccc {
state "ds" as amlds #lightblue {
state "em" as amldsem #88cc88 {
}
}
}


state "amldsem" as pstatename #88cc88 {
    state "Custom Function" as emfunction {
    }
}

        state "aml" as aml #88cccc {
state "ds" as amlds #lightblue {
state "em" as amldsem #88cc88 {
state "environment" as amldsemenvironment #88cc88 {
state "addpolicies" as amldsemenvironmentaddpolicies #88cc88 {
}
}
}
}
}


        state "aml" as aml #88cccc {
state "ds" as amlds #lightblue {
state "em" as amldsem #88cc88 {
state "environment" as amldsemenvironment #88cc88 {
state "create" as amldsemenvironmentcreate #88cc88 {
}
}
}
}
}


        state "aml" as aml #88cccc {
state "ds" as amlds #lightblue {
state "em" as amldsem #88cc88 {
state "environment" as amldsemenvironment #88cc88 {
state "destroy" as amldsemenvironmentdestroy #88cc88 {
}
}
}
}
}


        state "aml" as aml #88cccc {
state "ds" as amlds #lightblue {
state "em" as amldsem #88cc88 {
state "environment" as amldsemenvironment #88cc88 {
state "disable" as amldsemenvironmentdisable #88cc88 {
}
}
}
}
}


        state "aml" as aml #88cccc {
state "ds" as amlds #lightblue {
state "em" as amldsem #88cc88 {
state "environment" as amldsemenvironment #88cc88 {
state "enable" as amldsemenvironmentenable #88cc88 {
}
}
}
}
}


        state "aml" as aml #88cccc {
state "ds" as amlds #lightblue {
state "em" as amldsem #88cc88 {
state "environment" as amldsemenvironment #88cc88 {
state "list" as amldsemenvironmentlist #88cc88 {
}
}
}
}
}


        state "aml" as aml #88cccc {
state "ds" as amlds #lightblue {
state "em" as amldsem #88cc88 {
state "environment" as amldsemenvironment #88cc88 {
state "update" as amldsemenvironmentupdate #88cc88 {
}
}
}
}
}






@enduml
