@startuml
left to right direction



state "IT Operations" as ITOperations {
    state "Manage Environment" as ITOperationsManageEnvironment {
    }
}
state "edgemere" as edgemere #lightgreen {
state "aml" as edgemereaml #lightgreen {
state "ds" as edgemereamlds #lightgreen {
state "em" as edgemereamldsem #lightgreen {
state "environment" as edgemereamldsemenvironment #lightgreen {
state "list" as edgemereamldsemenvironmentlist #lightgreen {
}
}
}
}
}
}

ITOperationsManageEnvironment --> edgemereamldsemenvironmentlist

state "Stack Developer" as StackDeveloper {
    state "Manage Environment" as StackDeveloperManageEnvironment {
    }
}
state "edgemere" as edgemere #lightgreen {
state "aml" as edgemereaml #lightgreen {
state "ds" as edgemereamlds #lightgreen {
state "em" as edgemereamldsem #lightgreen {
state "environment" as edgemereamldsemenvironment #lightgreen {
state "list" as edgemereamldsemenvironmentlist #lightgreen {
}
}
}
}
}
}

StackDeveloperManageEnvironment --> edgemereamldsemenvironmentlist


    state "IT Operations" as ITOperations {
        state "Manage Environment" as ITOperationsManageEnvironment {
            state "Create Environment" as ITOperationsManageEnvironmentCreateEnvironment {
            }
        }
    }
    
    ITOperationsManageEnvironmentCreateEnvironment --> Null
    
 
    state "IT Operations" as ITOperations {
        state "Manage Environment" as ITOperationsManageEnvironment {
            state "Delete Environment" as ITOperationsManageEnvironmentDeleteEnvironment {
            }
        }
    }
    
    ITOperationsManageEnvironmentDeleteEnvironment --> Null
    
 
    state "IT Operations" as ITOperations {
        state "Manage Environment" as ITOperationsManageEnvironment {
            state "Disable Environment" as ITOperationsManageEnvironmentDisableEnvironment {
            }
        }
    }
    
    ITOperationsManageEnvironmentDisableEnvironment --> Null
    
 
    state "IT Operations" as ITOperations {
        state "Manage Environment" as ITOperationsManageEnvironment {
            state "Enable Environment" as ITOperationsManageEnvironmentEnableEnvironment {
            }
        }
    }
    
    ITOperationsManageEnvironmentEnableEnvironment --> Null
    
 
    state "IT Operations" as ITOperations {
        state "Manage Environment" as ITOperationsManageEnvironment {
            state "Manage Policies in Environment" as ITOperationsManageEnvironmentManagePoliciesinEnvironment {
            }
        }
    }
    
    ITOperationsManageEnvironmentManagePoliciesinEnvironment --> Null
    
 
    state "IT Operations" as ITOperations {
        state "Manage Environment" as ITOperationsManageEnvironment {
            state "Update Environment" as ITOperationsManageEnvironmentUpdateEnvironment {
            }
        }
    }
    
    ITOperationsManageEnvironmentUpdateEnvironment --> Null
    
 
 

@enduml
