@startuml


package "Service Orchestrator" #lightgreen {

}

package "Service Management Layer" #lightgreen {

}

package "Security Aspect" #pink {

}

package "Security Profile Manager" #pink {

}


package "Environment Management" #lightgreen {

    interface "Environment Management" as i {
    
            /edgemere/aml/ds/em/environment/addpolicies()
            /edgemere/aml/ds/em/environment/create()
            /edgemere/aml/ds/em/environment/destroy()
            /edgemere/aml/ds/em/environment/disable()
            /edgemere/aml/ds/em/environment/enable()
            /edgemere/aml/ds/em/environment/list()
            /edgemere/aml/ds/em/environment/update()
    
    }
}

circle REST
circle Web
circle CLI
circle WebSocket

i -down- Web
i -down- CLI
i -down- REST
WebSocket -left- i: events >

package "Environment Management" #lightgreen {


}


    "Service Orchestrator" <-- "Environment Management"


@enduml
