@startuml

left to right direction
Actor "IT Operations" as ITOperations
Actor "Stack Developer" as StackDeveloper


rectangle "Environment Management" #88cc88 {
usecase "ManageEnvironment" as ManageEnvironment
    ITOperations --> ManageEnvironment
    StackDeveloper --> ManageEnvironment
    }


@enduml
