@startuml



package "AI ML Services" #lightblue {

    interface "AI ML Services" as i {
    
    }


    CLI ()-- i
    REST ()-- i
    Web ()-- i
        class "AIModel" {
                 string attr1
                    }
                AIModel o--> "1" ModelName : assoc1
            




}

@enduml
