@startuml


package "Workflow Services" #88cccc {
    }


package "AI ML Services" #88cccc {

    interface "AI ML Services" as i {
    
    }
}

CLI ()-- i
REST ()-- i
Web ()-- i

package "AI ML Services" #88cccc {
        class "AIModel" {
                 string attr1
                    }
    
    

}


    "AI ML Services" --> "Workflow Services"


@enduml
