@startuml
left to right direction


state "aml" as aml #88cccc {
state "ams" as amlams #88cccc {
}
}


state "amlams" as pstatename #88cccc {
    state "Custom Function" as amsfunction {
    }
}





@enduml
