@startuml

class "WorkloadInstance" as Model {
 string name
 string status
 string message

 exit()
 failed()
 kill()
 provision()
 provisioned()
 start()
 stop()
 stopped()
 
}

rectangle "Workload" as Workload #lightblue {
}

Model o--> "1" Workload : app





@enduml
