@startuml

class "Application" as Model {
 string name
 string version

 
}

rectangle "Workload" as Workload {
}

Model o--> "n" Workload : workloads


rectangle "Stack" as Stack {
}

Model *--> "n" Stack : stacks


rectangle "DataReference" as DataReference {
}

Model o--> "n" DataReference : data


rectangle "ApplicationInstance" as ApplicationInstance {
}

Model *--> "n" ApplicationInstance : instances




@enduml
