@startuml


left to right direction

usecase "Manage Data Pipeline" as ManageDataPipeline #yellow

Actor "DataEngineer" as DataEngineer

DataEngineer --> ManageDataPipeline





usecase "Provide Business Information" as ProvideBusinessInformation #lightyellow

ManageDataPipeline <-- ProvideBusinessInformation : extends







@enduml
