@startuml
  interface CLI
  interface Web
  interface WebSocket
package "Service Management Layer" #lightgreen {
  component express as REST
  component socket.io as socket
  folder bin #ffffff {
    component " edgemere sml" as binName
  }
  binName --> REST

  folder deploy #ffffff {
      file "node server.js\ndocker-compose.yml" as sml_container
      REST --> sml_container

  
    file "node web/server.js" as web_container
    REST --> web_container
    socket ---> web_container
  
    file "node gateway/server.js" as gateway_container
    REST --> gateway_container
    socket ---> gateway_container
  
  }
  folder images #ffffff {
    collections "sml" as smlimage
    artifact "ailtire:swarm" as ailtireswarm
    smlimage <|-- ailtireswarm
    sml_container --> smlimage

  
      artifact sml_web
      web_container --> sml_web
    
      artifact sml_gw
      gateway_container --> sml_gw
    
  }
}
CLI " edgemere sml" -- binName
Web "/edgemere/sml" - REST
WebSocket ".edgemere.sml" -- socket

@enduml
