@startuml
  interface CLI
  interface Web
  interface WebSocket
package "Common Physical Layer" #lightgray {
  component express as REST
  component socket.io as socket
  folder bin #ffffff {
    component " edgemere cpl" as binName
  }
  binName --> REST

  folder deploy #ffffff {
      file "node server.js\ndocker-compose.yml" as cpl_container
      REST --> cpl_container

  
    file "web" as web_container
    REST --> web_container
    socket ---> web_container
  
  }
  folder images #ffffff {
    collections "cpl" as cplimage
    artifact "ailtire:swarm" as ailtireswarm
    cplimage <|-- ailtireswarm
    cpl_container --> cplimage

  
      artifact "cpl_web" as cpl_web
      web_container --> cpl_web
    
  }
}
CLI " edgemere cpl" -- binName
Web "/edgemere/cpl" - REST
WebSocket ".edgemere.cpl" -- socket

@enduml
