@startuml
left to right direction


state "cpl" as cpl #lightgray {
state "dm" as cpldm #lightgray {
}
}


state cpldm #lightgray {
    state "Custom Function" as dmfunction {
    }
}

        state "cpl" as cpl #lightgray {
state "dm" as cpldm #lightgray {
state "agent" as cpldmagent #lightgray {
state "register" as cpldmagentregister #lightgray {
}
}
}
}


        state "cpl" as cpl #lightgray {
state "dm" as cpldm #lightgray {
state "service" as cpldmservice #lightgray {
state "register" as cpldmserviceregister #lightgray {
}
}
}
}




    state "cpl" as cpl #lightgray {
state "dm" as cpldm #lightgray {
state "Agent" as cpldmagent #lightgray {
state "started" as cpldmagentstarted #lightgray {
}
}
}
}

    
    state "dm" as dm #lavender {
state "agent" as dmagent #lavender {
state "register" as dmagentregister #lavender {
}
}
}

    cpldmagentstarted ---> dmagentregister
  


    
    state "dm" as dm #lavender {
state "agent" as dmagent #lavender {
state "register" as dmagentregister #lavender {
}
}
}

        
       

@enduml
