@startuml


package "Pipeline Manager" #aaffff {
    
        class LedgerEntry {
        }
    
        class BuildLedger {
        }
    
        class StageInstance {
        }
    
        class Deliverable {
        }
    
        class Build {
        }
    
        class BuildLog {
        }
    
        class BuildInstance {
        }
    
        class StepInstance {
        }
    
        class Artifact {
        }
    
        class Stage {
        }
    
        class Step {
        }
    }

package "Service Management Layer" #88cc88 {
    
        class Image {
        }
    }

package "Environment Management" #88cc88 {
    
        class Environment {
        }
    }


package "Pipeline Manager" #aaffff {

    interface "Pipeline Manager" as i {
    
    }
}

CLI ()-- i
REST ()-- i
Web ()-- i

package "Pipeline Manager" #aaffff {
        class "Artifact" {
                 string name
                    }
                Artifact o--> "1" LedgerEntry : creator
                        Artifact o--> "n" LedgerEntry : consumer
            
    
    class "Build" {
                 string name
                 string tag
                    }
                Build *--> "1" BuildLedger : ledger
                        Build o--> "1" StageInstance : stages
                        Build *--> "n" Deliverable : deliverables
            
    
    class "BuildInstance" {
                 string name
                    }
                BuildInstance o--> "1" Build : build
                        BuildInstance *--> "n" StageInstance : stages
                        BuildInstance *--> "n" BuildLog : logs
                        BuildInstance *--> "1" BuildLedger : ledger
            
    
    class "BuildLedger" {
                 string name
                    }
                BuildLedger *--> "n" LedgerEntry : entries
                        BuildLedger o--> "1" BuildInstance : parent
            
    
    class "BuildLog" {
                 string name
                 string text
                 string file
                    }
                BuildLog o--> "1" BuildInstance : parent
            
    
    class "Deliverable" {
                 string name
                 string version
                    }
                Deliverable o--> "1" BuildInstance : parent
                        Deliverable o--> "1" Image : image
            
    
    class "LedgerEntry" {
                 string time
                 string message
                    }
                LedgerEntry o--> "1" StepInstance : step
                        LedgerEntry o--> "n" Artifact : input
                        LedgerEntry o--> "n" Artifact : output
            
    
    class "Pipeline" {
                 string name
                    }
                Pipeline *--> "n" Stage : stages
                        Pipeline *--> "n" Build : builds
            
    
    class "Stage" {
                 string name
                    }
                Stage o--> "n" StageInstance : instances
                        Stage *--> "n" Step : steps
                        Stage o--> "1" Environment : environment
            
    
    class "StageInstance" {
                 string attr1
                    }
                StageInstance o--> "1" BuildInstance : build
                        StageInstance o--> "1" Stage : definition
                        StageInstance *--> "n" StepInstance : steps
            
    
    class "Step" {
                 string name
                 string action
                    }
                Step o--> "1" Stage : stage
                        Step *--> "n" StepInstance : instances
            
    
    class "StepInstance" {
                 string name
                    }
                StepInstance o--> "1" Step : definition
                        StepInstance o--> "1" Stage : stage
            
    

}



@enduml
