@startuml
left to right direction


state "aml" as aml #88cccc {
state "ds" as amlds #aaffff {
state "pm" as amldspm #aaffff {
}
}
}


state "amldspm" as pstatename #aaffff {
    state "Custom Function" as pmfunction {
    }
}





@enduml
