@startuml
left to right direction


state "aml" as aml #lightblue {
state "ds" as amlds #lightblue {
state "pm" as amldspm #lightblue {
}
}
}


state "amldspm" as pstatename #lightblue {
    state "Custom Function" as pmfunction {
    }
}





@enduml
