@startuml


package "Pipeline Manager" #lightblue {

}

package "Service Management Layer" #88cc88 {

}

package "Environment Management" #88cc88 {

}


package "Pipeline Manager" #lightblue {

    interface "Pipeline Manager" as i {
    
    
    }
}

circle REST
circle Web
circle CLI
circle WebSocket

i -down- Web
i -down- CLI
i -down- REST
WebSocket -left- i: events >

package "Pipeline Manager" #lightblue {


}



@enduml
