@startuml


package "Pipeline Manager" #lightblue {

}

package "Service Management Layer" #lightgreen {

}

package "Environment Management" #lightgreen {

}


package "Pipeline Manager" #lightblue {

    interface "Pipeline Manager" as i {
    
    }
}

CLI ()-- i
REST ()-- i
Web ()-- i

package "Pipeline Manager" #lightblue {


}



@enduml
