@startuml

class "StackletDefinition" as Model {
 string name
 string version
 json parameters

 create()
 
}

rectangle "Stack" as Stack #lightblue {
}

Model o--> "1" Stack : stack


rectangle "Environment" as Environment #lightblue {
}

Model o--> "1" Environment : env


rectangle "Servicelet" as Servicelet #lightblue {
}

Model *--> "n" Servicelet : servicelets


rectangle "DataReference" as DataReference #lightblue {
}

Model o--> "n" DataReference : data





@enduml
