@startuml



package "Transform Services" ##aaffff {

    interface "Transform Services" as i {
    
    }
}

CLI ()-- i
REST ()-- i
Web ()-- i

package "Transform Services" ##aaffff {
    
}



@enduml
