@startuml
left to right direction


state "diml" as diml #ffcc88 {
state "cds" as dimlcds #ffcc88 {
state "transform" as dimlcdstransform #lightblue {
}
}
}


state dimlcdstransform #lightblue {
    state "Custom Function" as transformfunction {
    }
}





@enduml
