@startuml

left to right direction


boundary parent #black


entity children #blue

rectangle "diml_dml_do" as diml_dml_doStack #lightblue {
    queue diml_dml_doStacksnet #blue [
        <b><color:white>parent</color></b>
    ]
}
rectangle "sa_pe" as sa_peStack #cc8888 {
    queue sa_peStacksnet #blue [
        <b><color:white>parent</color></b>
    ]
}
rectangle "sml_so" as sml_soStack #88cc88 {
    queue sml_soStacksnet #blue [
        <b><color:white>parent</color></b>
    ]
}
rectangle "cpl_ta" as cpl_taStack #cccccc {
    queue cpl_taStacksnet #blue [
        <b><color:white>parent</color></b>
    ]
}



package "cpl_dm" #cccccc {
    queue parentnet #black [
            <b><color:white>parent</color></b>
    ]
    
    parentnet -[#black]- parent
    
    queue childrennet #blue [
            <b><color:white>children</color></b>
    ]
    
    childrennet -[#blue]- children
    
    queue siblingsnet #red [
            <b><color:white>siblings</color></b>
    ]
    

node "data_orchestrator" as data_orchestratorService
node "policy_engine" as policy_engineService
node "service_orchestrator" as service_orchestratorService
node "telemetry_aggregator" as telemetry_aggregatorService
node "portal" as portalService

        collections "diml_dml_do" as diml_dml_doimage
            collections "sa_pe" as sa_peimage
            collections "sml_so" as sml_soimage
            collections "cpl_ta" as cpl_taimage
    
        artifact "cpl_dm_web" as cpl_dm_webimage
    
}

data_orchestratorService -[#red]- siblingsnet

policy_engineService -[#red]- siblingsnet

service_orchestratorService -[#red]- siblingsnet

telemetry_aggregatorService -[#red]- siblingsnet

portalService -[#red]- siblingsnet
data_orchestratorService .... diml_dml_doimage
policy_engineService .... sa_peimage
service_orchestratorService .... sml_soimage
telemetry_aggregatorService .... cpl_taimage
portalService .... cpl_dm_webimage

diml_dml_doimage --> diml_dml_doStack
    
sa_peimage --> sa_peStack
    
sml_soimage --> sml_soStack
    
cpl_taimage --> cpl_taStack
    

@enduml
