@startuml

class "AcceleratorResource" as Model {
 string name
 string ename
 boolean disabled
 string type

 factory()
 provision()
 
}

rectangle "Request" as Request #lightblue {
}

Model o--> "1" Request : request


rectangle "PhysicalProfile" as PhysicalProfile #lightblue {
}

Model *--> "1" PhysicalProfile : profile


rectangle "Hardware" as Hardware #lightblue {
}

Model o--> "n" Hardware : hardware


rectangle "ServiceInstance" as ServiceInstance #lightblue {
}

Model o--> "n" ServiceInstance : instances


rectangle "Cloud" as Cloud #lightblue {
}

Model o--> "1" Cloud : cloud





@enduml
