@startuml


boundary _diml_dml_family #blue


entity _diml_family #orange


package  "Data Management Layer"  #lightblue {
    card children #blue [
        <b><color:white>children</color></b>
    ]
    
    _diml_dml_family -[#blue]- children
    
    
    card sibling #red [
        <b><color:white>sibling</color></b>
    ]
    
    
    card parent #orange [
        <b><color:white>parent</color></b>
    ]
    
    
    _diml_family -[#orange]- parent
    
    artifact images #ffffff {
        
        file diml_dml_web
        
        file diml_dml_gw
        
    }

    node frontend
    frontend .. diml_dml_web
    
        sibling -[#red]- frontend
    

    node gw
    gw .. diml_dml_gw
    
        children -[#blue]- gw
    
        sibling -[#red]- gw
    




    
}


package  "dc"  #lightgray {
    card dcparent #blue [
        <b><color:white>parent</color></b>
    ]
    dcparent ==[#blue]= children
}


package  "do"  #lightgray {
    card doparent #blue [
        <b><color:white>parent</color></b>
    ]
    doparent ==[#blue]= children
}


package  "fmdm"  #lightgray {
    card fmdmparent #blue [
        <b><color:white>parent</color></b>
    ]
    fmdmparent ==[#blue]= children
}


package  "ge"  #lightgray {
    card geparent #blue [
        <b><color:white>parent</color></b>
    ]
    geparent ==[#blue]= children
}




package diml #lightgray {
    card dimlchildren #orange [
        <b><color:white>children</color></b>
    ]
    dimlchildren ==[#orange]= parent
}


@enduml
