@startuml
left to right direction


state "diml" as diml #ffcc88 {
state "dml" as dimldml #ffcc88 {
}
}


state "dimldml" as pstatename #ffcc88 {
    state "Custom Function" as dmlfunction {
    }
}

        state "diml" as diml #ffcc88 {
state "dml" as dimldml #ffcc88 {
state "data" as dimldmldata #ffcc88 {
state "govern" as dimldmldatagovern #ffcc88 {
}
}
}
}


        state "diml" as diml #ffcc88 {
state "dml" as dimldml #ffcc88 {
state "data" as dimldmldata #ffcc88 {
state "source" as dimldmldatasource #ffcc88 {
state "name" as dimldmldatasourcename #ffcc88 {
}
}
}
}
}


        state "diml" as diml #ffcc88 {
state "dml" as dimldml #ffcc88 {
state "datapolicy" as dimldmldatapolicy #ffcc88 {
state "list" as dimldmldatapolicylist #ffcc88 {
}
}
}
}


        state "diml" as diml #ffcc88 {
state "dml" as dimldml #ffcc88 {
state "datasource" as dimldmldatasource #ffcc88 {
state "list" as dimldmldatasourcelist #ffcc88 {
}
}
}
}


        state "diml" as diml #ffcc88 {
state "dml" as dimldml #ffcc88 {
state "datastrategy" as dimldmldatastrategy #ffcc88 {
state "list" as dimldmldatastrategylist #ffcc88 {
}
}
}
}





    state "diml" as diml #ffcc88 {
state "dml" as dimldml #ffcc88 {
state "DataReference" as dimldmldatareference #ffcc88 {
state "provisioning" as dimldmldatareferenceprovisioning #ffcc88 {
}
}
}
}

    state "diml" as diml #ffcc88 {
state "dml" as dimldml #ffcc88 {
state "do" as dimldmldo #lightblue {
state "datainstance" as dimldmldodatainstance #lightblue {
state "create" as dimldmldodatainstancecreate #lightblue {
}
}
}
}
}

        dimldmldatareferenceprovisioning ---> dimldmldodatainstancecreate
       
    state "diml" as diml #ffcc88 {
state "dml" as dimldml #ffcc88 {
state "DataReference" as dimldmldatareference #ffcc88 {
state "provisioned" as dimldmldatareferenceprovisioned #ffcc88 {
}
}
}
}

    state "sml" as sml #lightgreen {
state "so" as smlso #lightgreen {
state "servicelet" as smlsoservicelet #lightgreen {
state "assignData" as smlsoserviceletassigndata #lightgreen {
}
}
}
}

        dimldmldatareferenceprovisioned ---> smlsoserviceletassigndata
       

@enduml
