@startuml
left to right direction


    package "edgemere" as edgemere {
package "diml" as edgemerediml {
package "dml" as edgemeredimldml #ffcc88 {
 component "data" as edgemeredimldmldata
 interface "govern" as edgemeredimldmldatagovern
edgemeredimldmldata -- edgemeredimldmldatagovern
}
}
}

    
    package "edgemere" as edgemere {
package "diml" as edgemerediml {
package "dml" as edgemeredimldml #ffcc88 {
package "data" as edgemeredimldmldata {
 component "source" as edgemeredimldmldatasource
 interface "name" as edgemeredimldmldatasourcename
edgemeredimldmldatasource -- edgemeredimldmldatasourcename
}
}
}
}

    
    package "edgemere" as edgemere {
package "diml" as edgemerediml {
package "dml" as edgemeredimldml #ffcc88 {
 component "datapolicy" as edgemeredimldmldatapolicy
 interface "list" as edgemeredimldmldatapolicylist
edgemeredimldmldatapolicy -- edgemeredimldmldatapolicylist
}
}
}

    
    package "edgemere" as edgemere {
package "diml" as edgemerediml {
package "dml" as edgemeredimldml #ffcc88 {
 component "datasource" as edgemeredimldmldatasource
 interface "list" as edgemeredimldmldatasourcelist
edgemeredimldmldatasource -- edgemeredimldmldatasourcelist
}
}
}

    
    package "edgemere" as edgemere {
package "diml" as edgemerediml {
package "dml" as edgemeredimldml #ffcc88 {
 component "datastrategy" as edgemeredimldmldatastrategy
 interface "list" as edgemeredimldmldatastrategylist
edgemeredimldmldatastrategy -- edgemeredimldmldatastrategylist
}
}
}

    







        rectangle "Manage Data" as ManageData #ffffaa {
            ("Destroy Data")/ as DataStewardManageDataDestroyData
        }
    
    edgemeredimldmldatasourcename <-- DataStewardManageDataDestroyData
    
        rectangle "Manage Data" as ManageData #ffffaa {
            ("Egress Data")/ as DataStewardManageDataEgressData
        }
    
    edgemeredimldmldatasourcename <-- DataStewardManageDataEgressData
    
        rectangle "Manage Data" as ManageData #ffffaa {
            ("Ingest Data")/ as DataStewardManageDataIngestData
        }
    
    edgemeredimldmldatasourcename <-- DataStewardManageDataIngestData
    









        rectangle "Manage Data Sources" as ManageDataSources #ffffaa {
            ("Deregister Data Source")/ as DataEngineerManageDataSourcesDeregisterDataSource
        }
    
    edgemeredimldmldatasourcelist <-- DataEngineerManageDataSourcesDeregisterDataSource
    
        rectangle "Manage Data Sources" as ManageDataSources #ffffaa {
            ("Register Data Source")/ as DataEngineerManageDataSourcesRegisterDataSource
        }
    
    edgemeredimldmldatasourcelist <-- DataEngineerManageDataSourcesRegisterDataSource
    





















@enduml
