@startuml


package "Software Defined Infrastructure" #lightyellow {

}

package "Security Aspect" #pink {

}

package "Service Management Layer" #lightgreen {

}

package "Common Data Service" #ffcc88 {

}

package "Data Definition Framework" #ffcc88 {

}


package "Data Management Layer" #ffcc88 {

    interface "Data Management Layer" as i {
            /edgemere/diml/dml/data/govern()
            /edgemere/diml/dml/data/source/name()
            /edgemere/diml/dml/datapolicy/list()
            /edgemere/diml/dml/datasource/list()
            /edgemere/diml/dml/datastrategy/list()
    
    }
}

CLI ()-- i
REST ()-- i
Web ()-- i

package "Data Management Layer" #ffcc88 {


rectangle "Data Controller" #white {
}

rectangle "Data Orchestrator" #white {
}

rectangle "Federated Meta Data Management" #white {
}

rectangle "Governance Engine" #white {
}

}


    "Data Management Layer" --> "Software Defined Infrastructure"

    "Data Management Layer" --> "Security Aspect"

    "Data Management Layer" --> "Service Management Layer"

    "Data Management Layer" --> "Common Data Service"


@enduml
