@startuml

class "Device" as Model {
 string name
 string ename
 string hostname
 string type

 addToHardware()
 archiveData()
 create()
 disable()
 disableAllFunctions()
 displayReservations()
 enable()
 enableAllFunctions()
 getReservations()
 initiateDevice()
 logDeviceStatus()
 provision()
 reserve()
 reserveResource()
 setupHardware()
 updateDeviceGroup()
 updateHardware()
 updateStatus()
 
}

rectangle "PhysicalProfile" as PhysicalProfile #lightblue {
}

Model o--> "1" PhysicalProfile : profile


rectangle "Hardware" as Hardware #lightblue {
}

Model *--> "n" Hardware : hardware


rectangle "DataCenter" as DataCenter #lightblue {
}

Model o--> "1" DataCenter : datacenter


rectangle "AggregatedDevice" as AggregatedDevice #lightblue {
}

Model o--> "1" AggregatedDevice : parent




    rectangle "AcceleratorHardware" as AcceleratorHardware #lightgreen {
    }
    
        AcceleratorHardware   o--> "1" Model : "device"
    
    rectangle "AggregatedDevice" as AggregatedDevice #lightgreen {
    }
    
        AggregatedDevice   *--> "n" Model : "devices"
    
    rectangle "ComputeHardware" as ComputeHardware #lightgreen {
    }
    
        ComputeHardware   o--> "1" Model : "device"
    
    rectangle "DataCenter" as DataCenter #lightgreen {
    }
    
        DataCenter   *--> "n" Model : "devices"
    
    rectangle "Hardware" as Hardware #lightgreen {
    }
    
        Hardware   o--> "1" Model : "device"
    
    rectangle "NetworkHardware" as NetworkHardware #lightgreen {
    }
    
        NetworkHardware   o--> "1" Model : "device"
    
    rectangle "StorageHardware" as StorageHardware #lightgreen {
    }
    
        StorageHardware   o--> "1" Model : "device"
    
    rectangle "CommunicationPathway" as CommunicationPathway #lightgreen {
    }
    
        CommunicationPathway   o--> "1" Model : "device"
    
    rectangle "PLC" as PLC #lightgreen {
    }
    
        PLC   o--> "1" Model : "device"
    
    rectangle "Cloud" as Cloud #lightgreen {
    }
    
        Cloud   o--> "n" Model : "devices"
    
    rectangle "Request" as Request #lightgreen {
    }
    
        Request   o--> "n" Model : "devices"
    
    rectangle "Reservation" as Reservation #lightgreen {
    }
    
        Reservation   o--> "1" Model : "device"
    

@enduml
