@startuml
left to right direction


state "cpl" as cpl #cccccc {
state "ta" as cplta #cccccc {
}
}


state "cplta" as pstatename #cccccc {
    state "Custom Function" as tafunction {
    }
}

        state "cpl" as cpl #cccccc {
state "ta" as cplta #cccccc {
state "list" as cpltalist #cccccc {
}
}
}


        state "cpl" as cpl #cccccc {
state "ta" as cplta #cccccc {
state "report" as cpltareport #cccccc {
}
}
}


        state "cpl" as cpl #cccccc {
state "ta" as cplta #cccccc {
state "setparent" as cpltasetparent #cccccc {
}
}
}


        state "cpl" as cpl #cccccc {
state "ta" as cplta #cccccc {
state "show" as cpltashow #cccccc {
}
}
}


        state "cpl" as cpl #cccccc {
state "ta" as cplta #cccccc {
state "stats" as cpltastats #cccccc {
state "get" as cpltastatsget #cccccc {
}
}
}
}


        state "cpl" as cpl #cccccc {
state "ta" as cplta #cccccc {
state "stats" as cpltastats #cccccc {
state "send" as cpltastatssend #cccccc {
}
}
}
}




        state "cpl" as cpl #cccccc {
state "Device" as cpldevice #cccccc {
state "stats" as cpldevicestats #cccccc {
}
}
}

        
    state "ta" as ta #lavender {
state "report" as tareport #lavender {
}
}

    cpldevicestats ---> tareport
  
    state "tc" as tc #lavender {
state "report" as tcreport #lavender {
}
}

    cpldevicestats ---> tcreport
  



@enduml
