@startuml



package "Telemetry Aggregator" #cccccc {

    interface "Telemetry Aggregator" as i {
            ^device.stats
    
            /edgemere/cpl/ta/list()
            /edgemere/cpl/ta/report()
            /edgemere/cpl/ta/setparent()
            /edgemere/cpl/ta/show()
            /edgemere/cpl/ta/stats/get()
            /edgemere/cpl/ta/stats/send()
    
    }
}

circle REST
circle Web
circle CLI
circle WebSocket

i -down- Web
i -down- CLI
i -down- REST
WebSocket -left- i: events >

package "Telemetry Aggregator" #cccccc {


}



@enduml
