@startuml

class "AggregatedDevice" as Model {
 string name
 string ename
 string hostname
 string type

 addDevices()
 disable()
 enable()
 reserve()
 addToHardware()
 create()
 getReservations()
 provision()
 
}

rectangle "Device" as Device #lightblue {
}

Model *--> "n" Device : devices


rectangle "PhysicalProfile" as PhysicalProfile #lightblue {
}

Model o--> "1" PhysicalProfile : profile


rectangle "DataCenter" as DataCenter #lightblue {
}

Model o--> "1" DataCenter : datacenter


rectangle "Hardware" as Hardware #lightblue {
}

Model *--> "n" Hardware : hardware


rectangle "AggregatedDevice" as AggregatedDevice #lightblue {
}

Model o--> "1" AggregatedDevice : parent




    rectangle "Device" as Device #lightgreen {
    }
    
        Device   o--> "1" Model : "parent"
    
    rectangle "DataCenter" as DataCenter #lightgreen {
    }
    
        DataCenter   *--> "n" Model : "adevices"
    
    rectangle "Cloud" as Cloud #lightgreen {
    }
    
        Cloud   o--> "n" Model : "adevices"
    
    rectangle "Request" as Request #lightgreen {
    }
    
        Request   o--> "n" Model : "aggregates"
    
    rectangle "AggregatedDevice" as AggregatedDevice #lightgreen {
    }
    
        AggregatedDevice   o--> "1" Model : "parent"
    

@enduml
