@startuml

class "AggregatedDevice" as Model {
 string name
 string ename
 string type

 addDevices()
 reserve()
 addToHardware()
 create()
 disable()
 enable()
 getReservations()
 provision()
 
}

rectangle "Device" as Device {
}

Model *--> "n" Device : devices


rectangle "PhysicalProfile" as PhysicalProfile {
}

Model o--> "1" PhysicalProfile : profile


rectangle "DataCenter" as DataCenter {
}

Model o--> "1" DataCenter : datacenter


rectangle "Hardware" as Hardware {
}

Model *--> "n" Hardware : hardware


rectangle "AggregatedDevice" as AggregatedDevice {
}

Model o--> "1" AggregatedDevice : parent




@enduml
