@startuml

frame local {
    database "shared"
    node "example1" <<small>> {
        database "/dev/sda"
        folder "/mnt/shared" as e1s
    }
    node "example2" <<small>> {
        database "/dev/sda" as s2
        folder "/mnt/shared" as e2s
    }
    node "example3" <<large>> {
        database "/dev/sda" as s3
        folder "/mnt/shared" as e3s
    }

   shared .. e1s
   shared .. e2s
   shared .. e3s
}

frame prod {
    cloud AWS
    database "sharedp1"
    node "examplep1" <<small>> {
        database "/dev/sda" as c1
        folder "/mnt/shared" as c1s
    }
    node "examplep2" <<small>> {
        database "/dev/sda" as c2
        folder "/mnt/shared" as c2s
    }
    node "examplep3" <<large>> {
        database "/dev/sda" as c3
        folder "/mnt/shared" as c3s
    }

   sharedp1 .. c1s
   sharedp1 .. c2s
   sharedp1 .. c3s
}
@enduml
