@startuml


usecase "Manage Data Instances" as ManageDataInstances #yellow

Actor "Data Scientist" as DataScientist

DataScientist --> ManageDataInstances

Actor "Application Developer" as ApplicationDeveloper

ApplicationDeveloper --> ManageDataInstances



usecase "CreateDataInstance" as CreateDataInstance #lightgrey

ManageDataInstances --> CreateDataInstance

usecase "FindDataInstance" as FindDataInstance #lightgrey

ManageDataInstances --> FindDataInstance

usecase "RemoveDataInstance" as RemoveDataInstance #lightgrey

ManageDataInstances --> RemoveDataInstance









@enduml
