@startuml


actor "DataEngineer"


entity EventBus

box Data Orchestrator #lightblue
    boundary do #white
end box


group Given [DataEngineer has access to datainstance/find method]

"DataEngineer" --/ do: DataEngineer uses the method to find a specific data instance
"do" -> do: Find Data Instance



"DataEngineer" /-- do: The specific data instance is retrieved and displayed to the DataEngineer


end

@enduml
