@startuml


actor "DataEngineer"


entity EventBus

box Data Orchestrator #lightblue
    boundary do #white
end box


group Given [A DataEngineer has a specific data instance to remove]

"DataEngineer" --/ do: The DataEngineer invokes the &#39;datainstance/destroy&#39; method
"do" -> do: Remove Data Instance



"DataEngineer" /-- do: The specified data instance is removed from the system


end

@enduml
