@startuml


usecase "Manage Cost Model" as ManageCostModel #yellow

Actor "IT Operations" as ITOperations

ITOperations --> ManageCostModel





usecase "Control Virtual Infrastructure" as ControlVirtualInfrastructure #lightyellow

ManageCostModel <-- ControlVirtualInfrastructure : extends







@enduml
