@startuml



state Environment #lightgreen {

    state Init #lightgreen {
    }

    state Enabled #lightgreen {
    }

    state Disabled #lightgreen {
    }

}


Init --> Enabled : create

Enabled --> Disabled : disable

Disabled --> Enabled : enable




@enduml
