@startuml



state Reservation #lightyellow {

    state Init #lightyellow {
    }

    state Created #lightyellow {
    }

    state Confirmed #lightyellow {
    }

    state Rejected #lightyellow {
    }

}


Init --> Created : create

Init --> Confirmed : confirm

Init --> Rejected : free

Created --> Confirmed : confirm

Created --> Rejected : free



 state "edgemere" as edgemere #lightyellow {
state "sdi" as edgemeresdi #lightyellow {
state "io" as edgemeresdiio #lightyellow {
state "provision" as edgemeresdiioprovision #lightyellow {
}
}
}
}

 Confirmed -[#black]--> edgemeresdiioprovision
 
 
 Rejected -[#black]--> Null
 

@enduml
