@startuml



state Reservation #cccc88 {

    state Init #cccc88 {
    }

    state Created #cccc88 {
    }

    state Confirmed #cccc88 {
    }

    state Rejected #cccc88 {
    }




Init -[#black]--> Created : create

Init -[#black]--> Confirmed : confirm

Init -[#black]--> Rejected : free

Created -[#black]--> Confirmed : confirm

Created -[#black]--> Rejected : free

}

 
 Confirmed -[#black]--> Null
 
 
 Rejected -[#black]--> Null
 

@enduml
