@startuml


package "Software Defined Infrastructure" #cccc88 {
    
        class Cloud {
        }
    }

package "Cloud Broker" #88cc88 {
    
        class ResourceMap {
        }
    
        class ResourceInstanceType {
        }
    
        class ResourceCost {
        }
    }

package "Common Physical Layer" #cccccc {
    
        class PhysicalProfile {
        }
    }


package "Cloud Broker" #88cc88 {

    interface "Cloud Broker" as i {
            /edgemere/sml/cb/billing/list()
            /edgemere/sml/cb/data/govern()
            /edgemere/sml/cb/multicloud/addclouds()
            /edgemere/sml/cb/multicloud/addpolicies()
            /edgemere/sml/cb/multicloud/list()
            /edgemere/sml/cb/multicloud/mapresources()
            /edgemere/sml/cb/multicloud/removepolicies()
            /edgemere/sml/cb/resourceinstancetype/list()
            /edgemere/sml/cb/resources/find()
            /edgemere/sml/cb/service/mapresources()
    
    }
}

CLI ()-- i
REST ()-- i
Web ()-- i

package "Cloud Broker" #88cc88 {
        class "CloudType" {
                 string name
                             create()
            }
                CloudType o--> "n" Cloud : clouds
                        CloudType *--> "n" ResourceMap : assetmap
                        CloudType *--> "n" ResourceInstanceType : instancetypes
                        CloudType *--> "n" ResourceMap : metricmap
            
    
    class "ResourceCost" {
                 string name
                 number amount
                 string units
                    }
                ResourceCost o--> "1" ResourceInstanceType : parent
            
    
    class "ResourceInstanceType" {
                 string name
                 string type
                    }
                ResourceInstanceType *--> "1" PhysicalProfile : profile
                        ResourceInstanceType *--> "n" ResourceCost : costs
            
    
    class "ResourceMap" {
                 string name
                    }
                ResourceMap o--> "1" ResourceInstanceType : value
            
    

}



@enduml
