@startuml
left to right direction


state "sml" as sml #88cc88 {
state "cb" as smlcb #88cc88 {
}
}


state "smlcb" as pstatename #88cc88 {
    state "Custom Function" as cbfunction {
    }
}

        state "sml" as sml #88cc88 {
state "cb" as smlcb #88cc88 {
state "billing" as smlcbbilling #88cc88 {
state "list" as smlcbbillinglist #88cc88 {
}
}
}
}


        state "sml" as sml #88cc88 {
state "cb" as smlcb #88cc88 {
state "data" as smlcbdata #88cc88 {
state "govern" as smlcbdatagovern #88cc88 {
}
}
}
}


        state "sml" as sml #88cc88 {
state "cb" as smlcb #88cc88 {
state "multicloud" as smlcbmulticloud #88cc88 {
state "addclouds" as smlcbmulticloudaddclouds #88cc88 {
}
}
}
}


        state "sml" as sml #88cc88 {
state "cb" as smlcb #88cc88 {
state "multicloud" as smlcbmulticloud #88cc88 {
state "addpolicies" as smlcbmulticloudaddpolicies #88cc88 {
}
}
}
}


        state "sml" as sml #88cc88 {
state "cb" as smlcb #88cc88 {
state "multicloud" as smlcbmulticloud #88cc88 {
state "list" as smlcbmulticloudlist #88cc88 {
}
}
}
}


        state "sml" as sml #88cc88 {
state "cb" as smlcb #88cc88 {
state "multicloud" as smlcbmulticloud #88cc88 {
state "mapresources" as smlcbmulticloudmapresources #88cc88 {
}
}
}
}


        state "sml" as sml #88cc88 {
state "cb" as smlcb #88cc88 {
state "multicloud" as smlcbmulticloud #88cc88 {
state "removepolicies" as smlcbmulticloudremovepolicies #88cc88 {
}
}
}
}


        state "sml" as sml #88cc88 {
state "cb" as smlcb #88cc88 {
state "resourceinstancetype" as smlcbresourceinstancetype #88cc88 {
state "list" as smlcbresourceinstancetypelist #88cc88 {
}
}
}
}


        state "sml" as sml #88cc88 {
state "cb" as smlcb #88cc88 {
state "resources" as smlcbresources #88cc88 {
state "find" as smlcbresourcesfind #88cc88 {
}
}
}
}


        state "sml" as sml #88cc88 {
state "cb" as smlcb #88cc88 {
state "service" as smlcbservice #88cc88 {
state "mapresources" as smlcbservicemapresources #88cc88 {
}
}
}
}






@enduml
