@startuml
left to right direction


state "sml" as sml #lightgreen {
state "cb" as smlcb #lightgreen {
}
}


state smlcb #lightgreen {
    state "Custom Function" as cbfunction {
    }
}

        state "sml" as sml #lightgreen {
state "cb" as smlcb #lightgreen {
state "billing" as smlcbbilling #lightgreen {
state "list" as smlcbbillinglist #lightgreen {
}
}
}
}


        state "sml" as sml #lightgreen {
state "cb" as smlcb #lightgreen {
state "data" as smlcbdata #lightgreen {
state "govern" as smlcbdatagovern #lightgreen {
}
}
}
}


        state "sml" as sml #lightgreen {
state "cb" as smlcb #lightgreen {
state "multicloud" as smlcbmulticloud #lightgreen {
state "addclouds" as smlcbmulticloudaddclouds #lightgreen {
}
}
}
}


        state "sml" as sml #lightgreen {
state "cb" as smlcb #lightgreen {
state "multicloud" as smlcbmulticloud #lightgreen {
state "addpolicies" as smlcbmulticloudaddpolicies #lightgreen {
}
}
}
}


        state "sml" as sml #lightgreen {
state "cb" as smlcb #lightgreen {
state "multicloud" as smlcbmulticloud #lightgreen {
state "list" as smlcbmulticloudlist #lightgreen {
}
}
}
}


        state "sml" as sml #lightgreen {
state "cb" as smlcb #lightgreen {
state "multicloud" as smlcbmulticloud #lightgreen {
state "mapresources" as smlcbmulticloudmapresources #lightgreen {
}
}
}
}


        state "sml" as sml #lightgreen {
state "cb" as smlcb #lightgreen {
state "multicloud" as smlcbmulticloud #lightgreen {
state "removepolicies" as smlcbmulticloudremovepolicies #lightgreen {
}
}
}
}


        state "sml" as sml #lightgreen {
state "cb" as smlcb #lightgreen {
state "resourceinstancetype" as smlcbresourceinstancetype #lightgreen {
state "list" as smlcbresourceinstancetypelist #lightgreen {
}
}
}
}


        state "sml" as sml #lightgreen {
state "cb" as smlcb #lightgreen {
state "resources" as smlcbresources #lightgreen {
state "find" as smlcbresourcesfind #lightgreen {
}
}
}
}


        state "sml" as sml #lightgreen {
state "cb" as smlcb #lightgreen {
state "service" as smlcbservice #lightgreen {
state "mapresources" as smlcbservicemapresources #lightgreen {
}
}
}
}






@enduml
