@startuml
left to right direction


    package "edgemere" as edgemere {
package "sml" as edgemeresml {
package "cb" as edgemeresmlcb #88cc88 {
 component "billing" as edgemeresmlcbbilling
 interface "list" as edgemeresmlcbbillinglist
edgemeresmlcbbilling -- edgemeresmlcbbillinglist
}
}
}

    
    package "edgemere" as edgemere {
package "sml" as edgemeresml {
package "cb" as edgemeresmlcb #88cc88 {
 component "data" as edgemeresmlcbdata
 interface "govern" as edgemeresmlcbdatagovern
edgemeresmlcbdata -- edgemeresmlcbdatagovern
}
}
}

    
    package "edgemere" as edgemere {
package "sml" as edgemeresml {
package "cb" as edgemeresmlcb #88cc88 {
 component "multicloud" as edgemeresmlcbmulticloud
 interface "addclouds" as edgemeresmlcbmulticloudaddclouds
edgemeresmlcbmulticloud -- edgemeresmlcbmulticloudaddclouds
}
}
}

    
    package "edgemere" as edgemere {
package "sml" as edgemeresml {
package "cb" as edgemeresmlcb #88cc88 {
 component "multicloud" as edgemeresmlcbmulticloud
 interface "addpolicies" as edgemeresmlcbmulticloudaddpolicies
edgemeresmlcbmulticloud -- edgemeresmlcbmulticloudaddpolicies
}
}
}

    
    package "edgemere" as edgemere {
package "sml" as edgemeresml {
package "cb" as edgemeresmlcb #88cc88 {
 component "multicloud" as edgemeresmlcbmulticloud
 interface "list" as edgemeresmlcbmulticloudlist
edgemeresmlcbmulticloud -- edgemeresmlcbmulticloudlist
}
}
}

    
    package "edgemere" as edgemere {
package "sml" as edgemeresml {
package "cb" as edgemeresmlcb #88cc88 {
 component "multicloud" as edgemeresmlcbmulticloud
 interface "mapresources" as edgemeresmlcbmulticloudmapresources
edgemeresmlcbmulticloud -- edgemeresmlcbmulticloudmapresources
}
}
}

    
    package "edgemere" as edgemere {
package "sml" as edgemeresml {
package "cb" as edgemeresmlcb #88cc88 {
 component "multicloud" as edgemeresmlcbmulticloud
 interface "removepolicies" as edgemeresmlcbmulticloudremovepolicies
edgemeresmlcbmulticloud -- edgemeresmlcbmulticloudremovepolicies
}
}
}

    
    package "edgemere" as edgemere {
package "sml" as edgemeresml {
package "cb" as edgemeresmlcb #88cc88 {
 component "resourceinstancetype" as edgemeresmlcbresourceinstancetype
 interface "list" as edgemeresmlcbresourceinstancetypelist
edgemeresmlcbresourceinstancetype -- edgemeresmlcbresourceinstancetypelist
}
}
}

    
    package "edgemere" as edgemere {
package "sml" as edgemeresml {
package "cb" as edgemeresmlcb #88cc88 {
 component "resources" as edgemeresmlcbresources
 interface "find" as edgemeresmlcbresourcesfind
edgemeresmlcbresources -- edgemeresmlcbresourcesfind
}
}
}

    
    package "edgemere" as edgemere {
package "sml" as edgemeresml {
package "cb" as edgemeresmlcb #88cc88 {
 component "service" as edgemeresmlcbservice
 interface "mapresources" as edgemeresmlcbservicemapresources
edgemeresmlcbservice -- edgemeresmlcbservicemapresources
}
}
}

    























        rectangle "Manage Multi Cloud" as ManageMultiCloud #ffffaa {
            ("Add Cloud to Multi Cloud")/ as ITOperationsManageMultiCloudAddCloudtoMultiCloud
        }
    
    edgemeresmlcbmulticloudaddclouds <-- ITOperationsManageMultiCloudAddCloudtoMultiCloud
    
        rectangle "Manage Multi Cloud" as ManageMultiCloud #ffffaa {
            ("Manage Policies for Multi Cloud")/ as ITOperationsManageMultiCloudManagePoliciesforMultiCloud
        }
    
    edgemeresmlcbmulticloudaddpolicies <-- ITOperationsManageMultiCloudManagePoliciesforMultiCloud
    
        rectangle "Manage Multi Cloud" as ManageMultiCloud #ffffaa {
            ("Manage Policies for Multi Cloud")/ as ITOperationsManageMultiCloudRemoveCloudfromMultiCloud
        }
    
    edgemeresmlcbmulticloudremovepolicies <-- ITOperationsManageMultiCloudRemoveCloudfromMultiCloud
    







@enduml
