@startuml
left to right direction



state "IT Operations" as ITOperations {
    state "Find Resources" as ITOperationsFindResources {
    }
}
state "edgemere" as edgemere #lightgreen {
state "sml" as edgemeresml #lightgreen {
state "cb" as edgemeresmlcb #lightgreen {
state "resources" as edgemeresmlcbresources #lightgreen {
state "find" as edgemeresmlcbresourcesfind #lightgreen {
}
}
}
}
}

ITOperationsFindResources --> edgemeresmlcbresourcesfind


 
state "ITOperations" as ITOperations {
    state "ManageBilling" as ITOperationsManageBilling {
    }
}
state "edgemere" as edgemere #lightgreen {
state "sml" as edgemeresml #lightgreen {
state "cb" as edgemeresmlcb #lightgreen {
state "billing" as edgemeresmlcbbilling #lightgreen {
state "list" as edgemeresmlcbbillinglist #lightgreen {
}
}
}
}
}

ITOperationsManageBilling --> edgemeresmlcbbillinglist


 
state "ITOperations" as ITOperations {
    state "ManageCostModel" as ITOperationsManageCostModel {
    }
}
state "edgemere" as edgemere #lightgreen {
state "sml" as edgemeresml #lightgreen {
state "cb" as edgemeresmlcb #lightgreen {
state "ResourceInstanceType" as edgemeresmlcbResourceInstanceType #lightgreen {
state "list" as edgemeresmlcbResourceInstanceTypelist #lightgreen {
}
}
}
}
}

ITOperationsManageCostModel --> edgemeresmlcbResourceInstanceTypelist


 
state "IT Operations" as ITOperations {
    state "Manage Multi Cloud" as ITOperationsManageMultiCloud {
    }
}
state "edgemere" as edgemere #lightgreen {
state "sml" as edgemeresml #lightgreen {
state "cb" as edgemeresmlcb #lightgreen {
state "multicloud" as edgemeresmlcbmulticloud #lightgreen {
state "list" as edgemeresmlcbmulticloudlist #lightgreen {
}
}
}
}
}

ITOperationsManageMultiCloud --> edgemeresmlcbmulticloudlist


    state "IT Operations" as ITOperations {
        state "Manage Multi Cloud" as ITOperationsManageMultiCloud {
            state "Add Cloud to Multi Cloud" as ITOperationsManageMultiCloudAddCloudtoMultiCloud {
            }
        }
    }
    
    ITOperationsManageMultiCloudAddCloudtoMultiCloud --> Null
    
 
    state "IT Operations" as ITOperations {
        state "Manage Multi Cloud" as ITOperationsManageMultiCloud {
            state "Manage Policies for Multi Cloud" as ITOperationsManageMultiCloudManagePoliciesforMultiCloud {
            }
        }
    }
    
    ITOperationsManageMultiCloudManagePoliciesforMultiCloud --> Null
    
 
    state "IT Operations" as ITOperations {
        state "Manage Multi Cloud" as ITOperationsManageMultiCloud {
            state "Manage Policies for Multi Cloud" as ITOperationsManageMultiCloudRemoveCloudfromMultiCloud {
            }
        }
    }
    
    ITOperationsManageMultiCloudRemoveCloudfromMultiCloud --> Null
    
 
 
state "IT Operations" as ITOperations {
    state "Map Assets to Cloud" as ITOperationsMapAssetstoCloud {
    }
}
state "edgemere" as edgemere #lightgreen {
state "sml" as edgemeresml #lightgreen {
state "cb" as edgemeresmlcb #lightgreen {
state "multicloud" as edgemeresmlcbmulticloud #lightgreen {
state "mapresources" as edgemeresmlcbmulticloudmapresources #lightgreen {
}
}
}
}
}

ITOperationsMapAssetstoCloud --> edgemeresmlcbmulticloudmapresources


 
state "IT Operations" as ITOperations {
    state "Map Services to Resources" as ITOperationsMapServicestoResources {
    }
}
state "edgemere" as edgemere #lightgreen {
state "sml" as edgemeresml #lightgreen {
state "cb" as edgemeresmlcb #lightgreen {
state "service" as edgemeresmlcbservice #lightgreen {
state "mapresources" as edgemeresmlcbservicemapresources #lightgreen {
}
}
}
}
}

ITOperationsMapServicestoResources --> edgemeresmlcbservicemapresources


 

@enduml
