@startuml
left to right direction



state "IT Operations" as ITOperations {
    state "Find Resources" as ITOperationsFindResources {
    }
}
state "sml" as sml #lightgreen {
state "cb" as smlcb #lightgreen {
state "resources" as smlcbresources #lightgreen {
state "find" as smlcbresourcesfind #lightgreen {
}
}
}
}

ITOperationsFindResources --> smlcbresourcesfind


 
state "ITOperations" as ITOperations {
    state "ManageBilling" as ITOperationsManageBilling {
    }
}
state "sml" as sml #lightgreen {
state "cb" as smlcb #lightgreen {
state "billing" as smlcbbilling #lightgreen {
state "list" as smlcbbillinglist #lightgreen {
}
}
}
}

ITOperationsManageBilling --> smlcbbillinglist


 
state "ITOperations" as ITOperations {
    state "ManageCostModel" as ITOperationsManageCostModel {
    }
}
state "sml" as sml #lightgreen {
state "cb" as smlcb #lightgreen {
state "ResourceInstanceType" as smlcbResourceInstanceType #lightgreen {
state "list" as smlcbResourceInstanceTypelist #lightgreen {
}
}
}
}

ITOperationsManageCostModel --> smlcbResourceInstanceTypelist


 
state "IT Operations" as ITOperations {
    state "Manage Multi Cloud" as ITOperationsManageMultiCloud {
    }
}
state "sml" as sml #lightgreen {
state "cb" as smlcb #lightgreen {
state "multicloud" as smlcbmulticloud #lightgreen {
state "list" as smlcbmulticloudlist #lightgreen {
}
}
}
}

ITOperationsManageMultiCloud --> smlcbmulticloudlist


    state "IT Operations" as ITOperations {
        state "Manage Multi Cloud" as ITOperationsManageMultiCloud {
            state "Add Cloud to Multi Cloud" as ITOperationsManageMultiCloudAddCloudtoMultiCloud {
            }
        }
    }
    state "sml" as sml #lightgreen {
state "cbmulticloud" as smlcbmulticloud #lightgreen {
state "addclouds" as smlcbmulticloudaddclouds #lightgreen {
}
}
}

    ITOperationsManageMultiCloudAddCloudtoMultiCloud --> smlcbmulticloudaddclouds
    
 
    state "IT Operations" as ITOperations {
        state "Manage Multi Cloud" as ITOperationsManageMultiCloud {
            state "Manage Policies for Multi Cloud" as ITOperationsManageMultiCloudManagePoliciesforMultiCloud {
            }
        }
    }
    state "sml" as sml #lightgreen {
state "cbmulticloud" as smlcbmulticloud #lightgreen {
state "addpolicies" as smlcbmulticloudaddpolicies #lightgreen {
}
}
}

    ITOperationsManageMultiCloudManagePoliciesforMultiCloud --> smlcbmulticloudaddpolicies
    
 
    state "IT Operations" as ITOperations {
        state "Manage Multi Cloud" as ITOperationsManageMultiCloud {
            state "Manage Policies for Multi Cloud" as ITOperationsManageMultiCloudRemoveCloudfromMultiCloud {
            }
        }
    }
    state "sml" as sml #lightgreen {
state "cbmulticloud" as smlcbmulticloud #lightgreen {
state "removepolicies" as smlcbmulticloudremovepolicies #lightgreen {
}
}
}

    ITOperationsManageMultiCloudRemoveCloudfromMultiCloud --> smlcbmulticloudremovepolicies
    
 
 
state "IT Operations" as ITOperations {
    state "Map Assets to Cloud" as ITOperationsMapAssetstoCloud {
    }
}
state "sml" as sml #lightgreen {
state "cb" as smlcb #lightgreen {
state "multicloud" as smlcbmulticloud #lightgreen {
state "mapresources" as smlcbmulticloudmapresources #lightgreen {
}
}
}
}

ITOperationsMapAssetstoCloud --> smlcbmulticloudmapresources


 
state "IT Operations" as ITOperations {
    state "Map Services to Resources" as ITOperationsMapServicestoResources {
    }
}
state "sml" as sml #lightgreen {
state "cb" as smlcb #lightgreen {
state "service" as smlcbservice #lightgreen {
state "mapresources" as smlcbservicemapresources #lightgreen {
}
}
}
}

ITOperationsMapServicestoResources --> smlcbservicemapresources


 

@enduml
