@startuml


package "Software Defined Infrastructure" #cccc88 {

}

package "Cloud Broker" #88cc88 {

}

package "Common Physical Layer" #cccccc {

}


package "Cloud Broker" #88cc88 {

    interface "Cloud Broker" as i {
    
            /edgemere/sml/cb/billing/list()
            /edgemere/sml/cb/data/govern()
            /edgemere/sml/cb/multicloud/addclouds()
            /edgemere/sml/cb/multicloud/addpolicies()
            /edgemere/sml/cb/multicloud/list()
            /edgemere/sml/cb/multicloud/mapresources()
            /edgemere/sml/cb/multicloud/removepolicies()
            /edgemere/sml/cb/resourceinstancetype/list()
            /edgemere/sml/cb/resources/find()
            /edgemere/sml/cb/service/mapresources()
    
    }
}

circle REST
circle Web
circle CLI
circle WebSocket

i -down- Web
i -down- CLI
i -down- REST
WebSocket -left- i: events >

package "Cloud Broker" #88cc88 {


}



@enduml
