@startuml

class "ResourceMap" as Model {
 string name

 
}

rectangle "ResourceInstanceType" as ResourceInstanceType #lightblue {
}

Model o--> "1" ResourceInstanceType : value




    rectangle "CloudType" as CloudType #lightgreen {
    }
    
        CloudType   *--> "n" Model : "assetmap"
    
    rectangle "CloudType" as CloudType #lightgreen {
    }
    
        CloudType   *--> "n" Model : "metricmap"
    

@enduml
