@startuml


package "Software Defined Infrastructure" #cccc88 {
    }


package "Provision Engine" #88cc88 {

    interface "Provision Engine" as i {
    
    }
}

CLI ()-- i
REST ()-- i
Web ()-- i

package "Provision Engine" #88cc88 {
    
}


    "Provision Engine" --> "Software Defined Infrastructure"


@enduml
