@startuml
left to right direction


state "sml" as sml #lightgreen {
state "pe" as smlpe #lightgreen {
}
}


state "smlpe" as pstatename #lightgreen {
    state "Custom Function" as pefunction {
    }
}





@enduml
