@startuml
left to right direction


state "sml" as sml #88cc88 {
state "pe" as smlpe #88cc88 {
}
}


state "smlpe" as pstatename #88cc88 {
    state "Custom Function" as pefunction {
    }
}





@enduml
