@startuml


package "Software Defined Infrastructure" #cccc88 {

}


package "Provision Engine" #88cc88 {

    interface "Provision Engine" as i {
    
    
    }
}

circle REST
circle Web
circle CLI
circle WebSocket

i -down- Web
i -down- CLI
i -down- REST
WebSocket -left- i: events >

package "Provision Engine" #88cc88 {


}


    "Software Defined Infrastructure" <-- "Provision Engine"


@enduml
