@startuml

class "SecurityProfile" as Model {
 string name

 
}

rectangle "Policy" as Policy #lightblue {
}

Model *--> "n" Policy : policies


rectangle "Identity" as Identity #lightblue {
}

Model o--> "n" Identity : enforcing




    rectangle "Environment" as Environment #lightgreen {
    }
    
        Environment   o--> "1" Model : "profile"
    

@enduml
