@startuml


usecase "Manage Meta Data" as ManageMetaData

Actor "Data Scientist" as DataScientist

DataScientist --> ManageMetaData



usecase "ManageDataCatalog" as ManageDataCatalog #lightgrey

ManageMetaData --> ManageDataCatalog

@enduml
