@startuml


package "Developer Services" #aaffff {
    }

package "Identity Aspect" #cc8888 {
    }


package "Workflow Services" #88cccc {

    interface "Workflow Services" as i {
    
    }
}

CLI ()-- i
REST ()-- i
Web ()-- i

package "Workflow Services" #88cccc {
    
}


    "Workflow Services" --> "Developer Services"

    "Workflow Services" --> "Identity Aspect"


@enduml
