@startuml
left to right direction


state "aml" as aml #88cccc {
state "ws" as amlws #88cccc {
}
}


state "amlws" as pstatename #88cccc {
    state "Custom Function" as wsfunction {
    }
}





@enduml
