@startuml


package "Developer Services" #lightblue {

}

package "Identity Aspect" #cc8888 {

}


package "Workflow Services" #88cccc {

    interface "Workflow Services" as i {
    
    
    }
}

circle REST
circle Web
circle CLI
circle WebSocket

i -down- Web
i -down- CLI
i -down- REST
WebSocket -left- i: events >

package "Workflow Services" #88cccc {


}


    "Developer Services" <-- "Workflow Services"

    "Identity Aspect" <-- "Workflow Services"


@enduml
