@startuml


usecase "Manage Clouds" as ManageClouds #yellow

Actor "IT Operations" as ITOperations

ITOperations --> ManageClouds





usecase "Coordinate Services" as CoordinateServices #lightyellow

ManageClouds <-- CoordinateServices : extends







@enduml
