@startuml

class "SourceMetaData" as Model {
 string connection
 string name
 string value

 
}

rectangle "Data" as Data #lightblue {
}

Model o--> "1" Data : data




    rectangle "Data" as Data #lightgreen {
    }
    
        Data   *--> "n" Model : "connection"
    
    rectangle "Data" as Data #lightgreen {
    }
    
        Data   *--> "n" Model : "connection"
    
    rectangle "Data" as Data #lightgreen {
    }
    
        Data   *--> "n" Model : "connection"
    
    rectangle "Data" as Data #lightgreen {
    }
    
        Data   *--> "n" Model : "connection"
    
    rectangle "Data" as Data #lightgreen {
    }
    
        Data   *--> "n" Model : "connection"
    
    rectangle "Data" as Data #lightgreen {
    }
    
        Data   *--> "n" Model : "connection"
    
    rectangle "Data" as Data #lightgreen {
    }
    
        Data   *--> "n" Model : "connection"
    
    rectangle "Data" as Data #lightgreen {
    }
    
        Data   *--> "n" Model : "connection"
    
    rectangle "Data" as Data #lightgreen {
    }
    
        Data   *--> "n" Model : "connection"
    
    rectangle "Data" as Data #lightgreen {
    }
    
        Data   *--> "n" Model : "connection"
    
    rectangle "Data" as Data #lightgreen {
    }
    
        Data   *--> "n" Model : "connection"
    
    rectangle "Data" as Data #lightgreen {
    }
    
        Data   *--> "n" Model : "connection"
    
    rectangle "Data" as Data #lightgreen {
    }
    
        Data   *--> "n" Model : "connection"
    
    rectangle "Data" as Data #lightgreen {
    }
    
        Data   *--> "n" Model : "connection"
    
    rectangle "Data" as Data #lightgreen {
    }
    
        Data   *--> "n" Model : "connection"
    
    rectangle "Data" as Data #lightgreen {
    }
    
        Data   *--> "n" Model : "connection"
    
    rectangle "Data" as Data #lightgreen {
    }
    
        Data   *--> "n" Model : "connection"
    
    rectangle "Data" as Data #lightgreen {
    }
    
        Data   *--> "n" Model : "connection"
    
    rectangle "Data" as Data #lightgreen {
    }
    
        Data   *--> "n" Model : "connection"
    
    rectangle "Data" as Data #lightgreen {
    }
    
        Data   *--> "n" Model : "connection"
    
    rectangle "Data" as Data #lightgreen {
    }
    
        Data   *--> "n" Model : "connection"
    
    rectangle "Data" as Data #lightgreen {
    }
    
        Data   *--> "n" Model : "connection"
    
    rectangle "Data" as Data #lightgreen {
    }
    
        Data   *--> "n" Model : "connection"
    
    rectangle "Data" as Data #lightgreen {
    }
    
        Data   *--> "n" Model : "connection"
    
    rectangle "Data" as Data #lightgreen {
    }
    
        Data   *--> "n" Model : "connection"
    
    rectangle "Data" as Data #lightgreen {
    }
    
        Data   *--> "n" Model : "connection"
    
    rectangle "Data" as Data #lightgreen {
    }
    
        Data   *--> "n" Model : "connection"
    
    rectangle "Data" as Data #lightgreen {
    }
    
        Data   *--> "n" Model : "connection"
    
    rectangle "Data" as Data #lightgreen {
    }
    
        Data   *--> "n" Model : "connection"
    
    rectangle "Data" as Data #lightgreen {
    }
    
        Data   *--> "n" Model : "connection"
    
    rectangle "Data" as Data #lightgreen {
    }
    
        Data   *--> "n" Model : "connection"
    
    rectangle "Data" as Data #lightgreen {
    }
    
        Data   *--> "n" Model : "connection"
    
    rectangle "Data" as Data #lightgreen {
    }
    
        Data   *--> "n" Model : "connection"
    
    rectangle "Data" as Data #lightgreen {
    }
    
        Data   *--> "n" Model : "connection"
    
    rectangle "Data" as Data #lightgreen {
    }
    
        Data   *--> "n" Model : "connection"
    
    rectangle "Data" as Data #lightgreen {
    }
    
        Data   *--> "n" Model : "connection"
    
    rectangle "Data" as Data #lightgreen {
    }
    
        Data   *--> "n" Model : "connection"
    
    rectangle "Data" as Data #lightgreen {
    }
    
        Data   *--> "n" Model : "connection"
    
    rectangle "Data" as Data #lightgreen {
    }
    
        Data   *--> "n" Model : "connection"
    
    rectangle "Data" as Data #lightgreen {
    }
    
        Data   *--> "n" Model : "connection"
    
    rectangle "Data" as Data #lightgreen {
    }
    
        Data   *--> "n" Model : "connection"
    
    rectangle "Data" as Data #lightgreen {
    }
    
        Data   *--> "n" Model : "connection"
    
    rectangle "Data" as Data #lightgreen {
    }
    
        Data   *--> "n" Model : "connection"
    
    rectangle "Data" as Data #lightgreen {
    }
    
        Data   *--> "n" Model : "connection"
    

@enduml
