@startuml


package "Software Defined Infrastructure" #lightyellow {
    }

package "Security Aspect" #pink {
    }

package "Service Management Layer" #lightgreen {
    
        class Servicelet {
        }
    }

package "Data Definition Framework" #ffcc88 {
    
        class DataSource {
        }
    
        class DataAdaptor {
        }
    }

package "Data Orchestrator" #lightblue {
    
        class DataInstance {
        }
    }

package "Federated Meta Data Management" #lightblue {
    
        class LineageMetaData {
        }
    
        class MetaData {
        }
    
        class SourceMetaData {
        }
    }


package "Data Management Layer" #ffcc88 {

    interface "Data Management Layer" as i {
            /edgemere/diml/dml/data/govern()
            /edgemere/diml/dml/data/source/name()
            /edgemere/diml/dml/datapolicy/list()
            /edgemere/diml/dml/datasource/list()
            /edgemere/diml/dml/datastrategy/list()
    
    }
}

CLI ()-- i
REST ()-- i
Web ()-- i

package "Data Management Layer" #ffcc88 {
        class "Data" {
                 string name
                 string access
                    }
                Data o--> "1" DataSource : source
                        Data o--> "1" DataAdaptor : adaptor
                        Data o--> "n" DataInstance : instances
                        Data *--> "n" LineageMetaData : lineage
                        Data *--> "n" MetaData : metadata
                        Data *--> "n" SourceMetaData : connection
            
    
    class "DataReference" {
                 string name
                 string shortName
                 json query
                 string connection
                    }
                DataReference *--> "n" DataInstance : instances
                        DataReference o--> "1" Servicelet : parent
            
    
    class "DataStrategy" {
                 string attr1
                    }
                DataStrategy o--> "1" ModelName : assoc1
            
    

}


    "Data Management Layer" --> "Software Defined Infrastructure"

    "Data Management Layer" --> "Security Aspect"

    "Data Management Layer" --> "Service Management Layer"


@enduml
