@startuml

left to right direction
Actor "Chief Data Officer" as ChiefDataOfficer
Actor "Chief Data Officer" as ChiefDataOfficer
Actor "Data Engineer" as DataEngineer
Actor "Chief Data Officer" as ChiefDataOfficer


rectangle "Data Management Layer" #ffcc88 {
usecase "ManageDataGovernance" as ManageDataGovernance
    ChiefDataOfficer --> ManageDataGovernance
    usecase "ManageDataPolicies" as ManageDataPolicies
    ChiefDataOfficer --> ManageDataPolicies
    usecase "ManageDataSources" as ManageDataSources
    DataEngineer --> ManageDataSources
    usecase "ManageDataStrategy" as ManageDataStrategy
    ChiefDataOfficer --> ManageDataStrategy
    }


@enduml
