@startuml

class "MultiCloud" as Model {
 string name

 
}

rectangle "Cloud" as Cloud #lightblue {
}

Model o--> "n" Cloud : clouds


rectangle "PolicyCollection" as PolicyCollection #lightblue {
}

Model o--> "1" PolicyCollection : polices




    rectangle "Environment" as Environment #lightgreen {
    }
    
        Environment   o--> "n" Model : "clouds"
    

@enduml
