@startuml

class "Workload" as Model {
 string name

 
}

rectangle "Application" as Application #lightblue {
}

Model o--> "n" Application : applications




    rectangle "Application" as Application #lightgreen {
    }
    
        Application   o--> "n" Model : "workloads"
    
    rectangle "WorkloadInstance" as WorkloadInstance #lightgreen {
    }
    
        WorkloadInstance   o--> "1" Model : "app"
    
    rectangle "WorkloadTemplate" as WorkloadTemplate #lightgreen {
    }
    
        WorkloadTemplate   o--> "n" Model : "workloads"
    

@enduml
