@startuml


left to right direction

usecase "Manage Services" as ManageServices #yellow

Actor "Stack Developer" as StackDeveloper

StackDeveloper --> ManageServices

Actor "Application Developer" as ApplicationDeveloper

ApplicationDeveloper --> ManageServices



json BuildService #lightyellow {
    "Given": "StackDeveloper uses Build Service",
    "When": "data/create method is invoked with name &#39;hello&#39; and file &#39;./templates/world.yml&#39;",
    "Then": "data/list response should provide the same name &#39;hello&#39; and file &#39;./templates/world.yml&#39;"
}

ManageServices <|-- BuildService



usecase "CoordinateServices" as CoordinateServices #lightyellow

ManageServices <-- CoordinateServices : extends







@enduml
