@startuml


usecase "Manage Services" as ManageServices #yellow

Actor "Stack Developer" as StackDeveloper

StackDeveloper --> ManageServices

Actor "Application Developer" as ApplicationDeveloper

ApplicationDeveloper --> ManageServices











@enduml
