version: "3.7"
services:
  aml:
    image: aml
    stop_grace_period: 1m
    stop_signal: SIGINT
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      replicas: 1
    environment:
      - AILTIRE_STACKNAME={{.Service.Name}}-{{.Task.Slot}}
      - AILTIRE_PARENT=${AILTIRE_APPNAME}
      - AILTIRE_SERVICENAME=aml
      - AILTIRE_APPNAME=${AILTIRE_APPNAME}
      - AILTIRE_PARENT_NETWORK=${AILTIRE_APPNAME}_edgemere_aml_family
    networks:
      childaml:
      sibling:
      parent:
        aliases:
          - aml
  cpl:
    image: cpl
    stop_grace_period: 1m
    stop_signal: SIGINT
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      replicas: 1
    environment:
      - AILTIRE_STACKNAME={{.Service.Name}}-{{.Task.Slot}}
      - AILTIRE_PARENT=${AILTIRE_APPNAME}
      - AILTIRE_SERVICENAME=cpl
      - AILTIRE_APPNAME=${AILTIRE_APPNAME}
      - AILTIRE_PARENT_NETWORK=${AILTIRE_APPNAME}_edgemere_cpl_family
    networks:
      childcpl:
      sibling:
      parent:
        aliases:
          - cpl
  diml:
    image: diml
    stop_grace_period: 1m
    stop_signal: SIGINT
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      replicas: 1
    environment:
      - AILTIRE_STACKNAME={{.Service.Name}}-{{.Task.Slot}}
      - AILTIRE_PARENT=${AILTIRE_APPNAME}
      - AILTIRE_SERVICENAME=diml
      - AILTIRE_APPNAME=${AILTIRE_APPNAME}
      - AILTIRE_PARENT_NETWORK=${AILTIRE_APPNAME}_edgemere_diml_family
    networks:
      childdiml:
      sibling:
      parent:
        aliases:
          - diml
  ia:
    image: ia
    stop_grace_period: 1m
    stop_signal: SIGINT
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      replicas: 1
    environment:
      - AILTIRE_STACKNAME={{.Service.Name}}-{{.Task.Slot}}
      - AILTIRE_PARENT=${AILTIRE_APPNAME}
      - AILTIRE_SERVICENAME=ia
      - AILTIRE_APPNAME=${AILTIRE_APPNAME}
      - AILTIRE_PARENT_NETWORK=${AILTIRE_APPNAME}_edgemere_ia_family
    networks:
      childia:
      sibling:
      parent:
        aliases:
          - ia
  sa:
    image: sa
    stop_grace_period: 1m
    stop_signal: SIGINT
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      replicas: 1
    environment:
      - AILTIRE_STACKNAME={{.Service.Name}}-{{.Task.Slot}}
      - AILTIRE_PARENT=${AILTIRE_APPNAME}
      - AILTIRE_SERVICENAME=sa
      - AILTIRE_APPNAME=${AILTIRE_APPNAME}
      - AILTIRE_PARENT_NETWORK=${AILTIRE_APPNAME}_edgemere_sa_family
    networks:
      childsa:
      sibling:
      parent:
        aliases:
          - sa
  sml:
    image: sml
    stop_grace_period: 1m
    stop_signal: SIGINT
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      replicas: 1
    environment:
      - AILTIRE_STACKNAME={{.Service.Name}}-{{.Task.Slot}}
      - AILTIRE_PARENT=${AILTIRE_APPNAME}
      - AILTIRE_SERVICENAME=sml
      - AILTIRE_APPNAME=${AILTIRE_APPNAME}
      - AILTIRE_PARENT_NETWORK=${AILTIRE_APPNAME}_edgemere_sml_family
    networks:
      childsml:
      sibling:
      parent:
        aliases:
          - sml
  sdi:
    image: sdi
    stop_grace_period: 1m
    stop_signal: SIGINT
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      replicas: 1
    environment:
      - AILTIRE_STACKNAME={{.Service.Name}}-{{.Task.Slot}}
      - AILTIRE_PARENT=${AILTIRE_APPNAME}
      - AILTIRE_SERVICENAME=sdi
      - AILTIRE_APPNAME=${AILTIRE_APPNAME}
      - AILTIRE_PARENT_NETWORK=${AILTIRE_APPNAME}_edgemere_sdi_family
    networks:
      childsdi:
      sibling:
      parent:
        aliases:
          - sdi
  web:
    image: edgemere_web
    stop_grace_period: 1m
    stop_signal: SIGINT
    deploy:
      replicas: 1
    environment:
      - AILTIRE_STACKNAME={{.Service.Name}}-{{.Task.Slot}}
      - AILTIRE_SERVICENAME=web
      - AILTIRE_PARENT=${AILTIRE_APPNAME}
      - AILTIRE_PARENTHOST=admin
      - AILTIRE_APPNAME=${AILTIRE_APPNAME}
    networks:
      sibling:
      parent:
        aliases:
        - web
  doc:
    image: edgemere_doc
    stop_grace_period: 1m
    stop_signal: SIGINT
    deploy:
      replicas: 1
    environment:
      - AILTIRE_STACKNAME={{.Service.Name}}-{{.Task.Slot}}
      - AILTIRE_SERVICENAME=doc
      - AILTIRE_PARENT=${AILTIRE_APPNAME}
      - AILTIRE_PARENTHOST=admin
      - AILTIRE_APPNAME=${AILTIRE_APPNAME}
    networks:
      sibling:
      parent:
        aliases:
        - doc
networks:
  sibling:
    driver: overlay
  parent:
    external: true
    name: ${AILTIRE_PARENT_NETWORK}
  childaml:
    driver: overlay
    attachable: true
    name: ${AILTIRE_APPNAME}_edgemere_aml_family
  childcpl:
    driver: overlay
    attachable: true
    name: ${AILTIRE_APPNAME}_edgemere_cpl_family
  childdiml:
    driver: overlay
    attachable: true
    name: ${AILTIRE_APPNAME}_edgemere_diml_family
  childia:
    driver: overlay
    attachable: true
    name: ${AILTIRE_APPNAME}_edgemere_ia_family
  childsa:
    driver: overlay
    attachable: true
    name: ${AILTIRE_APPNAME}_edgemere_sa_family
  childsml:
    driver: overlay
    attachable: true
    name: ${AILTIRE_APPNAME}_edgemere_sml_family
  childsdi:
    driver: overlay
    attachable: true
    name: ${AILTIRE_APPNAME}_edgemere_sdi_family

