version: "3.7"
services:
  pubsub:
    image: redis
    networks:
      children:
        aliases:
          - redis
      sibling:
        aliases:
          - redis
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=${APPNAME}_family
        - traefik.http.services.pubsub.loadbalancer.server.port=80
        - traefik.http.routers.pubsub_http.rule=Path(`/pubsub`)
        - traefik.http.routers.pubsub_http.service=pubsub
        - traefik.http.routers.pubsub_http.entrypoints=http
  frontend:
    image: traefik:latest
    command:
      - --api=true
      - --api.dashboard=true
      - --api.insecure=true
      - --api.debug=true
      - --log.level=DEBUG
      - --providers.docker=true
      - --providers.docker.swarmMode=true
      - --providers.docker.network=children
      - --providers.docker.exposedbydefault=false
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
    ports:
      - '80:80'
      - '8080:8080'
      - '443:443'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - children
  web:
    image: edgemere_web
    networks:
      - sibling
      - children
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=${APPNAME}_family
        - traefik.http.services.web.loadbalancer.server.port=3000
        - traefik.http.routers.web_http.rule=Path(`/web`)
        - traefik.http.routers.web_http.service=web
        - traefik.http.routers.web_http.entrypoints=http
  doc:
    image: edgemere_doc
    networks:
      - sibling
      - children
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=${APPNAME}_family
        - traefik.http.services.doc.loadbalancer.server.port=8088
        - traefik.http.routers.doc_http.rule=Path(`/doc`)
        - traefik.http.routers.doc_http.service=doc
        - traefik.http.routers.doc_http.entrypoints=http
networks:
  children:
    driver: overlay
    attachable: true
    name: ${APPNAME}_family
  sibling:
    driver: overlay
