@startuml


left to right direction

usecase "Manage Multi Cloud" as ManageMultiCloud #yellow

Actor "IT Operations" as ITOperations

ITOperations --> ManageMultiCloud



json AddCloudtoMultiCloud #lightyellow {
    "Given": "IT Operations is using a multi cloud system",
    "When": "IT Operations adds a new cloud to the system",
    "Then": "The new cloud is integrated into the multi cloud system"
}

ManageMultiCloud <|-- AddCloudtoMultiCloud

json ManagePoliciesforMultiCloud #lightyellow {
    "Given": "IT Operations needs to manage policies for Multicloud",
    "When": "IT Operations adds, removes, enables or disables policies",
    "Then": "The multicloud systems should update based on the changes"
}

ManageMultiCloud <|-- ManagePoliciesforMultiCloud

json RemoveCloudfromMultiCloud #lightyellow {
    "Given": "IT Operations are enabled to use Multi Cloud",
    "When": "A cloud policy needs to be removed",
    "Then": "IT operations remove the policy from Multi Cloud"
}

ManageMultiCloud <|-- RemoveCloudfromMultiCloud



usecase "Control Virtual Infrastructure" as ControlVirtualInfrastructure #lightyellow

ManageMultiCloud <-- ControlVirtualInfrastructure : extends







@enduml
