@startuml


usecase "Manage Multi Cloud" as ManageMultiCloud #yellow

Actor "IT Operations" as ITOperations

ITOperations --> ManageMultiCloud



usecase "AddCloudtoMultiCloud" as AddCloudtoMultiCloud #lightgrey

ManageMultiCloud --> AddCloudtoMultiCloud

usecase "ManagePoliciesforMultiCloud" as ManagePoliciesforMultiCloud #lightgrey

ManageMultiCloud --> ManagePoliciesforMultiCloud

usecase "RemoveCloudfromMultiCloud" as RemoveCloudfromMultiCloud #lightgrey

ManageMultiCloud --> RemoveCloudfromMultiCloud



usecase "Control Virtual Infrastructure" as ControlVirtualInfrastructure #lightyellow

ManageMultiCloud <-- ControlVirtualInfrastructure : extends







@enduml
