@startuml


actor "IT Operations"


entity EventBus

box Cloud Broker #88cc88
    boundary cb #white
end box


group Given [IT Operations is using a multi cloud system]

"IT Operations" --/ cb: IT Operations adds a new cloud to the system
"cb" -> cb: Add Cloud to Multi Cloud



"IT Operations" /-- cb: The new cloud is integrated into the multi cloud system


end

@enduml
