@startuml


actor "IT Operations"


entity EventBus

box Cloud Broker #88cc88
    boundary cb #white
end box


group Given [IT Operations needs to manage policies for Multicloud]

"IT Operations" --/ cb: IT Operations adds, removes, enables or disables policies
"cb" -> cb: Manage Policies for Multi Cloud



"IT Operations" /-- cb: The multicloud systems should update based on the changes


end

@enduml
