@startuml

actor "IT Operations"


entity EventBus

box Cloud Broker #lightgreen
    boundary cb #white
end box



"IT Operations" -> cb: Manage Policies for Multi Cloud




EventBus --/ cb : method2()
@enduml
