@startuml


actor "IT Operations"


entity EventBus

box Cloud Broker #88cc88
    boundary cb #white
end box


group Given [IT Operations are enabled to use Multi Cloud]

"IT Operations" --/ cb: A cloud policy needs to be removed
"cb" -> cb: Remove Cloud From Multi Cloud



"IT Operations" /-- cb: IT operations remove the policy from Multi Cloud


end

@enduml
