#!/usr/bin/env node

const program = require('commander');

const YAML = require('yamljs');
const Client = require('node-rest-client').Client;
const client = new Client();
global.ailtire = { config: require('C:\\Users\\dwpulsip\\work\\edgemere\\bin\\lib/../../.ailtire.js') };
program.command('addDatacenters [options]', 'Add items to the object')
	.option('--name <string>', 'Name of the object')
	.option('--items <string>', 'Name of the items to add')
	.option('--file <YAML>', 'file with the definition of the items');
program.parse(process.argv);
let url = global.ailtire.config.host + '/cloud/adddatacenters?';
url += 'mode=json';
let args = {headers: {'Content-Type': 'application/json'}, data: {}};
if(program['name']) { args.data['name'] = program['name']; }
if(program['items']) { args.data['items'] = program['items']; }
if(program['file']) { args.data['file'] = YAML.load(program['file']); }
client.post(url, args, (data, response) => {
console.log('URL:' + url);
console.log('ARGS:' + args);
console.log('DATA:' + data.toString());
console.log('RESPONSE:' + response.toString());
if (data.error) { console.error('Error:' + data.error); } else { 
for(let item in data) { console.log(data[item].toString()); } }
});