#!/user/bin/env node
const bent = require('bent');
const program = require('commander');
const YAML = require('yamljs');
const fs = require('fs');
global.ailtire = { config: require('C:\\Users\\dwpulsip\\IdeaProjects\\edgemere\\bin\\lib/../../.ailtire.js') };
program.description('Add items to the object')
	.option('--name <string>', 'Name of the object')
	.option('--items <string>', 'Name of the items to add')
	.option('--file <YAML>', 'file with the definition of the items');
program.parse(process.argv);
let url = global.ailtire.config.host;
let args = {};
let params = '/aggregateddevice/adddevices?';
params += 'mode=json';
let options = program.opts();

if(options['name']) { args['name'] = options['name']; }
if(options['items']) { args['items'] = options['items']; }
if(options['file']) { args['file'] = YAML.load(options['file']); }

        console.log("URL:", url);
        console.log("Args:", args);
const post = bent(url, 'POST', 'json', 200);
(async () => {
    const response = await post(params, args);
    console.log("Response:", response);
})().catch(e => {
    // Deal with the fact the chain failed
    console.error("Response Error:", e);
});