#!/user/bin/env node
const bent = require('bent');
const program = require('commander');
const YAML = require('yamljs');
global.ailtire = { config: require('/mnt/c/Users/dwpulsip/work/edgemere/bin/lib/../../.ailtire.js') };
program.command('addDevices [options]', 'Add items to the object')
	.option('--name <string>', 'Name of the object')
	.option('--items <string>', 'Name of the items to add')
	.option('--file <YAML>', 'file with the definition of the items');
program.parse(process.argv);
let url = global.ailtire.config.host;
let args = {};
let params = '/datacenter/adddevices?';
params += 'mode=json';
if(program['name']) { args['name'] = program['name']; }
if(program['items']) { args['items'] = program['items']; }
if(program['file']) { args['file'] = YAML.load(program['file']); }

const post = bent(url, 'POST', 'json', 200);
(async () => {
    const response = await post(params, args);
    console.log(response.results);
})().catch(e => {
    // Deal with the fact the chain failed
    console.error("Response Error:", e);
});