#!/usr/bin/env node

const program = require('commander');

const YAML = require('yamljs');
const Client = require('node-rest-client').Client;
const client = new Client();
global.ailtire = { config: require('C:\\Users\\dwpulsip\\work\\edgemere\\bin\\lib/../../.ailtire.js') };
program.command('create [options]', 'create entity')
	.option('--name <string>', 'Name of the cloud')
	.option('--file <YAML>', 'file with the definition')
	.option('--type <string>', 'Type of cloud');
program.parse(process.argv);
let url = global.ailtire.config.host + '/cloud/create?';
url += 'mode=json';
let args = {headers: {'Content-Type': 'application/json'}, data: {}};
if(program['name']) { args.data['name'] = program['name']; }
if(program['file']) { args.data['file'] = YAML.load(program['file']); }
if(program['type']) { args.data['type'] = program['type']; }
client.post(url, args, (data, response) => {
console.log('URL:' + url);
console.log('ARGS:' + args);
console.log('DATA:' + data.toString());
console.log('RESPONSE:' + response.toString());
if (data.error) { console.error('Error:' + data.error); } else { 
for(let item in data) { console.log(data[item].toString()); } }
});