#!/user/bin/env node
const bent = require('bent');
const program = require('commander');
const YAML = require('yamljs');
global.ailtire = { config: require('/mnt/c/Users/dwpulsip/work/edgemere/bin/lib/../../.ailtire.js') };
program.command('new [options]', 'New called for web interface');
program.parse(process.argv);
let url = global.ailtire.config.host;
let args = {};
let params = '/datacenter?';
params += 'mode=json';

const post = bent(url, 'POST', 'json', 200);
(async () => {
    const response = await post(params, args);
    console.log(response.results);
})().catch(e => {
    // Deal with the fact the chain failed
    console.error("Response Error:", e);
});