#!/usr/bin/env node

const program = require('commander');

const YAML = require('yamljs');
const Client = require('node-rest-client').Client;
const client = new Client();
global.ailtire = { config: require('C:\\Users\\dwpulsip\\work\\edgemere\\bin\\lib/../../.ailtire.js') };
program.command('new [options]', 'New called for web interface');
program.parse(process.argv);
let url = global.ailtire.config.host + '/datablueprint?';
url += 'mode=json';
let args = {headers: {'Content-Type': 'application/json'}, data: {}};
client.post(url, args, (data, response) => {
console.log('URL:' + url);
console.log('ARGS:' + args);
console.log('DATA:' + data.toString());
console.log('RESPONSE:' + response.toString());
if (data.error) { console.error('Error:' + data.error); } else { 
for(let item in data) { console.log(data[item].toString()); } }
});