#!/usr/bin/env node

const program = require('commander');

const YAML = require('yamljs');
const Client = require('node-rest-client').Client;
const client = new Client();
global.ailtire = { config: require('C:\\Users\\dwpulsip\\work\\edgemere\\bin\\lib/../../.ailtire.js') };
program.command('deploy [options]', 'Description of the action')
	.option('--name <string>', 'Name of the stack to deploy')
	.option('--tag <string>', 'Tag of the deployment of the stack. This is used to reference the deployed stack.')
	.option('--env <string>', 'Name of the deployment environment')
	.option('--args <json>', 'Arguments passed into the stack deployment');
program.parse(process.argv);
let url = global.ailtire.config.host + '/sml/so/stack/deploy?';
url += 'mode=json';
let args = {headers: {'Content-Type': 'application/json'}, data: {}};
if(program['name']) { args.data['name'] = program['name']; }
if(program['tag']) { args.data['tag'] = program['tag']; }
if(program['env']) { args.data['env'] = program['env']; }
if(program['args']) { args.data['args'] = program['args']; }
client.post(url, args, (data, response) => {
console.log('URL:' + url);
console.log('ARGS:' + args);
console.log('DATA:' + data.toString());
console.log('RESPONSE:' + response.toString());
if (data.error) { console.error('Error:' + data.error); } else { 
for(let item in data) { console.log(data[item].toString()); } }
});