#!/usr/bin/env node

const program = require('commander');

const YAML = require('yamljs');
const Client = require('node-rest-client').Client;
const client = new Client();
global.ailtire = { config: require('C:\\Users\\dwpulsip\\work\\edgemere\\bin\\lib/../../.ailtire.js') };
program.command('enable [options]', 'Enable Device and all of its hardware')
	.option('--name <string>', 'Name of the device')
	.option('--id <string>', 'ID of the device');
program.parse(process.argv);
let url = global.ailtire.config.host + '/cpl/datacenter/enable?';
url += 'mode=json';
let args = {headers: {'Content-Type': 'application/json'}, data: {}};
if(program['name']) { args.data['name'] = program['name']; }
if(program['id']) { args.data['id'] = program['id']; }
client.post(url, args, (data, response) => {
console.log('URL:' + url);
console.log('ARGS:' + args);
console.log('DATA:' + data.toString());
console.log('RESPONSE:' + response.toString());
if (data.error) { console.error('Error:' + data.error); } else { 
for(let item in data) { console.log(data[item].toString()); } }
});