#!/user/bin/env node
const bent = require('bent');
const program = require('commander');
const YAML = require('yamljs');
global.ailtire = { config: require('/mnt/c/Users/dwpulsip/work/edgemere/bin/lib/../../.ailtire.js') };
program.command('find [options]', 'Find the data and start up an instance')
	.option('--query <json>', 'Query of the data to find')
	.option('--file <YAML>', 'YAML file with complex query');
program.parse(process.argv);
let url = global.ailtire.config.host;
let args = {};
let params = '/diml/find?';
params += 'mode=json';
if(program['query']) { args['query'] = program['query']; }
if(program['file']) { args['file'] = YAML.load(program['file']); }

const post = bent(url, 'POST', 'json', 200);
(async () => {
    const response = await post(params, args);
    console.log(response.results);
})().catch(e => {
    // Deal with the fact the chain failed
    console.error("Response Error:", e);
});