#!/user/bin/env node
const bent = require('bent');
const program = require('commander');
const YAML = require('yamljs');
global.ailtire = { config: require('/mnt/c/Users/dwpulsip/work/edgemere/bin/lib/../../.ailtire.js') };
program.command('simulate [options]', 'Simulate data in the data source')
	.option('--name <string>', 'Name of the DataSource to simulate')
	.option('--file <YAML>', 'file that contains the data to simulate');
program.parse(process.argv);
let url = global.ailtire.config.host;
let args = {};
let params = '/diml/ddf/datasource/simulate?';
params += 'mode=json';
if(program['name']) { args['name'] = program['name']; }
if(program['file']) { args['file'] = YAML.load(program['file']); }

const post = bent(url, 'POST', 'json', 200);
(async () => {
    const response = await post(params, args);
    console.log(response.results);
})().catch(e => {
    // Deal with the fact the chain failed
    console.error("Response Error:", e);
});