@startuml

left to right direction


boundary parent #black


entity children #blue

rectangle "diml_dml" as diml_dmlStack #ffcc88 {
    queue diml_dmlStacksnet #blue [
        <b><color:white>parent</color></b>
    ]
}



package "diml" #ffcc88 {
    queue parentnet #black [
            <b><color:white>parent</color></b>
    ]
    
    parentnet -[#black]- parent
    
    queue childrennet #blue [
            <b><color:white>children</color></b>
    ]
    
    childrennet -[#blue]- children
    
    queue siblingsnet #red [
            <b><color:white>siblings</color></b>
    ]
    

node "web" as webService
node "diml_cds" as diml_cdsService
node "diml_ddf" as diml_ddfService
node "diml_dml" as diml_dmlService


        artifact "diml_web" as diml_webimage
    
        artifact "diml_cds" as diml_cdsimage
    
        artifact "diml_ddf" as diml_ddfimage
            collections "diml_dml" as diml_dmlimage
    
}

webService -[#blue]- childrennet

webService -[#red]- siblingsnet

diml_cdsService -[#blue]- childrennet

diml_ddfService -[#blue]- childrennet

diml_dmlService -[#blue]- childrennet
webService .... diml_webimage
diml_cdsService .... diml_cdsimage
diml_ddfService .... diml_ddfimage
diml_dmlService .... diml_dmlimage

diml_dmlimage --> diml_dmlStack
    

@enduml
