@startuml


usecase "Manage Data Strategy" as ManageDataStrategy #yellow

Actor "Chief Data Officer" as ChiefDataOfficer

ChiefDataOfficer --> ManageDataStrategy





usecase "Provide Business Information" as ProvideBusinessInformation #lightyellow

ManageDataStrategy <-- ProvideBusinessInformation : extends







@enduml
