@startuml

actor "IT Operations"


entity EventBus

box Software Defined Infrastructure #lightyellow
    boundary sdi #white
end box


box Common Physical Layer #lightgray
            participant device
            participant datacenter
    end box

box Software Defined Infrastructure #lightyellow
            participant cloud
    end box


"IT Operations" -> sdi: List Resources

    sdi -> "device": create (name: hostlr1,file: ./templates/device.yaml)

    "device" --/ EventBus: device.create

    sdi -> "device": create (name: hostlr2,file: ./templates/device.yaml)

    "device" --/ EventBus: device.create

    sdi -> "device": create (name: hostlr3,file: ./templates/device.yaml)

    "device" --/ EventBus: device.create

    sdi -> "device": create (name: hostlr4,file: ./templates/device.yaml)

    "device" --/ EventBus: device.create

    sdi -> "device": create (name: hostlr5,file: ./templates/device.yaml)

    "device" --/ EventBus: device.create

    sdi -> "device": create (name: hostlr6,file: ./templates/device.yaml)

    "device" --/ EventBus: device.create

    sdi -> "datacenter": create (name: dclr1)

    "datacenter" --/ EventBus: datacenter.create

    sdi -> "datacenter": adddevices (name: dclr1,items: hostlr1,hostlr2,hostlr3,hostlr4,hostlr5,hostlr6)

    "datacenter" --/ EventBus: datacenter.adddevices

    sdi -> "cloud": create (name: cloudlr1)

    "cloud" --/ EventBus: cloud.create

    sdi -> "cloud": adddatacenters (name: cloudlr1,items: dclr1)

    "cloud" --/ EventBus: cloud.adddatacenters

    sdi -> "datacenter": disable (name: dclr1)

    "datacenter" --/ EventBus: datacenter.disable

    sdi -> "software defined infrastructure": get (name: myRes,cloud: cloudlr1,requirements: ./templates/requirements.yaml)

    "software defined infrastructure" --/ EventBus: resource.get

    sdi -> "software defined infrastructure": get (name: myRes2,cloud: cloudlr1,requirements: ./templates/requirements2.yaml)

    "software defined infrastructure" --/ EventBus: resource.get

    sdi -> "software defined infrastructure": get (name: myRes3,cloud: cloudlr1,requirements: ./templates/requirements3.yaml)

    "software defined infrastructure" --/ EventBus: resource.get

    sdi -> "software defined infrastructure": get (name: myRes4,cloud: cloudlr1,requirements: ./templates/requirements.yaml)

    "software defined infrastructure" --/ EventBus: resource.get



@enduml
