@startuml


actor "IT Operations"


entity EventBus

box Software Defined Infrastructure #cccc88
    boundary sdi #white
end box


group Given [IT operations has requested resources using a specific name]

"IT Operations" --/ sdi: The resources are no longer needed
"sdi" -> sdi: Release Resources



"IT Operations" /-- sdi: The resources allocated under the specific name are released


end

@enduml
