@startuml
left to right direction



state "Stack Developer" as StackDeveloper {
    state "Manage Stacks" as StackDeveloperManageStacks {
    }
}
state "sml" as sml #lightgreen {
state "so" as smlso #lightgreen {
state "stack" as smlsostack #lightgreen {
state "list" as smlsostacklist #lightgreen {
}
}
}
}

StackDeveloperManageStacks --> smlsostacklist

state "Application Developer" as ApplicationDeveloper {
    state "Manage Stacks" as ApplicationDeveloperManageStacks {
    }
}
state "sml" as sml #lightgreen {
state "so" as smlso #lightgreen {
state "stack" as smlsostack #lightgreen {
state "list" as smlsostacklist #lightgreen {
}
}
}
}

ApplicationDeveloperManageStacks --> smlsostacklist


    state "DevOps Engineer" as DevOpsEngineer {
        state "Manage Stacks" as DevOpsEngineerManageStacks {
            state "Deploy Stack" as DevOpsEngineerManageStacksDeployStack {
            }
        }
    }
    state "sml" as sml #lightgreen {
state "sostack" as smlsostack #lightgreen {
state "deploy" as smlsostackdeploy #lightgreen {
}
}
}

    DevOpsEngineerManageStacksDeployStack --> smlsostackdeploy
    
 
    state "DevOps Engineer" as DevOpsEngineer {
        state "Manage Stacks" as DevOpsEngineerManageStacks {
            state "Uninstall Stack" as DevOpsEngineerManageStacksUninstallStack {
            }
        }
    }
    state "sml" as sml #lightgreen {
state "sostack" as smlsostack #lightgreen {
state "uninstall" as smlsostackuninstall #lightgreen {
}
}
}

    DevOpsEngineerManageStacksUninstallStack --> smlsostackuninstall
    
 
    state "DevOps Engineer" as DevOpsEngineer {
        state "Manage Stacks" as DevOpsEngineerManageStacks {
            state "Update Stack" as DevOpsEngineerManageStacksUpdateStack {
            }
        }
    }
    state "sml" as sml #lightgreen {
state "sostack" as smlsostack #lightgreen {
state "update" as smlsostackupdate #lightgreen {
}
}
}

    DevOpsEngineerManageStacksUpdateStack --> smlsostackupdate
    
 
 

@enduml
