@startuml


package "Service Controller" #lightgreen {

}

package "Service Repository" #lightgreen {

}

package "Data Orchestrator" #lightblue {

}

package "Infrastructure Orchestrator" #lightyellow {

}

package "Service Management Layer" #lightgreen {

}

package "Software Defined Infrastructure" #lightyellow {

}

package "Service Orchestrator" #lightgreen {

}

package "Application Management Layer" #lightblue {

}


package "Service Orchestrator" #lightgreen {

    interface "Service Orchestrator" as i {
            /edgemere/sml/so/servicelet/assigndata()
            /edgemere/sml/so/stack/deploy()
            /edgemere/sml/so/stack/list()
            /edgemere/sml/so/stack/uninstall()
            /edgemere/sml/so/stack/update()
    
    }
}

CLI ()-- i
REST ()-- i
Web ()-- i

package "Service Orchestrator" #lightgreen {


}


    "Service Orchestrator" --> "Service Controller"

    "Service Orchestrator" --> "Service Repository"

    "Service Orchestrator" --> "Data Orchestrator"

    "Service Orchestrator" --> "Infrastructure Orchestrator"


@enduml
