@startuml
left to right direction


state "sa" as sa #cc8888 {
state "spm" as saspm #cc8888 {
}
}


state "saspm" as pstatename #cc8888 {
    state "Custom Function" as spmfunction {
    }
}

        state "sa" as sa #cc8888 {
state "spm" as saspm #cc8888 {
state "data" as saspmdata #cc8888 {
state "create" as saspmdatacreate #cc8888 {
}
}
}
}


        state "sa" as sa #cc8888 {
state "spm" as saspm #cc8888 {
state "data" as saspmdata #cc8888 {
state "govern" as saspmdatagovern #cc8888 {
}
}
}
}


        state "sa" as sa #cc8888 {
state "spm" as saspm #cc8888 {
state "securityprofile" as saspmsecurityprofile #cc8888 {
state "attach" as saspmsecurityprofileattach #cc8888 {
}
}
}
}


        state "sa" as sa #cc8888 {
state "spm" as saspm #cc8888 {
state "securityprofile" as saspmsecurityprofile #cc8888 {
state "create" as saspmsecurityprofilecreate #cc8888 {
}
}
}
}


        state "sa" as sa #cc8888 {
state "spm" as saspm #cc8888 {
state "securityprofile" as saspmsecurityprofile #cc8888 {
state "deploy" as saspmsecurityprofiledeploy #cc8888 {
}
}
}
}


        state "sa" as sa #cc8888 {
state "spm" as saspm #cc8888 {
state "securityprofile" as saspmsecurityprofile #cc8888 {
state "destroy" as saspmsecurityprofiledestroy #cc8888 {
}
}
}
}


        state "sa" as sa #cc8888 {
state "spm" as saspm #cc8888 {
state "securityprofile" as saspmsecurityprofile #cc8888 {
state "disable" as saspmsecurityprofiledisable #cc8888 {
}
}
}
}


        state "sa" as sa #cc8888 {
state "spm" as saspm #cc8888 {
state "securityprofile" as saspmsecurityprofile #cc8888 {
state "enable" as saspmsecurityprofileenable #cc8888 {
}
}
}
}


        state "sa" as sa #cc8888 {
state "spm" as saspm #cc8888 {
state "securityprofile" as saspmsecurityprofile #cc8888 {
state "list" as saspmsecurityprofilelist #cc8888 {
}
}
}
}


        state "sa" as sa #cc8888 {
state "spm" as saspm #cc8888 {
state "securityprofile" as saspmsecurityprofile #cc8888 {
state "status" as saspmsecurityprofilestatus #cc8888 {
}
}
}
}


        state "sa" as sa #cc8888 {
state "spm" as saspm #cc8888 {
state "securityprofile" as saspmsecurityprofile #cc8888 {
state "test" as saspmsecurityprofiletest #cc8888 {
}
}
}
}






@enduml
