@startuml
left to right direction


    package "edgemere" as edgemere {
package "sa" as edgemeresa {
package "spm" as edgemeresaspm #cc8888 {
 component "data" as edgemeresaspmdata
 interface "create" as edgemeresaspmdatacreate
edgemeresaspmdata -- edgemeresaspmdatacreate
}
}
}

    
    package "edgemere" as edgemere {
package "sa" as edgemeresa {
package "spm" as edgemeresaspm #cc8888 {
 component "data" as edgemeresaspmdata
 interface "govern" as edgemeresaspmdatagovern
edgemeresaspmdata -- edgemeresaspmdatagovern
}
}
}

    
    package "edgemere" as edgemere {
package "sa" as edgemeresa {
package "spm" as edgemeresaspm #cc8888 {
 component "securityprofile" as edgemeresaspmsecurityprofile
 interface "attach" as edgemeresaspmsecurityprofileattach
edgemeresaspmsecurityprofile -- edgemeresaspmsecurityprofileattach
}
}
}

    
    package "edgemere" as edgemere {
package "sa" as edgemeresa {
package "spm" as edgemeresaspm #cc8888 {
 component "securityprofile" as edgemeresaspmsecurityprofile
 interface "create" as edgemeresaspmsecurityprofilecreate
edgemeresaspmsecurityprofile -- edgemeresaspmsecurityprofilecreate
}
}
}

    
    package "edgemere" as edgemere {
package "sa" as edgemeresa {
package "spm" as edgemeresaspm #cc8888 {
 component "securityprofile" as edgemeresaspmsecurityprofile
 interface "deploy" as edgemeresaspmsecurityprofiledeploy
edgemeresaspmsecurityprofile -- edgemeresaspmsecurityprofiledeploy
}
}
}

    
    package "edgemere" as edgemere {
package "sa" as edgemeresa {
package "spm" as edgemeresaspm #cc8888 {
 component "securityprofile" as edgemeresaspmsecurityprofile
 interface "destroy" as edgemeresaspmsecurityprofiledestroy
edgemeresaspmsecurityprofile -- edgemeresaspmsecurityprofiledestroy
}
}
}

    
    package "edgemere" as edgemere {
package "sa" as edgemeresa {
package "spm" as edgemeresaspm #cc8888 {
 component "securityprofile" as edgemeresaspmsecurityprofile
 interface "disable" as edgemeresaspmsecurityprofiledisable
edgemeresaspmsecurityprofile -- edgemeresaspmsecurityprofiledisable
}
}
}

    
    package "edgemere" as edgemere {
package "sa" as edgemeresa {
package "spm" as edgemeresaspm #cc8888 {
 component "securityprofile" as edgemeresaspmsecurityprofile
 interface "enable" as edgemeresaspmsecurityprofileenable
edgemeresaspmsecurityprofile -- edgemeresaspmsecurityprofileenable
}
}
}

    
    package "edgemere" as edgemere {
package "sa" as edgemeresa {
package "spm" as edgemeresaspm #cc8888 {
 component "securityprofile" as edgemeresaspmsecurityprofile
 interface "list" as edgemeresaspmsecurityprofilelist
edgemeresaspmsecurityprofile -- edgemeresaspmsecurityprofilelist
}
}
}

    
    package "edgemere" as edgemere {
package "sa" as edgemeresa {
package "spm" as edgemeresaspm #cc8888 {
 component "securityprofile" as edgemeresaspmsecurityprofile
 interface "status" as edgemeresaspmsecurityprofilestatus
edgemeresaspmsecurityprofile -- edgemeresaspmsecurityprofilestatus
}
}
}

    
    package "edgemere" as edgemere {
package "sa" as edgemeresa {
package "spm" as edgemeresaspm #cc8888 {
 component "securityprofile" as edgemeresaspmsecurityprofile
 interface "test" as edgemeresaspmsecurityprofiletest
edgemeresaspmsecurityprofile -- edgemeresaspmsecurityprofiletest
}
}
}

    



        rectangle "Manage Applications" as ManageApplications #ffffaa {
            ("Build Application")/ as ActorManageApplicationsBuildApplication
        }
    
    edgemeresaspmdatacreate <-- ActorManageApplicationsBuildApplication
    









        rectangle "Manage Meta Data" as ManageMetaData #ffffaa {
            ("Capture Meta Data")/ as DataEngineerManageMetaDataCaptureMetaData
        }
    
    edgemeresaspmdatacreate <-- DataEngineerManageMetaDataCaptureMetaData
    
        rectangle "Manage Meta Data" as ManageMetaData #ffffaa {
            ("Capture Meta Data")/ as DataStewardManageMetaDataCaptureMetaData
        }
    
    edgemeresaspmdatacreate <-- DataStewardManageMetaDataCaptureMetaData
    






        rectangle "Apply Security Profiles" as ApplySecurityProfiles #ffffaa {
            ("Attach Profile")/ as SecurityEngineerApplySecurityProfilesAttachProfile
        }
    
    edgemeresaspmsecurityprofileattach <-- SecurityEngineerApplySecurityProfilesAttachProfile
    
        rectangle "Apply Security Profiles" as ApplySecurityProfiles #ffffaa {
            ("Deploy Security Profile")/ as SecurityEngineerApplySecurityProfilesDeploySecurityProfile
        }
    
    edgemeresaspmsecurityprofiledeploy <-- SecurityEngineerApplySecurityProfilesDeploySecurityProfile
    

        rectangle "Manage Security Profiles" as ManageSecurityProfiles #ffffaa {
            ("Create Security Profile")/ as SecurityEngineerManageSecurityProfilesCreateSecurityProfile
        }
    
    edgemeresaspmsecurityprofilecreate <-- SecurityEngineerManageSecurityProfilesCreateSecurityProfile
    
        rectangle "Manage Security Profiles" as ManageSecurityProfiles #ffffaa {
            ("Disable Security Profile")/ as SecurityEngineerManageSecurityProfilesDisableSecurityProfile
        }
    
    edgemeresaspmsecurityprofiledisable <-- SecurityEngineerManageSecurityProfilesDisableSecurityProfile
    
        rectangle "Manage Security Profiles" as ManageSecurityProfiles #ffffaa {
            ("Enable Security Profile")/ as SecurityEngineerManageSecurityProfilesEnableSecurityProfile
        }
    
    edgemeresaspmsecurityprofileenable <-- SecurityEngineerManageSecurityProfilesEnableSecurityProfile
    
        rectangle "Manage Security Profiles" as ManageSecurityProfiles #ffffaa {
            ("Monitor Security Profile")/ as SecurityEngineerManageSecurityProfilesMonitorSecurityProfile
        }
    
    edgemeresaspmsecurityprofilestatus <-- SecurityEngineerManageSecurityProfilesMonitorSecurityProfile
    
        rectangle "Manage Security Profiles" as ManageSecurityProfiles #ffffaa {
            ("Remove Security Profile")/ as SecurityEngineerManageSecurityProfilesRemoveSecurityProfile
        }
    
    edgemeresaspmsecurityprofiledestroy <-- SecurityEngineerManageSecurityProfilesRemoveSecurityProfile
    
        rectangle "Manage Security Profiles" as ManageSecurityProfiles #ffffaa {
            ("Test Security Profile")/ as SecurityEngineerManageSecurityProfilesTestSecurityProfile
        }
    
    edgemeresaspmsecurityprofiletest <-- SecurityEngineerManageSecurityProfilesTestSecurityProfile
    







        rectangle "Manage Stacks" as ManageStacks #ffffaa {
            ("Build Stack")/ as ActorManageStacksBuildStack
        }
    
    edgemeresaspmdatacreate <-- ActorManageStacksBuildStack
    
        rectangle "Manage Stacks" as ManageStacks #ffffaa {
            ("Create Application Stack")/ as ActorManageStacksCreateApplicationStack
        }
    
    edgemeresaspmdatacreate <-- ActorManageStacksCreateApplicationStack
    
        rectangle "Manage Stacks" as ManageStacks #ffffaa {
            ("Create Service Stack")/ as ActorManageStacksCreateServiceStack
        }
    
    edgemeresaspmdatacreate <-- ActorManageStacksCreateServiceStack
    
        rectangle "Manage Stacks" as ManageStacks #ffffaa {
            ("Modify Application Stack")/ as ActorManageStacksModifyApplicationStack
        }
    
    edgemeresaspmdatacreate <-- ActorManageStacksModifyApplicationStack
    
        rectangle "Manage Stacks" as ManageStacks #ffffaa {
            ("Modify Service Stack")/ as ActorManageStacksModifyServiceStack
        }
    
    edgemeresaspmdatacreate <-- ActorManageStacksModifyServiceStack
    
        rectangle "Manage Stacks" as ManageStacks #ffffaa {
            ("Test Application Stack")/ as ActorManageStacksTestApplicationStack
        }
    
    edgemeresaspmdatacreate <-- ActorManageStacksTestApplicationStack
    
        rectangle "Manage Stacks" as ManageStacks #ffffaa {
            ("Test Service Stack")/ as ActorManageStacksTestServiceStack
        }
    
    edgemeresaspmdatacreate <-- ActorManageStacksTestServiceStack
    
        rectangle "Manage Stacks" as ManageStacks #ffffaa {
            ("Version Application Stack")/ as ActorManageStacksVersionApplicationStack
        }
    
    edgemeresaspmdatacreate <-- ActorManageStacksVersionApplicationStack
    
        rectangle "Manage Stacks" as ManageStacks #ffffaa {
            ("Version Service Stack")/ as ActorManageStacksVersionServiceStack
        }
    
    edgemeresaspmdatacreate <-- ActorManageStacksVersionServiceStack
    



        rectangle "Manage Services" as ManageServices #ffffaa {
            ("Build Service")/ as ActorManageServicesBuildService
        }
    
    edgemeresaspmdatacreate <-- ActorManageServicesBuildService
    

@enduml
