@startuml


package "Security Aspect" #pink {

}

package "Identity Aspect" #pink {

}


package "Security Profile Manager" #pink {

    interface "Security Profile Manager" as i {
    
            /edgemere/sa/spm/data/create()
            /edgemere/sa/spm/data/govern()
            /edgemere/sa/spm/securityprofile/attach()
            /edgemere/sa/spm/securityprofile/create()
            /edgemere/sa/spm/securityprofile/deploy()
            /edgemere/sa/spm/securityprofile/destroy()
            /edgemere/sa/spm/securityprofile/disable()
            /edgemere/sa/spm/securityprofile/enable()
            /edgemere/sa/spm/securityprofile/list()
            /edgemere/sa/spm/securityprofile/status()
            /edgemere/sa/spm/securityprofile/test()
    
    }
}

circle REST
circle Web
circle CLI
circle WebSocket

i -down- Web
i -down- CLI
i -down- REST
WebSocket -left- i: events >

package "Security Profile Manager" #pink {


}



@enduml
