@startuml


actor "SecurityOperator" as securityoperator

actor "SecurityEngineer" as securityengineer




securityoperator -> "Security Profile Manager": Apply Security Profiles
"Security Profile Manager" -> bin: data govern
bin -> REST: data/govern

securityengineer -> "Security Profile Manager": Manage Security Profiles
"Security Profile Manager" -> bin: securityprofile list
bin -> REST: securityprofile/list



@enduml
