@startuml
  interface CLI
  interface Web
  interface WebSocket
package "Governance Engine" #lightblue {
  component express as REST
  component socket.io as socket
  folder bin #ffffff {
    component " edgemere diml dml ge" as binName
  }
  binName --> REST

  folder deploy #ffffff {
      file "node server.js\ndocker-compose.yml" as diml_dml_ge_container
      REST --> diml_dml_ge_container

  
    file "node web/server.js" as web_container
    REST --> web_container
    socket ---> web_container
  
    file "node gateway/server.js" as gateway_container
    REST --> gateway_container
    socket ---> gateway_container
  
  }
  folder images #ffffff {
    collections "diml_dml_ge" as diml_dml_geimage
    artifact "ailtire:swarm" as ailtireswarm
    diml_dml_geimage <|-- ailtireswarm
    diml_dml_ge_container --> diml_dml_geimage

  
      artifact diml_dml_ge_web
      web_container --> diml_dml_ge_web
    
      artifact diml_dml_ge_gw
      gateway_container --> diml_dml_ge_gw
    
  }
}
CLI " edgemere diml dml ge" -- binName
Web "/edgemere/diml/dml/ge" - REST
WebSocket ".edgemere.diml.dml.ge" -- socket

@enduml
