@startuml

class "ResourceCost" as Model {
 string name
 number amount
 string units

 
}

rectangle "ResourceInstanceType" as ResourceInstanceType #lightblue {
}

Model o--> "1" ResourceInstanceType : parent




    rectangle "ResourceInstanceType" as ResourceInstanceType #lightgreen {
    }
    
        ResourceInstanceType   *--> "n" Model : "costs"
    
    rectangle "ResourceInstanceType" as ResourceInstanceType #lightgreen {
    }
    
        ResourceInstanceType   *--> "n" Model : "costs"
    
    rectangle "ResourceInstanceType" as ResourceInstanceType #lightgreen {
    }
    
        ResourceInstanceType   *--> "n" Model : "costs"
    
    rectangle "ResourceInstanceType" as ResourceInstanceType #lightgreen {
    }
    
        ResourceInstanceType   *--> "n" Model : "costs"
    
    rectangle "ResourceInstanceType" as ResourceInstanceType #lightgreen {
    }
    
        ResourceInstanceType   *--> "n" Model : "costs"
    
    rectangle "ResourceInstanceType" as ResourceInstanceType #lightgreen {
    }
    
        ResourceInstanceType   *--> "n" Model : "costs"
    
    rectangle "ResourceInstanceType" as ResourceInstanceType #lightgreen {
    }
    
        ResourceInstanceType   *--> "n" Model : "costs"
    
    rectangle "ResourceInstanceType" as ResourceInstanceType #lightgreen {
    }
    
        ResourceInstanceType   *--> "n" Model : "costs"
    
    rectangle "ResourceInstanceType" as ResourceInstanceType #lightgreen {
    }
    
        ResourceInstanceType   *--> "n" Model : "costs"
    
    rectangle "ResourceInstanceType" as ResourceInstanceType #lightgreen {
    }
    
        ResourceInstanceType   *--> "n" Model : "costs"
    
    rectangle "ResourceInstanceType" as ResourceInstanceType #lightgreen {
    }
    
        ResourceInstanceType   *--> "n" Model : "costs"
    
    rectangle "ResourceInstanceType" as ResourceInstanceType #lightgreen {
    }
    
        ResourceInstanceType   *--> "n" Model : "costs"
    
    rectangle "ResourceInstanceType" as ResourceInstanceType #lightgreen {
    }
    
        ResourceInstanceType   *--> "n" Model : "costs"
    
    rectangle "ResourceInstanceType" as ResourceInstanceType #lightgreen {
    }
    
        ResourceInstanceType   *--> "n" Model : "costs"
    
    rectangle "ResourceInstanceType" as ResourceInstanceType #lightgreen {
    }
    
        ResourceInstanceType   *--> "n" Model : "costs"
    
    rectangle "ResourceInstanceType" as ResourceInstanceType #lightgreen {
    }
    
        ResourceInstanceType   *--> "n" Model : "costs"
    
    rectangle "ResourceInstanceType" as ResourceInstanceType #lightgreen {
    }
    
        ResourceInstanceType   *--> "n" Model : "costs"
    
    rectangle "ResourceInstanceType" as ResourceInstanceType #lightgreen {
    }
    
        ResourceInstanceType   *--> "n" Model : "costs"
    
    rectangle "ResourceInstanceType" as ResourceInstanceType #lightgreen {
    }
    
        ResourceInstanceType   *--> "n" Model : "costs"
    
    rectangle "ResourceInstanceType" as ResourceInstanceType #lightgreen {
    }
    
        ResourceInstanceType   *--> "n" Model : "costs"
    
    rectangle "ResourceInstanceType" as ResourceInstanceType #lightgreen {
    }
    
        ResourceInstanceType   *--> "n" Model : "costs"
    
    rectangle "ResourceInstanceType" as ResourceInstanceType #lightgreen {
    }
    
        ResourceInstanceType   *--> "n" Model : "costs"
    
    rectangle "ResourceInstanceType" as ResourceInstanceType #lightgreen {
    }
    
        ResourceInstanceType   *--> "n" Model : "costs"
    
    rectangle "ResourceInstanceType" as ResourceInstanceType #lightgreen {
    }
    
        ResourceInstanceType   *--> "n" Model : "costs"
    
    rectangle "ResourceInstanceType" as ResourceInstanceType #lightgreen {
    }
    
        ResourceInstanceType   *--> "n" Model : "costs"
    
    rectangle "ResourceInstanceType" as ResourceInstanceType #lightgreen {
    }
    
        ResourceInstanceType   *--> "n" Model : "costs"
    
    rectangle "ResourceInstanceType" as ResourceInstanceType #lightgreen {
    }
    
        ResourceInstanceType   *--> "n" Model : "costs"
    
    rectangle "ResourceInstanceType" as ResourceInstanceType #lightgreen {
    }
    
        ResourceInstanceType   *--> "n" Model : "costs"
    
    rectangle "ResourceInstanceType" as ResourceInstanceType #lightgreen {
    }
    
        ResourceInstanceType   *--> "n" Model : "costs"
    
    rectangle "ResourceInstanceType" as ResourceInstanceType #lightgreen {
    }
    
        ResourceInstanceType   *--> "n" Model : "costs"
    
    rectangle "ResourceInstanceType" as ResourceInstanceType #lightgreen {
    }
    
        ResourceInstanceType   *--> "n" Model : "costs"
    
    rectangle "ResourceInstanceType" as ResourceInstanceType #lightgreen {
    }
    
        ResourceInstanceType   *--> "n" Model : "costs"
    
    rectangle "ResourceInstanceType" as ResourceInstanceType #lightgreen {
    }
    
        ResourceInstanceType   *--> "n" Model : "costs"
    
    rectangle "ResourceInstanceType" as ResourceInstanceType #lightgreen {
    }
    
        ResourceInstanceType   *--> "n" Model : "costs"
    
    rectangle "ResourceInstanceType" as ResourceInstanceType #lightgreen {
    }
    
        ResourceInstanceType   *--> "n" Model : "costs"
    
    rectangle "ResourceInstanceType" as ResourceInstanceType #lightgreen {
    }
    
        ResourceInstanceType   *--> "n" Model : "costs"
    
    rectangle "ResourceInstanceType" as ResourceInstanceType #lightgreen {
    }
    
        ResourceInstanceType   *--> "n" Model : "costs"
    
    rectangle "ResourceInstanceType" as ResourceInstanceType #lightgreen {
    }
    
        ResourceInstanceType   *--> "n" Model : "costs"
    
    rectangle "ResourceInstanceType" as ResourceInstanceType #lightgreen {
    }
    
        ResourceInstanceType   *--> "n" Model : "costs"
    
    rectangle "ResourceInstanceType" as ResourceInstanceType #lightgreen {
    }
    
        ResourceInstanceType   *--> "n" Model : "costs"
    
    rectangle "ResourceInstanceType" as ResourceInstanceType #lightgreen {
    }
    
        ResourceInstanceType   *--> "n" Model : "costs"
    
    rectangle "ResourceInstanceType" as ResourceInstanceType #lightgreen {
    }
    
        ResourceInstanceType   *--> "n" Model : "costs"
    
    rectangle "ResourceInstanceType" as ResourceInstanceType #lightgreen {
    }
    
        ResourceInstanceType   *--> "n" Model : "costs"
    
    rectangle "ResourceInstanceType" as ResourceInstanceType #lightgreen {
    }
    
        ResourceInstanceType   *--> "n" Model : "costs"
    

@enduml
