@startuml


left to right direction

usecase "Manage Data Policies" as ManageDataPolicies #yellow

Actor "Chief Data Officer" as ChiefDataOfficer

ChiefDataOfficer --> ManageDataPolicies





usecase "Provide Business Information" as ProvideBusinessInformation #lightyellow

ManageDataPolicies <-- ProvideBusinessInformation : extends







@enduml
