@startuml

left to right direction


hexagon external #black [
    <b><color:white>external</color></b>
]
    
interface 3001
3001 -- external
    




node "cpl_tc" #cccccc {

    portin "3001" as cpl_tcPort3001 #blue
    cpl_tcPort3001 -- external



node "consumer" as consumerService #white {


    artifact "cpl_tc_web:latest" as cpl_tc_weblatestimage
    
}
node "producer" as producerService #white {


    artifact "cpl_tp_producer:latest" as cpl_tp_producerlatestimage
    
}

}


@enduml
