@startuml

left to right direction


queue external #black [
    <b><color:white>external</color></b>
]
    
interface 80
80 -- external
    
interface 443
443 -- external
    
interface 8080
8080 -- external
    


entity ailtire_appname_family #black

stack "edgemere" as edgemereStack #lavender {
    queue edgemereStacksnet #black [
        <b><color:white>parent</color></b>
    ]
}
stack "aml" as amlStack #lightblue {
    queue amlStacksnet #black [
        <b><color:white>parent</color></b>
    ]
}
stack "cpl" as cplStack #lightgray {
    queue cplStacksnet #black [
        <b><color:white>parent</color></b>
    ]
}
stack "diml" as dimlStack #ffcc88 {
    queue dimlStacksnet #black [
        <b><color:white>parent</color></b>
    ]
}
stack "ia" as iaStack #pink {
    queue iaStacksnet #black [
        <b><color:white>parent</color></b>
    ]
}
stack "sa" as saStack #pink {
    queue saStacksnet #black [
        <b><color:white>parent</color></b>
    ]
}
stack "sml" as smlStack #lightgreen {
    queue smlStacksnet #black [
        <b><color:white>parent</color></b>
    ]
}
stack "sdi" as sdiStack #lightyellow {
    queue sdiStacksnet #black [
        <b><color:white>parent</color></b>
    ]
}



package "edgemere" #lavender {
    queue childrennet #black [
            <b><color:white>children</color></b>
    ]
    
    childrennet -[#black]- ailtire_appname_family
    
    queue siblingnet #blue [
            <b><color:white>sibling</color></b>
    ]
    


node "frontend" as frontendService {
    card "/web" as webmap
    card "/docs" as docsmap
    
}
node "admin" as adminService
node "aml" as amlService
node "cpl" as cplService
node "diml" as dimlService
node "ia" as iaService
node "sa" as saService
node "sml" as smlService
node "sdi" as sdiService
node "pubsub" as pubsubService
node "web" as webService
node "doc" as docService

        collections "edgemere:latest" as edgemerelatestimage
            collections "aml:latest" as amllatestimage
            collections "cpl:latest" as cpllatestimage
            collections "diml:latest" as dimllatestimage
            collections "ia:latest" as ialatestimage
            collections "sa:latest" as salatestimage
            collections "sml:latest" as smllatestimage
            collections "sdi:latest" as sdilatestimage
    
        artifact "redis" as redisimage
    
        artifact "traefik:latest" as traefiklatestimage
    
        artifact "edgemere_web" as edgemere_webimage
    
        artifact "edgemere_doc" as edgemere_docimage
    
}

external -[#black]- frontendService

webmap -[#black]-> webService

docsmap -[#black]-> docService

adminService -[#black]- childrennet

amlService -[#black]- childrennet

cplService -[#black]- childrennet

dimlService -[#black]- childrennet

iaService -[#black]- childrennet

saService -[#black]- childrennet

smlService -[#black]- childrennet

sdiService -[#black]- childrennet

pubsubService -[#black]- childrennet

pubsubService -[#blue]- siblingnet

webService -[#blue]- siblingnet

webService -[#black]- childrennet

docService -[#blue]- siblingnet

docService -[#black]- childrennet
adminService .... edgemerelatestimage
amlService .... amllatestimage
cplService .... cpllatestimage
dimlService .... dimllatestimage
iaService .... ialatestimage
saService .... salatestimage
smlService .... smllatestimage
sdiService .... sdilatestimage
pubsubService .... redisimage
webService .... edgemere_webimage
docService .... edgemere_docimage

frontendService .... traefiklatestimage

edgemerelatestimage --> edgemereStack
    
amllatestimage --> amlStack
    
amlStacksnet --[#black]-- ailtire_appname_family
    
cpllatestimage --> cplStack
    
cplStacksnet --[#black]-- ailtire_appname_family
    
dimllatestimage --> dimlStack
    
dimlStacksnet --[#black]-- ailtire_appname_family
    
ialatestimage --> iaStack
    
iaStacksnet --[#black]-- ailtire_appname_family
    
salatestimage --> saStack
    
smllatestimage --> smlStack
    
smlStacksnet --[#black]-- ailtire_appname_family
    
sdilatestimage --> sdiStack
    
sdiStacksnet --[#black]-- ailtire_appname_family
    

@enduml
