@startuml



package "Service Repository" #lightgreen {

    interface "Service Repository" as i {
            /edgemere/sml/sr/data/govern()
    
    }
}

CLI ()-- i
REST ()-- i
Web ()-- i

package "Service Repository" #lightgreen {
    
}



@enduml
