@startuml



package "Service Repository" #88cc88 {

    interface "Service Repository" as i {
            /edgemere/sml/sr/assets/list()
            /edgemere/sml/sr/data/govern()
    
    }
}

CLI ()-- i
REST ()-- i
Web ()-- i

package "Service Repository" #88cc88 {
    
}



@enduml
