@startuml
  interface CLI
  interface Web
  interface WebSocket
package "Service Repository" #lightblue {
  component express as REST
  component socket.io as socket
  folder bin #ffffff {
    component "edgemere/sml/sr" as binName
  }
  binName --> REST

  folder deploy #ffffff {
  
    file "node web/server.js" as web_container
    REST --> web_container
    socket ---> web_container
  
    file "node gateway/server.js" as gateway_container
    REST --> gateway_container
    socket ---> gateway_container
  
  }
  folder images #ffffff {
  
      artifact sml_sr_web
      web_container --> sml_sr_web
    
      artifact sml_sr_gw
      gateway_container --> sml_sr_gw
    
  }
}
CLI -- binName
Web - REST
WebSocket -- socket

@enduml
