@startuml
left to right direction


state "sml" as sml #lightgreen {
state "sr" as smlsr #lightgreen {
}
}


state "smlsr" as pstatename #lightgreen {
    state "Custom Function" as srfunction {
    }
}

        state "sml" as sml #lightgreen {
state "sr" as smlsr #lightgreen {
state "data" as smlsrdata #lightgreen {
state "govern" as smlsrdatagovern #lightgreen {
}
}
}
}






@enduml
