@startuml
left to right direction


state "sml" as sml #88cc88 {
state "sr" as smlsr #88cc88 {
}
}


state "smlsr" as pstatename #88cc88 {
    state "Custom Function" as srfunction {
    }
}

        state "sml" as sml #88cc88 {
state "sr" as smlsr #88cc88 {
state "assets" as smlsrassets #88cc88 {
state "list" as smlsrassetslist #88cc88 {
}
}
}
}


        state "sml" as sml #88cc88 {
state "sr" as smlsr #88cc88 {
state "data" as smlsrdata #88cc88 {
state "govern" as smlsrdatagovern #88cc88 {
}
}
}
}






@enduml
