@startuml
left to right direction



state "Actor" as Actor {
    state "Manage Assets" as ActorManageAssets {
    }
}
state "edgemere" as edgemere #lightgreen {
state "sml" as edgemeresml #lightgreen {
state "sr" as edgemeresmlsr #lightgreen {
state "data" as edgemeresmlsrdata #lightgreen {
state "govern" as edgemeresmlsrdatagovern #lightgreen {
}
}
}
}
}

ActorManageAssets --> edgemeresmlsrdatagovern


 

@enduml
