@startuml
left to right direction


    package "edgemere" as edgemere {
package "sml" as edgemeresml {
package "sr" as edgemeresmlsr #88cc88 {
 component "assets" as edgemeresmlsrassets
 interface "list" as edgemeresmlsrassetslist
edgemeresmlsrassets -- edgemeresmlsrassetslist
}
}
}

    
    package "edgemere" as edgemere {
package "sml" as edgemeresml {
package "sr" as edgemeresmlsr #88cc88 {
 component "data" as edgemeresmlsrdata
 interface "govern" as edgemeresmlsrdatagovern
edgemeresmlsrdata -- edgemeresmlsrdatagovern
}
}
}

    























































@enduml
