@startuml

left to right direction
Actor "ITOperations" as ITOperations


rectangle "Service Repository" #lightgreen {
usecase "ManageAssets" as ManageAssets
    ITOperations --> ManageAssets
    }


@enduml
