@startuml

class "Stacklet" as Model {
 string name
 string version
 json parameters
 json args
 number replicas
 json ports

 create()
 deploy()
 
}

rectangle "Stack" as Stack #lightblue {
}

Model o--> "1" Stack : stack


rectangle "Servicelet" as Servicelet #lightblue {
}

Model *--> "n" Servicelet : servicelets


rectangle "Resource" as Resource #lightblue {
}

Model o--> "n" Resource : resources


rectangle "Stacklet" as Stacklet #lightblue {
}

Model o--> "1" Stacklet : parent


rectangle "ServiceInstance" as ServiceInstance #lightblue {
}

Model o--> "n" ServiceInstance : instances


rectangle "Service" as Service #lightblue {
}

Model o--> "1" Service : service


rectangle "Environment" as Environment #lightblue {
}

Model o--> "1" Environment : env


rectangle "DataReference" as DataReference #lightblue {
}

Model *--> "n" DataReference : data




    rectangle "Servicelet" as Servicelet #lightgreen {
    }
    
        Servicelet   o--> "1" Model : "parent"
    
    rectangle "Stack" as Stack #lightgreen {
    }
    
        Stack   *--> "n" Model : "stacklets"
    
    rectangle "StackDefinition" as StackDefinition #lightgreen {
    }
    
        StackDefinition   *--> "n" Model : "stacklets"
    
    rectangle "StackInstance" as StackInstance #lightgreen {
    }
    
        StackInstance   o--> "1" Model : "stacklet"
    
    rectangle "Stacklet" as Stacklet #lightgreen {
    }
    
        Stacklet   o--> "1" Model : "parent"
    

@enduml
