@startuml

class "ApplicationTemplate" as Model {
 string name
 json args

 allocateResources()
 deleteApplication()
 duplicateApplication()
 getApplication()
 getApplicationTemplate()
 getApplicationUsage()
 listApplications()
 setTemplate()
 updateApplication()
 validateParameters()
 
}

rectangle "Application" as Application #lightblue {
}

Model o--> "n" Application : app





@enduml
