@startuml


actor "DevOpsEngineer"


entity EventBus

box Application Management Layer #88cccc
    boundary aml #white
end box


box Software Defined Infrastructure #cccc88
            participant storageresource
    end box

group Given [DevOpsEngineer has access to the application source code]

"DevOpsEngineer" --/ aml: DevOpsEngineer initiates the build process
"aml" -> aml: Build Application

    aml -> "storageresource": list (name: hello,file: ./templates/world.yml)

    "storageresource" --/ EventBus: data.list

    aml -> "storageresource": list (name: hello,file: ./templates/world.yml)

    "storageresource" --/ EventBus: data.list



"DevOpsEngineer" /-- aml: The application should be built successfully


end

@enduml
