@startuml


actor "DevOps Engineer"


entity EventBus

box Application Management Layer #88cccc
    boundary aml #white
end box


group Given [A DevOps Engineer has access to the application/destroy method]

"DevOps Engineer" --/ aml: The DevOps Engineer uses the application/destroy method
"aml" -> aml: Destroy Application



"DevOps Engineer" /-- aml: The specified application is destroyed


end

@enduml
