@startuml

actor "Application Developer"

actor "DevOps Engineer"


entity EventBus

box Application Management Layer #88cccc
    boundary aml #white
end box



"Application Developer" -> aml: Update Application


"DevOps Engineer" -> aml: Update Application



@enduml
