@startuml



state DataReference #ffcc88 {

    state Init #ffcc88 {
    }

    state Provisioning #ffcc88 {
    }

    state Provisioned #ffcc88 {
    }

    state FailedProvision #ffcc88 {
    }




Init -[#black]--> Provisioning : provision

Provisioning -[#black]--> Provisioned : provisioned

Provisioning -[#black]--> FailedProvision : failed

}

 
 Provisioning -[#black]--> Null
 
 
 Provisioned -[#black]--> Null
 

@enduml
