@startuml



package "Automation Framework" #aaffff {

    interface "Automation Framework" as i {
    
    }
}

CLI ()-- i
REST ()-- i
Web ()-- i

package "Automation Framework" #aaffff {
    
}



@enduml
