@startuml
left to right direction


state "aml" as aml #lightblue {
state "ds" as amlds #lightblue {
state "af" as amldsaf #lightblue {
}
}
}


state amldsaf #lightblue {
    state "Custom Function" as affunction {
    }
}





@enduml
