@startuml



package "Automation Framework" #lightblue {

    interface "Automation Framework" as i {
    
    }
}

CLI ()-- i
REST ()-- i
Web ()-- i

package "Automation Framework" #lightblue {


}



@enduml
