@startuml
left to right direction


state "diml" as diml #ffcc88 {
}


state "diml" as pstatename #ffcc88 {
    state "Custom Function" as dimlfunction {
    }
}

        state "diml" as diml #ffcc88 {
state "find" as dimlfind #ffcc88 {
}
}






@enduml
