@startuml
left to right direction


    package "edgemere" as edgemere {
 component "diml" as edgemerediml
 interface "find" as edgemeredimlfind
edgemerediml -- edgemeredimlfind
}

    























































@enduml
