@startuml


package "Data Management Layer" #ffcc88 {

}

package "Data Definition Framework" #ffcc88 {

}

package "Identity Aspect" #pink {

}


package "Data Definition Framework" #ffcc88 {

    interface "Data Definition Framework" as i {
            /edgemere/diml/ddf/data/govern()
            /edgemere/diml/ddf/data/source/name()
            /edgemere/diml/ddf/datablueprint/deploy()
            /edgemere/diml/ddf/datablueprint/list()
            /edgemere/diml/ddf/datacatalog/list()
            /edgemere/diml/ddf/datadaptor/list()
            /edgemere/diml/ddf/datapipeline/list()
            /edgemere/diml/ddf/dataprocedure/list()
            /edgemere/diml/ddf/datasource/simulate()
            /edgemere/diml/ddf/metadata/list()
    
    }
}

CLI ()-- i
REST ()-- i
Web ()-- i

package "Data Definition Framework" #ffcc88 {


rectangle "Blue Print Management" #white {
}

rectangle "Data Adaptor Framework" #white {
}

rectangle "Data Flow" #white {
}

rectangle "Data Repository" #white {
}

}


    "Data Definition Framework" --> "Data Management Layer"


@enduml
