@startuml

left to right direction


boundary parent #black


entity children #blue

rectangle "sml_cb" as sml_cbStack #88cc88 {
    queue sml_cbStacksnet #blue [
        <b><color:white>parent</color></b>
    ]
}
rectangle "sml_em" as sml_emStack #88cc88 {
    queue sml_emStacksnet #blue [
        <b><color:white>parent</color></b>
    ]
}
rectangle "sml_pe" as sml_peStack #88cc88 {
    queue sml_peStacksnet #blue [
        <b><color:white>parent</color></b>
    ]
}
rectangle "sml_sc" as sml_scStack #88cc88 {
    queue sml_scStacksnet #blue [
        <b><color:white>parent</color></b>
    ]
}
rectangle "sml_so" as sml_soStack #88cc88 {
    queue sml_soStacksnet #blue [
        <b><color:white>parent</color></b>
    ]
}
rectangle "sml_sr" as sml_srStack #88cc88 {
    queue sml_srStacksnet #blue [
        <b><color:white>parent</color></b>
    ]
}



package "sml" #88cc88 {
    queue parentnet #black [
            <b><color:white>parent</color></b>
    ]
    
    parentnet -[#black]- parent
    
    queue childrennet #blue [
            <b><color:white>children</color></b>
    ]
    
    childrennet -[#blue]- children
    
    queue siblingsnet #red [
            <b><color:white>siblings</color></b>
    ]
    

node "broker" as brokerService
node "envmangaer" as envmangaerService
node "provision" as provisionService
node "controller" as controllerService
node "orchestrator" as orchestratorService
node "repo" as repoService
node "web" as webService

        collections "sml_cb" as sml_cbimage
            collections "sml_em" as sml_emimage
            collections "sml_pe" as sml_peimage
            collections "sml_sc" as sml_scimage
            collections "sml_so" as sml_soimage
            collections "sml_sr" as sml_srimage
    
        artifact "sml_web" as sml_webimage
    
}

brokerService -[#blue]- childrennet

envmangaerService -[#blue]- childrennet

provisionService -[#blue]- childrennet

controllerService -[#blue]- childrennet

orchestratorService -[#blue]- childrennet

repoService -[#blue]- childrennet

webService -[#blue]- childrennet

webService -[#red]- siblingsnet
brokerService .... sml_cbimage
envmangaerService .... sml_emimage
provisionService .... sml_peimage
controllerService .... sml_scimage
orchestratorService .... sml_soimage
repoService .... sml_srimage
webService .... sml_webimage

sml_cbimage --> sml_cbStack
    
sml_emimage --> sml_emStack
    
sml_emStacksnet --[#black]-- parent
    
sml_peimage --> sml_peStack
    
sml_scimage --> sml_scStack
    
sml_soimage --> sml_soStack
    
sml_srimage --> sml_srStack
    

@enduml
