@startuml
left to right direction


state "diml" as diml #ffcc88 {
state "dml" as dimldml #ffcc88 {
state "fmdm" as dimldmlfmdm ##aaffff {
}
}
}


state "dimldmlfmdm" as pstatename ##aaffff {
    state "Custom Function" as fmdmfunction {
    }
}

        state "diml" as diml #ffcc88 {
state "dml" as dimldml #ffcc88 {
state "fmdm" as dimldmlfmdm ##aaffff {
state "query" as dimldmlfmdmquery ##aaffff {
}
}
}
}






@enduml
