@startuml


package "Data Orchestrator" #lightblue {

}

package "Data Management Layer" #ffcc88 {

}


package "Federated Meta Data Management" #lightblue {

    interface "Federated Meta Data Management" as i {
    
            /edgemere/diml/dml/fmdm/query()
    
    }
}

circle REST
circle Web
circle CLI
circle WebSocket

i -down- Web
i -down- CLI
i -down- REST
WebSocket -left- i: events >

package "Federated Meta Data Management" #lightblue {


}



@enduml
