@startuml


actor "IT Operations"


entity EventBus

box Environment Management #88cc88
    boundary em #white
end box


group Given [IT Operations has access to create an environment]

"IT Operations" --/ em: IT Operations creates an environment and assigns a Multi Cloud 
"em" -> em: Create Environment



"IT Operations" /-- em: The environment should be successfully created with the assigned Multi Cloud


end

@enduml
