@startuml


actor "IT Operations"


entity EventBus

box Environment Management #88cc88
    boundary em #white
end box


box Environment Management #88cc88
    end box

group Given [IT Operations has access to create an environment]

"IT Operations" --/ em: IT Operations creates an environment and assigns a Multi Cloud 
"em" -> em: Create Environment

    em -> "environment management": create (attr1: Provide The Description)

    "environment management" --/ EventBus: environment.create

    em -> "environment management": addpolicies (attr1: Assign a Multi Cloud Policy)

    "environment management" --/ EventBus: environment.addpolicies

    em -> "environment management": enable (attr1: Enable the Environment)

    "environment management" --/ EventBus: environment.enable

    em -> "environment management": list (attr1: List down the Environments)

    "environment management" --/ EventBus: environment.list



"IT Operations" /-- em: The environment should be successfully created with the assigned Multi Cloud


end

@enduml
