@startuml


actor "IT Operations"


entity EventBus

box Environment Management #88cc88
    boundary em #white
end box


group Given [IT Operations has access to an environment with running services]

"IT Operations" --/ em: IT Operations uses the environment/destroy method
"em" -> em: Delete Environment



"IT Operations" /-- em: The environment is deleted and all services in the environment are suspended


end

@enduml
