@startuml


actor "IT Operations"


entity EventBus

box Environment Management #88cc88
    boundary em #white
end box


group Given [IT Operations has access to manage environments]

"IT Operations" --/ em: IT Operations executes the &#39;environment/disable&#39; command
"em" -> em: Disable Environment



"IT Operations" /-- em: Services are suspended and cannot launch in the disabled environment


end

@enduml
