@startuml


actor "IT Operations"


entity EventBus

box Environment Management #88cc88
    boundary em #white
end box


group Given [IT Operations is able to modify environment polices]

"IT Operations" --/ em: IT Operations adds or removes policies from the environment
"em" -> em: Manage Policies in Environment



"IT Operations" /-- em: The environment policies are updated accordingly


end

@enduml
