@startuml


actor "IT Operations"


entity EventBus

box Environment Management #88cc88
    boundary em #white
end box


group Given [IT Operations has access to the environment settings]

"IT Operations" --/ em: IT Operations wants to update the attributes of the environment
"em" -> em: Update Environment



"IT Operations" /-- em: The changes made by IT Operations should be reflected in the environment attributes


end

@enduml
