@startuml

left to right direction


Actor "DevOps Engineer" as DevOpsEngineer


rectangle "Application Management Layer" as aml #88cccc {
        usecase "Manage AI Models" as ManageAIModels
    DevOpsEngineer --> ManageAIModels
    usecase "Manage Applications" as ManageApplications
    DevOpsEngineer --> ManageApplications
    usecase "Manage Workloads" as ManageWorkloads
    DevOpsEngineer --> ManageWorkloads

}

rectangle "edgemere" as edgemere #ccaaff {
        usecase "Coordinate Services" as CoordinateServices
    DevOpsEngineer --> CoordinateServices
    usecase "Organize Solutions" as OrganizeSolutions
    DevOpsEngineer --> OrganizeSolutions

}


@enduml
