version: "3.7"
services:
  frontend:
    image: _ia_web
    networks:
      - sibling
  gw:
    image: _ia_gw
    networks:
      children:
        aliases:
          - parent
          - top
      sibling:
        aliases:
          - gateway

networks:
  children:
    driver: overlay
    attachable: true
    name: ${APPNAME}__ia_family
  sibling:
    driver: overlay
  parent:
    external: true
    name: ${APPNAME}__family
