@startuml


boundary __sa_family #blue


entity __family #orange


package  "Security Aspect"  #lightblue {
    card children #blue [
        <b><color:white>children</color></b>
    ]
    
    __sa_family -[#blue]- children
    
    
    card sibling #red [
        <b><color:white>sibling</color></b>
    ]
    
    
    card parent #orange [
        <b><color:white>parent</color></b>
    ]
    
    
    __family -[#orange]- parent
    
    artifact images #ffffff {
        
        file _sa_web
        
        file _sa_gw
        
    }

    node frontend
    frontend .. _sa_web
    
        sibling -[#red]- frontend
    

    node gw
    gw .. _sa_gw
    
        children -[#blue]- gw
    
        sibling -[#red]- gw
    




    
}




package edgemere #lightgray {
    card edgemerechildren #orange [
        <b><color:white>children</color></b>
    ]
    edgemerechildren ==[#orange]= parent
}


@enduml
