@startuml


package "Security Aspect" #pink {
    
        class PolicyCollection {
        }
    
        class Policy {
        }
    }


package "Security Aspect" #pink {

    interface "Security Aspect" as i {
    
    }
}

CLI ()-- i
REST ()-- i
Web ()-- i

package "Security Aspect" #pink {
        class "Policy" {
                 string name
                    }
                Policy o--> "1" PolicyCollection : owner
            
    
    class "PolicyCollection" {
                    }
                PolicyCollection *--> "n" Policy : policies
            
    

}



@enduml
