@startuml

left to right direction


Actor "IT Operations" as ITOperations


rectangle "Common Physical Layer" as cpl  #lightblue {
        usecase "Manage Data Center" as ManageDataCenter
    ITOperations --> ManageDataCenter
    usecase "Manage Infrastructure" as ManageInfrastructure
    ITOperations --> ManageInfrastructure

}

rectangle "Software Defined Infrastructure" as sdi  #lightblue {
        usecase "Manage Resources" as ManageResources
    ITOperations --> ManageResources

}


@enduml
