@startuml

left to right direction


Actor "IT Operations" as ITOperations


rectangle "Environment Management" as em #88cc88 {
        usecase "Manage Environment" as ManageEnvironment
    ITOperations --> ManageEnvironment

}

rectangle "Common Physical Layer" as cpl #cccccc {
        usecase "Manage Data Center" as ManageDataCenter
    ITOperations --> ManageDataCenter
    usecase "Manage Infrastructure" as ManageInfrastructure
    ITOperations --> ManageInfrastructure

}

rectangle "Cloud Broker" as cb #88cc88 {
        usecase "Find Resources" as FindResources
    ITOperations --> FindResources
    usecase "Manage Billing" as ManageBilling
    ITOperations --> ManageBilling
    usecase "Manage Cost Model" as ManageCostModel
    ITOperations --> ManageCostModel
    usecase "Manage Multi Cloud" as ManageMultiCloud
    ITOperations --> ManageMultiCloud
    usecase "Map Assets to Cloud" as MapAssetstoCloud
    ITOperations --> MapAssetstoCloud
    usecase "Map Services to Resources" as MapServicestoResources
    ITOperations --> MapServicestoResources

}

rectangle "Service Repository" as sr #88cc88 {
        usecase "Manage Assets" as ManageAssets
    ITOperations --> ManageAssets

}

rectangle "Service Management Layer" as sml #88cc88 {
        usecase "Manage Clouds" as ManageClouds
    ITOperations --> ManageClouds

}

rectangle "Software Defined Infrastructure" as sdi #cccc88 {
        usecase "Manage Resources" as ManageResources
    ITOperations --> ManageResources

}

rectangle "edgemere" as edgemere #ccaaff {
        usecase "Control Virtual Infrastructure" as ControlVirtualInfrastructure
    ITOperations --> ControlVirtualInfrastructure
    usecase "Coordinate Services" as CoordinateServices
    ITOperations --> CoordinateServices
    usecase "Manage Physical Infrastructure" as ManagePhysicalInfrastructure
    ITOperations --> ManagePhysicalInfrastructure

}


@enduml
