@startuml

left to right direction


Actor "IT Operations" as ITOperations


rectangle "Environment Management" as em #lightgreen {
        usecase "Manage Environment" as ManageEnvironment
    ITOperations --> ManageEnvironment

}

rectangle "Common Physical Layer" as cpl #lightgray {
        usecase "Manage Data Center" as ManageDataCenter
    ITOperations --> ManageDataCenter
    usecase "Manage Infrastructure" as ManageInfrastructure
    ITOperations --> ManageInfrastructure

}

rectangle "Cloud Broker" as cb #lightgreen {
        usecase "Find Resources" as FindResources
    ITOperations --> FindResources
    usecase "ManageBilling" as ManageBilling
    ITOperations --> ManageBilling
    usecase "ManageCostModel" as ManageCostModel
    ITOperations --> ManageCostModel
    usecase "Manage Multi Cloud" as ManageMultiCloud
    ITOperations --> ManageMultiCloud
    usecase "Map Assets to Cloud" as MapAssetstoCloud
    ITOperations --> MapAssetstoCloud
    usecase "Map Services to Resources" as MapServicestoResources
    ITOperations --> MapServicestoResources

}

rectangle "Service Management Layer" as sml #lightgreen {
        usecase "Manage Clouds" as ManageClouds
    ITOperations --> ManageClouds

}

rectangle "Software Defined Infrastructure" as sdi #lightyellow {
        usecase "Manage Resources" as ManageResources
    ITOperations --> ManageResources

}


@enduml
