@startuml



state ApplicationInstance #88cccc {

    state Init #88cccc {
    }

    state Initializing #88cccc {
    }

    state Running #88cccc {
    }

    state Stopping #88cccc {
    }

    state Stopped #88cccc {
    }

    state Exit #88cccc {
    }

    state Failed #88cccc {
    }




Init -[#black]--> Initializing : create

Initializing -[#black]--> Running : provisoned

Running -[#black]--> Stopping : kill

Stopping -[#black]--> Stopped : stopped

Stopped -[#black]--> Exit : exit

Stopped -[#black]--> Failed : failed

}


@enduml
