@startuml

left to right direction





node "cpl_da" as cpl_daStack #cccccc {
    portin "parent" as cpl_daStackPortIn #red
}
node "cpl_dm" as cpl_dmStack #cccccc {
    portin "parent" as cpl_dmStackPortIn #red
}
node "cpl_tc" as cpl_tcStack #cccccc {
    portin "parent" as cpl_tcStackPortIn #red
}



node "cpl" #cccccc {


    hexagon telemetrynet #black [
            <b><color:white>telemetry</color></b>
    ]
    
    portout " " as telemetrynetPortOut #black
    telemetrynet -[#black]- telemetrynetPortOut
    
    hexagon parentnet #blue [
            <b><color:white>parent</color></b>
    ]
    
    portin " " as parentnetPortIn #blue
    parentnetPortIn -[#blue]- parentnet
    
    hexagon childrennet #red [
            <b><color:white>children</color></b>
    ]
    
    portout " " as childrennetPortOut #red
    childrennet -[#red]- childrennetPortOut
    
    hexagon siblingsnet #orange [
            <b><color:white>siblings</color></b>
    ]
    

node "web" as webService #white {
    portOut " " as webServicechildrennet #red
   webServicechildrennet -[#red]- childrennet
       portOut " " as webServicesiblingsnet #orange
   webServicesiblingsnet -[#orange]- siblingsnet
   

    artifact "aml_web" as aml_webimage
    
}
node "deviceagent" as deviceagentService #white {
    portOut " " as deviceagentServicechildrennet #red
   deviceagentServicechildrennet -[#red]- childrennet
   
    portIn " " as deviceagentServiceparentnet #blue
    parentnet -[#blue]- deviceagentServiceparentnet
    
    collections "cpl_da" as cpl_daimage
    
}
node "devicemanager" as devicemanagerService #white {
    portOut " " as devicemanagerServicechildrennet #red
   devicemanagerServicechildrennet -[#red]- childrennet
   
    portIn " " as devicemanagerServiceparentnet #blue
    parentnet -[#blue]- devicemanagerServiceparentnet
    
    collections "cpl_dm" as cpl_dmimage
    
}
node "telemetry" as telemetryService #white {
    portOut " " as telemetryServicechildrennet #red
   telemetryServicechildrennet -[#red]- childrennet
   
    portIn " " as telemetryServiceparentnet #blue
    parentnet -[#blue]- telemetryServiceparentnet
        portOut " " as telemetryServicetelemetrynet #black
   telemetryServicetelemetrynet -[#black]- telemetrynet
   
    collections "cpl_tc" as cpl_tcimage
    
}

}

cpl_daimage --> cpl_daStack
    
    childrennetPortOut -[#red]- cpl_daStackPortIn
    
cpl_dmimage --> cpl_dmStack
    
    childrennetPortOut -[#red]- cpl_dmStackPortIn
    
cpl_tcimage --> cpl_tcStack
    
    childrennetPortOut -[#red]- cpl_tcStackPortIn
    

@enduml
