@startuml


package "Distributed Information Management Layer" #ffcc88 {
    }

package "Service Management Layer" #lightgreen {
    
        class Stack {
        }
    }

package "Security Aspect" #pink {
    }

package "Identity Aspect" #pink {
    }

package "Application Management Layer" #lightblue {
    
        class Workload {
        }
    
        class ApplicationInstance {
        }
    }

package "Data Management Layer" #ffcc88 {
    
        class DataReference {
        }
    }


package "Application Management Layer" #lightblue {

    interface "Application Management Layer" as i {
            /edgemere/aml/aimodel/create()
            /edgemere/aml/aimodel/deploy()
            /edgemere/aml/aimodel/destroy()
            /edgemere/aml/aimodel/list()
            /edgemere/aml/aimodel/update()
            /edgemere/aml/application/create()
            /edgemere/aml/application/deploy()
            /edgemere/aml/application/destroy()
            /edgemere/aml/application/list()
            /edgemere/aml/application/monitor()
            /edgemere/aml/application/update()
            /edgemere/aml/workload/create()
            /edgemere/aml/workload/deploy()
            /edgemere/aml/workload/destroy()
            /edgemere/aml/workload/list()
            /edgemere/aml/workload/monitor()
            /edgemere/aml/workload/update()
    
    }
}

CLI ()-- i
REST ()-- i
Web ()-- i

package "Application Management Layer" #lightblue {
        class "Application" {
                 string name
                 string version
                    }
                Application o--> "n" Workload : workloads
                        Application *--> "n" Stack : stacks
                        Application o--> "n" DataReference : data
                        Application *--> "n" ApplicationInstance : instances
            
    
    class "ApplicationInstance" {
                 string name
                 string status
                 string message
                    }
                ApplicationInstance o--> "1" ModelName : assoc1
            
    
    class "ApplicationTemplate" {
                 string attr1
                    }
                ApplicationTemplate o--> "1" ModelName : assoc1
            
    
    class "Workload" {
                 string attr1
                    }
                Workload o--> "1" ModelName : assoc1
            
    
    class "WorkloadInstance" {
                 string attr1
                    }
                WorkloadInstance o--> "1" ModelName : assoc1
            
    
    class "WorkloadTemplate" {
                 string attr1
                    }
                WorkloadTemplate o--> "1" ModelName : assoc1
            
    

}


    "Application Management Layer" --> "Distributed Information Management Layer"

    "Application Management Layer" --> "Service Management Layer"

    "Application Management Layer" --> "Security Aspect"

    "Application Management Layer" --> "Identity Aspect"


@enduml
