@startuml

left to right direction







node "sml_sc" #88cc88 {


    hexagon parentnet #black [
            <b><color:white>parent</color></b>
    ]
    
    portin " " as parentnetPortIn #black
    parentnetPortIn -[#black]- parentnet
    
    hexagon childrennet #blue [
            <b><color:white>children</color></b>
    ]
    
    portout " " as childrennetPortOut #blue
    childrennet -[#blue]- childrennetPortOut
    
    hexagon siblingsnet #red [
            <b><color:white>siblings</color></b>
    ]
    

node "gw" as gwService #white {
    portOut " " as gwServicechildrennet #blue
   gwServicechildrennet -[#blue]- childrennet
       portOut " " as gwServicesiblingsnet #red
   gwServicesiblingsnet -[#red]- siblingsnet
   

    artifact "sml_sc_controller" as sml_sc_controllerimage
    
}

}


@enduml
