@startuml


usecase "Manage Data Adaptors" as ManageDataAdaptors #yellow

Actor "DataEngineer" as DataEngineer

DataEngineer --> ManageDataAdaptors

Actor "Data Scientist" as DataScientist

DataScientist --> ManageDataAdaptors



usecase "AttachDataBluePrint" as AttachDataBluePrint #lightgrey

ManageDataAdaptors --> AttachDataBluePrint

usecase "CreateDataAdaptor" as CreateDataAdaptor #lightgrey

ManageDataAdaptors --> CreateDataAdaptor

usecase "UpdateDataAdaptor" as UpdateDataAdaptor #lightgrey

ManageDataAdaptors --> UpdateDataAdaptor









@enduml
