@startuml

actor "Actor"


entity EventBus

box Data Definition Framework #ffcc88
    boundary ddf #white
end box



"Actor" -> ddf: Attach Data Blue Print



box "Data Management Layer" #ffcc88
    boundary dml #white
end box
EventBus -\ dml: method()
dml --/ EventBus: Model.Event2

EventBus --/ ddf : method2()
@enduml
