@startuml


actor "Data Scientist"


entity EventBus

box Data Definition Framework #ffcc88
    boundary ddf #white
end box


group Given [A Data Scientist is using the blueprint/attach method]

"Data Scientist" --/ ddf: They attach a data blueprint
"ddf" -> ddf: Attach Data Blue Print



"Data Scientist" /-- ddf: The system should manage data adaptors accordingly


end

@enduml
