@startuml


actor "DataEngineer"


entity EventBus

box Data Definition Framework #ffcc88
    boundary ddf #white
end box


group Given [A data engineer wants to update a specific data adaptor]

"DataEngineer" --/ ddf: The data engineer uses the &#39;dataadaptor/update&#39; method
"ddf" -> ddf: Update Data Adaptor



"DataEngineer" /-- ddf: The specified data adaptor should be updated


end

@enduml
