@startuml


left to right direction

usecase "Apply Security Profiles" as ApplySecurityProfiles #yellow

Actor "Security Operator" as SecurityOperator

SecurityOperator --> ApplySecurityProfiles



json AttachProfile #lightyellow {
    "Given": "Security engineer created security profile and identity",
    "When": "Security profile is deployed and attached to the identity",
    "Then": "Security profile is successfully attached to the identity"
}

ApplySecurityProfiles <|-- AttachProfile

json DeploySecurityProfile #lightyellow {
    "Given": "A security profile has been created",
    "When": "The Security Engineer deploys the security profile",
    "Then": "The system&#39;s identity has the new security profile applied"
}

ApplySecurityProfiles <|-- DeploySecurityProfile



usecase "Secure Assets" as SecureAssets #lightyellow

ApplySecurityProfiles <-- SecureAssets : extends







@enduml
