@startuml

class "User" as Model {
 string name
 string username
 string password
 string cert

 
}

rectangle "Group" as Group #lightblue {
}

Model o--> "n" Group : groups


rectangle "IdentityAttribute" as IdentityAttribute #lightblue {
}

Model o--> "n" IdentityAttribute : attributes


rectangle "SecurityProfile" as SecurityProfile #lightblue {
}

Model o--> "n" SecurityProfile : securityProfiles


rectangle "IdentityAttribute" as IdentityAttribute #lightblue {
}

Model o--> "n" IdentityAttribute : characterisitcs




    rectangle "Group" as Group #lightgreen {
    }
    
        Group   o--> "n" Model : "users"
    

@enduml
