@startuml

class "Hardware" as Model {
 string name
 string ename

 create()
 factory()
 
}

rectangle "PhysicalProfile" as PhysicalProfile {
}

Model o--> "1" PhysicalProfile : profile


rectangle "Device" as Device {
}

Model o--> "1" Device : device


rectangle "Resource" as Resource {
}

Model o--> "n" Resource : resources




@enduml
