@startuml

class "Hardware" as Model {
 string name
 string ename

 addStats()
 create()
 disable()
 enable()
 factory()
 
}

rectangle "PhysicalProfile" as PhysicalProfile #lightblue {
}

Model o--> "1" PhysicalProfile : profile


rectangle "Device" as Device #lightblue {
}

Model o--> "1" Device : device


rectangle "Resource" as Resource #lightblue {
}

Model o--> "n" Resource : resources




    rectangle "AggregatedDevice" as AggregatedDevice #lightgreen {
    }
    
        AggregatedDevice   *--> "n" Model : "hardware"
    
    rectangle "Device" as Device #lightgreen {
    }
    
        Device   *--> "n" Model : "hardware"
    
    rectangle "AcceleratorResource" as AcceleratorResource #lightgreen {
    }
    
        AcceleratorResource   o--> "n" Model : "hardware"
    
    rectangle "ComputeResource" as ComputeResource #lightgreen {
    }
    
        ComputeResource   o--> "n" Model : "hardware"
    
    rectangle "NetworkResource" as NetworkResource #lightgreen {
    }
    
        NetworkResource   o--> "n" Model : "hardware"
    
    rectangle "Resource" as Resource #lightgreen {
    }
    
        Resource   o--> "n" Model : "hardware"
    
    rectangle "StorageResource" as StorageResource #lightgreen {
    }
    
        StorageResource   o--> "n" Model : "hardware"
    

@enduml
