@startuml

left to right direction


boundary parent #blue


entity _telemetry_family #black

entity children #red

rectangle "cpl_da" as cpl_daStack #cccccc {
    queue cpl_daStacksnet #red [
        <b><color:white>parent</color></b>
    ]
}
rectangle "cpl_dm" as cpl_dmStack #cccccc {
    queue cpl_dmStacksnet #red [
        <b><color:white>parent</color></b>
    ]
}
rectangle "cpl_tc" as cpl_tcStack #cccccc {
    queue cpl_tcStacksnet #red [
        <b><color:white>parent</color></b>
    ]
}



package "cpl" #cccccc {
    queue telemetrynet #black [
            <b><color:white>telemetry</color></b>
    ]
    
    telemetrynet -[#black]- _telemetry_family
    
    queue parentnet #blue [
            <b><color:white>parent</color></b>
    ]
    
    parentnet -[#blue]- parent
    
    queue childrennet #red [
            <b><color:white>children</color></b>
    ]
    
    childrennet -[#red]- children
    
    queue siblingsnet #orange [
            <b><color:white>siblings</color></b>
    ]
    

node "web" as webService
node "deviceagent" as deviceagentService
node "devicemanager" as devicemanagerService
node "telemetry" as telemetryService


        artifact "aml_web" as aml_webimage
            collections "cpl_da" as cpl_daimage
            collections "cpl_dm" as cpl_dmimage
            collections "cpl_tc" as cpl_tcimage
    
}

webService -[#red]- childrennet

webService -[#orange]- siblingsnet

deviceagentService -[#red]- childrennet

deviceagentService -[#blue]- parentnet

devicemanagerService -[#red]- childrennet

devicemanagerService -[#blue]- parentnet

telemetryService -[#red]- childrennet

telemetryService -[#blue]- parentnet

telemetryService -[#black]- telemetrynet
webService .... aml_webimage
deviceagentService .... cpl_daimage
devicemanagerService .... cpl_dmimage
telemetryService .... cpl_tcimage

cpl_daimage --> cpl_daStack
    
cpl_dmimage --> cpl_dmStack
    
cpl_tcimage --> cpl_tcStack
    

@enduml
