@startuml

class "ServiceDefinition" as Model {
 string name

 
}



    rectangle "StackDefinition" as StackDefinition #lightgreen {
    }
    
        StackDefinition   *--> "n" Model : "services"
    

@enduml
