@startuml


usecase "Manage Data Governance" as ManageDataGovernance #yellow

Actor "Chief Data Officer" as ChiefDataOfficer

ChiefDataOfficer --> ManageDataGovernance





usecase "Provide Business Information" as ProvideBusinessInformation #lightyellow

ManageDataGovernance <-- ProvideBusinessInformation : extends







@enduml
