@startuml


left to right direction

usecase "Change Physical World" as ChangePhysicalWorld #yellow

Actor "Actor" as Actor

Actor --> ChangePhysicalWorld



json AdjustTemperature #lightyellow {
    "Given": "Actor has access to a temperature control asset",
    "When": "Actor uses the temperature control asset and monitoring system is activated",
    "Then": "Continuous temperature data is received and transmitted"
}

ChangePhysicalWorld <|-- AdjustTemperature

json toggleSwitch #lightyellow {
    "Given": "Switch control asset",
    "When": "Switch state needs changing",
    "Then": "Control command is sent"
}

ChangePhysicalWorld <|-- toggleSwitch









@enduml
