@startuml


actor "Actor"


entity EventBus

box PhysicalWorld #aaffff
    boundary pw #white
end box


box PhysicalWorld #aaffff
    end box

group Given [Actor has access to a temperature control asset]

"Actor" --/ pw: Actor uses the temperature control asset and monitoring system is activated
"pw" -> pw: Adjust Temperature

    pw -> "physicalworld": control (assetID: tempAssetID)

    "physicalworld" --/ EventBus: asset.control

    pw -> "physicalworld": startmonitoring (assetID: tempAssetID)

    "physicalworld" --/ EventBus: asset.startmonitoring

    pw -> "physicalworld": manage (assetID: tempAssetID)

    "physicalworld" --/ EventBus: physicalasset.manage

    pw -> "physicalworld": transmitdata ()

    "physicalworld" --/ EventBus: communicationpathway.transmitdata

    pw -> "physicalworld": create (attr1: temperature)

    "physicalworld" --/ EventBus: data.create

    pw -> "physicalworld": getreading (assetID: tempSensorID)

    "physicalworld" --/ EventBus: sensor.getreading

    pw -> "physicalworld": transmitdata ()

    "physicalworld" --/ EventBus: communicationpathway.transmitdata

    pw -> "physicalworld": create (attr1: temperature)

    "physicalworld" --/ EventBus: data.create

    pw -> "physicalworld": stopmonitoring (assetID: tempAssetID)

    "physicalworld" --/ EventBus: asset.stopmonitoring

    pw -> "physicalworld": manage (assetID: tempAssetID)

    "physicalworld" --/ EventBus: physicalasset.manage



"Actor" /-- pw: Continuous temperature data is received and transmitted


end

@enduml
