@startuml


actor "Actor"


entity EventBus

box PhysicalWorld #lightblue
    boundary pw #white
end box


box Software Defined Infrastructure #cccc88
            participant storageresource
    end box

group Given [Tempature control asset]

"Actor" --/ pw: Monitoring system is activated
"pw" -> pw: Adjust Temperature

    pw -> "storageresource": list (name: hello,file: ./templates/world.yml)

    "storageresource" --/ EventBus: data.list

    pw -> "storageresource": list (name: hello,file: ./templates/world.yml)

    "storageresource" --/ EventBus: data.list



"Actor" /-- pw: Continuous data stream is received


end

@enduml
