@startuml


actor "Actor"


entity EventBus

box PhysicalWorld #aaffff
    boundary pw #white
end box


box Software Defined Infrastructure #cccc88
            participant storageresource
    end box

group Given [Switch control asset]

"Actor" --/ pw: Switch state needs changing
"pw" -> pw: Toogle Switch

    pw -> "storageresource": list (name: hello,file: ./templates/world.yml)

    "storageresource" --/ EventBus: data.list

    pw -> "storageresource": list (name: hello,file: ./templates/world.yml)

    "storageresource" --/ EventBus: data.list



"Actor" /-- pw: Control command is sent


end

@enduml
