@startuml

class "Servicelet" as Model {
 string name
 json args
 number replicas
 json ports

 create()
 deploy()
 
}

rectangle "Resource" as Resource #lightblue {
}

Model o--> "n" Resource : resources


rectangle "Stacklet" as Stacklet #lightblue {
}

Model o--> "1" Stacklet : parent


rectangle "ServiceInstance" as ServiceInstance #lightblue {
}

Model o--> "n" ServiceInstance : instances


rectangle "Service" as Service #lightblue {
}

Model o--> "1" Service : service


rectangle "Environment" as Environment #lightblue {
}

Model o--> "1" Environment : env


rectangle "DataReference" as DataReference #lightblue {
}

Model *--> "n" DataReference : data




    rectangle "DataReference" as DataReference #lightgreen {
    }
    
        DataReference   o--> "1" Model : "parent"
    
    rectangle "Service" as Service #lightgreen {
    }
    
        Service   *--> "n" Model : "servicelets"
    
    rectangle "Stack" as Stack #lightgreen {
    }
    
        Stack   *--> "n" Model : "servicelets"
    
    rectangle "Stacklet" as Stacklet #lightgreen {
    }
    
        Stacklet   *--> "n" Model : "servicelets"
    
    rectangle "StackletDefinition" as StackletDefinition #lightgreen {
    }
    
        StackletDefinition   *--> "n" Model : "servicelets"
    
    rectangle "ServiceInstance" as ServiceInstance #lightgreen {
    }
    
        ServiceInstance   o--> "1" Model : "servicelet"
    
    rectangle "StackInstance" as StackInstance #lightgreen {
    }
    
        StackInstance   o--> "1" Model : "servicelet"
    

@enduml
