@startuml


boundary _diml_dml_do_family #blue


entity _diml_dml_family #orange


package  "Data Orchestrator"  #lightblue {
    card children #blue [
        <b><color:white>children</color></b>
    ]
    
    _diml_dml_do_family -[#blue]- children
    
    
    card sibling #red [
        <b><color:white>sibling</color></b>
    ]
    
    
    card parent #orange [
        <b><color:white>parent</color></b>
    ]
    
    
    _diml_dml_family -[#orange]- parent
    
    artifact images #ffffff {
        
        file diml_dml_do_web
        
        file diml_dml_do_gw
        
    }

    node frontend
    frontend .. diml_dml_do_web
    
        sibling -[#red]- frontend
    

    node gw
    gw .. diml_dml_do_gw
    
        children -[#blue]- gw
    
        sibling -[#red]- gw
    




    
}




package dml #lightgray {
    card dmlchildren #orange [
        <b><color:white>children</color></b>
    ]
    dmlchildren ==[#orange]= parent
}


@enduml
