@startuml
left to right direction


state "diml" as diml #ffcc88 {
state "dml" as dimldml #ffcc88 {
state "do" as dimldmldo ##aaffff {
}
}
}


state "dimldmldo" as pstatename ##aaffff {
    state "Custom Function" as dofunction {
    }
}

        state "diml" as diml #ffcc88 {
state "dml" as dimldml #ffcc88 {
state "do" as dimldmldo ##aaffff {
state "evaluate" as dimldmldoevaluate ##aaffff {
}
}
}
}


        state "diml" as diml #ffcc88 {
state "dml" as dimldml #ffcc88 {
state "do" as dimldmldo ##aaffff {
state "reserve" as dimldmldoreserve ##aaffff {
}
}
}
}


        state "diml" as diml #ffcc88 {
state "dml" as dimldml #ffcc88 {
state "do" as dimldmldo ##aaffff {
state "datainstance" as dimldmldodatainstance ##aaffff {
state "create" as dimldmldodatainstancecreate ##aaffff {
}
}
}
}
}


        state "diml" as diml #ffcc88 {
state "dml" as dimldml #ffcc88 {
state "do" as dimldmldo ##aaffff {
state "datainstance" as dimldmldodatainstance ##aaffff {
state "destroy" as dimldmldodatainstancedestroy ##aaffff {
}
}
}
}
}


        state "diml" as diml #ffcc88 {
state "dml" as dimldml #ffcc88 {
state "do" as dimldmldo ##aaffff {
state "datainstance" as dimldmldodatainstance ##aaffff {
state "find" as dimldmldodatainstancefind ##aaffff {
}
}
}
}
}


        state "diml" as diml #ffcc88 {
state "dml" as dimldml #ffcc88 {
state "do" as dimldmldo ##aaffff {
state "datainstance" as dimldmldodatainstance ##aaffff {
state "list" as dimldmldodatainstancelist ##aaffff {
}
}
}
}
}




        state "diml" as diml #ffcc88 {
state "dml" as dimldml #ffcc88 {
state "DataReference" as dimldmldatareference #ffcc88 {
state "provisioning" as dimldmldatareferenceprovisioning #ffcc88 {
}
}
}
}

        
    state "diml" as diml #ffcc88 {
state "dml" as dimldml #ffcc88 {
state "do" as dimldmldo ##aaffff {
state "datainstance" as dimldmldodatainstance ##aaffff {
state "create" as dimldmldodatainstancecreate ##aaffff {
}
}
}
}
}

    dimldmldatareferenceprovisioning ---> dimldmldodatainstancecreate
  

        state "diml" as diml #ffcc88 {
state "dml" as dimldml #ffcc88 {
state "do" as dimldmldo ##aaffff {
state "DataRequest" as dimldmldodatarequest ##aaffff {
state "needed" as dimldmldodatarequestneeded ##aaffff {
}
}
}
}
}

        
    state "diml" as diml #ffcc88 {
state "dml" as dimldml #ffcc88 {
state "do" as dimldmldo ##aaffff {
state "reserve" as dimldmldoreserve ##aaffff {
}
}
}
}

    dimldmldodatarequestneeded ---> dimldmldoreserve
  

        state "diml" as diml #ffcc88 {
state "dml" as dimldml #ffcc88 {
state "do" as dimldmldo ##aaffff {
state "DataRequest" as dimldmldodatarequest ##aaffff {
state "selected" as dimldmldodatarequestselected ##aaffff {
}
}
}
}
}

        
    state "diml" as diml #ffcc88 {
state "dml" as dimldml #ffcc88 {
state "do" as dimldmldo ##aaffff {
state "evaluate" as dimldmldoevaluate ##aaffff {
}
}
}
}

    dimldmldodatarequestselected ---> dimldmldoevaluate
  


    
    
        
       
    
    
        
       

@enduml
