@startuml
left to right direction



state "DataScientist" as DataScientist {
    state "Manage Data Instances" as DataScientistManageDataInstances {
    }
}
state "edgemere" as edgemere #lightblue {
state "diml" as edgemerediml #lightblue {
state "dml" as edgemeredimldml #lightblue {
state "do" as edgemeredimldmldo #lightblue {
state "datainstance" as edgemeredimldmldodatainstance #lightblue {
state "list" as edgemeredimldmldodatainstancelist #lightblue {
}
}
}
}
}
}

DataScientistManageDataInstances --> edgemeredimldmldodatainstancelist

state "ApplicationDeveloper" as ApplicationDeveloper {
    state "Manage Data Instances" as ApplicationDeveloperManageDataInstances {
    }
}
state "edgemere" as edgemere #lightblue {
state "diml" as edgemerediml #lightblue {
state "dml" as edgemeredimldml #lightblue {
state "do" as edgemeredimldmldo #lightblue {
state "datainstance" as edgemeredimldmldodatainstance #lightblue {
state "list" as edgemeredimldmldodatainstancelist #lightblue {
}
}
}
}
}
}

ApplicationDeveloperManageDataInstances --> edgemeredimldmldodatainstancelist


    state "Application Developer" as ApplicationDeveloper {
        state "Manage Data Instances" as ApplicationDeveloperManageDataInstances {
            state "Create Data Instance" as ApplicationDeveloperManageDataInstancesCreateDataInstance {
            }
        }
    }
    
    ApplicationDeveloperManageDataInstancesCreateDataInstance --> Null
    
 
    state "Actor" as Actor {
        state "Manage Data Instances" as ActorManageDataInstances {
            state "Find Data Instance" as ActorManageDataInstancesFindDataInstance {
            }
        }
    }
    
    ActorManageDataInstancesFindDataInstance --> Null
    
 
    state "Actor" as Actor {
        state "Manage Data Instances" as ActorManageDataInstances {
            state "Remove Data Instance" as ActorManageDataInstancesRemoveDataInstance {
            }
        }
    }
    
    ActorManageDataInstancesRemoveDataInstance --> Null
    
 
 

@enduml
