@startuml


package "Data Management Layer" #ffcc88 {

}

package "Data Orchestrator" ##aaffff {

}

package "Data Definition Framework" #ffcc88 {

}


package "Data Orchestrator" ##aaffff {

    interface "Data Orchestrator" as i {
            ^datareference.provisioning
            ^datarequest.needed
            ^datarequest.selected
    
            /edgemere/diml/dml/do/evaluate()
            /edgemere/diml/dml/do/reserve()
            /edgemere/diml/dml/do/datainstance/create()
            /edgemere/diml/dml/do/datainstance/destroy()
            /edgemere/diml/dml/do/datainstance/find()
            /edgemere/diml/dml/do/datainstance/list()
    
    }
}

circle REST
circle Web
circle CLI
circle WebSocket

i -down- Web
i -down- CLI
i -down- REST
WebSocket -left- i: events >

package "Data Orchestrator" ##aaffff {


}



@enduml
