@startuml

left to right direction
Actor "DataScientist" as DataScientist
Actor "ApplicationDeveloper" as ApplicationDeveloper


rectangle "Data Orchestrator" ##aaffff {
usecase "ManageDataInstances" as ManageDataInstances
    DataScientist --> ManageDataInstances
    ApplicationDeveloper --> ManageDataInstances
    }


@enduml
