@startuml

node "Edge Device (Machine)" #cccccc {
    component "Salt Minon" as sminon #cc8888
    component "Docker Swarm" as dockersed #88cc88
    collections "Device Agent" as dagent #white
    component "Docker Node" as dockernodeed #88cc88
    agent "Data Controller" as datac #ffcc88
    agent "Service Controller" as servicec #88cc88
    agent "Policy Engine" as pe #cc8888
    agent "Telemetry Producer" as tp #cccccc
}
dockernodeed --> datac
dockernodeed --> servicec
dockernodeed --> pe
dockernodeed --> tp
sminon -> dockersed
sminon -> dockernodeed
dockersed .. dockernodeed
dockersed -> dagent
datac <-- dagent
servicec <-- dagent
pe <-- dagent
tp <-- dagent

node "Aggregated Edge Device" #cccccc {
    node "Machine0" #white {
        component "Salt Master" as smaster2 #cc8888
        component "Salt Minon" as sminon2 #cc8888
        component "Docker Swarm" as dockersaed #88cc88
        agent "Service Orchestrator" as soad #88cc88
    }
    node "Machine1" #white {
        component "Salt Minon" as sminon21 #cc8888
        component "Docker Node" as dockernode21 #88cc88
        agent "Policy Engine" as pead #cc8888
        agent "Data Orchestrator" as doad #ffcc88
    }
    dockernode21 ..> pead
    dockernode21 ..> doad
    node "Machinen" #white {
        component "Salt Minon" as sminon22 #cc8888
        component "Docker Node" as dockernode22 #88cc88
        agent "Telemetry Aggregator" as tpad #cccccc
    }
    dockernode22 ..> tpad
    collections "Device Manager" as dm #white
    dockersaed --> dm
    pead --> dm
    doad <- dm
    soad <- dm
    tpad <- dm
    smaster2 ..> sminon21
    smaster2 ..> sminon22
    dockersaed ..> dockernode21
    dockersaed ..> dockernode22
    sminon21 -> dockernode21
    sminon22 -> dockernode22
    sminon2 --> dockersaed
}

node "Data Center" {
    component "Salt Master" as smaster
    component "Docker Swarm" as dockersdc #88cc88
    agent "Telemetry Consumer" as tc #cccccc
}
dockersdc .> tc
smaster ..> sminon2
smaster2 <= sminon2
smaster2 ..> sminon

@enduml
