@startuml



package "Device Agent" #lightgray {

    interface "Device Agent" as i {
            /edgemere/cpl/da/connect()
            /edgemere/cpl/da/register()
            /edgemere/cpl/da/service/register()
    
    }
}

CLI ()-- i
REST ()-- i
Web ()-- i

package "Device Agent" #lightgray {
    
}



@enduml
