@startuml
left to right direction


state "cpl" as cpl #cccccc {
state "da" as cplda #cccccc {
}
}


state "cplda" as pstatename #cccccc {
    state "Custom Function" as dafunction {
    }
}

        state "cpl" as cpl #cccccc {
state "da" as cplda #cccccc {
state "connect" as cpldaconnect #cccccc {
}
}
}


        state "cpl" as cpl #cccccc {
state "da" as cplda #cccccc {
state "register" as cpldaregister #cccccc {
}
}
}


        state "cpl" as cpl #cccccc {
state "da" as cplda #cccccc {
state "service" as cpldaservice #cccccc {
state "register" as cpldaserviceregister #cccccc {
}
}
}
}




        state "sml" as sml #88cc88 {
state "Service" as smlservice #88cc88 {
state "started" as smlservicestarted #88cc88 {
}
}
}

        
    state "da" as da #ccaaff {
state "service" as daservice #ccaaff {
state "register" as daserviceregister #ccaaff {
}
}
}

    smlservicestarted ---> daserviceregister
  



@enduml
