@startuml



package "Device Agent" #cccccc {

    interface "Device Agent" as i {
            ^service.started
    
            /edgemere/cpl/da/connect()
            /edgemere/cpl/da/register()
            /edgemere/cpl/da/service/register()
    
    }
}

circle REST
circle Web
circle CLI
circle WebSocket

i -down- Web
i -down- CLI
i -down- REST
WebSocket -left- i: events >

package "Device Agent" #cccccc {


}



@enduml
