@startuml
partition "Application Developer" #ffffcc {
(*) --> "Manage Applications"
}
partition "Application Developer" #ffffcc {
"Manage Applications" --> ===F2===
}

partition "edgemere" #ccaaff {
===F2=== --> "Create Application Stack"
}

partition "edgemere" #ccaaff {
===F2=== --> "Create Service Stack"
}
partition "edgemere" #ccaaff {
"Create Application Stack" --> "Modify Application Stack"
}
partition "edgemere" #ccaaff {
"Modify Application Stack" --> "Version Application Stack"
}
partition "Application Management Layer" #88cccc {
"Version Application Stack" --> "Test Application Stack"
}
partition "edgemere" #ccaaff {
"Create Service Stack" --> "Modify Service Stack"
}
partition "Service Management Layer" #88cc88 {
"Modify Service Stack" --> "Application Build Process"
}
partition "Service Management Layer" #88cc88 {
"Application Build Process" --> if "Build Results" then
}
partition "edgemere" #ccaaff {
else
--> [Passed] "Test Service Stack"
}
partition "edgemere" #ccaaff {
else
--> [Failed] "Modify Service Stack"
}
partition "edgemere" #ccaaff {
"Test Service Stack" --> if "Service Test" then
}
partition "edgemere" #ccaaff {
else
--> [success] "Version Service Stack"
}
partition "Application Developer" #ffffcc {
else
--> [failed] "Manage Applications"
}
partition "Application Management Layer" #88cccc {
"Version Service Stack" --> "Test Application Stack"
}
partition "Application Management Layer" #88cccc {
"Test Application Stack" --> "Create Application"
}
partition "Application Management Layer" #88cccc {
"Create Application" --> "Deploy Application"
}
partition "Application Management Layer" #88cccc {
"Deploy Application" --> "Destroy Application"
}

@enduml
