@startuml
partition "System Administrator" #ffffcc {
(*) --> "Configure Alerts for Asset"
}
partition "System Administrator" #ffffcc {
"Configure Alerts for Asset" --> "Monitor QoS"
}
partition "System Administrator" #ffffcc {
"Monitor QoS" --> "Poll Asset Status"
}

@enduml
