@startuml

left to right direction


boundary parent #black


entity children #blue




package "sa_pe" #cc8888 {
    queue parentnet #black [
            <b><color:white>parent</color></b>
    ]
    
    parentnet -[#black]- parent
    
    queue childrennet #blue [
            <b><color:white>children</color></b>
    ]
    
    childrennet -[#blue]- children
    
    queue siblingsnet #red [
            <b><color:white>siblings</color></b>
    ]
    

node "web" as webService
node "engine" as engineService


        artifact "sa_pe_web" as sa_pe_webimage
    
        artifact "sa_pe_engine" as sa_pe_engineimage
    
}

webService -[#blue]- childrennet

webService -[#red]- siblingsnet

engineService -[#blue]- childrennet

engineService -[#red]- siblingsnet
webService .... sa_pe_webimage
engineService .... sa_pe_engineimage


@enduml
