@startuml

left to right direction


boundary ailtire_appname_aml_family #red


entity ailtire_appname_aml_ams_family #black




package "aml_ams" #lightblue {
    queue childrennet #black [
            <b><color:white>children</color></b>
    ]
    
    childrennet -[#black]- ailtire_appname_aml_ams_family
    
    queue siblingnet #blue [
            <b><color:white>sibling</color></b>
    ]
    
    queue parentnet #red [
            <b><color:white>parent</color></b>
    ]
    
    parentnet -[#red]- ailtire_appname_aml_family
    

node "frontend" as frontendService
node "gw" as gwService


        artifact "aml_ams_web" as aml_ams_webimage
    
        artifact "aml_ams_gw" as aml_ams_gwimage
    
}

frontendService -[#blue]- siblingnet

gwService -[#black]- childrennet

gwService -[#blue]- siblingnet
frontendService .... aml_ams_webimage
gwService .... aml_ams_gwimage


@enduml
