@startuml

left to right direction







node "transform" #lightblue {


    hexagon childrennet #black [
            <b><color:white>children</color></b>
    ]
    
    portout " " as childrennetPortOut #black
    childrennet -[#black]- childrennetPortOut
    
    hexagon siblingnet #blue [
            <b><color:white>sibling</color></b>
    ]
    
    hexagon parentnet #red [
            <b><color:white>parent</color></b>
    ]
    
    portin " " as parentnetPortIn #red
    parentnetPortIn -[#red]- parentnet
    

node "frontend" as frontendService #white {
    portOut " " as frontendServicesiblingnet #blue
   frontendServicesiblingnet -[#blue]- siblingnet
   

    artifact "diml_cds_transform_web" as diml_cds_transform_webimage
    
}
node "gw" as gwService #white {
    portOut " " as gwServicechildrennet #black
   gwServicechildrennet -[#black]- childrennet
       portOut " " as gwServicesiblingnet #blue
   gwServicesiblingnet -[#blue]- siblingnet
   

    artifact "diml_cds_transform_gw" as diml_cds_transform_gwimage
    
}

}


@enduml
