@startuml

left to right direction

Actor "Actor" as Actor

Actor "Application Developer" as ApplicationDeveloper

Actor "Chief Data Officer" as ChiefDataOfficer

Actor "ChiefDataOfficier" as ChiefDataOfficier

Actor "Data Analyst" as DataAnalyst

Actor "DataEngineer" as DataEngineer

Actor "Data Scientist" as DataScientist

Actor "Data Steward" as DataSteward

Actor "DevOps Engineer" as DevOpsEngineer

Actor "IT Operations" as ITOperations

Actor "SecurityEngineer" as SecurityEngineer

Actor "Security Operator" as SecurityOperator

Actor "Stack Developer" as StackDeveloper



rectangle "Common Physical Layer" as cpl  #cccccc {
        usecase "Change Physical World" as ChangePhysicalWorld
    
        Actor ---> ChangePhysicalWorld
        
    usecase "Commission Physical Asset" as CommissionPhysicalAsset
    
        Actor ---> CommissionPhysicalAsset
        
    usecase "Connect Physical Asset to a Device" as ConnectPhysicalAssettoaDevice
    
        Actor ---> ConnectPhysicalAssettoaDevice
        
    usecase "Decommission Physical Asset" as DecommissionPhysicalAsset
    
        Actor ---> DecommissionPhysicalAsset
        
    usecase "Manage Physical Assets" as ManagePhysicalAssets
    
        Actor ---> ManagePhysicalAssets
        
    usecase "Monitor Physical World" as MonitorPhysicalWorld
    
        Actor ---> MonitorPhysicalWorld
        
    usecase "Replace Physical Asset" as ReplacePhysicalAsset
    
        Actor ---> ReplacePhysicalAsset
        
    usecase "Secure Data from Physical Asset" as SecureDatafromPhysicalAsset
    
        Actor ---> SecureDatafromPhysicalAsset
        
    usecase "Secure Physical Asset" as SecurePhysicalAsset
    
        Actor ---> SecurePhysicalAsset
        

}

rectangle "Application Management Layer" as aml  #88cccc {
        usecase "Manage AI Models" as ManageAIModels
    
        DataScientist --> ManageAIModels
        
        DevOpsEngineer --> ManageAIModels
        
        ApplicationDeveloper --> ManageAIModels
        
        DataEngineer --> ManageAIModels
        
    usecase "Manage Applications" as ManageApplications
    
        DevOpsEngineer --> ManageApplications
        
        ApplicationDeveloper --> ManageApplications
        
    usecase "Manage Workloads" as ManageWorkloads
    
        ApplicationDeveloper --> ManageWorkloads
        
        DevOpsEngineer --> ManageWorkloads
        

}

rectangle "Distributed Information Management Layer" as diml  #ffcc88 {
        usecase "Manage Data Instances" as ManageDataInstances
    
        DataScientist ---> ManageDataInstances
        
        ApplicationDeveloper ---> ManageDataInstances
        

}

rectangle "Service Management Layer" as sml  #88cc88 {
        usecase "Manage Stacks" as ManageStacks
    
        StackDeveloper --> ManageStacks
        
        ApplicationDeveloper --> ManageStacks
        

}

rectangle "Service Management Layer" as sml  #88cc88 {
        usecase "Manage Services" as ManageServices
    
        StackDeveloper ---> ManageServices
        
        ApplicationDeveloper ---> ManageServices
        
    usecase "Manage Clouds" as ManageClouds
    
        ITOperations ---> ManageClouds
        

}

rectangle "edgemere" as edgemere  #ccaaff {
        usecase "Organize Solutions" as OrganizeSolutions
    
        ApplicationDeveloper --> OrganizeSolutions
        
        DevOpsEngineer --> OrganizeSolutions
        
    usecase "Provide Business Information" as ProvideBusinessInformation
    
        DataAnalyst --> ProvideBusinessInformation
        
        DataEngineer --> ProvideBusinessInformation
        
        DataScientist --> ProvideBusinessInformation
        
        DataSteward --> ProvideBusinessInformation
        
        ChiefDataOfficier --> ProvideBusinessInformation
        
    usecase "Coordinate Services" as CoordinateServices
    
        StackDeveloper --> CoordinateServices
        
        ITOperations --> CoordinateServices
        
        DevOpsEngineer --> CoordinateServices
        
    usecase "Control Virtual Infrastructure" as ControlVirtualInfrastructure
    
        ITOperations --> ControlVirtualInfrastructure
        
    usecase "Manage Physical Infrastructure" as ManagePhysicalInfrastructure
    
        ITOperations --> ManagePhysicalInfrastructure
        
    usecase "Secure Assets" as SecureAssets
    
        SecurityEngineer --> SecureAssets
        
        SecurityOperator --> SecureAssets
        
    usecase "Govern Identities" as GovernIdentities
    
        SecurityOperator --> GovernIdentities
        

}

rectangle "Distributed Information Management Layer" as diml  #ffcc88 {
        usecase "Manage Data Procedures" as ManageDataProcedures
    
        DataEngineer ---> ManageDataProcedures
        
        ChiefDataOfficer ---> ManageDataProcedures
        
    usecase "Manage Data Adaptors" as ManageDataAdaptors
    
        DataEngineer ---> ManageDataAdaptors
        
        DataScientist ---> ManageDataAdaptors
        
    usecase "Manage Data Blue Prints" as ManageDataBluePrints
    
        DataEngineer ---> ManageDataBluePrints
        
        DataScientist ---> ManageDataBluePrints
        
    usecase "Manage Data Pipeline" as ManageDataPipeline
    
        DataEngineer ---> ManageDataPipeline
        
    usecase "Manage Meta Data" as ManageMetaData
    
        DataScientist ---> ManageMetaData
        

}

rectangle "Distributed Information Management Layer" as diml  #ffcc88 {
        usecase "Manage Data Governance" as ManageDataGovernance
    
        ChiefDataOfficer --> ManageDataGovernance
        
    usecase "Manage Data Policies" as ManageDataPolicies
    
        ChiefDataOfficer --> ManageDataPolicies
        
    usecase "Manage Data Strategy" as ManageDataStrategy
    
        ChiefDataOfficer --> ManageDataStrategy
        
    usecase "Manage Data Sources" as ManageDataSources
    
        DataEngineer --> ManageDataSources
        

}

rectangle "Distributed Information Management Layer" as diml  #ffcc88 {
        usecase "Manage Data" as ManageData
    
        DataScientist ---> ManageData
        
        DataAnalyst ---> ManageData
        
        DataEngineer ---> ManageData
        

}

rectangle "Application Management Layer" as aml  #88cccc {
        usecase "Manage Environment" as ManageEnvironment
    
        ITOperations --> ManageEnvironment
        
        StackDeveloper --> ManageEnvironment
        

}

rectangle "Common Physical Layer" as cpl  #cccccc {
        usecase "Manage Data Center" as ManageDataCenter
    
        ITOperations ---> ManageDataCenter
        
    usecase "Manage Infrastructure" as ManageInfrastructure
    
        ITOperations ---> ManageInfrastructure
        

}

rectangle "Service Management Layer" as sml  #88cc88 {
        usecase "Find Resources" as FindResources
    
        ITOperations --> FindResources
        
    usecase "Manage Billing" as ManageBilling
    
        ITOperations --> ManageBilling
        
    usecase "Manage Cost Model" as ManageCostModel
    
        ITOperations --> ManageCostModel
        
    usecase "Manage Multi Cloud" as ManageMultiCloud
    
        ITOperations --> ManageMultiCloud
        
    usecase "Map Assets to Cloud" as MapAssetstoCloud
    
        ITOperations --> MapAssetstoCloud
        
    usecase "Map Services to Resources" as MapServicestoResources
    
        ITOperations --> MapServicestoResources
        

}

rectangle "Service Management Layer" as sml  #88cc88 {
        usecase "Manage Assets" as ManageAssets
    
        ITOperations ---> ManageAssets
        

}

rectangle "Software Defined Infrastructure" as sdi  #cccc88 {
        usecase "Manage Resources" as ManageResources
    
        ITOperations --> ManageResources
        

}

rectangle "Security Aspect" as sa  #cc8888 {
        usecase "Manage Security Profiles" as ManageSecurityProfiles
    
        SecurityEngineer ---> ManageSecurityProfiles
        
    usecase "Apply Security Profiles" as ApplySecurityProfiles
    
        SecurityOperator ---> ApplySecurityProfiles
        

}


@enduml
