@startuml

left to right direction


Actor "Data Analyst" as DataAnalyst


rectangle "Common Data Service" as cds #ffcc88 {
        usecase "Manage Data" as ManageData
    DataAnalyst --> ManageData

}

rectangle "edgemere" as edgemere #ccaaff {
        usecase "Provide Business Information" as ProvideBusinessInformation
    DataAnalyst --> ProvideBusinessInformation

}


@enduml
