@startuml

left to right direction


Actor "Application Developer" as ApplicationDeveloper


rectangle "Application Management Layer" as aml  #lightblue {
        usecase "Manage Applications" as ManageApplications
    ApplicationDeveloper --> ManageApplications
    usecase "Manage Workflows" as ManageWorkflows
    ApplicationDeveloper --> ManageWorkflows

}


@enduml
