@startuml



package "Telemetry Consumer" #cccccc {

    interface "Telemetry Consumer" as i {
            /edgemere/cpl/tc/list()
            /edgemere/cpl/tc/report()
            /edgemere/cpl/tc/show()
    
    }
}

CLI ()-- i
REST ()-- i
Web ()-- i

package "Telemetry Consumer" #cccccc {
    
}



@enduml
