@startuml
left to right direction


state "cpl" as cpl #lightgray {
state "tc" as cpltc #lightgray {
}
}


state cpltc #lightgray {
    state "Custom Function" as tcfunction {
    }
}

        state "cpl" as cpl #lightgray {
state "tc" as cpltc #lightgray {
state "list" as cpltclist #lightgray {
}
}
}


        state "cpl" as cpl #lightgray {
state "tc" as cpltc #lightgray {
state "report" as cpltcreport #lightgray {
}
}
}


        state "cpl" as cpl #lightgray {
state "tc" as cpltc #lightgray {
state "show" as cpltcshow #lightgray {
}
}
}





        state "cpl" as cpl #lightgray {
state "Device" as cpldevice #lightgray {
state "stats" as cpldevicestats #lightgray {
}
}
}

        
    state "ta" as ta #lavender {
state "report" as tareport #lavender {
}
}

    cpldevicestats ---> tareport
  
    state "tc" as tc #lavender {
state "report" as tcreport #lavender {
}
}

    cpldevicestats ---> tcreport
  



@enduml
