@startuml
left to right direction


state "cpl" as cpl #cccccc {
state "tc" as cpltc #cccccc {
}
}


state "cpltc" as pstatename #cccccc {
    state "Custom Function" as tcfunction {
    }
}

        state "cpl" as cpl #cccccc {
state "tc" as cpltc #cccccc {
state "list" as cpltclist #cccccc {
}
}
}


        state "cpl" as cpl #cccccc {
state "tc" as cpltc #cccccc {
state "report" as cpltcreport #cccccc {
}
}
}


        state "cpl" as cpl #cccccc {
state "tc" as cpltc #cccccc {
state "show" as cpltcshow #cccccc {
}
}
}





        state "cpl" as cpl #cccccc {
state "Device" as cpldevice #cccccc {
state "stats" as cpldevicestats #cccccc {
}
}
}

        
    state "ta" as ta #ccaaff {
state "report" as tareport #ccaaff {
}
}

    cpldevicestats ---> tareport
  
    state "tc" as tc #ccaaff {
state "report" as tcreport #ccaaff {
}
}

    cpldevicestats ---> tcreport
  



@enduml
