@startuml



package "Telemetry Consumer" #cccccc {

    interface "Telemetry Consumer" as i {
            ^adevice.stats
            ^device.stats
    
            /edgemere/cpl/tc/list()
            /edgemere/cpl/tc/report()
            /edgemere/cpl/tc/show()
    
    }
}

circle REST
circle Web
circle CLI
circle WebSocket

i -down- Web
i -down- CLI
i -down- REST
WebSocket -left- i: events >

package "Telemetry Consumer" #cccccc {


}



@enduml
