@startuml


usecase "Manage Assets" as ManageAssets #yellow

Actor "IT Operations" as ITOperations

ITOperations --> ManageAssets





usecase "Control Virtual Infrastructure" as ControlVirtualInfrastructure #lightyellow

ManageAssets <-- ControlVirtualInfrastructure : extends







@enduml
