@startuml

left to right direction




node "sml_sc" as sml_scStack #88cc88 {
    portin "parent" as sml_scStackPortIn #blue
}



node "cpl_da" #cccccc {


    hexagon parentnet #black [
            <b><color:white>parent</color></b>
    ]
    
    portin " " as parentnetPortIn #black
    parentnetPortIn -[#black]- parentnet
    
    hexagon childrennet #blue [
            <b><color:white>children</color></b>
    ]
    
    portout " " as childrennetPortOut #blue
    childrennet -[#blue]- childrennetPortOut
    
    hexagon siblingsnet #red [
            <b><color:white>siblings</color></b>
    ]
    

node "datacontroller" as datacontrollerService #white {
    portOut " " as datacontrollerServicesiblingsnet #red
   datacontrollerServicesiblingsnet -[#red]- siblingsnet
   

    artifact "diml_dml_dc_controller" as diml_dml_dc_controllerimage
    
}
node "policyengine" as policyengineService #white {
    portOut " " as policyengineServicesiblingsnet #red
   policyengineServicesiblingsnet -[#red]- siblingsnet
   

    artifact "sa_pe_engine" as sa_pe_engineimage
    
}
node "servicecontroller" as servicecontrollerService #white {
    portOut " " as servicecontrollerServicesiblingsnet #red
   servicecontrollerServicesiblingsnet -[#red]- siblingsnet
   
    collections "sml_sc" as sml_scimage
    
}
node "telemetry_producer" as telemetry_producerService #white {
    portOut " " as telemetry_producerServicesiblingsnet #red
   telemetry_producerServicesiblingsnet -[#red]- siblingsnet
   

    artifact "cpl_tp_producer" as cpl_tp_producerimage
    
}
node "portal" as portalService #white {
    portOut " " as portalServicesiblingsnet #red
   portalServicesiblingsnet -[#red]- siblingsnet
   

    artifact "cpl_da_web" as cpl_da_webimage
    
}

}

sml_scimage --> sml_scStack
    
    childrennetPortOut -[#blue]- sml_scStackPortIn
    

@enduml
