@startuml

left to right direction




entity ailtire_appname_cpl_da_family #black

rectangle "sml_sc" as sml_scStack #lightgreen {
    queue sml_scStacksnet #black [
        <b><color:white>parent</color></b>
    ]
}



package "cpl_da" #lightgray {
    queue childrennet #black [
            <b><color:white>children</color></b>
    ]
    
    childrennet -[#black]- ailtire_appname_cpl_da_family
    
    queue siblingnet #blue [
            <b><color:white>sibling</color></b>
    ]
    


node "frontend" as frontendService {
    
}
node "datacontroller" as datacontrollerService
node "policyengine" as policyengineService
node "servicecontroller" as servicecontrollerService
node "telemetry_producer" as telemetry_producerService
node "portal" as portalService


        artifact "diml_dml_dc_controller:latest" as diml_dml_dc_controllerlatestimage
    
        artifact "sa_pe_engine:latest" as sa_pe_enginelatestimage
            collections "sml_sc:latest" as sml_sclatestimage
    
        artifact "cpl_tp_producer:latest" as cpl_tp_producerlatestimage
    
        artifact "cpl_da_web" as cpl_da_webimage
    
        artifact "traefik:latest" as traefiklatestimage
    
}

external -[#black]- frontendService

datacontrollerService -[#black]- childrennet

policyengineService -[#black]- childrennet

servicecontrollerService -[#black]- childrennet

telemetry_producerService -[#blue]- siblingnet

portalService -[#blue]- siblingnet
datacontrollerService .... diml_dml_dc_controllerlatestimage
policyengineService .... sa_pe_enginelatestimage
servicecontrollerService .... sml_sclatestimage
telemetry_producerService .... cpl_tp_producerlatestimage
portalService .... cpl_da_webimage

frontendService .... traefiklatestimage

sml_sclatestimage --> sml_scStack
    

@enduml
