version: "3.7"
services:
  frontend:
    image: _diml_web
    networks:
      - sibling
  gw:
    image: _diml_gw
    networks:
      children:
        aliases:
          - parent
          - top
      sibling:
        aliases:
          - gateway

networks:
  children:
    driver: overlay
    attachable: true
    name: ${APPNAME}__diml_family
  sibling:
    driver: overlay
  parent:
    external: true
    name: ${APPNAME}__family
