@startuml


boundary _aml_as_family #blue


entity _aml_family #orange


package  "Analytics Services"  #lightblue {
    card children #blue [
        <b><color:white>children</color></b>
    ]
    
    _aml_as_family -[#blue]- children
    
    
    card sibling #red [
        <b><color:white>sibling</color></b>
    ]
    
    
    card parent #orange [
        <b><color:white>parent</color></b>
    ]
    
    
    _aml_family -[#orange]- parent
    
    artifact images #ffffff {
        
        file aml_as_web
        
        file aml_as_gw
        
    }

    node frontend
    frontend .. aml_as_web
    
        sibling -[#red]- frontend
    

    node gw
    gw .. aml_as_gw
    
        children -[#blue]- gw
    
        sibling -[#red]- gw
    




    
}




package aml #lightgray {
    card amlchildren #orange [
        <b><color:white>children</color></b>
    ]
    amlchildren ==[#orange]= parent
}


@enduml
