@startuml
  interface CLI
  interface Web
  interface WebSocket
package "Analytics Services" #lightblue {
  component express as REST
  component socket.io as socket
  folder bin #ffffff {
    component "edgemere/aml/as" as binName
  }
  binName --> REST

  folder deploy #ffffff {
  
    file "node web/server.js" as web_container
    REST --> web_container
    socket ---> web_container
  
    file "node gateway/server.js" as gateway_container
    REST --> gateway_container
    socket ---> gateway_container
  
  }
  folder images #ffffff {
  
      artifact aml_as_web
      web_container --> aml_as_web
    
      artifact aml_as_gw
      gateway_container --> aml_as_gw
    
  }
}
CLI -- binName
Web - REST
WebSocket -- socket

@enduml
