@startuml
left to right direction


state "aml" as aml #88cccc {
state "as" as amlas #88cccc {
}
}


state "amlas" as pstatename #88cccc {
    state "Custom Function" as asfunction {
    }
}





@enduml
