@startuml


package "PhysicalWorld" #aaffff {

}

package "Common Physical Layer" #cccccc {

}


package "PhysicalWorld" #aaffff {

    interface "PhysicalWorld" as i {
            ^data.create
            ^location.create
            ^location.destroy
            ^physicalasset.create
            ^physicalasset.destroy
            ^physicalasset.updated
            ^plc.create
            ^sensor.updated
    
            /edgemere/cpl/pw/asset/control()
            /edgemere/cpl/pw/asset/startmonitoring()
            /edgemere/cpl/pw/asset/stopmonitoring()
            /edgemere/cpl/pw/communicationpathway/transmitdata()
            /edgemere/cpl/pw/data/create()
            /edgemere/cpl/pw/location/getlocationdetails()
            /edgemere/cpl/pw/location/setcoordinates()
            /edgemere/cpl/pw/physicalasset/manage()
            /edgemere/cpl/pw/plc/communicatewithasset()
            /edgemere/cpl/pw/sensor/getreading()
    
    }
}

circle REST
circle Web
circle CLI
circle WebSocket

i -down- Web
i -down- CLI
i -down- REST
WebSocket -left- i: events >

package "PhysicalWorld" #aaffff {


}



@enduml
