@startuml


package "PhysicalWorld" #lightblue {

}

package "Common Physical Layer" #cccccc {

}


package "PhysicalWorld" #lightblue {

    interface "PhysicalWorld" as i {
    
    
    }
}

circle REST
circle Web
circle CLI
circle WebSocket

i -down- Web
i -down- CLI
i -down- REST
WebSocket -left- i: events >

package "PhysicalWorld" #lightblue {


}



@enduml
