@startuml
left to right direction



state "IT Operations" as ITOperations {
    state "Manage Environment" as ITOperationsManageEnvironment {
    }
}
state "sml" as sml #lightgreen {
state "em" as smlem #lightgreen {
state "environment" as smlemenvironment #lightgreen {
state "list" as smlemenvironmentlist #lightgreen {
}
}
}
}

ITOperationsManageEnvironment --> smlemenvironmentlist

state "Stack Developer" as StackDeveloper {
    state "Manage Environment" as StackDeveloperManageEnvironment {
    }
}
state "sml" as sml #lightgreen {
state "em" as smlem #lightgreen {
state "environment" as smlemenvironment #lightgreen {
state "list" as smlemenvironmentlist #lightgreen {
}
}
}
}

StackDeveloperManageEnvironment --> smlemenvironmentlist


    state "IT Operations" as ITOperations {
        state "Manage Environment" as ITOperationsManageEnvironment {
            state "Create Environment" as ITOperationsManageEnvironmentCreateEnvironment {
            }
        }
    }
    state "sml" as sml #lightgreen {
state "emenvironment" as smlemenvironment #lightgreen {
state "create" as smlemenvironmentcreate #lightgreen {
}
}
}

    ITOperationsManageEnvironmentCreateEnvironment --> smlemenvironmentcreate
    
 
    state "IT Operations" as ITOperations {
        state "Manage Environment" as ITOperationsManageEnvironment {
            state "Delete Environment" as ITOperationsManageEnvironmentDeleteEnvironment {
            }
        }
    }
    state "sml" as sml #lightgreen {
state "emenvironment" as smlemenvironment #lightgreen {
state "destroy" as smlemenvironmentdestroy #lightgreen {
}
}
}

    ITOperationsManageEnvironmentDeleteEnvironment --> smlemenvironmentdestroy
    
 
    state "IT Operations" as ITOperations {
        state "Manage Environment" as ITOperationsManageEnvironment {
            state "Disable Environment" as ITOperationsManageEnvironmentDisableEnvironment {
            }
        }
    }
    state "sml" as sml #lightgreen {
state "emenvironment" as smlemenvironment #lightgreen {
state "disable" as smlemenvironmentdisable #lightgreen {
}
}
}

    ITOperationsManageEnvironmentDisableEnvironment --> smlemenvironmentdisable
    
 
    state "IT Operations" as ITOperations {
        state "Manage Environment" as ITOperationsManageEnvironment {
            state "Enable Environment" as ITOperationsManageEnvironmentEnableEnvironment {
            }
        }
    }
    state "sml" as sml #lightgreen {
state "emenvironment" as smlemenvironment #lightgreen {
state "enable" as smlemenvironmentenable #lightgreen {
}
}
}

    ITOperationsManageEnvironmentEnableEnvironment --> smlemenvironmentenable
    
 
    state "IT Operations" as ITOperations {
        state "Manage Environment" as ITOperationsManageEnvironment {
            state "Manage Policies in Environment" as ITOperationsManageEnvironmentManagePoliciesinEnvironment {
            }
        }
    }
    state "sml" as sml #lightgreen {
state "emenvironment" as smlemenvironment #lightgreen {
state "addpolicies" as smlemenvironmentaddpolicies #lightgreen {
}
}
}

    ITOperationsManageEnvironmentManagePoliciesinEnvironment --> smlemenvironmentaddpolicies
    
 
    state "IT Operations" as ITOperations {
        state "Manage Environment" as ITOperationsManageEnvironment {
            state "Update Environment" as ITOperationsManageEnvironmentUpdateEnvironment {
            }
        }
    }
    state "sml" as sml #lightgreen {
state "emenvironment" as smlemenvironment #lightgreen {
state "update" as smlemenvironmentupdate #lightgreen {
}
}
}

    ITOperationsManageEnvironmentUpdateEnvironment --> smlemenvironmentupdate
    
 
 

@enduml
