@startuml


left to right direction

usecase "Manage Infrastructure" as ManageInfrastructure #yellow

Actor "IT Operations" as ITOperations

ITOperations --> ManageInfrastructure



json AddDevice #lightyellow {
    "Given": "IT Operations uses data/source",
    "When": "device/create is actioned with parameters: name - hostad1, file - ./templates/device.yaml",
    "Then": "devices get disabled and enabled through cpl/device/disable and cpl/device/enable commands respectively"
}

ManageInfrastructure <|-- AddDevice

json ManageAggregatedDevices #lightyellow {
    "Given": "IT operations uses data/source",
    "When": "devices are created using template device.yaml",
    "Then": "aggregated device with added devices is created"
}

ManageInfrastructure <|-- ManageAggregatedDevices

json ManageDataCenter #lightyellow {
    "Given": "IT Operations uses a method for managing data sources",
    "When": "various actions are executed to create and modify devices in the data center",
    "Then": "the devices and data center are successfully created and modified according to the parameters given in the actions"
}

ManageInfrastructure <|-- ManageDataCenter

json RemoveDevice #lightyellow {
    "Given": "IT Operations has access to the device management system",
    "When": "A device needs to be removed from the system",
    "Then": "The device is successfully deleted from the system"
}

ManageInfrastructure <|-- RemoveDevice

json UpdateDevice #lightyellow {
    "Given": "IT Operations has access to the device database",
    "When": "The IT operations attempts to update a device",
    "Then": "The device should be successfully updated in the database"
}

ManageInfrastructure <|-- UpdateDevice



usecase "ManagePhysicalInfrastructure" as ManagePhysicalInfrastructure #lightyellow

ManageInfrastructure <-- ManagePhysicalInfrastructure : extends







@enduml
