@startuml


usecase "Manage Infrastructure" as ManageInfrastructure #yellow

Actor "IT Operations" as ITOperations

ITOperations --> ManageInfrastructure



usecase "AddDevice" as AddDevice #lightgrey

ManageInfrastructure --> AddDevice

usecase "ManageAggregatedDevices" as ManageAggregatedDevices #lightgrey

ManageInfrastructure --> ManageAggregatedDevices

usecase "ManageDataCenter" as ManageDataCenter #lightgrey

ManageInfrastructure --> ManageDataCenter

usecase "RemoveDevice" as RemoveDevice #lightgrey

ManageInfrastructure --> RemoveDevice

usecase "UpdateDevice" as UpdateDevice #lightgrey

ManageInfrastructure --> UpdateDevice









@enduml
