@startuml

actor "IT Operations"


entity EventBus

box Common Physical Layer #cccccc
    boundary cpl #white
end box


box Common Physical Layer #cccccc
            participant device
    end box


"IT Operations" -> cpl: Add Device

    cpl -> "device": create (name: hostad1,file: ./templates/device.yaml)

    "device" --/ EventBus: device.create

    cpl -> "common physical layer": disable (name: hostad1)

    "common physical layer" --/ EventBus: device.disable

    cpl -> "common physical layer": enable (name: hostad1)

    "common physical layer" --/ EventBus: device.enable

    cpl -> "common physical layer": disable (name: hostad1)

    "common physical layer" --/ EventBus: device.disable



@enduml
