@startuml

actor "IT Operations"


entity EventBus

box Common Physical Layer #lightgray
    boundary cpl #white
end box


box Common Physical Layer #lightgray
            participant device
            participant aggregateddevice
            participant datacenter
    end box


"IT Operations" -> cpl: Manage Data Center

    cpl -> "device": create (name: hostmdc1,file: ./templates/device.yaml)


    cpl -> "device": create (name: hostmdc2,file: ./templates/device.yaml)


    cpl -> "device": create (name: hostmdc3,file: ./templates/device.yaml)


    cpl -> "device": create (name: hostmdc4,file: ./templates/device.yaml)


    cpl -> "device": create (name: hostmdc5,file: ./templates/device.yaml)


    cpl -> "aggregateddevice": create (name: admdc1)


    cpl -> "aggregateddevice": create (name: admdc2)


    cpl -> "aggregateddevice": adddevices (name: admdc1,items: hostmdc1,hostmdc2)


    cpl -> "aggregateddevice": adddevices (name: admdc2,items: hostmdc3,hostmdc4)


    cpl -> "datacenter": create (name: dcmdc1)


    cpl -> "datacenter": adddevices (name: dcmdc1,items: hostmdc1,hostmdc2)


    cpl -> "datacenter": adddevices (name: dcmdc1,items: admdc2)


    cpl -> "datacenter": disable (name: dcmdc1)


    cpl -> "datacenter": enable (name: dcmdc1)





EventBus --/ cpl : method2()
@enduml
