@startuml


actor "IT Operations"


entity EventBus

box Common Physical Layer #cccccc
    boundary cpl #white
end box


group Given [IT Operations has access to the device management system]

"IT Operations" --/ cpl: A device needs to be removed from the system
"cpl" -> cpl: Remove Device



"IT Operations" /-- cpl: The device is successfully deleted from the system


end

@enduml
