@startuml

actor "IT Operations"


entity EventBus

box Common Physical Layer #lightgray
    boundary cpl #white
end box



"IT Operations" -> cpl: Update Device




EventBus --/ cpl : method2()
@enduml
