@startuml


actor "IT Operations"


entity EventBus

box Common Physical Layer #cccccc
    boundary cpl #white
end box


group Given [IT Operations has access to the device database]

"IT Operations" --/ cpl: The IT operations attempts to update a device
"cpl" -> cpl: Update Device



"IT Operations" /-- cpl: The device should be successfully updated in the database


end

@enduml
