@startuml



package "Blue Print Management" ##aaffff {

    interface "Blue Print Management" as i {
    
    }
}

CLI ()-- i
REST ()-- i
Web ()-- i

package "Blue Print Management" ##aaffff {
    
}



@enduml
