@startuml
  interface CLI
  interface Web
  interface WebSocket
package "Telemetry Aggregator" #cccccc {
  component express as REST
  component socket.io as socket
  folder bin #ffffff {
    component " edgemere cpl ta" as binName
  }
  binName --> REST

  folder deploy #ffffff {
      file "node server.js\ndocker-compose.yml" as cpl_ta_container
      REST --> cpl_ta_container

  
    file "web" as web_container
    REST --> web_container
    socket ---> web_container
  
  }
  folder images #ffffff {
    collections "cpl_ta" as cpl_taimage
    artifact "ailtire:swarm" as ailtireswarm
    cpl_taimage <|-- ailtireswarm
    cpl_ta_container --> cpl_taimage

  
      artifact "cpl_ta_web" as cpl_ta_web
      web_container --> cpl_ta_web
    
  }
}
CLI " edgemere cpl ta" -- binName
Web "/edgemere/cpl/ta" - REST
WebSocket ".edgemere.cpl.ta" -- socket

@enduml
