@startuml
left to right direction


state "sml" as sml #88cc88 {
}


state "sml" as pstatename #88cc88 {
    state "Custom Function" as smlfunction {
    }
}

        state "sml" as sml #88cc88 {
state "cloud" as smlcloud #88cc88 {
state "list" as smlcloudlist #88cc88 {
}
}
}


        state "sml" as sml #88cc88 {
state "data" as smldata #88cc88 {
state "govern" as smldatagovern #88cc88 {
}
}
}


        state "sml" as sml #88cc88 {
state "data" as smldata #88cc88 {
state "source" as smldatasource #88cc88 {
state "name" as smldatasourcename #88cc88 {
}
}
}
}


        state "sml" as sml #88cc88 {
state "environmenet" as smlenvironmenet #88cc88 {
state "addpolicies" as smlenvironmenetaddpolicies #88cc88 {
}
}
}


        state "sml" as sml #88cc88 {
state "environment" as smlenvironment #88cc88 {
state "create" as smlenvironmentcreate #88cc88 {
}
}
}


        state "sml" as sml #88cc88 {
state "environment" as smlenvironment #88cc88 {
state "destroy" as smlenvironmentdestroy #88cc88 {
}
}
}


        state "sml" as sml #88cc88 {
state "environment" as smlenvironment #88cc88 {
state "disable" as smlenvironmentdisable #88cc88 {
}
}
}


        state "sml" as sml #88cc88 {
state "environment" as smlenvironment #88cc88 {
state "enable" as smlenvironmentenable #88cc88 {
}
}
}


        state "sml" as sml #88cc88 {
state "environment" as smlenvironment #88cc88 {
state "list" as smlenvironmentlist #88cc88 {
}
}
}


        state "sml" as sml #88cc88 {
state "environment" as smlenvironment #88cc88 {
state "update" as smlenvironmentupdate #88cc88 {
}
}
}


        state "sml" as sml #88cc88 {
state "multicloud" as smlmulticloud #88cc88 {
state "addclouds" as smlmulticloudaddclouds #88cc88 {
}
}
}


        state "sml" as sml #88cc88 {
state "multicloud" as smlmulticloud #88cc88 {
state "addpolicies" as smlmulticloudaddpolicies #88cc88 {
}
}
}


        state "sml" as sml #88cc88 {
state "multicloud" as smlmulticloud #88cc88 {
state "list" as smlmulticloudlist #88cc88 {
}
}
}


        state "sml" as sml #88cc88 {
state "multicloud" as smlmulticloud #88cc88 {
state "removepolicies" as smlmulticloudremovepolicies #88cc88 {
}
}
}


        state "sml" as sml #88cc88 {
state "service" as smlservice #88cc88 {
state "list" as smlservicelist #88cc88 {
}
}
}


        state "sml" as sml #88cc88 {
state "stack" as smlstack #88cc88 {
state "list" as smlstacklist #88cc88 {
}
}
}





    state "sml" as sml #88cc88 {
state "Service" as smlservice #88cc88 {
state "started" as smlservicestarted #88cc88 {
}
}
}

    state "da" as da #lavender {
state "service" as daservice #lavender {
state "register" as daserviceregister #lavender {
}
}
}

        smlservicestarted ---> daserviceregister
       

@enduml
