@startuml
left to right direction


    package "edgemere" as edgemere {
package "sml" as edgemeresml #88cc88 {
 component "cloud" as edgemeresmlcloud
 interface "list" as edgemeresmlcloudlist
edgemeresmlcloud -- edgemeresmlcloudlist
}
}

    
    package "edgemere" as edgemere {
package "sml" as edgemeresml #88cc88 {
 component "data" as edgemeresmldata
 interface "create" as edgemeresmldatacreate
edgemeresmldata -- edgemeresmldatacreate
}
}

    
    package "edgemere" as edgemere {
package "sml" as edgemeresml #88cc88 {
 component "data" as edgemeresmldata
 interface "govern" as edgemeresmldatagovern
edgemeresmldata -- edgemeresmldatagovern
}
}

    
    package "edgemere" as edgemere {
package "sml" as edgemeresml #88cc88 {
package "data" as edgemeresmldata {
 component "source" as edgemeresmldatasource
 interface "name" as edgemeresmldatasourcename
edgemeresmldatasource -- edgemeresmldatasourcename
}
}
}

    
    package "edgemere" as edgemere {
package "sml" as edgemeresml #88cc88 {
 component "environmenet" as edgemeresmlenvironmenet
 interface "addpolicies" as edgemeresmlenvironmenetaddpolicies
edgemeresmlenvironmenet -- edgemeresmlenvironmenetaddpolicies
}
}

    
    package "edgemere" as edgemere {
package "sml" as edgemeresml #88cc88 {
 component "environment" as edgemeresmlenvironment
 interface "create" as edgemeresmlenvironmentcreate
edgemeresmlenvironment -- edgemeresmlenvironmentcreate
}
}

    
    package "edgemere" as edgemere {
package "sml" as edgemeresml #88cc88 {
 component "environment" as edgemeresmlenvironment
 interface "destroy" as edgemeresmlenvironmentdestroy
edgemeresmlenvironment -- edgemeresmlenvironmentdestroy
}
}

    
    package "edgemere" as edgemere {
package "sml" as edgemeresml #88cc88 {
 component "environment" as edgemeresmlenvironment
 interface "disable" as edgemeresmlenvironmentdisable
edgemeresmlenvironment -- edgemeresmlenvironmentdisable
}
}

    
    package "edgemere" as edgemere {
package "sml" as edgemeresml #88cc88 {
 component "environment" as edgemeresmlenvironment
 interface "enable" as edgemeresmlenvironmentenable
edgemeresmlenvironment -- edgemeresmlenvironmentenable
}
}

    
    package "edgemere" as edgemere {
package "sml" as edgemeresml #88cc88 {
 component "environment" as edgemeresmlenvironment
 interface "list" as edgemeresmlenvironmentlist
edgemeresmlenvironment -- edgemeresmlenvironmentlist
}
}

    
    package "edgemere" as edgemere {
package "sml" as edgemeresml #88cc88 {
 component "environment" as edgemeresmlenvironment
 interface "update" as edgemeresmlenvironmentupdate
edgemeresmlenvironment -- edgemeresmlenvironmentupdate
}
}

    
    package "edgemere" as edgemere {
package "sml" as edgemeresml #88cc88 {
 component "multicloud" as edgemeresmlmulticloud
 interface "addclouds" as edgemeresmlmulticloudaddclouds
edgemeresmlmulticloud -- edgemeresmlmulticloudaddclouds
}
}

    
    package "edgemere" as edgemere {
package "sml" as edgemeresml #88cc88 {
 component "multicloud" as edgemeresmlmulticloud
 interface "addpolicies" as edgemeresmlmulticloudaddpolicies
edgemeresmlmulticloud -- edgemeresmlmulticloudaddpolicies
}
}

    
    package "edgemere" as edgemere {
package "sml" as edgemeresml #88cc88 {
 component "multicloud" as edgemeresmlmulticloud
 interface "list" as edgemeresmlmulticloudlist
edgemeresmlmulticloud -- edgemeresmlmulticloudlist
}
}

    
    package "edgemere" as edgemere {
package "sml" as edgemeresml #88cc88 {
 component "multicloud" as edgemeresmlmulticloud
 interface "removepolicies" as edgemeresmlmulticloudremovepolicies
edgemeresmlmulticloud -- edgemeresmlmulticloudremovepolicies
}
}

    
    package "edgemere" as edgemere {
package "sml" as edgemeresml #88cc88 {
 component "service" as edgemeresmlservice
 interface "list" as edgemeresmlservicelist
edgemeresmlservice -- edgemeresmlservicelist
}
}

    
    package "edgemere" as edgemere {
package "sml" as edgemeresml #88cc88 {
 component "stack" as edgemeresmlstack
 interface "list" as edgemeresmlstacklist
edgemeresmlstack -- edgemeresmlstacklist
}
}

    

        rectangle "Manage Environment" as ManageEnvironment #ffffaa {
            ("Create Environment")/ as ITOperationsManageEnvironmentCreateEnvironment
        }
    
    edgemeresmlenvironmentcreate <-- ITOperationsManageEnvironmentCreateEnvironment
    
        rectangle "Manage Environment" as ManageEnvironment #ffffaa {
            ("Delete Environment")/ as ITOperationsManageEnvironmentDeleteEnvironment
        }
    
    edgemeresmlenvironmentdestroy <-- ITOperationsManageEnvironmentDeleteEnvironment
    
        rectangle "Manage Environment" as ManageEnvironment #ffffaa {
            ("Disable Environment")/ as ITOperationsManageEnvironmentDisableEnvironment
        }
    
    edgemeresmlenvironmentdisable <-- ITOperationsManageEnvironmentDisableEnvironment
    
        rectangle "Manage Environment" as ManageEnvironment #ffffaa {
            ("Enable Environment")/ as ITOperationsManageEnvironmentEnableEnvironment
        }
    
    edgemeresmlenvironmentenable <-- ITOperationsManageEnvironmentEnableEnvironment
    
        rectangle "Manage Environment" as ManageEnvironment #ffffaa {
            ("Update Environment")/ as ITOperationsManageEnvironmentUpdateEnvironment
        }
    
    edgemeresmlenvironmentupdate <-- ITOperationsManageEnvironmentUpdateEnvironment
    


        rectangle "Manage Applications" as ManageApplications #ffffaa {
            ("Build Application")/ as DevOpsEngineerManageApplicationsBuildApplication
        }
    
    edgemeresmldatacreate <-- DevOpsEngineerManageApplicationsBuildApplication
    


        rectangle "Change Physical World" as ChangePhysicalWorld #ffffaa {
            ("Adjust Temperature")/ as ActorChangePhysicalWorldAdjustTemperature
        }
    
    edgemeresmldatacreate <-- ActorChangePhysicalWorldAdjustTemperature
    
        rectangle "Change Physical World" as ChangePhysicalWorld #ffffaa {
            ("Toogle Switch")/ as ActorChangePhysicalWorldtoggleSwitch
        }
    
    edgemeresmldatacreate <-- ActorChangePhysicalWorldtoggleSwitch
    


        rectangle "Connect Physical Asset to a Device" as ConnectPhysicalAssettoaDevice #ffffaa {
            ("Asset Digital Device Connectivity")/ as ActorConnectPhysicalAssettoaDeviceAssetDigitalDeviceConnectivity
        }
    
    edgemeresmldatacreate <-- ActorConnectPhysicalAssettoaDeviceAssetDigitalDeviceConnectivity
    



        rectangle "Monitor Physical World" as MonitorPhysicalWorld #ffffaa {
            ("Continuous Monitoring")/ as ActorMonitorPhysicalWorldContinuousMonitoring
        }
    
    edgemeresmldatacreate <-- ActorMonitorPhysicalWorldContinuousMonitoring
    






        rectangle "Manage Data" as ManageData #ffffaa {
            ("Destroy Data")/ as DataStewardManageDataDestroyData
        }
    
    edgemeresmldatasourcename <-- DataStewardManageDataDestroyData
    
        rectangle "Manage Data" as ManageData #ffffaa {
            ("Egress Data")/ as DataStewardManageDataEgressData
        }
    
    edgemeresmldatasourcename <-- DataStewardManageDataEgressData
    
        rectangle "Manage Data" as ManageData #ffffaa {
            ("Ingest Data")/ as DataStewardManageDataIngestData
        }
    
    edgemeresmldatasourcename <-- DataStewardManageDataIngestData
    





        rectangle "Manage Meta Data" as ManageMetaData #ffffaa {
            ("Capture Meta Data")/ as DataEngineerManageMetaDataCaptureMetaData
        }
    
    edgemeresmldatacreate <-- DataEngineerManageMetaDataCaptureMetaData
    
        rectangle "Manage Meta Data" as ManageMetaData #ffffaa {
            ("Capture Meta Data")/ as DataStewardManageMetaDataCaptureMetaData
        }
    
    edgemeresmldatacreate <-- DataStewardManageMetaDataCaptureMetaData
    











        rectangle "Manage Multi Cloud" as ManageMultiCloud #ffffaa {
            ("Add Cloud to Multi Cloud")/ as ITOperationsManageMultiCloudAddCloudtoMultiCloud
        }
    
    edgemeresmlmulticloudaddclouds <-- ITOperationsManageMultiCloudAddCloudtoMultiCloud
    
        rectangle "Manage Multi Cloud" as ManageMultiCloud #ffffaa {
            ("Manage Policies for Multi Cloud")/ as ITOperationsManageMultiCloudManagePoliciesforMultiCloud
        }
    
    edgemeresmlmulticloudaddpolicies <-- ITOperationsManageMultiCloudManagePoliciesforMultiCloud
    
        rectangle "Manage Multi Cloud" as ManageMultiCloud #ffffaa {
            ("Remove Cloud From Multi Cloud")/ as ITOperationsManageMultiCloudRemoveCloudfromMultiCloud
        }
    
    edgemeresmlmulticloudremovepolicies <-- ITOperationsManageMultiCloudRemoveCloudfromMultiCloud
    



        rectangle "Manage Stacks" as ManageStacks #ffffaa {
            ("Build Stack")/ as DevOpsEngineerManageStacksBuildStack
        }
    
    edgemeresmldatacreate <-- DevOpsEngineerManageStacksBuildStack
    
        rectangle "Manage Stacks" as ManageStacks #ffffaa {
            ("Create Application Stack")/ as ApplicationDeveloperManageStacksCreateApplicationStack
        }
    
    edgemeresmldatacreate <-- ApplicationDeveloperManageStacksCreateApplicationStack
    
        rectangle "Manage Stacks" as ManageStacks #ffffaa {
            ("Create Application Stack")/ as StackDeveloperManageStacksCreateApplicationStack
        }
    
    edgemeresmldatacreate <-- StackDeveloperManageStacksCreateApplicationStack
    
        rectangle "Manage Stacks" as ManageStacks #ffffaa {
            ("Create Service Stack")/ as StackDeveloperManageStacksCreateServiceStack
        }
    
    edgemeresmldatacreate <-- StackDeveloperManageStacksCreateServiceStack
    
        rectangle "Manage Stacks" as ManageStacks #ffffaa {
            ("Modify Application Stack")/ as StackDeveloperManageStacksModifyApplicationStack
        }
    
    edgemeresmldatacreate <-- StackDeveloperManageStacksModifyApplicationStack
    
        rectangle "Manage Stacks" as ManageStacks #ffffaa {
            ("Modify Application Stack")/ as ApplicationDeveloperManageStacksModifyApplicationStack
        }
    
    edgemeresmldatacreate <-- ApplicationDeveloperManageStacksModifyApplicationStack
    
        rectangle "Manage Stacks" as ManageStacks #ffffaa {
            ("Modify Service Stack")/ as StackDeveloperManageStacksModifyServiceStack
        }
    
    edgemeresmldatacreate <-- StackDeveloperManageStacksModifyServiceStack
    
        rectangle "Manage Stacks" as ManageStacks #ffffaa {
            ("Test Application Stack")/ as StackDeveloperManageStacksTestApplicationStack
        }
    
    edgemeresmldatacreate <-- StackDeveloperManageStacksTestApplicationStack
    
        rectangle "Manage Stacks" as ManageStacks #ffffaa {
            ("Test Application Stack")/ as ApplicationDeveloperManageStacksTestApplicationStack
        }
    
    edgemeresmldatacreate <-- ApplicationDeveloperManageStacksTestApplicationStack
    
        rectangle "Manage Stacks" as ManageStacks #ffffaa {
            ("Test Service Stack")/ as StackDeveloperManageStacksTestServiceStack
        }
    
    edgemeresmldatacreate <-- StackDeveloperManageStacksTestServiceStack
    
        rectangle "Manage Stacks" as ManageStacks #ffffaa {
            ("Version Application Stack")/ as ApplicationDeveloperManageStacksVersionApplicationStack
        }
    
    edgemeresmldatacreate <-- ApplicationDeveloperManageStacksVersionApplicationStack
    
        rectangle "Manage Stacks" as ManageStacks #ffffaa {
            ("Version Service Stack")/ as StackDeveloperManageStacksVersionServiceStack
        }
    
    edgemeresmldatacreate <-- StackDeveloperManageStacksVersionServiceStack
    



        rectangle "Manage Services" as ManageServices #ffffaa {
            ("Build Service")/ as StackDeveloperManageServicesBuildService
        }
    
    edgemeresmldatacreate <-- StackDeveloperManageServicesBuildService
    








@enduml
