@startuml


package "Software Defined Infrastructure" #lightyellow {

}

package "Distributed Information Management Layer" #ffcc88 {

}

package "Security Aspect" #pink {

}

package "Service Management Layer" #lightgreen {

}

package "Data Management Layer" #ffcc88 {

}

package "Application Management Layer" #lightblue {

}


package "Service Management Layer" #lightgreen {

    interface "Service Management Layer" as i {
            /edgemere/sml/cloud/list()
            /edgemere/sml/data/govern()
            /edgemere/sml/data/source/name()
            /edgemere/sml/environmenet/addpolicies()
            /edgemere/sml/environment/create()
            /edgemere/sml/environment/destroy()
            /edgemere/sml/environment/disable()
            /edgemere/sml/environment/enable()
            /edgemere/sml/environment/list()
            /edgemere/sml/environment/update()
            /edgemere/sml/multicloud/addclouds()
            /edgemere/sml/multicloud/addpolicies()
            /edgemere/sml/multicloud/list()
            /edgemere/sml/multicloud/removepolicies()
            /edgemere/sml/service/list()
            /edgemere/sml/stack/list()
    
    }
}

CLI ()-- i
REST ()-- i
Web ()-- i

package "Service Management Layer" #lightgreen {


rectangle "Cloud Broker" #white {
}

rectangle "Environment Management" #white {
}

rectangle "Provision Engine" #white {
}

rectangle "Service Controller" #white {
}

rectangle "Service Orchestrator" #white {
}

rectangle "Service Repository" #white {
}

    "Environment Management" --> "Service Orchestrator"
    
    "Provision Engine" --> "Software Defined Infrastructure"
    
    "Service Controller" --> "Provision Engine"
    
    "Service Orchestrator" --> "Service Controller"
    
    "Service Orchestrator" --> "Service Repository"
    
    "Service Orchestrator" --> "Data Orchestrator"
    
    "Service Orchestrator" --> "Infrastructure Orchestrator"
    
}


    "Service Management Layer" --> "Software Defined Infrastructure"

    "Service Management Layer" --> "Distributed Information Management Layer"


@enduml
