@startuml

left to right direction
Actor "IT Operations" as ITOperations
Actor "Stack Developer" as StackDeveloper
Actor "Application Developer" as ApplicationDeveloper


rectangle "Service Management Layer" #88cc88 {
usecase "ManageClouds" as ManageClouds
    ITOperations --> ManageClouds
    usecase "ManageServices" as ManageServices
    StackDeveloper --> ManageServices
    ApplicationDeveloper --> ManageServices
    }


@enduml
