@startuml
left to right direction


state "cpl" as cpl #cccccc {
state "c" as cplc #aaffff {
}
}


state "cplc" as pstatename #aaffff {
    state "Custom Function" as cfunction {
    }
}





@enduml
