@startuml



package "Cyber" #lightblue {

    interface "Cyber" as i {
    
    
    }
}

circle REST
circle Web
circle CLI
circle WebSocket

i -down- Web
i -down- CLI
i -down- REST
WebSocket -left- i: events >

package "Cyber" #lightblue {


}



@enduml
