@startuml



package "Data Controller" ##aaffff {

    interface "Data Controller" as i {
    
    
    }
}

circle REST
circle Web
circle CLI
circle WebSocket

i -down- Web
i -down- CLI
i -down- REST
WebSocket -left- i: events >

package "Data Controller" ##aaffff {


}



@enduml
