@startuml

actor "IT Operations"


entity EventBus

box Common Physical Layer #lightgray
    boundary cpl #white
end box


box Common Physical Layer #lightgray
            participant device
            participant aggregateddevice
            participant datacenter
    end box


"IT Operations" -> cpl: Remove Data Center

    cpl -> "device": create (name: host1,file: ./templates/device.yaml)


    cpl -> "device": create (name: host2,file: ./templates/device.yaml)


    cpl -> "device": create (name: host3,file: ./templates/device.yaml)


    cpl -> "device": create (name: host4,file: ./templates/device.yaml)


    cpl -> "device": create (name: host5,file: ./templates/device.yaml)


    cpl -> "aggregateddevice": create (name: ad1)


    cpl -> "aggregateddevice": adddevices (name: ad2,items: host3,host4)


    cpl -> "datacenter": create (name: dc1)


    cpl -> "datacenter": adddevices (name: dc1,items: host1,host2)


    cpl -> "datacenter": adddevices (name: dc1,items: ad1)


    cpl -> "datacenter": destroy (name: dc1)





EventBus --/ cpl : method2()
@enduml
