@startuml

left to right direction


boundary ailtire_appname_diml_dml_family #red


entity ailtire_appname_diml_dml_do_family #black




package "diml_dml_do" #lightblue {
    queue childrennet #black [
            <b><color:white>children</color></b>
    ]
    
    childrennet -[#black]- ailtire_appname_diml_dml_do_family
    
    queue siblingnet #blue [
            <b><color:white>sibling</color></b>
    ]
    
    queue parentnet #red [
            <b><color:white>parent</color></b>
    ]
    
    parentnet -[#red]- ailtire_appname_diml_dml_family
    

node "frontend" as frontendService
node "gw" as gwService


        artifact "diml_dml_do_web" as diml_dml_do_webimage
    
        artifact "diml_dml_do_gw" as diml_dml_do_gwimage
    
}

frontendService -[#blue]- siblingnet

gwService -[#black]- childrennet

gwService -[#blue]- siblingnet
frontendService .... diml_dml_do_webimage
gwService .... diml_dml_do_gwimage


@enduml
