@startuml



state DataReservation #lightblue {

    state Init #lightblue {
    }

    state Created #lightblue {
    }

    state Confirmed #lightblue {
    }

    state Rejected #lightblue {
    }

}


Init --> Created : create

Init --> Confirmed : confirm

Init --> Rejected : free

Created --> Confirmed : confirm

Created --> Rejected : free




@enduml
