@startuml

left to right direction




node "diml_dml_do" as diml_dml_doStack ##aaffff {
    portin "parent" as diml_dml_doStackPortIn #blue
}
node "sa_pe" as sa_peStack #cc8888 {
    portin "parent" as sa_peStackPortIn #blue
}
node "sml_so" as sml_soStack #88cc88 {
    portin "parent" as sml_soStackPortIn #blue
}
node "cpl_ta" as cpl_taStack #cccccc {
    portin "parent" as cpl_taStackPortIn #blue
}



node "cpl_dm" #cccccc {


    hexagon parentnet #black [
            <b><color:white>parent</color></b>
    ]
    
    portin " " as parentnetPortIn #black
    parentnetPortIn -[#black]- parentnet
    
    hexagon childrennet #blue [
            <b><color:white>children</color></b>
    ]
    
    portout " " as childrennetPortOut #blue
    childrennet -[#blue]- childrennetPortOut
    
    hexagon siblingsnet #red [
            <b><color:white>siblings</color></b>
    ]
    

node "data_orchestrator" as data_orchestratorService #white {
    portOut " " as data_orchestratorServicesiblingsnet #red
   data_orchestratorServicesiblingsnet -[#red]- siblingsnet
   
    collections "diml_dml_do" as diml_dml_doimage
    
}
node "policy_engine" as policy_engineService #white {
    portOut " " as policy_engineServicesiblingsnet #red
   policy_engineServicesiblingsnet -[#red]- siblingsnet
   
    collections "sa_pe" as sa_peimage
    
}
node "service_orchestrator" as service_orchestratorService #white {
    portOut " " as service_orchestratorServicesiblingsnet #red
   service_orchestratorServicesiblingsnet -[#red]- siblingsnet
   
    collections "sml_so" as sml_soimage
    
}
node "telemetry_aggregator" as telemetry_aggregatorService #white {
    portOut " " as telemetry_aggregatorServicesiblingsnet #red
   telemetry_aggregatorServicesiblingsnet -[#red]- siblingsnet
   
    collections "cpl_ta" as cpl_taimage
    
}
node "portal" as portalService #white {
    portOut " " as portalServicesiblingsnet #red
   portalServicesiblingsnet -[#red]- siblingsnet
   

    artifact "cpl_dm_web" as cpl_dm_webimage
    
}

}

diml_dml_doimage --> diml_dml_doStack
    
    childrennetPortOut -[#blue]- diml_dml_doStackPortIn
    
sa_peimage --> sa_peStack
    
    childrennetPortOut -[#blue]- sa_peStackPortIn
    
sml_soimage --> sml_soStack
    
    childrennetPortOut -[#blue]- sml_soStackPortIn
    
cpl_taimage --> cpl_taStack
    
    childrennetPortOut -[#blue]- cpl_taStackPortIn
    

@enduml
