@startuml



package "Ingress Services" #lightblue {

    interface "Ingress Services" as i {
    
    }
}

CLI ()-- i
REST ()-- i
Web ()-- i

package "Ingress Services" #lightblue {
    
}



@enduml
