@startuml


boundary _diml_ddf_family #blue


entity _diml_family #orange


package  "Data Definition Framework"  #lightblue {
    card children #blue [
        <b><color:white>children</color></b>
    ]
    
    _diml_ddf_family -[#blue]- children
    
    
    card sibling #red [
        <b><color:white>sibling</color></b>
    ]
    
    
    card parent #orange [
        <b><color:white>parent</color></b>
    ]
    
    
    _diml_family -[#orange]- parent
    
    artifact images #ffffff {
        
        file diml_ddf_web
        
        file diml_ddf_gw
        
    }

    node frontend
    frontend .. diml_ddf_web
    
        sibling -[#red]- frontend
    

    node gw
    gw .. diml_ddf_gw
    
        children -[#blue]- gw
    
        sibling -[#red]- gw
    




    
}


package  "bpm"  #lightgray {
    card bpmparent #blue [
        <b><color:white>parent</color></b>
    ]
    bpmparent ==[#blue]= children
}


package  "daf"  #lightgray {
    card dafparent #blue [
        <b><color:white>parent</color></b>
    ]
    dafparent ==[#blue]= children
}


package  "df"  #lightgray {
    card dfparent #blue [
        <b><color:white>parent</color></b>
    ]
    dfparent ==[#blue]= children
}


package  "dr"  #lightgray {
    card drparent #blue [
        <b><color:white>parent</color></b>
    ]
    drparent ==[#blue]= children
}




package diml #lightgray {
    card dimlchildren #orange [
        <b><color:white>children</color></b>
    ]
    dimlchildren ==[#orange]= parent
}


@enduml
