@startuml
Actor "Actor" as Actor
Participant "Distributed Infromation Management Layer" as DIML #ffcc88
Participant "Data Definition Framework" as DDF #ffcc88
Participant "Data Management Layer" as DML #ffcc88
Actor --> DIML : Add Data Adaptor (dataadaptor-filesystem.yaml)
DIML --> DDF : dataadaptor create(name, parameters)
Actor --> DIML : Add Data Flow(dataflow-filesystem.yaml)
DIML --> DDF : dataflow create(name:'filesystem', file: 'dataflow-filesystem.yaml')
Actor --> DIML : Add Blue Print
DIML --> DDF : datablueprint create(name: 'myFileSystem', file: 'datablueprintfilesystem.yaml')
DDF --> DDF : datablueprint addflow(name, dataflow, parameters)
DDF --> DDF : datablueprint addadaptor(name, adapator, parameters)

Actor --> DIML : Add Data Source
DIML --> DML : datasource create(name)
Actor --> DML : datasource addblueprint(name, blueprint)
DML --> DML : datasource activateBlueprint(name)
DML --> DML : data create(name, adaptor, metadata)

@enduml
