@startuml
left to right direction


state "diml" as diml #ffcc88 {
state "ddf" as dimlddf #ffcc88 {
}
}


state "dimlddf" as pstatename #ffcc88 {
    state "Custom Function" as ddffunction {
    }
}

        state "diml" as diml #ffcc88 {
state "ddf" as dimlddf #ffcc88 {
state "data" as dimlddfdata #ffcc88 {
state "create" as dimlddfdatacreate #ffcc88 {
}
}
}
}


        state "diml" as diml #ffcc88 {
state "ddf" as dimlddf #ffcc88 {
state "data" as dimlddfdata #ffcc88 {
state "govern" as dimlddfdatagovern #ffcc88 {
}
}
}
}


        state "diml" as diml #ffcc88 {
state "ddf" as dimlddf #ffcc88 {
state "data" as dimlddfdata #ffcc88 {
state "source" as dimlddfdatasource #ffcc88 {
state "name" as dimlddfdatasourcename #ffcc88 {
}
}
}
}
}


        state "diml" as diml #ffcc88 {
state "ddf" as dimlddf #ffcc88 {
state "datablueprint" as dimlddfdatablueprint #ffcc88 {
state "deploy" as dimlddfdatablueprintdeploy #ffcc88 {
}
}
}
}


        state "diml" as diml #ffcc88 {
state "ddf" as dimlddf #ffcc88 {
state "datablueprint" as dimlddfdatablueprint #ffcc88 {
state "list" as dimlddfdatablueprintlist #ffcc88 {
}
}
}
}


        state "diml" as diml #ffcc88 {
state "ddf" as dimlddf #ffcc88 {
state "datacatalog" as dimlddfdatacatalog #ffcc88 {
state "list" as dimlddfdatacataloglist #ffcc88 {
}
}
}
}


        state "diml" as diml #ffcc88 {
state "ddf" as dimlddf #ffcc88 {
state "datadaptor" as dimlddfdatadaptor #ffcc88 {
state "list" as dimlddfdatadaptorlist #ffcc88 {
}
}
}
}


        state "diml" as diml #ffcc88 {
state "ddf" as dimlddf #ffcc88 {
state "datapipeline" as dimlddfdatapipeline #ffcc88 {
state "list" as dimlddfdatapipelinelist #ffcc88 {
}
}
}
}


        state "diml" as diml #ffcc88 {
state "ddf" as dimlddf #ffcc88 {
state "dataprocedure" as dimlddfdataprocedure #ffcc88 {
state "list" as dimlddfdataprocedurelist #ffcc88 {
}
}
}
}


        state "diml" as diml #ffcc88 {
state "ddf" as dimlddf #ffcc88 {
state "datasource" as dimlddfdatasource #ffcc88 {
state "simulate" as dimlddfdatasourcesimulate #ffcc88 {
}
}
}
}


        state "diml" as diml #ffcc88 {
state "ddf" as dimlddf #ffcc88 {
state "metadata" as dimlddfmetadata #ffcc88 {
state "list" as dimlddfmetadatalist #ffcc88 {
}
}
}
}






@enduml
