@startuml
left to right direction



state "Data Engineer" as DataEngineer {
    state "Manage Data Adaptors" as DataEngineerManageDataAdaptors {
    }
}
state "edgemere" as edgemere #ffcc88 {
state "diml" as edgemerediml #ffcc88 {
state "ddf" as edgemeredimlddf #ffcc88 {
state "datadaptor" as edgemeredimlddfdatadaptor #ffcc88 {
state "list" as edgemeredimlddfdatadaptorlist #ffcc88 {
}
}
}
}
}

DataEngineerManageDataAdaptors --> edgemeredimlddfdatadaptorlist

state "Data Scientist" as DataScientist {
    state "Manage Data Adaptors" as DataScientistManageDataAdaptors {
    }
}
state "edgemere" as edgemere #ffcc88 {
state "diml" as edgemerediml #ffcc88 {
state "ddf" as edgemeredimlddf #ffcc88 {
state "datadaptor" as edgemeredimlddfdatadaptor #ffcc88 {
state "list" as edgemeredimlddfdatadaptorlist #ffcc88 {
}
}
}
}
}

DataScientistManageDataAdaptors --> edgemeredimlddfdatadaptorlist


    state "Data Scientist" as DataScientist {
        state "Manage Data Adaptors" as DataScientistManageDataAdaptors {
            state "Attach Data Blue Print" as DataScientistManageDataAdaptorsAttachDataBluePrint {
            }
        }
    }
    
    DataScientistManageDataAdaptorsAttachDataBluePrint --> Null
    
 
    state "Data Engineer" as DataEngineer {
        state "Manage Data Adaptors" as DataEngineerManageDataAdaptors {
            state "Create Data Adaptor" as DataEngineerManageDataAdaptorsCreateDataAdaptor {
            }
        }
    }
    
    DataEngineerManageDataAdaptorsCreateDataAdaptor --> Null
    
 
    state "DataEngineer" as DataEngineer {
        state "Manage Data Adaptors" as DataEngineerManageDataAdaptors {
            state "Update Data Adaptor" as DataEngineerManageDataAdaptorsUpdateDataAdaptor {
            }
        }
    }
    
    DataEngineerManageDataAdaptorsUpdateDataAdaptor --> Null
    
 
 
state "Data Engineer" as DataEngineer {
    state "Manage Data Blue Prints" as DataEngineerManageDataBluePrints {
    }
}
state "edgemere" as edgemere #ffcc88 {
state "diml" as edgemerediml #ffcc88 {
state "ddf" as edgemeredimlddf #ffcc88 {
state "datablueprint" as edgemeredimlddfdatablueprint #ffcc88 {
state "list" as edgemeredimlddfdatablueprintlist #ffcc88 {
}
}
}
}
}

DataEngineerManageDataBluePrints --> edgemeredimlddfdatablueprintlist

state "Data Scientist" as DataScientist {
    state "Manage Data Blue Prints" as DataScientistManageDataBluePrints {
    }
}
state "edgemere" as edgemere #ffcc88 {
state "diml" as edgemerediml #ffcc88 {
state "ddf" as edgemeredimlddf #ffcc88 {
state "datablueprint" as edgemeredimlddfdatablueprint #ffcc88 {
state "list" as edgemeredimlddfdatablueprintlist #ffcc88 {
}
}
}
}
}

DataScientistManageDataBluePrints --> edgemeredimlddfdatablueprintlist


    state "DataScientist" as DataScientist {
        state "Manage Data Blue Prints" as DataScientistManageDataBluePrints {
            state "Create Blue Print" as DataScientistManageDataBluePrintsCreateBluePrint {
            }
        }
    }
    
    DataScientistManageDataBluePrintsCreateBluePrint --> Null
    
 
 
state "Data Engineer" as DataEngineer {
    state "Manage Data Pipeline" as DataEngineerManageDataPipeline {
    }
}
state "edgemere" as edgemere #ffcc88 {
state "diml" as edgemerediml #ffcc88 {
state "ddf" as edgemeredimlddf #ffcc88 {
state "datapipeline" as edgemeredimlddfdatapipeline #ffcc88 {
state "list" as edgemeredimlddfdatapipelinelist #ffcc88 {
}
}
}
}
}

DataEngineerManageDataPipeline --> edgemeredimlddfdatapipelinelist


 
state "Data Engineer" as DataEngineer {
    state "Manage Data Procedures" as DataEngineerManageDataProcedures {
    }
}
state "edgemere" as edgemere #ffcc88 {
state "diml" as edgemerediml #ffcc88 {
state "ddf" as edgemeredimlddf #ffcc88 {
state "dataprocedure" as edgemeredimlddfdataprocedure #ffcc88 {
state "list" as edgemeredimlddfdataprocedurelist #ffcc88 {
}
}
}
}
}

DataEngineerManageDataProcedures --> edgemeredimlddfdataprocedurelist

state "Chief Data Officer" as ChiefDataOfficer {
    state "Manage Data Procedures" as ChiefDataOfficerManageDataProcedures {
    }
}
state "edgemere" as edgemere #ffcc88 {
state "diml" as edgemerediml #ffcc88 {
state "ddf" as edgemeredimlddf #ffcc88 {
state "dataprocedure" as edgemeredimlddfdataprocedure #ffcc88 {
state "list" as edgemeredimlddfdataprocedurelist #ffcc88 {
}
}
}
}
}

ChiefDataOfficerManageDataProcedures --> edgemeredimlddfdataprocedurelist


 
state "Data Scientist" as DataScientist {
    state "Manage Meta Data" as DataScientistManageMetaData {
    }
}
state "edgemere" as edgemere #ffcc88 {
state "diml" as edgemerediml #ffcc88 {
state "ddf" as edgemeredimlddf #ffcc88 {
state "metadata" as edgemeredimlddfmetadata #ffcc88 {
state "list" as edgemeredimlddfmetadatalist #ffcc88 {
}
}
}
}
}

DataScientistManageMetaData --> edgemeredimlddfmetadatalist


    state "DataEngineer" as DataEngineer {
        state "Manage Meta Data" as DataEngineerManageMetaData {
            state "Capture Meta Data" as DataEngineerManageMetaDataCaptureMetaData {
            }
        }
    }
    
    DataEngineerManageMetaDataCaptureMetaData --> Null
    
    state "DataSteward" as DataSteward {
        state "Manage Meta Data" as DataStewardManageMetaData {
            state "Capture Meta Data" as DataStewardManageMetaDataCaptureMetaData {
            }
        }
    }
    
    DataStewardManageMetaDataCaptureMetaData --> Null
    
 
    state "DataScientist" as DataScientist {
        state "Manage Meta Data" as DataScientistManageMetaData {
            state "Manage Data Catalog" as DataScientistManageMetaDataManageDataCatalog {
            }
        }
    }
    
    DataScientistManageMetaDataManageDataCatalog --> Null
    
 
 

@enduml
