@startuml

left to right direction







node "a_d_pm" #lightblue {


    hexagon childrennet #black [
            <b><color:white>children</color></b>
    ]
    
    portout " " as childrennetPortOut #black
    childrennet -[#black]- childrennetPortOut
    
    hexagon siblingnet #blue [
            <b><color:white>sibling</color></b>
    ]
    
    hexagon parentnet #red [
            <b><color:white>parent</color></b>
    ]
    
    portin " " as parentnetPortIn #red
    parentnetPortIn -[#red]- parentnet
    

node "child" as childService #white {
    portOut " " as childServicechildrennet #black
   childServicechildrennet -[#black]- childrennet
   
    portIn " " as childServiceparentnet #red
    parentnet -[#red]- childServiceparentnet
    

    artifact "child_image:latest" as child_imagelatestimage
    
}
node "frontend" as frontendService #white {
    portOut " " as frontendServicesiblingnet #blue
   frontendServicesiblingnet -[#blue]- siblingnet
   

    artifact "a_d_pm_web" as a_d_pm_webimage
    
}
node "gw" as gwService #white {
    portOut " " as gwServicechildrennet #black
   gwServicechildrennet -[#black]- childrennet
       portOut " " as gwServicesiblingnet #blue
   gwServicesiblingnet -[#blue]- siblingnet
   

    artifact "a_d_pm_gw" as a_d_pm_gwimage
    
}

}


@enduml
