version: "3.7"
services:
  frontend:
    image: aml_web
    networks:
      - sibling
  gw:
    image: aml_gw
    networks:
      children:
        aliases:
          - parent
          - top
      sibling:
        aliases:
          - gateway
networks:
  children:
    driver: overlay
    attachable: true
    name: ${AILTIRE_APPNAME}_aml_family
  sibling:
    driver: overlay
  parent:
    external: true
    name: ${AILTIRE_APPNAME}_family
