remote_theme: pmarsceill/just-the-docs
title: edgemere Architecture
description: Edgemere is a conceptual architecture targeted to multi-hybrid cloud and edge computing strategies including data,application, service, and infrastructure management. With the growth of IoT devices management of these elements from edge to data center is important to the success of the solution.
google_analytics: G-SDCPXLJ9YG
