@startuml



package "edgemere" #lavender {

    interface "edgemere" as i {
    
            /edgemere/admin/status()
    
    }
}

circle REST
circle Web
circle CLI
circle WebSocket

i -down- Web
i -down- CLI
i -down- REST
WebSocket -left- i: events >

package "edgemere" #lavender {


rectangle "Application Management Layer" #white {
}

rectangle "Common Physical Layer" #white {
}

rectangle "Distributed Information Management Layer" #white {
}

rectangle "Identity Aspect" #white {
}

rectangle "Security Aspect" #white {
}

rectangle "Service Management Layer" #white {
}

rectangle "Software Defined Infrastructure" #white {
}

    "Application Management Layer" --> "Distributed Information Management Layer"
    
    "Application Management Layer" --> "Service Management Layer"
    
    "Application Management Layer" --> "Security Aspect"
    
    "Application Management Layer" --> "Identity Aspect"
    
    "Distributed Information Management Layer" --> "Software Defined Infrastructure"
    
    "Distributed Information Management Layer" --> "Service Management Layer"
    
    "Distributed Information Management Layer" --> "Security Aspect"
    
    "Distributed Information Management Layer" --> "Identity Aspect"
    
    "Service Management Layer" --> "Software Defined Infrastructure"
    
    "Service Management Layer" --> "Distributed Information Management Layer"
    
    "Software Defined Infrastructure" --> "Common Physical Layer"
    
}



@enduml
