@startuml


package "Developer Services" #lightblue {
    }

package "Identity Aspect" #pink {
    }


package "Workflow Services" #lightblue {

    interface "Workflow Services" as i {
    
    }
}

CLI ()-- i
REST ()-- i
Web ()-- i

package "Workflow Services" #lightblue {
    
}


    "Workflow Services" --> "Developer Services"

    "Workflow Services" --> "Identity Aspect"


@enduml
