@startuml
  interface CLI
  interface Web
  interface WebSocket
node "Data Controller" #lightblue {
  component express as REST
  component socket.io as socket
  folder bin #ffffff {
    card " edgemere diml dml dc" as binName
  }
  binName --> REST

  folder deploy #ffffff {
      file "node server.js\n" as diml_dml_dc_container
      REST --> diml_dml_dc_container


    file "controller" as controller_container
    REST --> controller_container
    socket ---> controller_container

  }
  folder images #ffffff {
    collections "diml_dml_dc" as diml_dml_dcimage
    artifact "ailtire:swarm" as ailtireswarm
    diml_dml_dcimage <|-- ailtireswarm
    diml_dml_dc_container --> diml_dml_dcimage


      artifact "diml_dml_dc_controller" as diml_dml_dc_controller
      controller_container --> diml_dml_dc_controller

  }
}
CLI " edgemere diml dml dc" -- binName
Web "/edgemere/diml/dml/dc" - REST
WebSocket ".edgemere.diml.dml.dc" -- socket

@enduml
