@startuml



state StackInstance #88cc88 {

    state Init #88cc88 {
    }

    state Deploying #88cc88 {
    }

    state Running #88cc88 {
    }

    state Failed #88cc88 {
    }

    state Completed #88cc88 {
    }




Init -[#black]--> Deploying : create

}


@enduml
