@startuml


left to right direction

usecase "Manage Billing" as ManageBilling #yellow

Actor "IT Operations" as ITOperations

ITOperations --> ManageBilling





usecase "Control Virtual Infrastructure" as ControlVirtualInfrastructure #lightyellow

ManageBilling <-- ControlVirtualInfrastructure : extends







@enduml
