@startuml


left to right direction

usecase "Map Services to Resources" as MapServicestoResources #yellow

Actor "IT Operations" as ITOperations

ITOperations --> MapServicestoResources





usecase "Coordinate Services" as CoordinateServices #lightyellow

MapServicestoResources <-- CoordinateServices : extends







@enduml
