@startuml


package "Security Aspect" #cc8888 {
    }


package "Developer Services" #lightblue {

    interface "Developer Services" as i {
    
    }
}

CLI ()-- i
REST ()-- i
Web ()-- i

package "Developer Services" #lightblue {
    
}


    "Developer Services" --> "Security Aspect"


@enduml
