@startuml
left to right direction


state "aml" as aml #88cccc {
state "ds" as amlds #lightblue {
}
}


state "amlds" as pstatename #lightblue {
    state "Custom Function" as dsfunction {
    }
}





@enduml
