@startuml


package "Security Aspect" #pink {

}


package "Developer Services" #lightblue {

    interface "Developer Services" as i {
    
    }
}

CLI ()-- i
REST ()-- i
Web ()-- i

package "Developer Services" #lightblue {


rectangle "Automation Framework" #white {
}

rectangle "Environment Management" #white {
}

rectangle "Pipeline Manager" #white {
}

    "Environment Management" --> "Service Orchestrator"
    
}


    "Developer Services" --> "Security Aspect"


@enduml
