@startuml


package "Security Aspect" #cc8888 {

}


package "Developer Services" #aaffff {

    interface "Developer Services" as i {
    
    
    }
}

circle REST
circle Web
circle CLI
circle WebSocket

i -down- Web
i -down- CLI
i -down- REST
WebSocket -left- i: events >

package "Developer Services" #aaffff {


rectangle "Automation Framework" #white {
}

rectangle "Environment Management" #white {
}

rectangle "Pipeline Manager" #white {
}

    "Environment Management" --> "Service Orchestrator"
    
}


    "Security Aspect" <-- "Developer Services"


@enduml
