@startuml

left to right direction
Actor "Developer" as Developer
Actor "Developer" as Developer
Actor "Developer" as Developer
Actor "System Administrator" as SystemAdministrator


rectangle "Developer Services" #aaffff {
usecase "AutomationFramework" as AutomationFramework
    Developer --> AutomationFramework
    usecase "CICDPipeline" as CICDPipeline
    Developer --> CICDPipeline
    usecase "EnvironmentDeployments" as EnvironmentDeployments
    Developer --> EnvironmentDeployments
    usecase "SecurityProfiles" as SecurityProfiles
    SystemAdministrator --> SecurityProfiles
    }


@enduml
