@startuml
left to right direction


state "diml" as diml #ffcc88 {
state "dml" as dimldml #ffcc88 {
state "dc" as dimldmldc #lightblue {
}
}
}


state dimldmldc #lightblue {
    state "Custom Function" as dcfunction {
    }
}





@enduml
