@startuml
  interface CLI
  interface Web
  interface WebSocket
package "Provision Engine" #lightgreen {
  component express as REST
  component socket.io as socket
  folder bin #ffffff {
    component " edgemere sml pe" as binName
  }
  binName --> REST

  folder deploy #ffffff {
      file "node server.js\ndocker-compose.yml" as sml_pe_container
      REST --> sml_pe_container

  
    file "web" as web_container
    REST --> web_container
    socket ---> web_container
  
    file "gateway" as gateway_container
    REST --> gateway_container
    socket ---> gateway_container
  
  }
  folder images #ffffff {
    collections "sml_pe" as sml_peimage
    artifact "ailtire:swarm" as ailtireswarm
    sml_peimage <|-- ailtireswarm
    sml_pe_container --> sml_peimage

  
      artifact sml_pe_web
      web_container --> sml_pe_web
    
      artifact sml_pe_gw
      gateway_container --> sml_pe_gw
    
  }
}
CLI " edgemere sml pe" -- binName
Web "/edgemere/sml/pe" - REST
WebSocket ".edgemere.sml.pe" -- socket

@enduml
