@startuml
left to right direction


state "diml" as diml #ffcc88 {
state "ddf" as dimlddf #ffcc88 {
state "df" as dimlddfdf ##aaffff {
}
}
}


state "dimlddfdf" as pstatename ##aaffff {
    state "Custom Function" as dffunction {
    }
}





@enduml
