@startuml
left to right direction


state "diml" as diml #ffcc88 {
state "ddf" as dimlddf #ffcc88 {
state "df" as dimlddfdf #lightblue {
}
}
}


state dimlddfdf #lightblue {
    state "Custom Function" as dffunction {
    }
}





@enduml
