@startuml



package "Data Flow" #lightblue {

    interface "Data Flow" as i {
    
    
    }
}

circle REST
circle Web
circle CLI
circle WebSocket

i -down- Web
i -down- CLI
i -down- REST
WebSocket -left- i: events >

package "Data Flow" #lightblue {


}



@enduml
