@startuml


left to right direction

usecase "Manage Data" as ManageData #yellow

Actor "Data Scientist" as DataScientist

DataScientist --> ManageData

Actor "Data Analyst" as DataAnalyst

DataAnalyst --> ManageData

Actor "DataEngineer" as DataEngineer

DataEngineer --> ManageData



json DestroyData #lightyellow {
    "Given": "Data Steward has access to the data source",
    "When": "Data Steward uses method to destroy data",
    "Then": "The data from the particular source should be destroyed"
}

ManageData <|-- DestroyData

json EgressData #lightyellow {
    "Given": "A data steward uses the system",
    "When": "Data Steward selects &#39;data/source/name&#39;",
    "Then": "Egress Data is displayed to the Data Steward"
}

ManageData <|-- EgressData

json IngestData #lightyellow {
    "Given": "A data steward uses data source",
    "When": "Data is ingested from named source",
    "Then": "Data should be managed in the ingest process"
}

ManageData <|-- IngestData

json MoveData #lightyellow {
    "Given": "A Data Steward needs to move specific data",
    "When": "they use the &#39;data/move&#39; method",
    "Then": "the specified data should be successfully moved"
}

ManageData <|-- MoveData



usecase "Provide Business Information" as ProvideBusinessInformation #lightyellow

ManageData <-- ProvideBusinessInformation : extends







@enduml
