@startuml


usecase "Manage Data" as ManageData

Actor "Data Scientist" as DataScientist

DataScientist --> ManageData

Actor "Data Analyst" as DataAnalyst

DataAnalyst --> ManageData

Actor "DataEngineer" as DataEngineer

DataEngineer --> ManageData



usecase "DestroyData" as DestroyData #lightgrey

ManageData --> DestroyData

usecase "EgressData" as EgressData #lightgrey

ManageData --> EgressData

usecase "IngestData" as IngestData #lightgrey

ManageData --> IngestData

usecase "MoveData" as MoveData #lightgrey

ManageData --> MoveData

@enduml
