@startuml


actor "Data Steward"


entity EventBus

box Common Data Service #ffcc88
    boundary cds #white
end box


group Given [Data Steward has access to the data source]

"Data Steward" --/ cds: Data Steward uses method to destroy data
"cds" -> cds: Destroy Data



"Data Steward" /-- cds: The data from the particular source should be destroyed


end

@enduml
