@startuml


actor "Data Steward"


entity EventBus

box Common Data Service #ffcc88
    boundary cds #white
end box


group Given [A data steward uses the system]

"Data Steward" --/ cds: Data Steward selects &#39;data/source/name&#39;
"cds" -> cds: Egress Data



"Data Steward" /-- cds: Egress Data is displayed to the Data Steward


end

@enduml
