@startuml


actor "Data Steward"


entity EventBus

box Common Data Service #ffcc88
    boundary cds #white
end box


group Given [A data steward uses data source]

"Data Steward" --/ cds: Data is ingested from named source
"cds" -> cds: Ingest Data



"Data Steward" /-- cds: Data should be managed in the ingest process


end

@enduml
