@startuml



package "Device Manager" #cccccc {

    interface "Device Manager" as i {
            /edgemere/cpl/dm/agent/register()
            /edgemere/cpl/dm/service/register()
    
    }
}

CLI ()-- i
REST ()-- i
Web ()-- i

package "Device Manager" #cccccc {
        class "Agent" {
                 string name
                 string url
                    }
    
    

}



@enduml
