@startuml
left to right direction


state "cpl" as cpl #cccccc {
state "dm" as cpldm #cccccc {
}
}


state "cpldm" as pstatename #cccccc {
    state "Custom Function" as dmfunction {
    }
}

        state "cpl" as cpl #cccccc {
state "dm" as cpldm #cccccc {
state "agent" as cpldmagent #cccccc {
state "register" as cpldmagentregister #cccccc {
}
}
}
}


        state "cpl" as cpl #cccccc {
state "dm" as cpldm #cccccc {
state "service" as cpldmservice #cccccc {
state "register" as cpldmserviceregister #cccccc {
}
}
}
}




        state "cpl" as cpl #cccccc {
state "dm" as cpldm #cccccc {
state "Agent" as cpldmagent #cccccc {
state "started" as cpldmagentstarted #cccccc {
}
}
}
}

        
    state "dm" as dm #lavender {
state "agent" as dmagent #lavender {
state "register" as dmagentregister #lavender {
}
}
}

    cpldmagentstarted ---> dmagentregister
  


    
    state "dm" as dm #lavender {
state "agent" as dmagent #lavender {
state "register" as dmagentregister #lavender {
}
}
}

        
       

@enduml
