@startuml


usecase "Manage Data Sources" as ManageDataSources #yellow

Actor "DataEngineer" as DataEngineer

DataEngineer --> ManageDataSources



usecase "DeregisterDataSource" as DeregisterDataSource #lightgrey

ManageDataSources --> DeregisterDataSource

usecase "RegisterDataSource" as RegisterDataSource #lightgrey

ManageDataSources --> RegisterDataSource









@enduml
