@startuml


actor "Data Engineer"


entity EventBus

box Data Management Layer #ffcc88
    boundary dml #white
end box


box Data Definition Framework #ffcc88
            participant dataadaptor
            participant datasource
    end box

group Given [Data source &#39;myDataVolume1&#39; is registered in the system using adaptor &#39;filesystem1&#39;]

"Data Engineer" --/ dml: Data engineer uses &#39;datasource/list&#39; method to deregister &#39;myDataVolume1&#39;
"dml" -> dml: Deregister Data Source

    dml -> "dataadaptor": create (name: filesystem1,file: ./templates/dataadaptor-filesystem.yaml)

    "dataadaptor" --/ EventBus: dataadaptor.create

    dml -> "datasource": create (name: myDataVolume1,adaptor: filesystem1,file: ./templates/datasource.yaml)

    "datasource" --/ EventBus: datasource.create



"Data Engineer" /-- dml: All BluePrints, DataFlows, and associated data become unavailable but metadata remains


end

@enduml
