@startuml


actor "DataEngineer"


entity EventBus

box Data Management Layer #ffcc88
    boundary dml #white
end box


box Data Definition Framework #ffcc88
            participant dataadaptor
            participant datasource
    end box

group Given [A system to monitor data sources]

"DataEngineer" --/ dml: A data source is registered to the system
"dml" -> dml: Register Data Source

    dml -> "dataadaptor": create (name: filesystem1,file: ./templates/dataadaptor-filesystem.yaml)

    "dataadaptor" --/ EventBus: dataadaptor.create

    dml -> "datasource": create (name: myDataVolume1,adaptor: filesystem1,file: ./templates/datasource.yaml)

    "datasource" --/ EventBus: datasource.create

    dml -> "datasource": create (name: myDataVolume2,adaptor: filesystem1,parameters: host=localhost, filesystem=/tmp/user2)

    "datasource" --/ EventBus: datasource.create

    dml -> "datasource": create (name: myDataVolume3,adaptor: filesystem1,parameters: host=localhost, filesystem=/tmp/user3)

    "datasource" --/ EventBus: datasource.create

    dml -> "datasource": create (name: myDataVolume4,adaptor: filesystem1,parameters: host=localhost, filesystem=/tmp/user4)

    "datasource" --/ EventBus: datasource.create



"DataEngineer" /-- dml: Data generated at the data source can now be processed by DataBluePrints


end

@enduml
