@startuml
 actor "Data Engineer" as de
 participant "Data Management Layer" as dml #ffcc88
 participant "Data Source" as ds #ffcc88
 participant "Data Adaptor" as da #ffcc88
 participant "Data Blue Print" as dbp #ffcc88
 participant "Data Blue Print Instance" as dbpi #ffcc88
 participant "Meta Data" as md #ffcc88
 participant "Data" as data #ffcc88

== Register Datasource ==
de -> dml : datasource/register
dml -> ds  ** : create(name, DataAdaptor, parameters)
de -> dbp : deploy (name, source, parameters)
dbp -> dbpi ** : create(name, blueprint, source, parameters)
loop while data generated
    ds -> dbpi : newData
    dbpi -> data ** : create(name, source)
    dbpi -> md ** : create(data, metadata)
end

== UnRegister Datasource ==
de -> dml : datasource/unregister
dml -> ds : disable()
ds -> dbpi : disable()
loop all data
    dbpi -> data : disable()
    data -> md : unavailable()
end
ds -> dbpi !! : destroy()

@enduml
