@startuml


package "Service Controller" #88cc88 {
    }

package "Service Repository" #88cc88 {
    }

package "Data Orchestrator" ##aaffff {
    
        class DataInstance {
        }
    }

package "Infrastructure Orchestrator" #cccc88 {
    }

package "Service Management Layer" #88cc88 {
    
        class Image {
        }
    
        class Servicelet {
        }
    
        class RunScript {
        }
    
        class Stack {
        }
    
        class Stacklet {
        }
    }

package "Software Defined Infrastructure" #cccc88 {
    
        class Resource {
        }
    }

package "Service Orchestrator" #88cc88 {
    
        class StackInstance {
        }
    
        class ServiceInstance {
        }
    }

package "Application Management Layer" #88cccc {
    
        class ApplicationInstance {
        }
    }


package "Service Orchestrator" #88cc88 {

    interface "Service Orchestrator" as i {
            /edgemere/sml/so/data/create()
            /edgemere/sml/so/servicelet/assigndata()
            /edgemere/sml/so/stack/deploy()
            /edgemere/sml/so/stack/list()
            /edgemere/sml/so/stack/uninstall()
            /edgemere/sml/so/stack/update()
    
    }
}

CLI ()-- i
REST ()-- i
Web ()-- i

package "Service Orchestrator" #88cc88 {
        class "ServiceInstance" {
                    }
                ServiceInstance o--> "1" Image : image
                        ServiceInstance o--> "n" DataInstance : data
                        ServiceInstance o--> "n" Resource : resources
                        ServiceInstance o--> "1" Servicelet : servicelet
                        ServiceInstance o--> "1" StackInstance : stack
                        ServiceInstance *--> "n" RunScript : runScripts
            
    
    class "StackInstance" {
                 string name
                    }
                StackInstance o--> "1" ApplicationInstance : app
                        StackInstance o--> "1" Stack : stack
                        StackInstance o--> "1" Stacklet : stacklet
                        StackInstance *--> "n" ServiceInstance : services
                        StackInstance o--> "1" Image : image
                        StackInstance o--> "n" DataInstance : data
                        StackInstance o--> "n" Resource : resources
                        StackInstance o--> "1" Servicelet : servicelet
                        StackInstance *--> "n" RunScript : runScripts
            
    
        ServiceInstance <|-- StackInstance
    

}


    "Service Orchestrator" --> "Service Controller"

    "Service Orchestrator" --> "Service Repository"

    "Service Orchestrator" --> "Data Orchestrator"

    "Service Orchestrator" --> "Infrastructure Orchestrator"


@enduml
