@startuml
left to right direction


state "sml" as sml #lightgreen {
state "so" as smlso #lightgreen {
}
}


state "smlso" as pstatename #lightgreen {
    state "Custom Function" as sofunction {
    }
}

        state "sml" as sml #lightgreen {
state "so" as smlso #lightgreen {
state "servicelet" as smlsoservicelet #lightgreen {
state "assigndata" as smlsoserviceletassigndata #lightgreen {
}
}
}
}


        state "sml" as sml #lightgreen {
state "so" as smlso #lightgreen {
state "stack" as smlsostack #lightgreen {
state "deploy" as smlsostackdeploy #lightgreen {
}
}
}
}


        state "sml" as sml #lightgreen {
state "so" as smlso #lightgreen {
state "stack" as smlsostack #lightgreen {
state "list" as smlsostacklist #lightgreen {
}
}
}
}


        state "sml" as sml #lightgreen {
state "so" as smlso #lightgreen {
state "stack" as smlsostack #lightgreen {
state "uninstall" as smlsostackuninstall #lightgreen {
}
}
}
}


        state "sml" as sml #lightgreen {
state "so" as smlso #lightgreen {
state "stack" as smlsostack #lightgreen {
state "update" as smlsostackupdate #lightgreen {
}
}
}
}




        state "diml" as diml #ffcc88 {
state "dml" as dimldml #ffcc88 {
state "DataReference" as dimldmldatareference #ffcc88 {
state "provisioned" as dimldmldatareferenceprovisioned #ffcc88 {
}
}
}
}

        
    state "sml" as sml #lightgreen {
state "so" as smlso #lightgreen {
state "servicelet" as smlsoservicelet #lightgreen {
state "assignData" as smlsoserviceletassigndata #lightgreen {
}
}
}
}

    dimldmldatareferenceprovisioned ---> smlsoserviceletassigndata
  



@enduml
