@startuml
left to right direction


state "sml" as sml #88cc88 {
state "so" as smlso #88cc88 {
}
}


state "smlso" as pstatename #88cc88 {
    state "Custom Function" as sofunction {
    }
}

        state "sml" as sml #88cc88 {
state "so" as smlso #88cc88 {
state "data" as smlsodata #88cc88 {
state "create" as smlsodatacreate #88cc88 {
}
}
}
}


        state "sml" as sml #88cc88 {
state "so" as smlso #88cc88 {
state "servicelet" as smlsoservicelet #88cc88 {
state "assigndata" as smlsoserviceletassigndata #88cc88 {
}
}
}
}


        state "sml" as sml #88cc88 {
state "so" as smlso #88cc88 {
state "stack" as smlsostack #88cc88 {
state "deploy" as smlsostackdeploy #88cc88 {
}
}
}
}


        state "sml" as sml #88cc88 {
state "so" as smlso #88cc88 {
state "stack" as smlsostack #88cc88 {
state "list" as smlsostacklist #88cc88 {
}
}
}
}


        state "sml" as sml #88cc88 {
state "so" as smlso #88cc88 {
state "stack" as smlsostack #88cc88 {
state "uninstall" as smlsostackuninstall #88cc88 {
}
}
}
}


        state "sml" as sml #88cc88 {
state "so" as smlso #88cc88 {
state "stack" as smlsostack #88cc88 {
state "update" as smlsostackupdate #88cc88 {
}
}
}
}




        state "diml" as diml #ffcc88 {
state "dml" as dimldml #ffcc88 {
state "DataReference" as dimldmldatareference #ffcc88 {
state "provisioned" as dimldmldatareferenceprovisioned #ffcc88 {
}
}
}
}

        
    state "sml" as sml #88cc88 {
state "so" as smlso #88cc88 {
state "servicelet" as smlsoservicelet #88cc88 {
state "assignData" as smlsoserviceletassigndata #88cc88 {
}
}
}
}

    dimldmldatareferenceprovisioned ---> smlsoserviceletassigndata
  



@enduml
