@startuml
left to right direction



state "Stack Developer" as StackDeveloper {
    state "Manage Stacks" as StackDeveloperManageStacks {
    }
}
state "edgemere" as edgemere #lightgreen {
state "sml" as edgemeresml #lightgreen {
state "so" as edgemeresmlso #lightgreen {
state "stack" as edgemeresmlsostack #lightgreen {
state "list" as edgemeresmlsostacklist #lightgreen {
}
}
}
}
}

StackDeveloperManageStacks --> edgemeresmlsostacklist

state "Application Developer" as ApplicationDeveloper {
    state "Manage Stacks" as ApplicationDeveloperManageStacks {
    }
}
state "edgemere" as edgemere #lightgreen {
state "sml" as edgemeresml #lightgreen {
state "so" as edgemeresmlso #lightgreen {
state "stack" as edgemeresmlsostack #lightgreen {
state "list" as edgemeresmlsostacklist #lightgreen {
}
}
}
}
}

ApplicationDeveloperManageStacks --> edgemeresmlsostacklist


    state "DevOps Engineer" as DevOpsEngineer {
        state "Manage Stacks" as DevOpsEngineerManageStacks {
            state "Deploy Stack" as DevOpsEngineerManageStacksDeployStack {
            }
        }
    }
    
    DevOpsEngineerManageStacksDeployStack --> Null
    
 
    state "DevOps Engineer" as DevOpsEngineer {
        state "Manage Stacks" as DevOpsEngineerManageStacks {
            state "Uninstall Stack" as DevOpsEngineerManageStacksUninstallStack {
            }
        }
    }
    
    DevOpsEngineerManageStacksUninstallStack --> Null
    
 
    state "DevOps Engineer" as DevOpsEngineer {
        state "Manage Stacks" as DevOpsEngineerManageStacks {
            state "Update Stack" as DevOpsEngineerManageStacksUpdateStack {
            }
        }
    }
    
    DevOpsEngineerManageStacksUpdateStack --> Null
    
 
 

@enduml
