@startuml
left to right direction


    package "edgemere" as edgemere {
package "sml" as edgemeresml {
package "so" as edgemeresmlso #88cc88 {
 component "data" as edgemeresmlsodata
 interface "create" as edgemeresmlsodatacreate
edgemeresmlsodata -- edgemeresmlsodatacreate
}
}
}

    
    package "edgemere" as edgemere {
package "sml" as edgemeresml {
package "so" as edgemeresmlso #88cc88 {
 component "servicelet" as edgemeresmlsoservicelet
 interface "assigndata" as edgemeresmlsoserviceletassigndata
edgemeresmlsoservicelet -- edgemeresmlsoserviceletassigndata
}
}
}

    
    package "edgemere" as edgemere {
package "sml" as edgemeresml {
package "so" as edgemeresmlso #88cc88 {
 component "stack" as edgemeresmlsostack
 interface "deploy" as edgemeresmlsostackdeploy
edgemeresmlsostack -- edgemeresmlsostackdeploy
}
}
}

    
    package "edgemere" as edgemere {
package "sml" as edgemeresml {
package "so" as edgemeresmlso #88cc88 {
 component "stack" as edgemeresmlsostack
 interface "list" as edgemeresmlsostacklist
edgemeresmlsostack -- edgemeresmlsostacklist
}
}
}

    
    package "edgemere" as edgemere {
package "sml" as edgemeresml {
package "so" as edgemeresmlso #88cc88 {
 component "stack" as edgemeresmlsostack
 interface "uninstall" as edgemeresmlsostackuninstall
edgemeresmlsostack -- edgemeresmlsostackuninstall
}
}
}

    
    package "edgemere" as edgemere {
package "sml" as edgemeresml {
package "so" as edgemeresmlso #88cc88 {
 component "stack" as edgemeresmlsostack
 interface "update" as edgemeresmlsostackupdate
edgemeresmlsostack -- edgemeresmlsostackupdate
}
}
}

    
hexagon "datareference.provisioned" as datareferenceprovisioned
            edgemeresmlso <-- datareferenceprovisioned
        



        rectangle "Manage Applications" as ManageApplications #ffffaa {
            ("Build Application")/ as DevOpsEngineerManageApplicationsBuildApplication
        }
    
    edgemeresmlsodatacreate <-- DevOpsEngineerManageApplicationsBuildApplication
    









        rectangle "Manage Meta Data" as ManageMetaData #ffffaa {
            ("Capture Meta Data")/ as DataEngineerManageMetaDataCaptureMetaData
        }
    
    edgemeresmlsodatacreate <-- DataEngineerManageMetaDataCaptureMetaData
    
        rectangle "Manage Meta Data" as ManageMetaData #ffffaa {
            ("Capture Meta Data")/ as DataStewardManageMetaDataCaptureMetaData
        }
    
    edgemeresmlsodatacreate <-- DataStewardManageMetaDataCaptureMetaData
    














        rectangle "Manage Stacks" as ManageStacks #ffffaa {
            ("Build Stack")/ as DevOpsEngineerManageStacksBuildStack
        }
    
    edgemeresmlsodatacreate <-- DevOpsEngineerManageStacksBuildStack
    
        rectangle "Manage Stacks" as ManageStacks #ffffaa {
            ("Create Application Stack")/ as ApplicationDeveloperManageStacksCreateApplicationStack
        }
    
    edgemeresmlsodatacreate <-- ApplicationDeveloperManageStacksCreateApplicationStack
    
        rectangle "Manage Stacks" as ManageStacks #ffffaa {
            ("Create Application Stack")/ as StackDeveloperManageStacksCreateApplicationStack
        }
    
    edgemeresmlsodatacreate <-- StackDeveloperManageStacksCreateApplicationStack
    
        rectangle "Manage Stacks" as ManageStacks #ffffaa {
            ("Create Service Stack")/ as StackDeveloperManageStacksCreateServiceStack
        }
    
    edgemeresmlsodatacreate <-- StackDeveloperManageStacksCreateServiceStack
    
        rectangle "Manage Stacks" as ManageStacks #ffffaa {
            ("Deploy Stack")/ as DevOpsEngineerManageStacksDeployStack
        }
    
    edgemeresmlsostackdeploy <-- DevOpsEngineerManageStacksDeployStack
    
        rectangle "Manage Stacks" as ManageStacks #ffffaa {
            ("Modify Application Stack")/ as StackDeveloperManageStacksModifyApplicationStack
        }
    
    edgemeresmlsodatacreate <-- StackDeveloperManageStacksModifyApplicationStack
    
        rectangle "Manage Stacks" as ManageStacks #ffffaa {
            ("Modify Application Stack")/ as ApplicationDeveloperManageStacksModifyApplicationStack
        }
    
    edgemeresmlsodatacreate <-- ApplicationDeveloperManageStacksModifyApplicationStack
    
        rectangle "Manage Stacks" as ManageStacks #ffffaa {
            ("Modify Service Stack")/ as StackDeveloperManageStacksModifyServiceStack
        }
    
    edgemeresmlsodatacreate <-- StackDeveloperManageStacksModifyServiceStack
    
        rectangle "Manage Stacks" as ManageStacks #ffffaa {
            ("Test Application Stack")/ as StackDeveloperManageStacksTestApplicationStack
        }
    
    edgemeresmlsodatacreate <-- StackDeveloperManageStacksTestApplicationStack
    
        rectangle "Manage Stacks" as ManageStacks #ffffaa {
            ("Test Application Stack")/ as ApplicationDeveloperManageStacksTestApplicationStack
        }
    
    edgemeresmlsodatacreate <-- ApplicationDeveloperManageStacksTestApplicationStack
    
        rectangle "Manage Stacks" as ManageStacks #ffffaa {
            ("Test Service Stack")/ as StackDeveloperManageStacksTestServiceStack
        }
    
    edgemeresmlsodatacreate <-- StackDeveloperManageStacksTestServiceStack
    
        rectangle "Manage Stacks" as ManageStacks #ffffaa {
            ("Uninstall Stack")/ as DevOpsEngineerManageStacksUninstallStack
        }
    
    edgemeresmlsostackuninstall <-- DevOpsEngineerManageStacksUninstallStack
    
        rectangle "Manage Stacks" as ManageStacks #ffffaa {
            ("Update Stack")/ as DevOpsEngineerManageStacksUpdateStack
        }
    
    edgemeresmlsostackupdate <-- DevOpsEngineerManageStacksUpdateStack
    
        rectangle "Manage Stacks" as ManageStacks #ffffaa {
            ("Version Application Stack")/ as ApplicationDeveloperManageStacksVersionApplicationStack
        }
    
    edgemeresmlsodatacreate <-- ApplicationDeveloperManageStacksVersionApplicationStack
    
        rectangle "Manage Stacks" as ManageStacks #ffffaa {
            ("Version Service Stack")/ as StackDeveloperManageStacksVersionServiceStack
        }
    
    edgemeresmlsodatacreate <-- StackDeveloperManageStacksVersionServiceStack
    



        rectangle "Manage Services" as ManageServices #ffffaa {
            ("Build Service")/ as StackDeveloperManageServicesBuildService
        }
    
    edgemeresmlsodatacreate <-- StackDeveloperManageServicesBuildService
    








@enduml
