@startuml


package "Service Controller" #lightgreen {

}

package "Service Repository" #lightgreen {

}

package "Data Orchestrator" #lightblue {

}

package "Infrastructure Orchestrator" #lightyellow {

}

package "Service Management Layer" #lightgreen {

}

package "Software Defined Infrastructure" #lightyellow {

}

package "Service Orchestrator" #lightgreen {

}

package "Application Management Layer" #lightblue {

}


package "Service Orchestrator" #lightgreen {

    interface "Service Orchestrator" as i {
            ^datareference.provisioned
    
            /edgemere/sml/so/servicelet/assigndata()
            /edgemere/sml/so/stack/deploy()
            /edgemere/sml/so/stack/list()
            /edgemere/sml/so/stack/uninstall()
            /edgemere/sml/so/stack/update()
    
    }
}

circle REST
circle Web
circle CLI
circle WebSocket

i -down- Web
i -down- CLI
i -down- REST
WebSocket -left- i: events >

package "Service Orchestrator" #lightgreen {


}


    "Service Controller" <-- "Service Orchestrator"

    "Service Repository" <-- "Service Orchestrator"

    "Data Orchestrator" <-- "Service Orchestrator"

    "Infrastructure Orchestrator" <-- "Service Orchestrator"


@enduml
