@startuml


package "Service Controller" #88cc88 {

}

package "Service Repository" #88cc88 {

}

package "Data Orchestrator" #lightblue {

}

package "Infrastructure Orchestrator" #cccc88 {

}

package "Service Management Layer" #88cc88 {

}

package "Software Defined Infrastructure" #cccc88 {

}

package "Service Orchestrator" #88cc88 {

}

package "Application Management Layer" #88cccc {

}


package "Service Orchestrator" #88cc88 {

    interface "Service Orchestrator" as i {
            ^datareference.provisioned
    
            /edgemere/sml/so/servicelet/assigndata()
            /edgemere/sml/so/stack/deploy()
            /edgemere/sml/so/stack/list()
            /edgemere/sml/so/stack/uninstall()
            /edgemere/sml/so/stack/update()
    
    }
}

circle REST
circle Web
circle CLI
circle WebSocket

i -down- Web
i -down- CLI
i -down- REST
WebSocket -left- i: events >

package "Service Orchestrator" #88cc88 {


}


    "Service Controller" <-- "Service Orchestrator"

    "Service Repository" <-- "Service Orchestrator"

    "Data Orchestrator" <-- "Service Orchestrator"

    "Infrastructure Orchestrator" <-- "Service Orchestrator"


@enduml
