@startuml

left to right direction
Actor "Stack Developer" as StackDeveloper
Actor "Application Developer" as ApplicationDeveloper


rectangle "Service Orchestrator" #lightgreen {
usecase "ManageStacks" as ManageStacks
    StackDeveloper --> ManageStacks
    ApplicationDeveloper --> ManageStacks
    }


@enduml
