@startuml



state DataRequest #lightblue {

    state Init #lightblue {
    }

    state Needed #lightblue {
    }

    state Failed #lightblue {
    }

    state Selected #lightblue {
    }

    state Satisfied #lightblue {
    }

    state Evaluated #lightblue {
    }

    state Completed #lightblue {
    }

}


Init --> Needed : fulfill

Needed --> Selected : selected

Needed --> Failed : failed

Selected --> Evaluated : evaluated

Satisfied --> Completed : complete

Evaluated --> Satisfied : satisfied

Evaluated --> Failed : failed



 state "edgemere" as edgemere #lightblue {
state "diml" as edgemerediml #lightblue {
state "dml" as edgemeredimldml #lightblue {
state "do" as edgemeredimldmldo #lightblue {
state "reserve" as edgemeredimldmldoreserve #lightblue {
}
}
}
}
}

 Needed -[#black]--> edgemeredimldmldoreserve
 
 state "edgemere" as edgemere #lightblue {
state "diml" as edgemerediml #lightblue {
state "dml" as edgemeredimldml #lightblue {
state "do" as edgemeredimldmldo #lightblue {
state "evaluate" as edgemeredimldmldoevaluate #lightblue {
}
}
}
}
}

 Selected -[#black]--> edgemeredimldmldoevaluate
 

@enduml
