@startuml



state DataRequest #lightblue {

    state Init #lightblue {
    }

    state Needed #lightblue {
    }

    state Failed #lightblue {
    }

    state Selected #lightblue {
    }

    state Satisfied #lightblue {
    }

    state Evaluated #lightblue {
    }

    state Completed #lightblue {
    }




Init -[#black]--> Needed : fulfill

Needed -[#black]--> Selected : selected

Needed -[#black]--> Failed : failed

Selected -[#black]--> Evaluated : evaluated

Satisfied -[#black]--> Completed : complete

Evaluated -[#black]--> Satisfied : satisfied

Evaluated -[#black]--> Failed : failed

}

 
 Needed -[#black]--> Null
 
 
 Selected -[#black]--> Null
 

@enduml
