@startuml
left to right direction


state "sa" as sa #cc8888 {
state "pe" as sape #cc8888 {
}
}


state "sape" as pstatename #cc8888 {
    state "Custom Function" as pefunction {
    }
}





@enduml
