@startuml
  interface CLI
  interface Web
  interface WebSocket
node "Developer Services" #lightblue {
  component express as REST
  component socket.io as socket
  folder bin #ffffff {
    card " edgemere aml ds" as binName
  }
  binName --> REST

  folder deploy #ffffff {
      file "node server.js\n" as aml_ds_container
      REST --> aml_ds_container

  
    file "web" as web_container
    REST --> web_container
    socket ---> web_container
  
  }
  folder images #ffffff {
    collections "aml_ds" as aml_dsimage
    artifact "ailtire:swarm" as ailtireswarm
    aml_dsimage <|-- ailtireswarm
    aml_ds_container --> aml_dsimage

  
      artifact "aml_ds_web" as aml_ds_web
      web_container --> aml_ds_web
    
  }
}
CLI " edgemere aml ds" -- binName
Web "/edgemere/aml/ds" - REST
WebSocket ".edgemere.aml.ds" -- socket

@enduml
