@startuml


package "Software Defined Infrastructure" #lightyellow {

}

package "Cloud Broker" #lightgreen {

}

package "Common Physical Layer" #lightgray {

}


package "Cloud Broker" #lightgreen {

    interface "Cloud Broker" as i {
            /edgemere/sml/cb/billing/list()
            /edgemere/sml/cb/data/govern()
            /edgemere/sml/cb/multicloud/addclouds()
            /edgemere/sml/cb/multicloud/addpolicies()
            /edgemere/sml/cb/multicloud/list()
            /edgemere/sml/cb/multicloud/mapresources()
            /edgemere/sml/cb/multicloud/removepolicies()
            /edgemere/sml/cb/resourceinstancetype/list()
            /edgemere/sml/cb/resources/find()
            /edgemere/sml/cb/service/mapresources()
    
    }
}

CLI ()-- i
REST ()-- i
Web ()-- i

package "Cloud Broker" #lightgreen {


}



@enduml
