version: "3.7"
services:
  frontend:
    image: sml_so_web
    networks:
      - sibling
  gw:
    image: sml_so_gw
    networks:
      children:
        aliases:
          - parent
          - top
      sibling:
        aliases:
          - gateway

networks:
  children:
    driver: overlay
    attachable: true
    name: ${AILTIRE_APPNAME}_sml_so_family
  sibling:
    driver: overlay
  parent:
    external: true
    name: ${AILTIRE_APPNAME}_sml_family
