@startuml

left to right direction







node "edgemere" #ccaaff {


    hexagon parentnet #black [
            <b><color:white>parent</color></b>
    ]
    
    portin " " as parentnetPortIn #black
    parentnetPortIn -[#black]- parentnet
    
    hexagon childrennet #blue [
            <b><color:white>children</color></b>
    ]
    
    portout " " as childrennetPortOut #blue
    childrennet -[#blue]- childrennetPortOut
    
    hexagon siblingsnet #red [
            <b><color:white>siblings</color></b>
    ]
    

node "web" as webService #white {
    portOut " " as webServicechildrennet #blue
   webServicechildrennet -[#blue]- childrennet
       portOut " " as webServicesiblingsnet #red
   webServicesiblingsnet -[#red]- siblingsnet
   

    artifact "edgemere_web" as edgemere_webimage
    
}
node "doc" as docService #white {
    portOut " " as docServicesiblingsnet #red
   docServicesiblingsnet -[#red]- siblingsnet
   

    artifact "edgemere_doc" as edgemere_docimage
    
}

}


@enduml
