@startuml

left to right direction


queue external #black [
    <b><color:white>external</color></b>
]
    
interface 80
80 -- external
    
interface 443
443 -- external
    
interface 8080
8080 -- external
    


entity ailtire_appname_family #black

stack "edgemere" as edgemereStack #lavender {
    queue edgemereStacksnet #black [
        <b><color:white>parent</color></b>
    ]
}



package "edgemere" #lavender {
    queue childrennet #black [
            <b><color:white>children</color></b>
    ]
    
    childrennet -[#black]- ailtire_appname_family
    
    queue siblingnet #blue [
            <b><color:white>sibling</color></b>
    ]
    


node "frontend" as frontendService {
    card "/web" as webmap
    card "/docs" as docsmap
    
}
node "admin" as adminService
node "pubsub" as pubsubService
node "web" as webService
node "doc" as docService

        collections "edgemere:latest" as edgemerelatestimage
    
        artifact "redis" as redisimage
    
        artifact "traefik:latest" as traefiklatestimage
    
        artifact "edgemere_web" as edgemere_webimage
    
        artifact "edgemere_doc" as edgemere_docimage
    
}

external -[#black]- frontendService

webmap -[#black]-> webService

docsmap -[#black]-> docService

adminService -[#black]- childrennet

pubsubService -[#black]- childrennet

pubsubService -[#blue]- siblingnet

webService -[#blue]- siblingnet

webService -[#black]- childrennet

docService -[#blue]- siblingnet

docService -[#black]- childrennet
adminService .... edgemerelatestimage
pubsubService .... redisimage
webService .... edgemere_webimage
docService .... edgemere_docimage

frontendService .... traefiklatestimage

edgemerelatestimage --> edgemereStack
    

@enduml
