@startuml
  interface CLI
  interface Web
  interface WebSocket
package "edgemere" #lavender {
  component express as REST
  component socket.io as socket
  folder bin #ffffff {
    component " edgemere" as binName
  }
  binName --> REST

  folder deploy #ffffff {
      file "node server.js\ndocker-compose.yml" as edgemere_container
      REST --> edgemere_container

  
    file "web" as web_container
    REST --> web_container
    socket ---> web_container
  
    file "doc" as doc_container
    REST --> doc_container
    socket ---> doc_container
  
  }
  folder images #ffffff {
    collections "edgemere" as edgemereimage
    artifact "ailtire:swarm" as ailtireswarm
    edgemereimage <|-- ailtireswarm
    edgemere_container --> edgemereimage

  
      artifact "edgemere_web" as edgemere_web
      web_container --> edgemere_web
    
      artifact "edgemere_doc" as edgemere_doc
      doc_container --> edgemere_doc
    
  }
}
CLI " edgemere" -- binName
Web "/edgemere" - REST
WebSocket ".edgemere" -- socket

@enduml
