@startuml
  interface CLI
  interface Web
  interface WebSocket
package "Data Orchestrator" #lightblue {
  component express as REST
  component socket.io as socket
  folder bin #ffffff {
    component " edgemere diml dml do" as binName
  }
  binName --> REST

  folder deploy #ffffff {
      file "node server.js\ndocker-compose.yml" as diml_dml_do_container
      REST --> diml_dml_do_container

  
    file "node web/server.js" as web_container
    REST --> web_container
    socket ---> web_container
  
    file "node gateway/server.js" as gateway_container
    REST --> gateway_container
    socket ---> gateway_container
  
  }
  folder images #ffffff {
    collections "diml_dml_do" as diml_dml_doimage
    artifact "ailtire:swarm" as ailtireswarm
    diml_dml_doimage <|-- ailtireswarm
    diml_dml_do_container --> diml_dml_doimage

  
      artifact diml_dml_do_web
      web_container --> diml_dml_do_web
    
      artifact diml_dml_do_gw
      gateway_container --> diml_dml_do_gw
    
  }
}
CLI " edgemere diml dml do" -- binName
Web "/edgemere/diml/dml/do" - REST
WebSocket ".edgemere.diml.dml.do" -- socket

@enduml
