@startuml
  interface CLI
  interface Web
  interface WebSocket
package "Data Flow" #lightblue {
  component express as REST
  component socket.io as socket
  folder bin #ffffff {
    component " edgemere diml ddf df" as binName
  }
  binName --> REST

  folder deploy #ffffff {
      file "node server.js\ndocker-compose.yml" as diml_ddf_df_container
      REST --> diml_ddf_df_container

  
    file "web" as web_container
    REST --> web_container
    socket ---> web_container
  
    file "gateway" as gateway_container
    REST --> gateway_container
    socket ---> gateway_container
  
  }
  folder images #ffffff {
    collections "diml_ddf_df" as diml_ddf_dfimage
    artifact "ailtire:swarm" as ailtireswarm
    diml_ddf_dfimage <|-- ailtireswarm
    diml_ddf_df_container --> diml_ddf_dfimage

  
      artifact diml_ddf_df_web
      web_container --> diml_ddf_df_web
    
      artifact diml_ddf_df_gw
      gateway_container --> diml_ddf_df_gw
    
  }
}
CLI " edgemere diml ddf df" -- binName
Web "/edgemere/diml/ddf/df" - REST
WebSocket ".edgemere.diml.ddf.df" -- socket

@enduml
