@startuml
(*)  -right-> "1. Identify Current Tools"
-right-> "2. Identify Interfaces"
-right-> "3. Identify Ownership"
-down-> "4. Develop Roadmap" #lightgray
-right-> "5. Identify Gaps" #lightgray
-right-> "6. Execute Plan" #lightgray
-down-> "7. Re-evaluate Roadmaps\nand Use Cases" #lightgray
-up-> "4. Develop Roadmap"
@enduml
