@startuml


boundary _sml_sc_family #blue


entity _sml_family #orange


package  "Service Controller"  #lightblue {
    card children #blue [
        <b><color:white>children</color></b>
    ]
    
    _sml_sc_family -[#blue]- children
    
    
    card sibling #red [
        <b><color:white>sibling</color></b>
    ]
    
    
    card parent #orange [
        <b><color:white>parent</color></b>
    ]
    
    
    _sml_family -[#orange]- parent
    
    artifact images #ffffff {
        
        file sml_sc_web
        
        file sml_sc_gw
        
    }

    node frontend
    frontend .. sml_sc_web
    
        sibling -[#red]- frontend
    

    node gw
    gw .. sml_sc_gw
    
        children -[#blue]- gw
    
        sibling -[#red]- gw
    




    
}




package sml #lightgray {
    card smlchildren #orange [
        <b><color:white>children</color></b>
    ]
    smlchildren ==[#orange]= parent
}


@enduml
