@startuml


package "Provision Engine" #88cc88 {
    }


package "Service Controller" #88cc88 {

    interface "Service Controller" as i {
    
    }
}

CLI ()-- i
REST ()-- i
Web ()-- i

package "Service Controller" #88cc88 {
    
}


    "Service Controller" --> "Provision Engine"


@enduml
