@startuml
left to right direction


state "sml" as sml #lightgreen {
state "sc" as smlsc #lightgreen {
}
}


state "smlsc" as pstatename #lightgreen {
    state "Custom Function" as scfunction {
    }
}





@enduml
