@startuml
left to right direction


state "sml" as sml #88cc88 {
state "sc" as smlsc #88cc88 {
}
}


state "smlsc" as pstatename #88cc88 {
    state "Custom Function" as scfunction {
    }
}





@enduml
