@startuml


package "Provision Engine" #88cc88 {

}


package "Service Controller" #88cc88 {

    interface "Service Controller" as i {
    
    
    }
}

circle REST
circle Web
circle CLI
circle WebSocket

i -down- Web
i -down- CLI
i -down- REST
WebSocket -left- i: events >

package "Service Controller" #88cc88 {


}


    "Provision Engine" <-- "Service Controller"


@enduml
