@startuml


usecase "Manage Data Center" as ManageDataCenter #yellow

Actor "IT Operations" as ITOperations

ITOperations --> ManageDataCenter



usecase "CreateDataCenter" as CreateDataCenter #lightgrey

ManageDataCenter --> CreateDataCenter

usecase "DisableDataCenter" as DisableDataCenter #lightgrey

ManageDataCenter --> DisableDataCenter

usecase "EnableDataCenter" as EnableDataCenter #lightgrey

ManageDataCenter --> EnableDataCenter

usecase "RemoveDataCenter" as RemoveDataCenter #lightgrey

ManageDataCenter --> RemoveDataCenter

usecase "UpdateDataCenter" as UpdateDataCenter #lightgrey

ManageDataCenter --> UpdateDataCenter



usecase "Manage Physical Infrastructure" as ManagePhysicalInfrastructure #lightyellow

ManageDataCenter <-- ManagePhysicalInfrastructure : extends







@enduml
