@startuml

actor "IT Operations"


entity EventBus

box Common Physical Layer #lightgray
    boundary cpl #white
end box


box Common Physical Layer #lightgray
            participant device
            participant aggregateddevice
            participant datacenter
    end box


"IT Operations" -> cpl: Update Data Center

    cpl -> "device": create (name: host1,file: ./templates/device.yaml)

    "device" --/ EventBus: device.create

    cpl -> "device": create (name: host2,file: ./templates/device.yaml)

    "device" --/ EventBus: device.create

    cpl -> "device": create (name: host3,file: ./templates/device.yaml)

    "device" --/ EventBus: device.create

    cpl -> "device": create (name: host4,file: ./templates/device.yaml)

    "device" --/ EventBus: device.create

    cpl -> "device": create (name: host5,file: ./templates/device.yaml)

    "device" --/ EventBus: device.create

    cpl -> "aggregateddevice": create (name: ad1)

    "aggregateddevice" --/ EventBus: aggregateddevice.create

    cpl -> "aggregateddevice": adddevices (name: ad2,items: host3,host4)

    "aggregateddevice" --/ EventBus: aggregateddevice.adddevices

    cpl -> "datacenter": create (name: dc1)

    "datacenter" --/ EventBus: datacenter.create

    cpl -> "datacenter": adddevices (name: dc1,items: host1,host2)

    "datacenter" --/ EventBus: datacenter.adddevices

    cpl -> "datacenter": adddevices (name: dc1,items: ad1)

    "datacenter" --/ EventBus: datacenter.adddevices



@enduml
