@startuml



package "Telemetry Producer" #cccccc {

    interface "Telemetry Producer" as i {
            /edgemere/cpl/tp/setparent()
            /edgemere/cpl/tp/stats/get()
            /edgemere/cpl/tp/stats/send()
    
    }
}

CLI ()-- i
REST ()-- i
Web ()-- i

package "Telemetry Producer" #cccccc {
    
}



@enduml
