@startuml
left to right direction


state "cpl" as cpl #lightgray {
state "tp" as cpltp #lightgray {
}
}


state cpltp #lightgray {
    state "Custom Function" as tpfunction {
    }
}

        state "cpl" as cpl #lightgray {
state "tp" as cpltp #lightgray {
state "setparent" as cpltpsetparent #lightgray {
}
}
}


        state "cpl" as cpl #lightgray {
state "tp" as cpltp #lightgray {
state "stats" as cpltpstats #lightgray {
state "get" as cpltpstatsget #lightgray {
}
}
}
}


        state "cpl" as cpl #lightgray {
state "tp" as cpltp #lightgray {
state "stats" as cpltpstats #lightgray {
state "send" as cpltpstatssend #lightgray {
}
}
}
}






@enduml
