@startuml
left to right direction


state "cpl" as cpl #cccccc {
state "tp" as cpltp #cccccc {
}
}


state "cpltp" as pstatename #cccccc {
    state "Custom Function" as tpfunction {
    }
}

        state "cpl" as cpl #cccccc {
state "tp" as cpltp #cccccc {
state "setparent" as cpltpsetparent #cccccc {
}
}
}


        state "cpl" as cpl #cccccc {
state "tp" as cpltp #cccccc {
state "stats" as cpltpstats #cccccc {
state "get" as cpltpstatsget #cccccc {
}
}
}
}


        state "cpl" as cpl #cccccc {
state "tp" as cpltp #cccccc {
state "stats" as cpltpstats #cccccc {
state "send" as cpltpstatssend #cccccc {
}
}
}
}






@enduml
