@startuml



package "Telemetry Producer" #cccccc {

    interface "Telemetry Producer" as i {
    
            /edgemere/cpl/tp/setparent()
            /edgemere/cpl/tp/stats/get()
            /edgemere/cpl/tp/stats/send()
    
    }
}

circle REST
circle Web
circle CLI
circle WebSocket

i -down- Web
i -down- CLI
i -down- REST
WebSocket -left- i: events >

package "Telemetry Producer" #cccccc {


}



@enduml
