@startuml
  interface CLI
  interface Web
  interface WebSocket
package "Software Defined Infrastructure" #cccc88 {
  component express as REST
  component socket.io as socket
  folder bin #ffffff {
    component " edgemere sdi" as binName
  }
  binName --> REST

  folder deploy #ffffff {
      file "node server.js\n" as sdi_container
      REST --> sdi_container

  
    file "web" as web_container
    REST --> web_container
    socket ---> web_container
  
  }
  folder images #ffffff {
    collections "sdi" as sdiimage
    artifact "ailtire:swarm" as ailtireswarm
    sdiimage <|-- ailtireswarm
    sdi_container --> sdiimage

  
      artifact "sdi_web" as sdi_web
      web_container --> sdi_web
    
  }
}
CLI " edgemere sdi" -- binName
Web "/edgemere/sdi" - REST
WebSocket ".edgemere.sdi" -- socket

@enduml
