@startuml
left to right direction


state "sdi" as sdi #lightyellow {
}


state sdi #lightyellow {
    state "Custom Function" as sdifunction {
    }
}

        state "sdi" as sdi #lightyellow {
state "checkrequest" as sdicheckrequest #lightyellow {
}
}


        state "sdi" as sdi #lightyellow {
state "reserve" as sdireserve #lightyellow {
}
}


        state "sdi" as sdi #lightyellow {
state "resource" as sdiresource #lightyellow {
state "get" as sdiresourceget #lightyellow {
}
}
}


        state "sdi" as sdi #lightyellow {
state "resource" as sdiresource #lightyellow {
state "list" as sdiresourcelist #lightyellow {
}
}
}


        state "sdi" as sdi #lightyellow {
state "resource" as sdiresource #lightyellow {
state "release" as sdiresourcerelease #lightyellow {
}
}
}




    state "sdi" as sdi #lightyellow {
state "Request" as sdirequest #lightyellow {
state "satisfied" as sdirequestsatisfied #lightyellow {
}
}
}

    
    state "sdi" as sdi #lightyellow {
state "Function" as sdifunction #lightyellow {
}
}

    sdirequestsatisfied ---> sdifunction
  

    state "sdi" as sdi #lightyellow {
state "Resource" as sdiresource #lightyellow {
state "ready" as sdiresourceready #lightyellow {
}
}
}

    
    state "sdi" as sdi #lightyellow {
state "request" as sdirequest #lightyellow {
state "reserve" as sdirequestreserve #lightyellow {
}
}
}

    sdiresourceready ---> sdirequestreserve
  


    state "sdi" as sdi #lightyellow {
state "Request" as sdirequest #lightyellow {
state "needed" as sdirequestneeded #lightyellow {
}
}
}

    state "cpl" as cpl #lightgray {
state "Function" as cplfunction #lightgray {
}
}

        sdirequestneeded ---> cplfunction
       
    
    state "cpl" as cpl #lightgray {
state "reserve" as cplreserve #lightgray {
}
}

        sdirequestneeded ---> cplreserve
       
    state "sdi" as sdi #lightyellow {
state "Reservation" as sdireservation #lightyellow {
state "rejected" as sdireservationrejected #lightyellow {
}
}
}

    
        sdireservationrejected ---> cplfunction
       
    state "sdi" as sdi #lightyellow {
state "Resource" as sdiresource #lightyellow {
state "provisioning" as sdiresourceprovisioning #lightyellow {
}
}
}

    state "cpl" as cpl #lightgray {
state "provision" as cplprovision #lightgray {
}
}

        sdiresourceprovisioning ---> cplprovision
       
    state "sdi" as sdi #lightyellow {
state "Request" as sdirequest #lightyellow {
state "selected" as sdirequestselected #lightyellow {
}
}
}

    state "sdi" as sdi #lightyellow {
state "io" as sdiio #lightyellow {
state "evaluateRequest" as sdiioevaluaterequest #lightyellow {
}
}
}

        sdirequestselected ---> sdiioevaluaterequest
       
    state "sdi" as sdi #lightyellow {
state "Reservation" as sdireservation #lightyellow {
state "confirmed" as sdireservationconfirmed #lightyellow {
}
}
}

    state "sdi" as sdi #lightyellow {
state "io" as sdiio #lightyellow {
state "provision" as sdiioprovision #lightyellow {
}
}
}

        sdireservationconfirmed ---> sdiioprovision
       
    
    
        
       
    
    state "sdi" as sdi #lightyellow {
state "request" as sdirequest #lightyellow {
state "reserve" as sdirequestreserve #lightyellow {
}
}
}

        
       

@enduml
