@startuml
left to right direction



state "IT Operations" as ITOperations {
    state "Manage Resources" as ITOperationsManageResources {
    }
}
state "sdi" as sdi #lightyellow {
state "resource" as sdiresource #lightyellow {
state "list" as sdiresourcelist #lightyellow {
}
}
}

ITOperationsManageResources --> sdiresourcelist


    state "IT Operations" as ITOperations {
        state "Manage Resources" as ITOperationsManageResources {
            state "Get Resources" as ITOperationsManageResourcesGetResources {
            }
        }
    }
    state "sdiresource" as sdiresource #lavender {
state "get" as sdiresourceget #lavender {
}
}

    ITOperationsManageResourcesGetResources --> sdiresourceget
    
 
    state "IT Operations" as ITOperations {
        state "Manage Resources" as ITOperationsManageResources {
            state "List Resources" as ITOperationsManageResourcesListResources {
            }
        }
    }
    state "sdiresource" as sdiresource #lavender {
state "list" as sdiresourcelist #lavender {
}
}

    ITOperationsManageResourcesListResources --> sdiresourcelist
    
 
    state "IT Operations" as ITOperations {
        state "Manage Resources" as ITOperationsManageResources {
            state "Release Resources" as ITOperationsManageResourcesReleaseResources {
            }
        }
    }
    state "sdiresource" as sdiresource #lavender {
state "release" as sdiresourcerelease #lavender {
}
}

    ITOperationsManageResourcesReleaseResources --> sdiresourcerelease
    
 
 

@enduml
